const RIFT_V24_MARKER=`Riftbound Spatial Ability Grammar V24`;
const RIFT_V24_VERSION=24;
const RIFT_V24_SPATIAL_TYPES=Object.freeze({
 self:{label:`SELF`,glyph:`◎`,family:`origin`},target:{label:`TARGET`,glyph:`⌖`,family:`point`},strike:{label:`STRIKE`,glyph:`✦`,family:`point`},arc:{label:`WEAPON ARC`,glyph:`◔`,family:`sweep`},sweep:{label:`SWEEP`,glyph:`◒`,family:`sweep`},thrust:{label:`THRUST`,glyph:`⇥`,family:`line`},dash:{label:`DASH`,glyph:`➤`,family:`path`},dashSlash:{label:`DASH CUT`,glyph:`⫻`,family:`path`},line:{label:`LINE`,glyph:`━`,family:`line`},beam:{label:`BEAM`,glyph:`═`,family:`line`},projectile:{label:`PROJECTILE`,glyph:`•`,family:`path`},cone:{label:`CONE`,glyph:`◁`,family:`fan`},wave:{label:`WAVE`,glyph:`)))`,family:`fan`},area:{label:`IMPACT AREA`,glyph:`◉`,family:`area`},ring:{label:`EXPANDING RING`,glyph:`◯`,family:`area`},field:{label:`PERSISTENT FIELD`,glyph:`▧`,family:`area`},wall:{label:`WALL`,glyph:`▮`,family:`area`},cross:{label:`CROSS CUT`,glyph:`╳`,family:`point`},barrage:{label:`BARRAGE`,glyph:`⁙`,family:`multi`},scatter:{label:`SCATTER`,glyph:`∴`,family:`multi`},chain:{label:`CHAIN`,glyph:`⌁`,family:`path`},tether:{label:`TETHER`,glyph:`⌇`,family:`path`},grab:{label:`GRAB`,glyph:`⊃`,family:`point`},ricochet:{label:`RICOCHET`,glyph:`↯`,family:`path`},summon:{label:`SUMMON`,glyph:`◇`,family:`area`},teleport:{label:`TELEPORT`,glyph:`⌬`,family:`path`},zone:{label:`CONTROL ZONE`,glyph:`⬡`,family:`area`},orbit:{label:`ORBIT`,glyph:`⟳`,family:`area`},rain:{label:`FALLING AREA`,glyph:`⋮`,family:`multi`}
});
const RIFT_V24_TAG=(set,...names)=>names.some(name=>set.has(name));
const RIFT_V24_TEXT=(action)=>`${action?.sourcePower||``} ${action?.name||action?.move?.name||``} ${action?.description||action?.move?.description||``}`.toLowerCase();
function RIFT_V24_ACTIVE_WEAPON(fighter){try{return RIFT_SPARTAN_ACTIVE_ID(fighter)||RIFT_ACTIVE_ITEM(fighter)?.id||fighter?.weapon?.name||null}catch{return fighter?.weapon?.name||null}}
function RIFT_V24_CLASSIFY(action,fighter=null,geometry=null){
 const move=action?.move||action||{},tags=new Set(move.tags||[]),text=RIFT_V24_TEXT(action?.move? action:{...action,move}),core=geometry||{},weapon=String(RIFT_V24_ACTIVE_WEAPON(fighter)||``).toLowerCase();let type=`target`,variant=`standard`,spread=38,arc=112;
 if(action?.type===`guard`||action?.type===`rest`||RIFT_V24_TAG(tags,`selfCast`,`cursedSwordParry`,`standToggle`,`rikaCommand`,`v14FInertia`,`v14Translucency`)&&!RIFT_V24_TAG(tags,`selfAoe`,`area`))type=`self`;
 else if(RIFT_V24_TAG(tags,`spardaHeavySwing`)||/heavy swing/.test(text)){type=`arc`;arc=weapon.includes(`yamato`)?92:weapon.includes(`beowulf`)?72:weapon.includes(`ebony`)?58:weapon.includes(`sparda`)?148:126;variant=weapon.includes(`yamato`)?`iaido`:weapon.includes(`beowulf`)?`gauntlet`:weapon.includes(`ebony`)?`gunfan`:`greatsword`}
 else if(RIFT_V24_TAG(tags,`teleport`,`kcrTimeDodge`,`gerRealityBend`,`calamityLightningBlink`,`standTimeSkip`,`standJump`,`standQuickStop`)||/teleport|blink|time skip|reality bend/.test(text))type=`teleport`;
 else if(RIFT_V24_TAG(tags,`summon`,`rikaPartialSummon`,`rikaFullManifest`,`controlChainsawSummon`,`calamitySummon`)||/summon|manifest|create .*ally|life generation/.test(text))type=`summon`;
 else if(RIFT_V24_TAG(tags,`grab`,`consume`,`devour`,`seize`)||/grab|grapple|clutch|devour|swallow/.test(text))type=`grab`;
 else if(RIFT_V24_TAG(tags,`blackwhip`,`controlChain`,`chain`,`restrain`)||/chainvest|chain|blackwhip/.test(text))type=RIFT_V24_TAG(tags,`blackwhip`,`tether`)?`tether`:`chain`;
 else if(RIFT_V24_TAG(tags,`ricochet`,`reflect`,`bounce`)||/ricochet|pinball|rebound/.test(text))type=`ricochet`;
 else if(RIFT_V24_TAG(tags,`spardaBlitz`,`chainsawBlitz`,`dashAttack`,`dashCut`,`lunge`)||/blitz|dash cut|flash step|speedblitz|rush through/.test(text)){type=/cut|slash|blitz|weapon|chainsaw/.test(text)||RIFT_V24_TAG(tags,`slash`,`cut`,`weapon`)?`dashSlash`:`dash`}
 else if(RIFT_V24_TAG(tags,`thrust`,`stab`,`pierce`,`standStarFinger`)||/thrust|stab|pierce|star finger|spear|lance/.test(text))type=`thrust`;
 else if(RIFT_V24_TAG(tags,`crossCut`,`worldCut`,`judgementCut`)||/cross cut|judgement cut|dimensional severance|world cutting/.test(text))type=`cross`;
 else if(RIFT_V24_TAG(tags,`sweep`,`slash`,`cut`,`blade`,`weapon`)&&/swing|slash|cleave|sweep|slice|scythe|sword|blade/.test(text)||/swing|cleave|sweeping|wide slash/.test(text)){type=`arc`;arc=/wide|great|heavy|cleave/.test(text)?138:102}
 else if(RIFT_V24_TAG(tags,`rain`)||/rain|meteor shower|knife storm|falling stars/.test(text))type=`rain`;
 else if(Number(move.hits||1)>=3||RIFT_V24_TAG(tags,`multi`,`barrage`)||/barrage|ora ora|muda muda|ratatata|beatdown|gatling|flurry|combo/.test(text))type=`barrage`;
 else if(RIFT_V24_TAG(tags,`scatter`,`shotgun`)||/scatter|buckshot|volley|spread shot|shrapnel/.test(text))type=`scatter`;
 else if(RIFT_V24_TAG(tags,`beam`,`laser`)||/beam|laser|ray|kamehameha|hollow purple|demonic beam/.test(text))type=`beam`;
 else if(RIFT_V24_TAG(tags,`cone`,`breath`,`fear`)||/breath|roar|shout|horror|repulsion/.test(text)){type=`cone`;spread=/fear|horror|roar/.test(text)?70:44}
 else if(RIFT_V24_TAG(tags,`wave`,`shockwave`)||/shockwave|tidal wave|air cannon|sonic boom|wind wave/.test(text))type=`wave`;
 else if(RIFT_V24_TAG(tags,`wall`,`barrier`)||/wall|barrier|ice block|rampart/.test(text))type=`wall`;
 else if(RIFT_V24_TAG(tags,`domain`,`field`,`gravityWell`,`persistent`)||/domain|field|well|shrine|zone|event horizon|smokescreen/.test(text))type=`field`;
 else if(RIFT_V24_TAG(tags,`ring`,`nova`,`pulse`)||/nova|pulse|expanding|eruption ring/.test(text))type=`ring`;
 else if(RIFT_V24_TAG(tags,`orbit`)||/orbit|satellite/.test(text))type=`orbit`;
 else if(RIFT_V24_TAG(tags,`selfAoe`,`area`,`explosion`)||core.shape===`area`||/explosion|detonate|cataclysm|storm|quake|slam|impact/.test(text))type=`area`;
 else if(RIFT_V24_TAG(tags,`projectile`)||core.shape===`projectile`||/shot|bullet|arrow|ball|bubble|bolt|launch|throw/.test(text))type=`projectile`;
 else if(RIFT_V24_TAG(tags,`line`)||core.shape===`line`)type=`line`;
 else if(core.shape===`cone`)type=`cone`;else if(core.shape===`teleport`)type=`teleport`;else if(core.shape===`melee`||RIFT_V24_TAG(tags,`physical`,`melee`))type=`strike`;else if(core.shape===`self`)type=`self`;
 const definition=RIFT_V24_SPATIAL_TYPES[type]||RIFT_V24_SPATIAL_TYPES.target;return{type,label:definition.label,glyph:definition.glyph,family:definition.family,variant,spread,arc,coreShape:core.shape||null,presentationOnly:true,mechanicsChanged:false};
}
function RIFT_V24_POINT_STYLE(battlefield,point){return{left:`${point.x/Math.max(1,battlefield.width)*100}%`,top:`${point.y/Math.max(1,battlefield.height)*100}%`}}
function RIFT_V24_LINE_STYLE(battlefield,origin,target){const dx=target.x-origin.x,dy=target.y-origin.y,distance=Math.hypot(dx,dy),angle=Math.atan2(dy,dx);return{left:`${origin.x/battlefield.width*100}%`,top:`${origin.y/battlefield.height*100}%`,width:`${distance/battlefield.width*100}%`,transform:`rotate(${angle}rad)`,"--v24-angle":`${angle}rad`}}
function RIFT_V24_AREA_STYLE(battlefield,point,radius){return{left:`${point.x/battlefield.width*100}%`,top:`${point.y/battlefield.height*100}%`,width:`${radius*2/battlefield.width*100}%`,height:`${radius*2/battlefield.height*100}%`}}
function RIFT_V24_SPATIAL_LAYER({battlefield,action,fighter,aim}){
 if(!battlefield||!aim?.origin||!aim?.target)return null;const profile=RIFT_V24_CLASSIFY(action,fighter,aim),origin=aim.origin,target=aim.target,line=RIFT_V24_LINE_STYLE(battlefield,origin,target),radius=Math.max(2,Number(aim.radius||3)),reach=Math.max(radius,Math.min(Number(aim.range||aim.distance||8),Math.max(radius,Number(aim.distance||aim.range||8)))),area=RIFT_V24_AREA_STYLE(battlefield,target,radius),originArea=RIFT_V24_AREA_STYLE(battlefield,origin,reach),lineTypes=new Set([`line`,`beam`,`projectile`,`thrust`,`dash`,`dashSlash`,`chain`,`tether`,`ricochet`]),areaTypes=new Set([`area`,`ring`,`field`,`zone`,`orbit`,`summon`,`rain`]);
 const children=[];if(lineTypes.has(profile.type))children.push((0,E.jsxs)(`div`,{className:`v24-path path-${profile.type} variant-${profile.variant}`,style:line,children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),profile.type===`ricochet`&&(0,E.jsx)(`b`,{})]},`path`));
 if([`cone`,`wave`,`scatter`].includes(profile.type))children.push((0,E.jsxs)(`div`,{className:`v24-fan fan-${profile.type}`,style:{...line,"--v24-spread":`${profile.spread}deg`},children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{})]},`fan`));
 if([`arc`,`sweep`].includes(profile.type))children.push((0,E.jsxs)(`div`,{className:`v24-arc variant-${profile.variant}`,style:{...originArea,"--v24-angle":`${Math.atan2(target.y-origin.y,target.x-origin.x)}rad`,"--v24-arc":`${profile.arc}deg`},children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{})]},`arc`));
 if(areaTypes.has(profile.type))children.push((0,E.jsxs)(`div`,{className:`v24-area area-${profile.type}`,style:area,children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{children:profile.glyph})]},`area`));
 if(profile.type===`wall`)children.push((0,E.jsx)(`div`,{className:`v24-wall`,style:{...area,"--v24-angle":`${Math.atan2(target.y-origin.y,target.x-origin.x)+Math.PI/2}rad`}},`wall`));
 if(profile.type===`cross`)children.push((0,E.jsxs)(`div`,{className:`v24-cross`,style:area,children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{})]},`cross`));
 if(profile.type===`barrage`)children.push((0,E.jsx)(`div`,{className:`v24-barrage`,style:line,children:Array.from({length:9},(_,index)=>(0,E.jsx)(`i`,{style:{"--v24-beat":index}},index))},`barrage`));
 if([`target`,`strike`,`grab`].includes(profile.type))children.push((0,E.jsxs)(`div`,{className:`v24-point point-${profile.type}`,style:area,children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{children:profile.glyph})]},`point`));
 if(profile.type===`teleport`)children.push((0,E.jsxs)(E.Fragment,{children:[(0,E.jsx)(`div`,{className:`v24-teleport origin`,style:RIFT_V24_AREA_STYLE(battlefield,origin,3)}),(0,E.jsx)(`div`,{className:`v24-teleport destination`,style:area}),(0,E.jsx)(`div`,{className:`v24-teleport-thread`,style:line})]},`teleport`));
 children.push((0,E.jsxs)(`span`,{className:`v24-spatial-label`,style:RIFT_V24_POINT_STYLE(battlefield,target),children:[(0,E.jsx)(`b`,{children:profile.glyph}),(0,E.jsx)(`small`,{children:profile.label})]},`label`));return(0,E.jsx)(`div`,{className:`v24-spatial-layer type-${profile.type} family-${profile.family} ${aim.contact?`contact`:`miss`}`,"data-spatial-type":profile.type,"aria-hidden":`true`,children});
}
function RIFT_V24_COVERAGE(){const rows=[],add=(source,channel,moves)=>{(moves||[]).forEach((move,index)=>{const action={id:`${qt(source)}-${channel}-${index}`,name:move.name,description:move.description,sourcePower:source,type:index===3?`ultimate`:`special`,move},profile=RIFT_V24_CLASSIFY(action,null,{shape:(move.tags||[]).includes(`selfCast`)?`self`:(move.tags||[]).includes(`area`)?`area`:(move.tags||[]).includes(`line`)?`line`:(move.tags||[]).includes(`projectile`)?`projectile`:`target`});rows.push({source,channel,move:move.name,index,...profile})})};g.forEach(power=>add(power.name,`body`,power.moves));h.forEach(stand=>{add(stand.name,`stand`,stand.moves||stand.partial||stand.summoned);if(stand.evolved)add(stand.evolved.name||`${stand.name} · Evolved`,`stand`,stand.evolved.moves)});const counts={};for(const row of rows)counts[row.type]=(counts[row.type]||0)+1;return{version:24,total:rows.length,typed:rows.filter(row=>RIFT_V24_SPATIAL_TYPES[row.type]).length,untyped:rows.filter(row=>!RIFT_V24_SPATIAL_TYPES[row.type]),counts,rows}}
const RIFT_V24_BASE_PREVIEW=RIFT_V19_ACTION_PREVIEW;
RIFT_V19_ACTION_PREVIEW=function RIFT_V24_ACTION_PREVIEW(run,actionId){const preview=RIFT_V24_BASE_PREVIEW(run,actionId);if(!preview)return preview;const action=La(run.player).find(entry=>entry.id===actionId),profile=RIFT_V24_CLASSIFY(action,run.player,{shape:preview.shape,range:preview.range});return{...preview,spatialType:profile.type,spatialLabel:profile.label,coreShape:preview.shape,presentationOnly:true}}
const RIFT_V24_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V24_NORMALIZE_RUN_BUILD(run){run=RIFT_V24_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(24,Number(run.riftboundSchemaVersion||0));run.v24Spatial=run.v24Spatial&&typeof run.v24Spatial===`object`?run.v24Spatial:{grammarVersion:1};return run};
const RIFT_V24_COVERAGE_REPORT=RIFT_V24_COVERAGE();
globalThis.RIFTBOUND_SPATIAL={version:24,types:RIFT_V24_SPATIAL_TYPES,classify:RIFT_V24_CLASSIFY,coverage:()=>RIFT_V24_COVERAGE(),render:RIFT_V24_SPATIAL_LAYER};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:24,release:`V24 · Combat Reforged`,spatialGrammar:{version:1,types:Object.keys(RIFT_V24_SPATIAL_TYPES),moves:RIFT_V24_COVERAGE_REPORT.total,typed:RIFT_V24_COVERAGE_REPORT.typed,presentationOnly:true,mechanicsChanged:false}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:24,spatial:RIFT_V24_COVERAGE};
