const RIFT_V27_MARKER=`Riftbound Living Rift V27`;
const RIFT_V27_VERSION=27;
const RIFT_V27_ARENA_PALETTES=Object.freeze({archive:[`#25485f`,`#9ec9d1`,`#0c1721`],astral:[`#563c8f`,`#d8b8ff`,`#090716`],cinder:[`#7a2d22`,`#ff9a51`,`#170807`],clock:[`#60532f`,`#f0d17a`,`#11100a`],flood:[`#185e76`,`#77d9ec`,`#06151c`],sunkenforge:[`#75421e`,`#ffb257`,`#160e07`],garden:[`#315f42`,`#8be0a6`,`#07140d`],glass:[`#467383`,`#d7fbff`,`#09151a`],gravitycathedral:[`#4a3376`,`#bd9cff`,`#0a0712`],mirror:[`#426479`,`#e6f5ff`,`#081117`],nave:[`#44385e`,`#c7a8e9`,`#0d0a12`],neon:[`#713c75`,`#ff7dea`,`#090611`],null:[`#393d48`,`#d8dde6`,`#050608`],orchard:[`#6c3b58`,`#f0a2c1`,`#140912`],ossuary:[`#685a44`,`#d8c7a4`,`#100e0a`],plaza:[`#31576e`,`#84c9e7`,`#081218`],quarry:[`#5f5144`,`#c9b69e`,`#100d0a`],siege:[`#6e3039`,`#ed7a81`,`#14070a`],stormrail:[`#2e5577`,`#91d7ff`,`#070d16`],vault:[`#5b456c`,`#d1afe6`,`#0c0911`]});
function RIFT_V27_ARENA_IDENTITY(battlefield){const theme=String(battlefield?.theme||`null`).toLowerCase(),palette=RIFT_V27_ARENA_PALETTES[theme]||RIFT_V27_ARENA_PALETTES.null,seed=Number(battlefield?.seed||0);return{theme,name:battlefield?.name||theme.toUpperCase(),palette,lightAngle:(seed%280)-140,depthLayers:4,ambience:`${theme}-rift`,hazardCue:theme===`flood`?`ripples`:theme===`cinder`||theme===`sunkenforge`?`embers`:theme===`stormrail`?`arcs`:theme===`glass`||theme===`mirror`?`refractions`:`rift-dust`}}
function RIFT_V27_ENVIRONMENT_STATE(battlefield){if(!battlefield)return{damage:0,scars:[]};const features=battlefield.features||[],destroyed=features.filter(feature=>feature.integrity<=0),damaged=features.filter(feature=>feature.maxIntegrity&&feature.integrity>0&&feature.integrity<feature.maxIntegrity),hazards=battlefield.hazards||[];return{damage:Math.min(1,(destroyed.length*1.5+damaged.length*.5+hazards.length*.3)/Math.max(1,features.length+4)),scars:[...destroyed.map(feature=>({id:feature.id,kind:`rubble`,position:feature.position,accent:feature.accent})),...hazards.slice(-8).map(hazard=>({id:hazard.id,kind:hazard.kind,position:hazard.position,accent:hazard.accent,radius:hazard.radius}))].slice(-18)}}
function RIFT_V27_FIGHTER_STANCE(fighter){if(!fighter)return`neutral`;if(fighter.hp<=0)return`defeated`;if(fighter.statuses?.stun||fighter.statuses?.staggered)return`staggered`;if(fighter.guard)return`guarding`;if(fighter.statuses?.spardaDevTrigger||fighter.sparda?.devTrigger)return`transformed`;if(fighter.hp/fighter.maxHp<.3)return`critical`;return`ready`}
function RIFT_V27_PRESENTATION({battlefield,player,enemy}){const identity=RIFT_V27_ARENA_IDENTITY(battlefield),environment=RIFT_V27_ENVIRONMENT_STATE(battlefield);return(0,E.jsxs)(`div`,{className:`v27-world-layer theme-${identity.theme} cue-${identity.hazardCue}`,style:{"--v27-a":identity.palette[0],"--v27-b":identity.palette[1],"--v27-c":identity.palette[2],"--v27-light":`${identity.lightAngle}deg`,"--v27-damage":environment.damage,"--v27-player-stance":RIFT_V27_FIGHTER_STANCE(player),"--v27-enemy-stance":RIFT_V27_FIGHTER_STANCE(enemy)},"aria-hidden":`true`,children:[(0,E.jsx)(`i`,{className:`v27-depth far`}),(0,E.jsx)(`i`,{className:`v27-depth middle`}),(0,E.jsx)(`i`,{className:`v27-depth near`}),(0,E.jsx)(`i`,{className:`v27-light`}),(0,E.jsx)(`div`,{className:`v27-ambience`,children:Array.from({length:12},(_,index)=>(0,E.jsx)(`b`,{style:{"--v27-particle":index,left:`${(index*37+11)%100}%`,top:`${(index*61+7)%100}%`}},index))}),environment.scars.map((scar,index)=>(0,E.jsx)(`span`,{className:`v27-scar scar-${qt(scar.kind)}`,style:{left:`${scar.position.x/battlefield.width*100}%`,top:`${scar.position.y/battlefield.height*100}%`,"--v27-scar":scar.accent||identity.palette[1],"--v27-scar-size":Math.max(3,Number(scar.radius||4))}},scar.id||index))]})}
const RIFT_V27_AUDIO_STATE={master:1,impact:.8,ability:.75,environment:.58,interface:.5,music:.5,context:null};
function RIFT_V27_AUDIO_TONE(frequency=160,duration=.06,gain=.018,type=`triangle`){if(typeof window===`undefined`||RIFT_V20_ACCESS?.reducedMotion)return;try{const Ctx=window.AudioContext||window.webkitAudioContext,context=RIFT_V27_AUDIO_STATE.context||(RIFT_V27_AUDIO_STATE.context=new Ctx),osc=context.createOscillator(),volume=context.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,context.currentTime);osc.frequency.exponentialRampToValueAtTime(Math.max(38,frequency*.58),context.currentTime+duration);volume.gain.setValueAtTime(gain*RIFT_V27_AUDIO_STATE.master,context.currentTime);volume.gain.exponentialRampToValueAtTime(.001,context.currentTime+duration);osc.connect(volume).connect(context.destination);osc.start();osc.stop(context.currentTime+duration)}catch{}}
const RIFT_V27_AUDIO_BUS=Object.freeze({state:RIFT_V27_AUDIO_STATE,set(channel,value){if(!(channel in RIFT_V27_AUDIO_STATE)||channel===`context`)return false;RIFT_V27_AUDIO_STATE[channel]=M(Number(value),0,1);return true},cue(kind,payload={}){if(kind===`impact`)RIFT_V27_AUDIO_TONE(payload.heavy?72:105,payload.heavy?.13:.07,(payload.heavy?.04:.02)*RIFT_V27_AUDIO_STATE.impact,payload.heavy?`sawtooth`:`triangle`);else if(kind===`move`)RIFT_V27_AUDIO_TONE(220,.04,.012*RIFT_V27_AUDIO_STATE.ability,`sine`);else if(kind===`status`)RIFT_V27_AUDIO_TONE(360,.08,.012*RIFT_V27_AUDIO_STATE.ability,`sine`);else if(kind===`environment`)RIFT_V27_AUDIO_TONE(58,.18,.022*RIFT_V27_AUDIO_STATE.environment,`sawtooth`)}});
RIFT_V22_EVENT_BUS.on(`DAMAGE_APPLIED`,event=>RIFT_V27_AUDIO_BUS.cue(`impact`,{heavy:Number(event.payload.amount||0)>28}));RIFT_V22_EVENT_BUS.on(`ACTOR_MOVED`,()=>RIFT_V27_AUDIO_BUS.cue(`move`));RIFT_V22_EVENT_BUS.on(`STATUS_APPLIED`,()=>RIFT_V27_AUDIO_BUS.cue(`status`));RIFT_V22_EVENT_BUS.on(`ENVIRONMENT_DESTROYED`,()=>RIFT_V27_AUDIO_BUS.cue(`environment`));
function RIFT_V27_EFFECT_PRIMITIVES(){return Object.freeze({line:(origin,target)=>({kind:`line`,origin,target}),arc:(origin,target,angle=110)=>({kind:`arc`,origin,target,angle}),trail:(origin,target)=>({kind:`trail`,origin,target}),shockwave:(target,radius)=>({kind:`shockwave`,target,radius}),distortion:(target,radius)=>({kind:`distortion`,target,radius}),debris:(target,count=8)=>({kind:`debris`,target,count}),light:(target,color)=>({kind:`light`,target,color}),afterimage:(origin,target,count=4)=>({kind:`afterimage`,origin,target,count}),timeline:(mode,turns)=>({kind:`timeline`,mode,turns})})}
const RIFT_V27_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V27_NORMALIZE_RUN_BUILD(run){run=RIFT_V27_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(27,Number(run.riftboundSchemaVersion||0));if(run.battlefield)run.battlefield.v27Environment=RIFT_V27_ENVIRONMENT_STATE(run.battlefield);return run};
globalThis.RIFTBOUND_PRESENTATION={version:27,arena:RIFT_V27_ARENA_IDENTITY,environment:RIFT_V27_ENVIRONMENT_STATE,stance:RIFT_V27_FIGHTER_STANCE,primitives:RIFT_V27_EFFECT_PRIMITIVES(),audio:RIFT_V27_AUDIO_BUS};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:27,release:`V27 · Living Rift`,presentation:{arenaThemes:Object.keys(RIFT_V27_ARENA_PALETTES),depthLayers:4,persistentScars:true,stanceStates:[`ready`,`guarding`,`staggered`,`critical`,`transformed`,`defeated`],effectPrimitives:Object.keys(RIFT_V27_EFFECT_PRIMITIVES()),audioChannels:[`impact`,`ability`,`environment`,`interface`,`music`]}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:27,presentation:()=>({themes:Object.keys(RIFT_V27_ARENA_PALETTES).length,audio:{...RIFT_V27_AUDIO_STATE,context:!!RIFT_V27_AUDIO_STATE.context}})};
