/* V36.3 · active-loadout core, health-cap stability, Takeover exit authority, and presentation upgrades */
const RIFT_V363_HEARTBREAKER_CINEMA_MS=1580;
const RIFT_ACTIVE_LOADOUT_VERSION=1;
const RIFT_ACTIVE_LOADOUT_PROVIDERS=[];

function RIFT_ACTIVE_LOADOUT_SLOT(action){const slot=Number(action?.slot);return Number.isFinite(slot)?slot:null}
function RIFT_ACTIVE_LOADOUT_REGISTER(id,priority,provider){if(!id||typeof provider!==`function`)return false;const at=RIFT_ACTIVE_LOADOUT_PROVIDERS.findIndex(row=>row.id===id);const row={id:String(id),priority:Number(priority||0),provider};if(at>=0)RIFT_ACTIVE_LOADOUT_PROVIDERS.splice(at,1,row);else RIFT_ACTIVE_LOADOUT_PROVIDERS.push(row);RIFT_ACTIVE_LOADOUT_PROVIDERS.sort((a,b)=>a.priority-b.priority);return true}
function RIFT_ACTIVE_LOADOUT_STATE(fighter){if(!fighter||typeof fighter!==`object`)return{overrides:{}};fighter.activeMoveLoadout=fighter.activeMoveLoadout&&typeof fighter.activeMoveLoadout===`object`?fighter.activeMoveLoadout:{overrides:{}};fighter.activeMoveLoadout.overrides=fighter.activeMoveLoadout.overrides&&typeof fighter.activeMoveLoadout.overrides===`object`?fighter.activeMoveLoadout.overrides:{};return fighter.activeMoveLoadout}
function RIFT_ACTIVE_LOADOUT_SET(fighter,slot,action,source=`runtime`){slot=Number(slot);if(!fighter||!Number.isFinite(slot)||!action)return false;const state=RIFT_ACTIVE_LOADOUT_STATE(fighter);state.overrides[String(slot)]={source:String(source),action:P(action)};return true}
function RIFT_ACTIVE_LOADOUT_CLEAR(fighter,slot=null,source=null){if(!fighter?.activeMoveLoadout?.overrides)return false;const overrides=fighter.activeMoveLoadout.overrides;if(slot==null){if(source==null)fighter.activeMoveLoadout.overrides={};else for(const key of Object.keys(overrides))if(overrides[key]?.source===source)delete overrides[key];return true}const key=String(Number(slot));if(!overrides[key]||source!=null&&overrides[key].source!==source)return false;delete overrides[key];return true}
function RIFT_ACTIVE_LOADOUT_RESOLVE(fighter,baseActions=[],run=globalThis.__RIFTBOUND_ACTIVE_RUN__){let actions=Array.isArray(baseActions)?baseActions.filter(Boolean).map(action=>action):[];const api={fighter,run,get actions(){return actions},set actions(value){actions=Array.isArray(value)?value.filter(Boolean):[]},remove(predicate){actions=actions.filter(action=>!predicate(action))},replace(slot,action){slot=Number(slot);actions=actions.filter(row=>RIFT_ACTIVE_LOADOUT_SLOT(row)!==slot);if(action)actions.push({...action,slot})}};const state=RIFT_ACTIVE_LOADOUT_STATE(fighter);for(const [key,override] of Object.entries(state.overrides||{})){const slot=Number(key);if(Number.isFinite(slot)&&override?.action)api.replace(slot,P(override.action))}for(const row of RIFT_ACTIVE_LOADOUT_PROVIDERS){try{row.provider(api)}catch(error){try{console.warn(`[RIFT ACTIVE LOADOUT] ${row.id}`,error)}catch{}}}const slotted=new Map(),unslotted=[];for(const action of actions){const slot=RIFT_ACTIVE_LOADOUT_SLOT(action);if(slot==null)unslotted.push(action);else slotted.set(slot,action)}actions=[...unslotted,...[...slotted.entries()].sort((a,b)=>a[0]-b[0]).map(([,action])=>action)];return{version:RIFT_ACTIVE_LOADOUT_VERSION,power:fighter?.power?.name||null,state:fighter?.statuses?.v35Takeover?`takeover`:fighter?.statuses?.v35AbductWindow>0?`recast`:`base`,actions,slots:Object.fromEntries([...slotted.entries()].map(([slot,action])=>[String(slot),action]))}}

RIFT_ACTIVE_LOADOUT_REGISTER(`viego-takeover`,90,ctx=>{const fighter=ctx.fighter;if(!fighter?.statuses?.v35Takeover)return;const heart=RIFT_V35_COPY(RIFT_V35_RUINED_POWER.moves[3]),state=fighter.statuses.v35Takeover;ctx.remove(action=>{const tags=action?.move?.tags||[];return RIFT_ACTIVE_LOADOUT_SLOT(action)===8||Number(action?.moveIndex)===3||action?.type===`ultimate`||tags.includes(`ultimate`)||tags.includes(`allEnergy`)});ctx.replace(8,{id:`v363-heartbreaker-takeover`,name:`Heartbreaker`,description:`TAKEOVER ${state.remaining}T · FREE ULTIMATE · Viego's own Heartbreaker. The cast resolves, then possession ends immediately.`,glyph:`心`,type:`ultimate`,cost:0,move:{...heart,cost:0,tags:[...(heart.tags||[]).filter(tag=>tag!==`allEnergy`),`ultimate`,`v35TakeoverExit`,`v351FreeHeartbreaker`,`v36TakeoverHeartbreaker`,`v363TakeoverExit`]},moveIndex:3,sourcePower:RIFT_V35_RUINED})});
RIFT_ACTIVE_LOADOUT_REGISTER(`sylas-abduct-recast`,80,ctx=>{const fighter=ctx.fighter;if(!RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)||Number(fighter?.statuses?.v35AbductWindow||0)<=0)return;let recast=ctx.actions.find(action=>(action?.move?.tags||[]).includes(`v35Abduct`)||action?.id===`v351-abduct-recast`);const abscond=ctx.actions.find(action=>(action?.move?.tags||[]).includes(`v35Abscond`));if(!recast&&!abscond)return;const slot=RIFT_ACTIVE_LOADOUT_SLOT(abscond)||RIFT_ACTIVE_LOADOUT_SLOT(recast)||7,recastAction=recast||{...abscond,id:`v363-abduct-recast`,name:`Abduct`,glyph:`鏈`,type:`special`,cost:0,move:{...RIFT_V35_COPY(RIFT_V35_ABDUCT_MOVE),description:RIFT_V351_ABDUCT_DESCRIPTION},moveIndex:2,sourcePower:RIFT_V35_UNSHACKLED};ctx.remove(action=>(action?.move?.tags||[]).includes(`v35Abscond`)||(action?.move?.tags||[]).includes(`v35Abduct`)||action?.id===`v35-abduct`||action?.id===`v351-abduct-recast`);ctx.replace(slot,{...recastAction,id:`v363-abduct-recast`,name:`Abduct`,slot})});

const RIFT_V363_BASE_LA=La;
La=function RIFT_V363_ACTIONS(fighter){return RIFT_ACTIVE_LOADOUT_RESOLVE(fighter,RIFT_V363_BASE_LA(fighter),globalThis.__RIFTBOUND_ACTIVE_RUN__).actions};

function RIFT_V363_IS_TAKEOVER_HEARTBREAKER(fighter,action){const tags=action?.move?.tags||[];return !!fighter?.statuses?.v35Takeover&&(tags.includes(`v35Heartbreaker`)||tags.includes(`v35TakeoverExit`)||tags.includes(`v351FreeHeartbreaker`)||tags.includes(`v36TakeoverHeartbreaker`)||tags.includes(`v363TakeoverExit`))}
const RIFT_V363_BASE_RS=rs;
rs=function RIFT_V363_RESOLVE(run,side,action,ctx={}){const fighter=ctx.attacker||(side===`player`?run?.player:run?.enemy),exitAfter=RIFT_V363_IS_TAKEOVER_HEARTBREAKER(fighter,action),result=RIFT_V363_BASE_RS(run,side,action,ctx);if(exitAfter&&fighter?.statuses?.v35Takeover){RIFT_V35_RESTORE_TAKEOVER(run,fighter,`Heartbreaker cashes out the stolen body`);RIFT_ACTIVE_LOADOUT_CLEAR(fighter,8,`viego-takeover`)}return result};

/* Decay wounds are combat wounds, not a hidden permanent max-HP tax between floors. */
function RIFT_V363_CLEAR_COMBAT_WOUNDS(fighter){if(!fighter?.statuses)return fighter;delete fighter.statuses.decayWound;delete fighter.statuses.decayPoison;delete fighter.statuses.decayPoisonPower;return fighter}
const RIFT_V363_BASE_GI=Gi;
Gi=function RIFT_V363_ENCOUNTER(run,...args){for(const fighter of [run?.player,run?.enemy,...(run?.auxiliaryCombatants||[]).map(entry=>entry?.fighter)].filter(Boolean))RIFT_V363_CLEAR_COMBAT_WOUNDS(fighter);const out=RIFT_V363_BASE_GI(run,...args);for(const fighter of [run?.player,run?.enemy,...(run?.auxiliaryCombatants||[]).map(entry=>entry?.fighter)].filter(Boolean))if(fighter.hp>fighter.maxHp)fighter.hp=fighter.maxHp;return out};

function RIFT_V363_HEARTBREAKER_CUTSCENE(){if(typeof document===`undefined`)return;document.getElementById(`rift-v363-heartbreaker`)?.remove();const node=document.createElement(`div`);node.id=`rift-v363-heartbreaker`;node.innerHTML=`<i class="v363-hb-mist"></i><div class="v363-hb-viego"><i></i><b></b></div><i class="v363-hb-blade"></i><div class="v363-hb-impact"><i></i><b></b></div>`;document.body.appendChild(node);requestAnimationFrame(()=>node.classList.add(`live`));setTimeout(()=>node.classList.add(`descend`),180);setTimeout(()=>node.classList.add(`rupture`),760);setTimeout(()=>node.remove(),RIFT_V363_HEARTBREAKER_CINEMA_MS)}

/* Presentation events keep the existing V35 renderer contract but give Viego richer authored silhouettes. */
const RIFT_V363_BASE_V35_RENDER_FX=RIFT_V35_RENDER_FX;
RIFT_V35_RENDER_FX=function RIFT_V363_VIEGO_RENDER_FX(event,bf){const node=RIFT_V363_BASE_V35_RENDER_FX(event,bf);return node};

if(globalThis.RIFTBOUND_V35)globalThis.RIFTBOUND_V35={...globalThis.RIFTBOUND_V35,activeLoadout:true,hotfix:{...globalThis.RIFTBOUND_V35.hotfix,version:`36.3`,heartbreakerExitAuthoritative:true,viegoPresentation:`v363`}};
globalThis.RIFTBOUND_ACTIVE_LOADOUT={version:RIFT_ACTIVE_LOADOUT_VERSION,register:RIFT_ACTIVE_LOADOUT_REGISTER,resolve:RIFT_ACTIVE_LOADOUT_RESOLVE,current:(fighter,run=globalThis.__RIFTBOUND_ACTIVE_RUN__)=>RIFT_ACTIVE_LOADOUT_RESOLVE(fighter,RIFT_V363_BASE_LA(fighter),run),set:RIFT_ACTIVE_LOADOUT_SET,clear:RIFT_ACTIVE_LOADOUT_CLEAR,state:RIFT_ACTIVE_LOADOUT_STATE};
globalThis.RIFTBOUND_V36_3={version:`36.3`,healthCapFloorReset:true,takeoverHeartbreakerExit:true,rikaManifestationGain:{minimum:6,scale:75},activeLoadout:RIFT_ACTIVE_LOADOUT_VERSION,swoon:`pixel-sweep`,viegoPresentation:true};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,v36:{...globalThis.RIFTBOUND_MANIFEST.v36,hotfix:`36.3`,healthCapFloorReset:true,takeoverHeartbreakerExit:true,rikaManifestationGain:`min 6 · scale 75`,activeLoadout:RIFT_ACTIVE_LOADOUT_VERSION,swoonPixelSweep:true,viegoPresentation:true}};
