const RIFT_V25_MARKER=`Riftbound Armory Complete V25`;
const RIFT_V25_VERSION=25;
function RIFT_V25_COMPATIBLE_SLOT(fighter,item){if(!item)return null;const inventory=Array.isArray(fighter?.inventory)?fighter.inventory:Array(6).fill(null);if(item.category===`Weapon`)return 0;const free=inventory.findIndex((entry,index)=>index>0&&!entry);return free>0?free:Math.max(1,inventory.map((entry,index)=>({entry,index,item:entry?RIFT_ITEM(entry.itemId):null})).filter(row=>row.index>0).sort((a,b)=>(a.item?.price||0)-(b.item?.price||0))[0]?.index||1)}
function RIFT_V25_ITEM_DELTA(fighter,item,plan=null){const consumed=new Set(plan?.consumeUids||[]),delta={};for(const stat of RIFT_ITEM_STAT_KEYS){const removed=RIFT_ITEM_INSTANCES(fighter).filter(instance=>consumed.has(instance.uid)).reduce((sum,instance)=>sum+Number(RIFT_ITEM(instance.itemId)?.stats?.[stat]||0),0);delta[stat]=Number(item?.stats?.[stat]||0)-removed}return delta}
function RIFT_V25_ITEM_DECISION(fighter,item,shards=0){
 if(!fighter||!item)return null;const plan=RIFT_RECIPE_PLAN(fighter,item.id),slot=plan.ok?plan.slot:null,delta=RIFT_V25_ITEM_DELTA(fighter,item,plan),profile=RIFT_V18_POWER_PROFILE(fighter),warnings=[],owned=RIFT_OWNS_ITEM(fighter,item.id),consumed=new Set(plan.consumeUids||[]),current=slot!=null&&fighter.inventory?.[slot]&&!consumed.has(fighter.inventory[slot].uid)?RIFT_ITEM(fighter.inventory[slot].itemId):null;
 if(item.rarity===`Mythical`&&RIFT_ITEM_INSTANCES(fighter).some(instance=>RIFT_ITEM(instance.itemId)?.rarity===`Mythical`&&instance.itemId!==item.id))warnings.push(`Replaces the build's existing Mythical commitment.`);
 if(item.category===`Weapon`&&current&&current.id!==item.id)warnings.push(`Replaces equipped weapon ${current.name}.`);
 if(profile.primary===`as`&&(item.stats?.ap||0)>(item.stats?.as||0)+2)warnings.push(`AP-heavy item on an AS-led power. The passive may still justify it.`);
 if(profile.primary===`ap`&&(item.stats?.as||0)>(item.stats?.ap||0)+2)warnings.push(`AS-heavy item on an AP-led power. Check the passive interaction.`);
 if(!plan.ok)warnings.push(plan.reason||`No legal purchase path is currently available.`);
 const score=RIFT_V18_ITEM_SCORE(fighter,item,{plan,shards}),paths=RIFT_V18_ARCHETYPES(fighter,RIFT_ITEM_CATALOG,shards).filter(path=>path.items.some(entry=>entry.id===item.id)).map(path=>path.name);
 return{itemId:item.id,owned,affordable:!!plan.ok&&plan.cost<=shards,cost:plan.ok?plan.cost:item.price,slot,current:current?{id:current.id,name:current.name}:null,delta,componentsOwned:plan.consumeUids?.length||0,componentsMissing:[...new Set(plan.missing||[])],score,relevance:score>=48?`CORE FIT`:score>=28?`STRONG OPTION`:score>=12?`SPECIALIST OPTION`:`OFF-PATH`,paths,warnings};
}
function RIFT_V25_DECISION_PANEL({item,fighter,plan,shards=0}){const decision=RIFT_V25_ITEM_DECISION(fighter,item,Number(shards||0)),stats=Object.entries(decision?.delta||{}).filter(([,value])=>value);if(!decision)return null;return(0,E.jsxs)(`section`,{className:`v25-decision-panel`,children:[(0,E.jsxs)(`header`,{children:[(0,E.jsx)(`small`,{children:`BUILD DECISION`}),(0,E.jsx)(`strong`,{children:decision.relevance}),(0,E.jsxs)(`span`,{children:[decision.slot==null?`NO LEGAL SLOT`:`SLOT ${decision.slot===0?`W`:decision.slot+1}`,decision.current?` · REPLACES ${decision.current.name.toUpperCase()}`:decision.slot==null?``:` · OPEN` ]})]}),(0,E.jsx)(`div`,{className:`v25-delta-grid`,children:stats.length?stats.map(([stat,value])=>(0,E.jsxs)(`span`,{className:value>0?`gain`:`loss`,children:[(0,E.jsx)(`small`,{children:stat.toUpperCase()}),(0,E.jsx)(`b`,{children:`${value>0?`+`:``}${value}`})]},stat)):(0,E.jsx)(`em`,{children:`Passive-only change · no direct stat delta`})}),(0,E.jsxs)(`footer`,{children:[(0,E.jsxs)(`span`,{children:[decision.componentsOwned,` OWNED · `,decision.componentsMissing.length,` MISSING`]}),(0,E.jsx)(`span`,{children:decision.paths.length?decision.paths.join(` · `):`VALID ALTERNATIVE`})]}),decision.warnings.map((warning,index)=>(0,E.jsxs)(`p`,{children:[(0,E.jsx)(`b`,{children:`!`}),(0,E.jsx)(`span`,{children:warning})]},index))]})}
const RIFT_V25_BASE_SELL=RIFT_SELL_ITEM;
RIFT_SELL_ITEM=function RIFT_V25_SELL(run,slot){const before=run?.player?.inventory?.[slot]?P(run.player.inventory[slot]):null,result=RIFT_V25_BASE_SELL(run,slot);if(result?.ok&&before){run.v25Transactions=run.v25Transactions&&typeof run.v25Transactions===`object`?run.v25Transactions:{};run.v25Transactions.lastSale={id:`sale-${Date.now()}-${before.uid||slot}`,at:Date.now(),slot:Number(slot),instance:before,itemId:before.itemId,refund:Number(result.refund||0),undone:false};result.undoAvailable=true}return result};
function RIFT_V25_UNDO_SALE(run){RIFT_NORMALIZE_RUN_BUILD(run);const sale=run?.v25Transactions?.lastSale;if(!sale||sale.undone)return{ok:false,reason:`No recent sale to undo.`};if(Date.now()-Number(sale.at||0)>1000*60*15)return{ok:false,reason:`The sale undo window has expired.`};if((run.shards||0)<sale.refund)return{ok:false,reason:`The refunded ${sale.refund} Shards were already spent.`};const item=RIFT_ITEM(sale.itemId),owned=RIFT_ITEM_INSTANCES(run.player).map(instance=>RIFT_ITEM(instance.itemId));if(item?.rarity===`Mythical`&&owned.some(entry=>entry?.rarity===`Mythical`&&entry.id!==item.id))return{ok:false,reason:`Another Mythical now occupies the build commitment.`};if(item?.rarity===`Legendary`&&owned.some(entry=>entry?.id===item.id))return{ok:false,reason:`That unique Legendary has already been rebuilt.`};let slot=Number(sale.slot);if(item?.category===`Weapon`){if(run.player.inventory[0])return{ok:false,reason:`The weapon slot is occupied. Clear it before undoing.`};slot=0}else if(slot===0||run.player.inventory[slot])slot=run.player.inventory.findIndex((entry,index)=>index>0&&!entry);if(slot<1&&item?.category!==`Weapon`)return{ok:false,reason:`All five equipment slots are occupied.`};run.player.inventory[slot]=P(sale.instance);run.shards-=sale.refund;sale.undone=true;sale.restoredSlot=slot;RIFT_SYNC_WEAPON(run.player);RIFT_REFRESH_ITEM_POOLS(run.player);run.ownedLegendaries=RIFT_ITEM_INSTANCES(run.player).map(entry=>RIFT_ITEM(entry.itemId)).filter(entry=>entry?.rarity===`Legendary`).map(entry=>entry.id);return{ok:true,message:`RESTORED ${item?.name||`ITEM`} · −${sale.refund} ◆`,slot}}
function RIFT_V25_UNDO_BAR({run,onCommit}){const sale=run?.v25Transactions?.lastSale,active=sale&&!sale.undone&&Date.now()-Number(sale.at||0)<=1000*60*15;if(!active)return null;return(0,E.jsxs)(`div`,{className:`v25-undo-bar`,children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`RECENT SALE`}),(0,E.jsx)(`strong`,{children:RIFT_ITEM(sale.itemId)?.name||`Item`}),(0,E.jsxs)(`em`,{children:[`Refunded `,sale.refund,` ◆ · undo preserves the exact item instance`]})]}),(0,E.jsx)(`button`,{type:`button`,onClick:()=>{const next=P(run),result=RIFT_V25_UNDO_SALE(next);if(result.ok)onCommit(next)},children:`UNDO SALE`})]})}
function RIFT_V25_BUILD_PLAN(fighter,shards=0){return RIFT_V18_ARCHETYPES(fighter,RIFT_ITEM_CATALOG,shards).map(path=>({...path,items:path.items.map(item=>{const plan=RIFT_RECIPE_PLAN(fighter,item.id);return{id:item.id,name:item.name,owned:RIFT_OWNS_ITEM(fighter,item.id),cost:plan.cost,affordable:plan.ok&&plan.cost<=shards,components:plan.consumeUids?.length||0}}),warnings:RIFT_V18_BUILD_WARNINGS(fighter)}))}
const RIFT_V25_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V25_NORMALIZE_RUN_BUILD(run){run=RIFT_V25_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(25,Number(run.riftboundSchemaVersion||0));run.v25Transactions=run.v25Transactions&&typeof run.v25Transactions===`object`?run.v25Transactions:{lastSale:null};return run};
globalThis.RIFTBOUND_ARMORY={version:25,decision:RIFT_V25_ITEM_DECISION,plan:RIFT_V25_BUILD_PLAN,undoSale:RIFT_V25_UNDO_SALE,modes:RIFT_V17_ARMORY_MODES.map(([id])=>id)};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:25,release:`V25 · Armory Complete`,armory:{modes:RIFT_V17_ARMORY_MODES.map(([id])=>id),continuousWorkbench:true,decisionPreview:[`slot`,`statDelta`,`passive`,`recipe`,`components`,`paths`,`conflicts`],undoSale:true,buildPaths:3}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:25,armory:()=>({catalog:RIFT_ITEM_CATALOG.length,modes:RIFT_V17_ARMORY_MODES.length,undoSale:true})};
