const RIFT_V23_MARKER=`Riftbound Interface Reborn V23`;
const RIFT_V23_VERSION=23,RIFT_V23_INPUT_KEY=`riftbound:v23:input`;
const RIFT_V23_DEFAULT_BINDINGS=Object.freeze({confirm:`Enter`,back:`Escape`,map:`m`,armory:`a`,inspect:`i`,buy:`b`,favorite:`f`,compare:`c`,search:`/`,action1:`1`,action2:`2`,action3:`3`,action4:`4`,action5:`5`,action6:`6`,action7:`7`,action8:`8`});
function RIFT_V23_LOAD_INPUT(){let stored={};try{stored=JSON.parse(RIFT_V21_STORAGE().getItem(RIFT_V23_INPUT_KEY)||`{}`)||{}}catch{}return{bindings:{...RIFT_V23_DEFAULT_BINDINGS,...stored.bindings},device:stored.device||`keyboard`,updatedAt:stored.updatedAt||0}}
let RIFT_V23_INPUT=RIFT_V23_LOAD_INPUT();
function RIFT_V23_SAVE_INPUT(){RIFT_V23_INPUT.updatedAt=Date.now();try{RIFT_V21_STORAGE().setItem(RIFT_V23_INPUT_KEY,JSON.stringify(RIFT_V23_INPUT))}catch{}return RIFT_V23_INPUT}
function RIFT_V23_SET_BINDING(action,key){if(!RIFT_V23_DEFAULT_BINDINGS[action])return{ok:false,reason:`Unknown input action.`};key=String(key||``).trim();if(!key)return{ok:false,reason:`A key is required.`};for(const [other,value] of Object.entries(RIFT_V23_INPUT.bindings))if(other!==action&&value.toLowerCase()===key.toLowerCase())return{ok:false,reason:`${key} is already assigned to ${other}.`};RIFT_V23_INPUT.bindings[action]=key;RIFT_V23_SAVE_INPUT();return{ok:true,bindings:{...RIFT_V23_INPUT.bindings}}}
function RIFT_V23_DEVICE(device){if(![`mouse`,`keyboard`,`touch`,`controller`].includes(device)||RIFT_V23_INPUT.device===device)return;RIFT_V23_INPUT.device=device;RIFT_V23_SAVE_INPUT();if(typeof document!==`undefined`){document.documentElement.dataset.riftInput=device;document.querySelector(`#rift-v23-device`)?.replaceChildren(document.createTextNode(device.toUpperCase()))}}
function RIFT_V23_VISIBLE_CONTROLS(root=document){return[...root.querySelectorAll(`button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])`)].filter(node=>{const box=node.getBoundingClientRect(),style=getComputedStyle(node);return box.width>0&&box.height>0&&style.visibility!==`hidden`&&style.display!==`none`})}
function RIFT_V23_FOCUS_GRAPH(root=document){
 const nodes=RIFT_V23_VISIBLE_CONTROLS(root).map(node=>{const rect=node.getBoundingClientRect();return{node,rect,cx:rect.left+rect.width/2,cy:rect.top+rect.height/2}});
 const move=(direction,from=document.activeElement)=>{const current=nodes.find(row=>row.node===from)||nodes[0];if(!current)return null;const vector={left:[-1,0],right:[1,0],up:[0,-1],down:[0,1]}[direction];if(!vector)return null;const ranked=nodes.filter(row=>row!==current).map(row=>{const dx=row.cx-current.cx,dy=row.cy-current.cy,forward=dx*vector[0]+dy*vector[1],cross=Math.abs(dx*vector[1]-dy*vector[0]);return{...row,score:forward>0?forward+cross*2.4:Infinity}}).sort((a,b)=>a.score-b.score);const next=ranked[0]?.node;if(next&&Number.isFinite(ranked[0].score)){next.focus({preventScroll:false});return next}return null};
 return{nodes:nodes.map(row=>row.node),move};
}
const RIFT_V23_ACTION_LISTENERS=new Map();
const RIFT_V23_INPUT_ROUTER=Object.freeze({get bindings(){return{...RIFT_V23_INPUT.bindings}},get device(){return RIFT_V23_INPUT.device},bind:RIFT_V23_SET_BINDING,on(action,listener){if(!RIFT_V23_ACTION_LISTENERS.has(action))RIFT_V23_ACTION_LISTENERS.set(action,new Set());RIFT_V23_ACTION_LISTENERS.get(action).add(listener);return()=>RIFT_V23_ACTION_LISTENERS.get(action)?.delete(listener)},dispatch(action,detail={}){for(const listener of RIFT_V23_ACTION_LISTENERS.get(action)||[])try{listener(detail)}catch{}return action},focusGraph:RIFT_V23_FOCUS_GRAPH});
const RIFT_V23_ACTION_KEYS=Object.freeze({...RIFT_V23_DEFAULT_BINDINGS});
function RIFT_V23_SYNTHETIC_KEY(key){if(typeof document===`undefined`)return;const code=/^\d$/.test(key)?`Digit${key}`:key.length===1?`Key${key.toUpperCase()}`:key;const routed=new KeyboardEvent(`keydown`,{key,code,bubbles:true,cancelable:true});Object.defineProperty(routed,`__riftV23Synthetic`,{value:true});document.dispatchEvent(routed)}
let RIFT_V23_BRIDGES_INSTALLED=false;
function RIFT_V23_INSTALL_BRIDGES(){if(RIFT_V23_BRIDGES_INSTALLED)return;RIFT_V23_BRIDGES_INSTALLED=true;for(const [action,key] of Object.entries(RIFT_V23_ACTION_KEYS))RIFT_V23_INPUT_ROUTER.on(action,detail=>{if(detail?.native||detail?.event?.__riftV23Synthetic)return;if(action===`confirm`&&document.activeElement?.matches?.(`button,a[href],[role="button"]`)){document.activeElement.click();return}RIFT_V23_SYNTHETIC_KEY(key)})}
function RIFT_V23_ROUTE_KEY(event){if(event.__riftV23Synthetic)return null;RIFT_V23_DEVICE(`keyboard`);if([`INPUT`,`TEXTAREA`,`SELECT`].includes(event.target?.tagName))return null;const action=Object.entries(RIFT_V23_INPUT.bindings).find(([,key])=>key.toLowerCase()===event.key.toLowerCase())?.[0];if(!action)return null;const native=RIFT_V23_ACTION_KEYS[action].toLowerCase()===event.key.toLowerCase();if(!native){event.preventDefault();event.stopImmediatePropagation()}RIFT_V23_INPUT_ROUTER.dispatch(action,{event,native});return{action,native}}
function RIFT_V23_SPACE_FOR(node){if(node.closest?.(`.combat-shell,.combat-layout,.tactical-map-backdrop`))return`combat`;if(node.closest?.(`.v17-armory-viewport,.shop-shell,.armory-shell`))return`workshop`;if(node.closest?.(`.route-draft,.intermission,.home-screen,.wheel-stage`))return`ascension`;return`system`}
function RIFT_V23_DECORATE_UI(root=document){
 if(!root?.querySelectorAll)return;for(const surface of root.querySelectorAll(`section,article,aside,nav,header,footer`)){if(!surface.dataset.riftSpace)surface.dataset.riftSpace=RIFT_V23_SPACE_FOR(surface)}for(const button of root.querySelectorAll(`button`)){if(!button.getAttribute(`aria-label`)&&!button.textContent.trim())button.setAttribute(`aria-label`,button.title||`Riftbound control`);button.dataset.riftControl=button.dataset.riftControl||`true`}for(const input of root.querySelectorAll(`input,select,textarea`))input.dataset.riftControl=`true`;
}
function RIFT_V23_SYSTEM_PANEL(){
 if(typeof document===`undefined`||document.getElementById(`rift-v23-system-root`))return;const root=document.createElement(`div`);root.id=`rift-v23-system-root`;root.innerHTML=`<button type="button" id="rift-v23-system-toggle">SYSTEM</button><section hidden><header><span><small>V23 INTERFACE REBORN</small><strong>CONTROL DECK</strong></span><button type="button" data-close>×</button></header><div class="v23-input-readout"><span><small>ACTIVE INPUT</small><strong id="rift-v23-device">${RIFT_V23_INPUT.device.toUpperCase()}</strong></span><span><small>FOCUS GRAPH</small><strong>GEOMETRIC</strong></span></div><div data-bindings></div><footer>Mouse, keyboard, touch, and controller prompts adapt automatically. Every primary workflow remains available without hover.</footer></section>`;document.body.appendChild(root);const panel=root.querySelector(`section`),render=()=>{root.querySelector(`[data-bindings]`).innerHTML=Object.entries(RIFT_V23_INPUT.bindings).slice(0,10).map(([action,key])=>`<button type="button" data-action="${action}"><span>${action.replace(/\d/g,` $&`).toUpperCase()}</span><b>${key.toUpperCase()}</b></button>`).join(``)};root.querySelector(`#rift-v23-system-toggle`).onclick=()=>{panel.hidden=!panel.hidden;render()};root.querySelector(`[data-close]`).onclick=()=>panel.hidden=true;root.addEventListener(`click`,event=>{const target=event.target.closest(`[data-action]`);if(!target)return;const next=prompt(`Key for ${target.dataset.action}:`,RIFT_V23_INPUT.bindings[target.dataset.action]);if(next){const result=RIFT_V23_SET_BINDING(target.dataset.action,next);if(!result.ok)alert(result.reason);render()}});render();
}
let RIFT_V23_GAMEPAD_FRAME=0,RIFT_V23_GAMEPAD_LAST={};
function RIFT_V23_GAMEPAD_LOOP(){if(typeof navigator===`undefined`||!globalThis.requestAnimationFrame)return;const pad=[...(navigator.getGamepads?.()||[])].find(Boolean);if(pad){RIFT_V23_DEVICE(`controller`);const now=performance.now(),pressed=index=>!!pad.buttons[index]?.pressed;if(pressed(0)&&!RIFT_V23_GAMEPAD_LAST[0])document.activeElement?.click?.();if(pressed(1)&&!RIFT_V23_GAMEPAD_LAST[1])RIFT_V23_INPUT_ROUTER.dispatch(`back`);const axes={left:pad.axes[0]<-.6,right:pad.axes[0]>.6,up:pad.axes[1]<-.6,down:pad.axes[1]>.6};for(const [direction,on] of Object.entries(axes))if(on&&now-(RIFT_V23_GAMEPAD_LAST[direction]||0)>190){RIFT_V23_FOCUS_GRAPH().move(direction);RIFT_V23_GAMEPAD_LAST[direction]=now}RIFT_V23_GAMEPAD_LAST[0]=pressed(0);RIFT_V23_GAMEPAD_LAST[1]=pressed(1)}RIFT_V23_GAMEPAD_FRAME=requestAnimationFrame(RIFT_V23_GAMEPAD_LOOP)}
function RIFT_V23_BOOT(){if(typeof document===`undefined`||globalThis.__RIFT_V23_BOOTED__)return;globalThis.__RIFT_V23_BOOTED__=true;document.documentElement.classList.add(`rift-interface-reborn`);document.documentElement.dataset.riftInput=RIFT_V23_INPUT.device;RIFT_V23_DECORATE_UI();RIFT_V23_SYSTEM_PANEL();RIFT_V23_INSTALL_BRIDGES();new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes)if(node.nodeType===1)RIFT_V23_DECORATE_UI(node)}).observe(document.body,{subtree:true,childList:true});addEventListener(`pointerdown`,event=>RIFT_V23_DEVICE(event.pointerType===`touch`?`touch`:`mouse`),{passive:true});addEventListener(`keydown`,RIFT_V23_ROUTE_KEY,true);RIFT_V23_GAMEPAD_LOOP()}
const RIFT_V23_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V23_NORMALIZE_RUN_BUILD(run){run=RIFT_V23_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(23,Number(run.riftboundSchemaVersion||0));run.v23Interface=run.v23Interface&&typeof run.v23Interface===`object`?run.v23Interface:{lastInput:RIFT_V23_INPUT.device};return run};
globalThis.RIFTBOUND_INTERFACE={version:23,input:RIFT_V23_INPUT_ROUTER,focus:RIFT_V23_FOCUS_GRAPH,decorate:RIFT_V23_DECORATE_UI,routeKey:RIFT_V23_ROUTE_KEY,spaces:[`ascension`,`combat`,`workshop`,`system`]};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:23,release:`V23 · Interface Reborn`,interface:{spaces:[`Ascension`,`Combat`,`Workshop`,`System`],inputs:[`mouse`,`keyboard`,`controller`,`touch`],remappable:true,hoverRequired:false,focusGraph:`geometric`}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:23,interface:()=>({device:RIFT_V23_INPUT.device,bindings:{...RIFT_V23_INPUT.bindings},focusables:typeof document===`undefined`?0:RIFT_V23_VISIBLE_CONTROLS().length})};
if(typeof window!==`undefined`){document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,RIFT_V23_BOOT,{once:true}):RIFT_V23_BOOT()}
