/* Riftbound Major Balance V9 Hardening */
const RIFT_V9_HARDENING_VERSION=1;
function RIFT_V9_HAS(fighter,id){return !!RIFT_HAS_PASSIVE(fighter,id)}
function RIFT_V9_STUN_METADATA(entry){const move=entry?.move||entry||{},tags=[...(move.tags||[]),...(entry?.tags||[])].map(tag=>String(tag).toLowerCase());if(tags.some(tag=>tag===`stun`||tag===`applystun`||tag===`status:stun`||tag===`stunning`||/(^|[:_-])stun($|[:_-])/.test(tag)))return true;let blob=``;try{blob=JSON.stringify({status:move.status,statuses:move.statuses,applyStatus:move.applyStatus,effects:move.effects,statusEffect:move.statusEffect}).toLowerCase()}catch{}return /(^|["':,_-])stun(["':,_-]|$)/.test(blob)}
function RIFT_V9_CURSED_SPEECH_METADATA(entry){const move=entry?.move||entry||{},tags=[...(move.tags||[]),...(entry?.tags||[])].map(tag=>String(tag).toLowerCase()),name=String(move.name||entry?.name||``).toLowerCase(),id=String(entry?.id||``).toLowerCase();return name.includes(`cursed speech`)||id.includes(`cursed-speech`)||tags.some(tag=>tag.includes(`cursedspeech`)||tag.includes(`mimiccursedspeech`))}
function RIFT_V9_COPIED_ACTION(action){if(!action)return false;const source=String(action.sourcePower||action.powerName||action.boundPower||``);return String(action.id||``).startsWith(`mimic`)||!!action.mimicryId||!!action.domainTechnique||(source&&source!==`Cursed Child`)||(action.move?.tags||[]).includes(`borrowedPower`)}
function RIFT_V9_COPY_RESTRICTED(entry,domain=false){return RIFT_V9_STUN_METADATA(entry)||(domain&&RIFT_V9_CURSED_SPEECH_METADATA(entry))}

const RIFT_V9_PYRO=RIFT_V9_POWER(`Pyrokinesis`);
if(RIFT_V9_PYRO)RIFT_V9_PYRO.moves.filter(move=>(move.power||0)>0).forEach(move=>RIFT_SCALING_OVERRIDES.set(move.name,{mode:`AP`,as:0,ap:1}));

const RIFT_V9_HARDEN_RECIPE=RIFT_RECIPE_PLAN;
RIFT_RECIPE_PLAN=function RIFT_V9_RECIPE_PLAN(fighter,itemId){const target=RIFT_ITEM(itemId);if(target?.rarity===`Mythical`){const owned=RIFT_ITEM_INSTANCES(fighter).map(instance=>RIFT_ITEM(instance.itemId)).find(item=>item?.rarity===`Mythical`);if(owned)return{ok:false,item:target,reason:`MYTHICAL SLOT OCCUPIED · ${owned.name} must be removed or sold before another Mythical can be bought or completed.`}}return RIFT_V9_HARDEN_RECIPE(fighter,itemId)};

const RIFT_V9_HARDEN_OFFERS=RIFT_SHOP_OFFERS;
RIFT_SHOP_OFFERS=function RIFT_V9_SHOP_OFFERS(floor=1,fighter=null){const offers=RIFT_V9_HARDEN_OFFERS(floor,fighter);return Number(floor)<35?offers.filter(item=>item.rarity!==`Mythical`):offers};

const RIFT_V9_HARDEN_LA=La;
La=function RIFT_V9_HARDEN_ACTIONS(fighter){let actions=RIFT_V9_HARDEN_LA(fighter),active=RIFT_ACTIVE_ITEM(fighter);if(active?.passiveId===`airForce`)actions.push({id:`v9-air-force-wave`,slot:94,name:`AIR WAVE`,description:`Weapon Move. Detonate a directional compressed-air blast. Targets are hurled backward and are stunned if the knockback ends in solid terrain.`,glyph:`風`,type:`weapon`,cost:18,move:{name:`Air Wave`,description:`A concentrated blast of compressed air.`,cost:18,power:1.08,destruction:.72,tags:[`physical`,`weapon`,`force`,`airForceWave`]}});if(RIFT_V9_HAS(fighter,`flyingRaijin`)&&fighter.statuses.v9RaijinMark)actions.push({id:`v9-raijin-teleport`,slot:95,name:`Flying Raijin`,description:`Bonus action. Teleport directly to your most recent valid seal mark.`,glyph:`飛`,type:`special`,cost:0,move:{name:`Flying Raijin`,cost:0,power:0,destruction:0,tags:[`v9RaijinTeleport`,`bonusAction`,`selfCast`]}});if(RIFT_V9_HAS(fighter,`slingRing`)&&fighter.statuses.v9SlingPortal)actions.push({id:`v9-sling-step`,slot:96,name:`Sling Portal`,description:`Bonus action. Fold space toward the selected hostile without traversing intervening terrain.`,glyph:`◎`,type:`special`,cost:0,move:{name:`Sling Portal`,cost:0,power:0,destruction:0,tags:[`v9SlingStep`,`bonusAction`,`selfCast`]}});return actions};

const RIFT_V9_HARDEN_RS=rs;
rs=function RIFT_V9_HARDEN_RESOLVE(run,side,action,ctx={}){const attacker=ctx.attacker||(side===`player`?run.player:run.enemy),actorId=ctx.actorId||RIFT_ACTOR_ID_FOR_FIGHTER(run,attacker)||side,tags=action?.move?.tags||[];if(RIFT_CURSED_CHILD(attacker)&&RIFT_V9_COPIED_ACTION(action)&&RIFT_V9_COPY_RESTRICTED(action,false)){G(run,`MIMICRY REJECTED // ${action.name||action.move?.name||`Copied technique`} applies Stun and cannot be used by Cursed Child's copied/stored move system.`,`system`);return}if(tags.includes(`v9RaijinTeleport`)){const mark=attacker.statuses.v9RaijinMark;if(mark?.position){ki(run,actorId,Wi(run.battlefield,mark.position,Ft(run,actorId).map(entry=>entry.position)));G(run,`FLYING RAIJIN // ${attacker.name} disappears into the seal and reappears at the marked position.`,`mythic`)}delete attacker.statuses.v9RaijinMark;return}if(tags.includes(`v9SlingStep`)){const hostile=U(run,run.activeTargetId)||U(run,side===`player`?`enemy`:`player`),from=W(run,actorId),to=hostile?W(run,hostile.id):from,dx=to.x-from.x,dy=to.y-from.y,len=Math.max(1,Math.hypot(dx,dy)),dest=Wi(run.battlefield,{x:from.x+dx/len*Math.min(10,len*.7),y:from.y+dy/len*Math.min(10,len*.7)},Ft(run,actorId).map(entry=>entry.position));ki(run,actorId,dest);delete attacker.statuses.v9SlingPortal;G(run,`SLING PORTAL // Space folds around ${attacker.name}; intervening terrain never becomes part of the route.`,`mythic`);return}if(RIFT_V9_HAS(attacker,`andurilHeir`)&&(action?.type===`guard`||action?.type===`ultimate`)&&(attacker.statuses.v9Kingship||0)>=3){attacker.statuses.v9Kingship=0;attacker.statuses.v9AndurilRally=2;attacker.posture=Math.max(0,Math.round((attacker.posture||0)*.35));delete attacker.statuses.fearPenalty;delete attacker.statuses.despairPenalty;G(run,`ANDÚRIL · KINGSHIP // Three marks answer the rally. Fear breaks, posture steadies, and the Flame of the West empowers the next two turns.`,`mythic`)}if(RIFT_V9_HAS(attacker,`slingRing`)&&action?.type===`special`&&!tags.includes(`v9SlingStep`))attacker.statuses.v9SlingPortal=1;return RIFT_V9_HARDEN_RS(run,side,action,ctx)};

const RIFT_V9_HARDEN_KATANA=RIFT_KATANA_PROC;
RIFT_KATANA_PROC=function RIFT_V9_KATANA_PROC(run,attacker,target,bound){if(RIFT_V9_COPY_RESTRICTED(bound,false)){G(run,`DOMAIN KATANA REJECTED // Copied techniques that apply Stun cannot be stored in Authentic Mutual Love's katana cycle.`,`system`);return 0}return RIFT_V9_HARDEN_KATANA(run,attacker,target,bound)};

RIFT_DOMAIN_PULSE=function RIFT_V9_HARDEN_DOMAIN_PULSE(run,fighter,actorId){let domain=RIFT_DOMAIN_ACTIVE(run,actorId);if(!domain)return;RIFT_PREP_CURSED_CHILD(fighter);let mimic=RIFT_MIMIC_BY_ID(fighter,fighter.statuses.authenticLoveSureHitId)||fighter.mimicryInventory[0],owner=U(run,actorId),targets=H(run).filter(entry=>entry.id!==actorId&&entry.fighter.hp>0&&(!owner||entry.team!==owner.team)&&Dt(domain,W(run,entry.id)));if(mimic&&!RIFT_V9_COPY_RESTRICTED(mimic,true)){let pow=Math.max(.72,mimic.move.power||1.45),base=(27+Y(fighter,`ap`)*4.8)*pow;targets.forEach(entry=>go(run,fighter,entry.fighter,base,!0,[...(mimic.move.tags||[]),`magic`,`guaranteedHit`,`infinityBypass`,`ignoreDefenseHax`,`domainSureHit`,`noCounter`]));targets.length&&G(run,`AUTHENTIC MUTUAL LOVE · SURE-HIT // ${mimic.name} resolves on ${targets.length} hostile${targets.length===1?``:`s`}.`,`mythic`)}else if(mimic)G(run,`DOMAIN ENGRAVING REJECTED // Cursed Speech and any copied technique carrying Stun metadata cannot become Authentic Mutual Love's sure-hit.`,`system`);let katana=RIFT_ROLL_KATANA(fighter);if(RIFT_V9_COPY_RESTRICTED(katana,false))katana=null;fighter.statuses.authenticLoveWeapon=katana;domain.turns=Math.max(0,(domain.turns||1)-1);domain.turns<=0&&Bo(run,domain,`expired`)};

const RIFT_V9_HARDEN_TO=To;
To=function RIFT_V9_HARDEN_AFTER_HIT(run,attacker,target,tags,damage,action){let actorId=null,restoredPrior=0;if(tags?.includes(`gravityMpCrush`)&&target?.statuses?.gravityMpCut?.amount){actorId=RIFT_ACTOR_ID_FOR_FIGHTER(run,target);if(actorId){restoredPrior=target.statuses.gravityMpCut.amount;Mi(run,actorId,ji(run,actorId)+restoredPrior)}delete target.statuses.gravityMpCut}const hpBefore=target?.hp;RIFT_V9_HARDEN_TO(run,attacker,target,tags,damage,action);if(tags?.includes(`gravityMpCrush`)&&target&&Number.isFinite(hpBefore)){const rawBonus=Math.max(0,hpBefore-target.hp);if(rawBonus>0){target.hp=hpBefore;go(run,attacker,target,rawBonus,!0,[`magic`,`gravity`,`gravityCrushBonus`,`noCounter`,`noItemProc`])}}};

const RIFT_V9_HARDEN_OUT=RIFT_ITEM_OUTGOING;
RIFT_ITEM_OUTGOING=function RIFT_V9_HARDEN_OUTGOING(run,attacker,target,amount,tags=[]){let value=RIFT_V9_HARDEN_OUT(run,attacker,target,amount,tags);if(RIFT_V9_HAS(attacker,`andurilHeir`)&&attacker.statuses.v9AndurilRally>0)value*=1.18;if(RIFT_V9_HAS(attacker,`gunbai`)&&attacker.statuses.v9GunbaiCharge>0&&attacker.statuses.riftItemActionType===`weapon`){value*=1+Math.min(.35,attacker.statuses.v9GunbaiCharge);delete attacker.statuses.v9GunbaiCharge}if(RIFT_V9_HAS(attacker,`blackBarrel`)&&target&&(target.revivals>0||target.statuses?.immortal||target.statuses?.revivalReady))value*=1.25;return value};

const RIFT_V9_HARDEN_IN=RIFT_ITEM_INCOMING;
RIFT_ITEM_INCOMING=function RIFT_V9_HARDEN_INCOMING(run,attacker,target,amount,tags=[]){let value=RIFT_V9_HARDEN_IN(run,attacker,target,amount,tags);if(RIFT_V9_HAS(target,`gunbai`)&&target.guard&&tags.some(tag=>[`projectile`,`magic`,`energy`].includes(tag))){target.statuses.v9GunbaiCharge=Math.min(.35,(target.statuses.v9GunbaiCharge||0)+.12)}if(RIFT_V9_HAS(target,`stoneMask`)&&tags.some(tag=>[`light`,`sun`,`holy`,`radiant`].includes(String(tag).toLowerCase())))value*=1.35;return value};

const RIFT_V9_HARDEN_AFTER=RIFT_ITEM_AFTER_DAMAGE;
RIFT_ITEM_AFTER_DAMAGE=function RIFT_V9_HARDEN_ITEM_AFTER(run,attacker,target,damage,tags=[]){RIFT_V9_HARDEN_AFTER(run,attacker,target,damage,tags);if(damage<=0||tags.includes(`itemProc`)||tags.includes(`noItemProc`))return;const actionType=attacker?.statuses?.riftItemActionType;if(RIFT_V9_HAS(attacker,`andurilHeir`)&&actionType===`weapon`){const item=RIFT_HAS_PASSIVE(attacker,`andurilHeir`);if(RIFT_ITEM_PROC_ONCE(run,attacker,item,`kingship`)){attacker.statuses.v9Kingship=Math.min(3,(attacker.statuses.v9Kingship||0)+1);G(run,`ANDÚRIL · KINGSHIP ${attacker.statuses.v9Kingship}/3 // The reforged blade gathers authority from a clean hit.`,`mythic`)}}if(RIFT_V9_HAS(attacker,`flyingRaijin`)&&actionType===`weapon`){attacker.statuses.v9RaijinMark={position:{...Oo(run,target)},turns:3};G(run,`FLYING RAIJIN SEAL // ${target.name}'s position is marked for instantaneous return.`,`mythic`)}if(RIFT_V9_HAS(attacker,`moonlightGreatsword`)&&actionType===`weapon`&&attacker.energy/Math.max(1,attacker.maxEnergy)>.5){const item=RIFT_HAS_PASSIVE(attacker,`moonlightGreatsword`);if(RIFT_ITEM_PROC_ONCE(run,attacker,item,`moonlightWave`))RIFT_ITEM_PROC_DAMAGE(run,attacker,target,Math.max(1,Math.round(damage*.24)),item,[`magic`,`moonlightWave`])}if(RIFT_V9_HAS(attacker,`hogyoku`)&&attacker.statuses.v9Hogyoku){for(const key of [`stun`,`blind`,`restrain`,`speedDown`,`skillDown`,`antiRegen`,`defenseDown`,`despairPenalty`])if(attacker.statuses[key]){delete attacker.statuses[key];G(run,`HŌGYOKU ADAPTATION // ${key} is shed during evolution.`,`mythic`);break}}};

const RIFT_V9_HARDEN_TURN=RIFT_ITEM_TURN_END;
RIFT_ITEM_TURN_END=function RIFT_V9_HARDEN_TURN_END(run,fighter){const gravity=fighter?.statuses?.gravityMpCut?{...fighter.statuses.gravityMpCut}:null,actorId=gravity?RIFT_ACTOR_ID_FOR_FIGHTER(run,fighter):null,maxBefore=actorId?ji(run,actorId):0;RIFT_V9_HARDEN_TURN(run,fighter);if(gravity?.turns===1&&actorId&&!fighter.statuses.gravityMpCut){const restored=Math.max(1,maxBefore+(gravity.amount||0));Mi(run,actorId,restored);Ai(run,actorId,Math.min(restored,Oi(run,actorId)+(gravity.amount||0)));G(run,`GRAVITY CRUSH ENDS // ${fighter.name}'s ${Number(gravity.amount||0).toFixed(1)} suppressed MP returns.`,fighter===run.player?`player`:`enemy`)}if(fighter.statuses.v9AndurilRally>0&&--fighter.statuses.v9AndurilRally<=0)delete fighter.statuses.v9AndurilRally;if(fighter.statuses.v9RaijinMark?.turns>0&&--fighter.statuses.v9RaijinMark.turns<=0)delete fighter.statuses.v9RaijinMark;if(RIFT_V9_HAS(fighter,`sandevistan`)){const id=RIFT_ACTOR_ID_FOR_FIGHTER(run,fighter);if(id&&Oi(run,id)<=ji(run,id)*.25){fighter.statuses.v9SandevistanHeat=Math.min(4,(fighter.statuses.v9SandevistanHeat||0)+1);fighter.statuses.speedBuff=Math.max(fighter.statuses.speedBuff||0,2);if(fighter.statuses.v9SandevistanHeat>1)go(run,fighter,fighter,Math.max(1,Math.round(fighter.maxHp*.025*fighter.statuses.v9SandevistanHeat)),!1,[`physical`,`selfDamage`,`sandevistanRecoil`,`noCounter`,`noItemProc`]);G(run,`SANDEVISTAN // Time dilates at low MP. Speed surges; neural heat rises to ${fighter.statuses.v9SandevistanHeat}/4.`,`mythic`)}else fighter.statuses.v9SandevistanHeat=Math.max(0,(fighter.statuses.v9SandevistanHeat||0)-1)}if(RIFT_V9_HAS(fighter,`millenniumPuzzle`)&&run.enemyIntent&&fighter===run.player&&fighter.statuses.v9PuzzleTurn!==run.turn){fighter.statuses.v9PuzzleTurn=run.turn;fighter.ultimate=Math.min(100,(fighter.ultimate||0)+4);G(run,`MILLENNIUM PUZZLE // Reading the revealed intent adds 4 Ultimate charge.`,`mythic`)}};

if(typeof window!==`undefined`&&window.RIFTBOUND_V9_DEBUG){Object.assign(window.RIFTBOUND_V9_DEBUG,{markFloor50(){let m=RIFT_V9_META();m.calamityUnlocked=true;return RIFT_V9_SAVE_META(m)},testMythicalLimit(run){const mythics=RIFT_ITEM_CATALOG.filter(item=>item.rarity===`Mythical`);return mythics.slice(0,2).map(item=>({id:item.id,result:RIFT_RECIPE_PLAN(run.player,item.id)}))},testOpenDomain(run){run.player.statuses.openDomain=1;return run.player.statuses.openDomain},grantExtraVessel(run){run.player.statuses.vesselExtra=1;return Gn(run.player)},testRikaBar(run,value=100){run.player.statuses.rikaSummon=M(Number(value)||0,0,100);return run.player.statuses.rikaSummon},testEnemyBuild(run){RIFT_V9_GIVE_ENEMY_ITEMS(run,run.enemy);return run.enemy.inventory},testSpeedsterRewind(run){return(run.v9UltimateTimeline||[]).slice(-3)}})}
