/* V36.2 · browser-runtime stability, Codex reconciliation, and one-shot SWOON cinematic */
const RIFT_V362_SWOON_CINEMA_MS=1500;
function RIFT_V362_VALID_POINT(point){return !!point&&Number.isFinite(Number(point.x))&&Number.isFinite(Number(point.y))}
function RIFT_V362_COPY_POINT(point){return{x:Number(point.x),y:Number(point.y)}}
function RIFT_V362_ENTRY_POINT(run,entry){if(RIFT_V362_VALID_POINT(entry?.position))return RIFT_V362_COPY_POINT(entry.position);if(RIFT_V362_VALID_POINT(entry?.pos))return RIFT_V362_COPY_POINT(entry.pos);try{const id=entry?.id||RIFT_V36_ACTOR(run,entry?.fighter),point=id?W(run,id):null;if(RIFT_V362_VALID_POINT(point))return RIFT_V362_COPY_POINT(point)}catch{}if(entry?.fighter===run?.player&&RIFT_V362_VALID_POINT(run?.battlefield?.player))return RIFT_V362_COPY_POINT(run.battlefield.player);if(entry?.fighter===run?.enemy&&RIFT_V362_VALID_POINT(run?.battlefield?.enemy))return RIFT_V362_COPY_POINT(run.battlefield.enemy);return null}
RIFT_V36_POINT=function RIFT_V362_POINT(run,thing){const battlefield=run?.battlefield;if(!battlefield)return{x:0,y:0};if(RIFT_V362_VALID_POINT(thing))return RIFT_V362_COPY_POINT(thing);const id=typeof thing===`string`?thing:RIFT_V36_ACTOR(run,thing);try{const point=id?W(run,id):null;if(RIFT_V362_VALID_POINT(point))return RIFT_V362_COPY_POINT(point)}catch{}if(thing===run?.player&&RIFT_V362_VALID_POINT(battlefield.player))return RIFT_V362_COPY_POINT(battlefield.player);if(thing===run?.enemy&&RIFT_V362_VALID_POINT(battlefield.enemy))return RIFT_V362_COPY_POINT(battlefield.enemy);return{x:(Number(battlefield.width)||100)/2,y:(Number(battlefield.height)||64)/2}};
RIFT_V36_SEGMENT_DISTANCE=function RIFT_V362_SEGMENT_DISTANCE(point,start,end){if(!RIFT_V362_VALID_POINT(point)||!RIFT_V362_VALID_POINT(start)||!RIFT_V362_VALID_POINT(end))return Infinity;const p=RIFT_V362_COPY_POINT(point),a=RIFT_V362_COPY_POINT(start),b=RIFT_V362_COPY_POINT(end),dx=b.x-a.x,dy=b.y-a.y,length2=dx*dx+dy*dy;if(!length2)return Math.hypot(p.x-a.x,p.y-a.y);const t=M(((p.x-a.x)*dx+(p.y-a.y)*dy)/length2,0,1),qx=a.x+t*dx,qy=a.y+t*dy;return Math.hypot(p.x-qx,p.y-qy)};
RIFT_V36_DASH=function RIFT_V362_DASH(run,fighter,target,maxDistance){const id=RIFT_V36_ACTOR(run,fighter);if(!id||!run?.battlefield)return null;const from=RIFT_V36_POINT(run,fighter),to=RIFT_V36_POINT(run,target);if(!RIFT_V362_VALID_POINT(from)||!RIFT_V362_VALID_POINT(to))return null;const dx=to.x-from.x,dy=to.y-from.y,distance=Math.max(.001,Math.hypot(dx,dy)),scale=Math.min(1,Math.max(0,Number(maxDistance)||0)/distance),wanted={x:from.x+dx*scale,y:from.y+dy*scale};let occupied=[];try{occupied=(Ft(run,id)||[]).map(entry=>entry?.position||entry?.pos).filter(RIFT_V362_VALID_POINT).map(RIFT_V362_COPY_POINT)}catch{}let dest;try{dest=Wi(run.battlefield,wanted,occupied)}catch{dest=wanted}if(!RIFT_V362_VALID_POINT(dest))dest=wanted;if(!RIFT_V362_VALID_POINT(dest))return null;ki(run,id,dest);return{from,dest:RIFT_V362_COPY_POINT(dest),id}};
RIFT_V36_PROCESS_WORLD=function RIFT_V362_PROCESS_WORLD(run){if(!run?.battlefield||run.battlefield.v36ProcessedTurn===run.turn)return;run.battlefield.v36ProcessedTurn=run.turn;const features=Array.isArray(run.battlefield.features)?run.battlefield.features:[],keep=[];for(const feature of features){const featurePoint=RIFT_V362_VALID_POINT(feature?.position)?RIFT_V362_COPY_POINT(feature.position):null;if(feature?.v36CrystalDue&&Number(run.turn||0)>=Number(feature.dueTurn||0)){if(featurePoint)for(const entry of H(run).filter(row=>row.kind===`fighter`&&row.fighter?.hp>0)){const entryPoint=RIFT_V362_ENTRY_POINT(run,entry);if(entryPoint&&Math.hypot(entryPoint.x-featurePoint.x,entryPoint.y-featurePoint.y)<=Number(feature.radius||0)){go(run,feature.owner||run.player,entry.fighter,feature.damage||28,true,[`magic`,`area`,`corrosive`,`v36CrystalRain`,`noItemProc`]);entry.fighter.statuses=entry.fighter.statuses||{};entry.fighter.statuses.v36Corrosion=Math.max(Number(entry.fighter.statuses.v36Corrosion||0),feature.corrosionTurns||2)}}if(featurePoint)RIFT_V36_FX(run,`crystal-rain`,feature.owner||run.player,featurePoint,{radius:feature.radius,accent:`#7b39e8`});continue}if(feature?.v36DecayPatch){if(Number(feature.expiresTurn||0)<=Number(run.turn||0))continue;if(feature.lastTick!==run.turn){feature.lastTick=run.turn;if(featurePoint)for(const entry of H(run).filter(row=>row.kind===`fighter`&&row.fighter?.hp>0)){const entryPoint=RIFT_V362_ENTRY_POINT(run,entry);if(entry.fighter!==feature.owner&&entryPoint&&Math.hypot(entryPoint.x-featurePoint.x,entryPoint.y-featurePoint.y)<=Number(feature.radius||0))go(run,feature.owner||run.player,entry.fighter,feature.damage||18,true,[`magic`,`area`,`decay`,`environment`,`v36DecayGroundTick`,`noItemProc`])}}}keep.push(feature)}run.battlefield.features=keep};

/* The V36 catalog is already authored for the Symbol rework. Never send it back through V31.1's frozen pre-rework order checker. */
RIFT_V31_BUILD_CATALOG=function RIFT_V362_BUILD_CATALOG(){return RIFT_V36_CATALOG};
if(globalThis.RIFTBOUND_CODEX)globalThis.RIFTBOUND_CODEX={...globalThis.RIFTBOUND_CODEX,version:36,release:`Shadows Converge`,build:()=>RIFT_V36_CATALOG,catalog:()=>RIFT_V36_CATALOG};

globalThis.RIFTBOUND_V36_2={version:`36.2`,geometrySafe:true,codexReconciled:true,symbolBuiltinsVisible:true,swoonSingleCinematic:true};
