const RIFT_V21_MARKER=`Riftbound Preservation Boundary V21`;
const RIFT_V21_VERSION=21;
const RIFT_V21_PROFILE_KEY=`riftbound-profile-v1`,RIFT_V21_RUN_KEY=`riftbound-run-v1`;
const RIFT_V21_VAULT_KEY=`riftbound:v21:save-vault`,RIFT_V21_BACKUP_KEY=`riftbound:v21:backups`;
const RIFT_V21_MEMORY_STORAGE=new Map();
function RIFT_V21_STORAGE(){if(typeof localStorage!==`undefined`)return localStorage;return{getItem:key=>RIFT_V21_MEMORY_STORAGE.has(key)?RIFT_V21_MEMORY_STORAGE.get(key):null,setItem:(key,value)=>RIFT_V21_MEMORY_STORAGE.set(key,String(value)),removeItem:key=>RIFT_V21_MEMORY_STORAGE.delete(key)}}
function RIFT_V21_CANONICAL(value){
 if(value===null||typeof value!==`object`)return JSON.stringify(value);
 if(Array.isArray(value))return`[${value.map(RIFT_V21_CANONICAL).join(`,`)}]`;
 return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${RIFT_V21_CANONICAL(value[key])}`).join(`,`)}}`;
}
function RIFT_V21_HASH(value){const text=typeof value===`string`?value:RIFT_V21_CANONICAL(value);let hash=2166136261;for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,`0`)}
function RIFT_V21_MOVE_FINGERPRINT(move,index,channel=`body`){
 const mechanical={};for(const key of [`cooldown`,`turnCooldown`,`uses`,`duration`,`radius`,`range`,`chance`,`threshold`,`limit`,`resource`,`requires`,`condition`])if(move?.[key]!==void 0)mechanical[key]=P(move[key]);
 return{index,channel,name:String(move?.name||`Unknown`),cost:Number(move?.cost||0),power:Number(move?.power||0),destruction:Number(move?.destruction||0),hits:Number(move?.hits||1),tags:[...(move?.tags||[])].map(String).sort(),mechanical};
}
function RIFT_V21_ABILITY_ROWS(){
 const rows=[],seen=new Set(),add=(definition,kind=`power`,moves=definition?.moves||[],channel=`body`)=>{if(!definition||!Array.isArray(moves)||!moves.length)return;const key=`${kind}:${definition.name}:${channel}`;if(seen.has(key))return;seen.add(key);rows.push({kind,name:String(definition.name||`Unknown`),channel,rarity:String(definition.rarity||definition.rarityLabel||`Unknown`),damageType:String(definition.damageType||`Special`),passive:String(definition.passive||``),rollable:definition.rollable!==false,enemyRollable:definition.enemyRollable!==false,moves:moves.map((move,index)=>RIFT_V21_MOVE_FINGERPRINT(move,index,channel))})};
 try{g.forEach(power=>add(power,`power`,power.moves,`body`))}catch{}
 try{h.forEach(stand=>{add(stand,`stand`,stand.moves||stand.partial||stand.summoned,`stand`);if(stand.evolved)add({...stand.evolved,name:stand.evolved.name||`${stand.name} · Evolved`},`stand-evolution`,stand.evolved.moves,`stand`)})}catch{}
 return rows.sort((a,b)=>`${a.kind}:${a.name}:${a.channel}`.localeCompare(`${b.kind}:${b.name}:${b.channel}`));
}
function RIFT_V21_ABILITY_CONSTITUTION(){const abilities=RIFT_V21_ABILITY_ROWS(),payload={contractVersion:1,capturedFrom:`V20.0.1`,abilities};return Object.freeze({...payload,counts:{abilities:abilities.length,moves:abilities.reduce((sum,row)=>sum+row.moves.length,0)},hash:RIFT_V21_HASH(payload)})}
const RIFT_V21_CONSTITUTION=RIFT_V21_ABILITY_CONSTITUTION();
const RIFT_V21_EXPECTED_HASH=`7598b438`;
function RIFT_V21_ASSERT_CONSTITUTION(){const current=RIFT_V21_ABILITY_CONSTITUTION();return{ok:current.hash===RIFT_V21_EXPECTED_HASH,expected:RIFT_V21_EXPECTED_HASH,actual:current.hash,counts:current.counts}}
function RIFT_V21_READ_JSON(key,fallback){try{const raw=RIFT_V21_STORAGE().getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function RIFT_V21_WRITE_JSON(key,value){RIFT_V21_STORAGE().setItem(key,JSON.stringify(value));return value}
function RIFT_V21_BACKUPS(){const rows=RIFT_V21_READ_JSON(RIFT_V21_BACKUP_KEY,[]);return Array.isArray(rows)?rows:[]}
function RIFT_V21_BACKUP_RAW(raw,label=`recovery`){
 try{const parsed=typeof raw===`string`?JSON.parse(raw):P(raw),rows=RIFT_V21_BACKUPS(),hash=RIFT_V21_HASH(parsed);if(rows[0]?.hash===hash&&rows[0]?.label===label)return rows[0];const entry={id:`backup-${Date.now()}-${hash}`,label:String(label).slice(0,40),at:Date.now(),hash,run:parsed};rows.unshift(entry);RIFT_V21_WRITE_JSON(RIFT_V21_BACKUP_KEY,rows.slice(0,8));return entry}catch{return null}
}
function RIFT_V21_CAPTURE_BACKUP(label=`automatic`){
 const storage=RIFT_V21_STORAGE(),profile=RIFT_V21_READ_JSON(RIFT_V21_PROFILE_KEY,null),run=RIFT_V21_READ_JSON(RIFT_V21_RUN_KEY,null);if(!profile&&!run)return null;
 const payload={profile,run},rows=RIFT_V21_BACKUPS(),hash=RIFT_V21_HASH(payload);if(rows[0]?.hash===hash)return rows[0];const entry={id:`backup-${Date.now()}-${hash}`,label:String(label).slice(0,40),at:Date.now(),hash,...payload};rows.unshift(entry);RIFT_V21_WRITE_JSON(RIFT_V21_BACKUP_KEY,rows.slice(0,8));return entry;
}
let RIFT_V21_LAST_WRITE_HASH={};
function RIFT_V21_WRITE_STORAGE(key,value,label=`save`){
 const storage=RIFT_V21_STORAGE(),next=JSON.stringify(value),hash=RIFT_V21_HASH(next),previous=storage.getItem(key);if(previous&&RIFT_V21_LAST_WRITE_HASH[key]!==hash)RIFT_V21_CAPTURE_BACKUP(`${label}-write`);storage.setItem(key,next);RIFT_V21_LAST_WRITE_HASH[key]=hash;return value;
}
function RIFT_V21_VAULT(){const vault=RIFT_V21_READ_JSON(RIFT_V21_VAULT_KEY,{version:21,activeId:null,slots:[]});vault.version=21;vault.slots=Array.isArray(vault.slots)?vault.slots.slice(0,12):[];return vault}
function RIFT_V21_SLOT_CREATE(name=`Ascension`){const vault=RIFT_V21_VAULT(),profile=RIFT_V21_READ_JSON(RIFT_V21_PROFILE_KEY,null),run=RIFT_V21_READ_JSON(RIFT_V21_RUN_KEY,null),slot={id:`slot-${Date.now()}-${RIFT_V21_HASH(name).slice(0,4)}`,name:String(name||`Ascension`).trim().slice(0,32)||`Ascension`,createdAt:Date.now(),updatedAt:Date.now(),profile,run,hash:RIFT_V21_HASH({profile,run})};vault.slots.unshift(slot);vault.activeId=slot.id;RIFT_V21_WRITE_JSON(RIFT_V21_VAULT_KEY,vault);return slot}
function RIFT_V21_SLOT_UPDATE(id){const vault=RIFT_V21_VAULT(),slot=vault.slots.find(row=>row.id===id);if(!slot)return{ok:false,reason:`Save slot not found.`};slot.profile=RIFT_V21_READ_JSON(RIFT_V21_PROFILE_KEY,null);slot.run=RIFT_V21_READ_JSON(RIFT_V21_RUN_KEY,null);slot.updatedAt=Date.now();slot.hash=RIFT_V21_HASH({profile:slot.profile,run:slot.run});vault.activeId=id;RIFT_V21_WRITE_JSON(RIFT_V21_VAULT_KEY,vault);return{ok:true,slot}}
function RIFT_V21_SLOT_ACTIVATE(id,{reload=true}={}){const vault=RIFT_V21_VAULT(),slot=vault.slots.find(row=>row.id===id);if(!slot)return{ok:false,reason:`Save slot not found.`};RIFT_V21_CAPTURE_BACKUP(`slot-switch`);const storage=RIFT_V21_STORAGE();slot.profile?storage.setItem(RIFT_V21_PROFILE_KEY,JSON.stringify(slot.profile)):storage.removeItem(RIFT_V21_PROFILE_KEY);slot.run?storage.setItem(RIFT_V21_RUN_KEY,JSON.stringify(slot.run)):storage.removeItem(RIFT_V21_RUN_KEY);vault.activeId=id;RIFT_V21_WRITE_JSON(RIFT_V21_VAULT_KEY,vault);if(reload&&typeof location!==`undefined`)location.reload();return{ok:true,slot}}
function RIFT_V21_SLOT_REMOVE(id){const vault=RIFT_V21_VAULT(),before=vault.slots.length;vault.slots=vault.slots.filter(row=>row.id!==id);if(vault.activeId===id)vault.activeId=null;RIFT_V21_WRITE_JSON(RIFT_V21_VAULT_KEY,vault);return{ok:vault.slots.length<before}}
function RIFT_V21_RESTORE_BACKUP(id,{reload=true}={}){const row=RIFT_V21_BACKUPS().find(entry=>entry.id===id);if(!row)return{ok:false,reason:`Backup not found.`};const storage=RIFT_V21_STORAGE();if(`profile`in row)row.profile?storage.setItem(RIFT_V21_PROFILE_KEY,JSON.stringify(row.profile)):storage.removeItem(RIFT_V21_PROFILE_KEY);if(`run`in row)row.run?storage.setItem(RIFT_V21_RUN_KEY,JSON.stringify(row.run)):storage.removeItem(RIFT_V21_RUN_KEY);if(reload&&typeof location!==`undefined`)location.reload();return{ok:true,row}}
function RIFT_V21_VAULT_EXPORT(){return{format:`riftbound-remastered-vault`,version:21,exportedAt:new Date().toISOString(),constitutionHash:RIFT_V21_CONSTITUTION.hash,vault:RIFT_V21_VAULT(),backups:RIFT_V21_BACKUPS()}}
function RIFT_V21_VAULT_IMPORT(payload){if(payload?.format!==`riftbound-remastered-vault`||!payload.vault)throw Error(`Invalid Riftbound Save Vault`);if(payload.constitutionHash&&payload.constitutionHash!==RIFT_V21_EXPECTED_HASH)throw Error(`Save Vault ability constitution mismatch`);RIFT_V21_CAPTURE_BACKUP(`vault-import`);RIFT_V21_WRITE_JSON(RIFT_V21_VAULT_KEY,{...payload.vault,version:21});if(Array.isArray(payload.backups))RIFT_V21_WRITE_JSON(RIFT_V21_BACKUP_KEY,payload.backups.slice(0,8));return RIFT_V21_VAULT()}
const RIFT_V21_REPLAY_STATE={seed:null,startedAt:0,inputs:[],snapshots:[]};
function RIFT_V21_REPLAY_BEGIN(seed=`rift-${Date.now()}`){RIFT_V21_REPLAY_STATE.seed=String(seed);RIFT_V21_REPLAY_STATE.startedAt=Date.now();RIFT_V21_REPLAY_STATE.inputs=[];RIFT_V21_REPLAY_STATE.snapshots=[];return RIFT_V21_REPLAY_STATE.seed}
function RIFT_V21_REPLAY_RECORD(kind,payload,state=null){const row={index:RIFT_V21_REPLAY_STATE.inputs.length,kind:String(kind),payload:P(payload),stateHash:state?RIFT_V21_HASH(state):null};RIFT_V21_REPLAY_STATE.inputs.push(row);if(RIFT_V21_REPLAY_STATE.inputs.length>600)RIFT_V21_REPLAY_STATE.inputs.shift();return row}
function RIFT_V21_REPLAY_EXPORT(){const replay={version:21,seed:RIFT_V21_REPLAY_STATE.seed,startedAt:RIFT_V21_REPLAY_STATE.startedAt,inputs:P(RIFT_V21_REPLAY_STATE.inputs),constitutionHash:RIFT_V21_CONSTITUTION.hash};return{...replay,hash:RIFT_V21_HASH(replay)}}
function RIFT_V21_GOLDEN_SCENARIO(name,initialState,inputs,finalState){const scenario={name:String(name),constitutionHash:RIFT_V21_CONSTITUTION.hash,initialHash:RIFT_V21_HASH(initialState),inputHash:RIFT_V21_HASH(inputs),finalHash:RIFT_V21_HASH(finalState)};return{...scenario,hash:RIFT_V21_HASH(scenario)}}
function RIFT_V21_SAVE_VAULT_UI(){
 if(typeof document===`undefined`||document.getElementById(`rift-v21-vault-root`))return;const root=document.createElement(`div`);root.id=`rift-v21-vault-root`;root.innerHTML=`<button type="button" id="rift-v21-vault-toggle">SAVES</button><section hidden><header><span><small>V21 PRESERVATION</small><strong>SAVE VAULT</strong></span><button type="button" data-close>×</button></header><div data-summary></div><div data-slots></div><footer><button type="button" data-create>NEW SNAPSHOT</button><button type="button" data-download>EXPORT VAULT</button></footer></section>`;document.body.appendChild(root);const panel=root.querySelector(`section`),render=()=>{const vault=RIFT_V21_VAULT(),backups=RIFT_V21_BACKUPS();root.querySelector(`[data-summary]`).innerHTML=`<b>${vault.slots.length} NAMED SLOTS</b><span>${backups.length} recovery points · ability lock ${RIFT_V21_CONSTITUTION.hash}</span>`;root.querySelector(`[data-slots]`).innerHTML=vault.slots.length?vault.slots.map(slot=>`<article><span><strong>${String(slot.name).replace(/[<>&]/g,``)}</strong><small>${slot.run?`FLOOR ${slot.run.floor||1}`:`PROFILE`} · ${new Date(slot.updatedAt).toLocaleString()}</small></span><button type="button" data-load="${slot.id}">LOAD</button><button type="button" data-update="${slot.id}">UPDATE</button></article>`).join(``):`<p>No named slots yet. Your normal local save is still protected automatically.</p>`};root.querySelector(`#rift-v21-vault-toggle`).onclick=()=>{panel.hidden=!panel.hidden;render()};root.querySelector(`[data-close]`).onclick=()=>panel.hidden=true;root.querySelector(`[data-create]`).onclick=()=>{const name=prompt(`Name this run snapshot:`,`Ascension ${RIFT_V21_VAULT().slots.length+1}`);if(name)RIFT_V21_SLOT_CREATE(name);render()};root.querySelector(`[data-download]`).onclick=()=>{const blob=new Blob([JSON.stringify(RIFT_V21_VAULT_EXPORT(),null,2)],{type:`application/json`}),url=URL.createObjectURL(blob),a=document.createElement(`a`);a.href=url;a.download=`riftbound-remastered-vault.json`;a.click();URL.revokeObjectURL(url)};root.addEventListener(`click`,event=>{const load=event.target.closest(`[data-load]`),update=event.target.closest(`[data-update]`);if(load&&confirm(`Load this save slot? The current state will be backed up first.`))RIFT_V21_SLOT_ACTIVATE(load.dataset.load);if(update){RIFT_V21_SLOT_UPDATE(update.dataset.update);render()}});render();
}
const RIFT_V21_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V21_NORMALIZE_RUN_BUILD(run){run=RIFT_V21_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(21,Number(run.riftboundSchemaVersion||0));run.v21Preservation=run.v21Preservation&&typeof run.v21Preservation===`object`?run.v21Preservation:{constitutionHash:RIFT_V21_CONSTITUTION.hash,replaySeed:null};run.v21Preservation.constitutionHash=RIFT_V21_CONSTITUTION.hash;return run};
globalThis.RIFTBOUND_PRESERVATION={version:21,constitution:()=>RIFT_V21_ABILITY_CONSTITUTION(),assert:RIFT_V21_ASSERT_CONSTITUTION,hash:RIFT_V21_HASH,golden:RIFT_V21_GOLDEN_SCENARIO,replay:{begin:RIFT_V21_REPLAY_BEGIN,record:RIFT_V21_REPLAY_RECORD,export:RIFT_V21_REPLAY_EXPORT},saves:{vault:RIFT_V21_VAULT,create:RIFT_V21_SLOT_CREATE,update:RIFT_V21_SLOT_UPDATE,activate:RIFT_V21_SLOT_ACTIVATE,remove:RIFT_V21_SLOT_REMOVE,backups:RIFT_V21_BACKUPS,restore:RIFT_V21_RESTORE_BACKUP,export:RIFT_V21_VAULT_EXPORT,import:RIFT_V21_VAULT_IMPORT}};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:21,release:`V21 · Preservation`,preservation:{constitutionHash:RIFT_V21_CONSTITUTION.hash,abilities:RIFT_V21_CONSTITUTION.counts.abilities,moves:RIFT_V21_CONSTITUTION.counts.moves,saveSlots:true,backups:8,replays:true}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:21,preservation:RIFT_V21_ASSERT_CONSTITUTION};
if(typeof window!==`undefined`){const boot=()=>RIFT_V21_SAVE_VAULT_UI();document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,boot,{once:true}):boot()}
