Object.assign(RIFT_V35_PREVIEW,{[`${RIFT_V36_KNIGHT}|Crystal Barrage`]:{pattern:`point-delayed-area`,geometry:{shape:`area`,range:34,radius:10},acquisition:`Choose a large Dark region.`,resolution:`The floor is marked first; crystal rain falls one combatant turn later.`,aftermath:`Corrosive damage and temporary Durability erosion.`},[`${RIFT_V36_KNIGHT}|Dark Sword`]:{pattern:`projectile-multi`,geometry:{shape:`projectile`,range:36,radius:2.6},acquisition:`Aim the sword-bullet lane.`,resolution:`Three blades manifest behind the Knight and fire in sequence.`,aftermath:`Each contact can trigger ordinary on-hit passives.`},[`${RIFT_V36_KNIGHT}|Slice`]:{pattern:`line-slash-delayed`,geometry:{shape:`line`,range:24,radius:3.4},acquisition:`Aim the extended sword arc.`,resolution:`A long void blade crosses the lane.`,aftermath:`A successful hit seeds next-turn Dark crystals at the impact point.`},[`${RIFT_V36_KNIGHT}|SWOON`]:{pattern:`global-slash`,geometry:{shape:`global`,range:9999,radius:9999},acquisition:`Global.`,resolution:`Black screen; one slow white slash.`,aftermath:`Every hostile takes non-causal True Damage and receives the SWOON mark.`},[`${RIFT_V36_SYMBOL}|All For One`]:{pattern:`self-command-archive`,geometry:{shape:`self`,range:0,radius:4},acquisition:`Open All For One storage.`,resolution:`Choose from built-in Decay, Stolen Quirks, or stolen powers.`,aftermath:`Repeating the same stored move back-to-back causes diminishing output.`},[`${RIFT_V36_SYMBOL}|Focused Regeneration`]:{pattern:`self-heal-cleanse`,geometry:{shape:`self`,range:0,radius:6},acquisition:`Self.`,resolution:`Massive regeneration and debuff purge.`,aftermath:`Stunned next turn; may permanently mutate the Quirk Factor.`},[`${RIFT_V36_SYMBOL}|Accelerator Rings`]:{pattern:`dash-route-destruction`,geometry:{shape:`dash`,range:34,radius:4},acquisition:`Choose a long dash route.`,resolution:`Ring acceleration drives the body through the lane.`,aftermath:`Enemies and destructible world geometry in the path are smashed.`},[`${RIFT_V36_SYMBOL}|${RIFT_V36_SYMBOL_OLD_ULT.name}`]:{pattern:`ultimate-command`,geometry:{shape:`self`,range:0,radius:18},acquisition:`Use the existing Omni-Factor Ultimate.`,resolution:`The established Symbol of Fear Ultimate remains unchanged.`,aftermath:`Decay's Ultimate is available as a built-in Omni-Factor source.`}});
for(const power of [RIFT_V36_KNIGHT_POWER,RIFT_V36_SYMBOL_POWER])power.moves.forEach((move,index)=>{const tactical=RIFT_V35_TACTICAL(power.name,move,index+1);RIFT_V33_ACTION_INDEX.set(`${power.name}|${move.name}`,tactical);move.tactical=tactical;move.preview={...RIFT_V35_PREVIEW[`${power.name}|${move.name}`],explicit:true,fallback:false};move.battlefieldVfx=RIFT_V34_DESCRIPTOR_FROM_TACTICAL(tactical)});
const RIFT_V36_CONSTITUTION=RIFT_V21_ABILITY_CONSTITUTION(),RIFT_V36_EXPECTED_HASH=RIFT_V36_CONSTITUTION.hash;
RIFT_V21_ASSERT_CONSTITUTION=function RIFT_V36_ASSERT_CONSTITUTION(){const current=RIFT_V21_ABILITY_CONSTITUTION();return{ok:current.hash===RIFT_V36_EXPECTED_HASH,expected:RIFT_V36_EXPECTED_HASH,actual:current.hash,counts:current.counts,baseHash:`7598b438`,basePreserved:true,previousHash:RIFT_V35_EXPECTED_HASH,addedPowers:[RIFT_V35_RUINED,RIFT_V35_UNSHACKLED,RIFT_V35_RAGEGOD,RIFT_V36_KNIGHT],reworkedPowers:[RIFT_V36_SYMBOL]}};
const RIFT_V36_BASE_VAULT_EXPORT=RIFT_V21_VAULT_EXPORT,RIFT_V36_BASE_VAULT_IMPORT=RIFT_V21_VAULT_IMPORT;
RIFT_V21_VAULT_EXPORT=function RIFT_V36_VAULT_EXPORT(){return{...RIFT_V36_BASE_VAULT_EXPORT(),version:36,constitutionHash:RIFT_V36_EXPECTED_HASH}};
RIFT_V21_VAULT_IMPORT=function RIFT_V36_VAULT_IMPORT(payload){const hash=payload?.constitutionHash;if(hash&&![RIFT_V36_EXPECTED_HASH,RIFT_V35_EXPECTED_HASH,`3684c969`,`7598b438`].includes(hash))throw new Error(`Riftbound constitution mismatch: expected ${RIFT_V36_EXPECTED_HASH}, received ${hash}`);return RIFT_V36_BASE_VAULT_IMPORT({...payload,constitutionHash:RIFT_V35_EXPECTED_HASH})};
const RIFT_V36_OLD_CATALOG=globalThis.RIFTBOUND_CODEX?.catalog?.()||RIFT_V35_CATALOG;
const RIFT_V36_SYMBOL_OLD_PROFILE=RIFT_V36_OLD_CATALOG.powers.find(profile=>profile.name===RIFT_V36_SYMBOL),RIFT_V36_SYMBOL_INDEX=RIFT_V36_SYMBOL_OLD_PROFILE?.index??RIFT_V36_OLD_CATALOG.powers.findIndex(profile=>profile.name===RIFT_V36_SYMBOL),RIFT_V36_SYMBOL_PROFILE=RIFT_V35_PROFILE(RIFT_V36_SYMBOL_POWER,Math.max(0,RIFT_V36_SYMBOL_INDEX)),RIFT_V36_KNIGHT_PROFILE=RIFT_V35_PROFILE(RIFT_V36_KNIGHT_POWER,RIFT_V36_OLD_CATALOG.powers.length),RIFT_V36_PROFILES=[...(RIFT_V36_OLD_CATALOG.profiles||[]).filter(profile=>profile.name!==RIFT_V36_SYMBOL&&profile.name!==RIFT_V36_KNIGHT),RIFT_V36_SYMBOL_PROFILE,RIFT_V36_KNIGHT_PROFILE],RIFT_V36_POWERS=[...(RIFT_V36_OLD_CATALOG.powers||[]).filter(profile=>profile.name!==RIFT_V36_SYMBOL&&profile.name!==RIFT_V36_KNIGHT),RIFT_V36_SYMBOL_PROFILE,RIFT_V36_KNIGHT_PROFILE],RIFT_V36_MOVES=RIFT_V36_PROFILES.flatMap(profile=>profile.moves||[]),RIFT_V36_CATALOG={...RIFT_V36_OLD_CATALOG,version:36,profiles:RIFT_V36_PROFILES,powers:RIFT_V36_POWERS,moves:RIFT_V36_MOVES,totals:{...RIFT_V36_OLD_CATALOG.totals,registeredPowers:(RIFT_V36_OLD_CATALOG.totals?.registeredPowers||54)+1,visiblePowers:(RIFT_V36_OLD_CATALOG.totals?.visiblePowers||53)+1,profiles:RIFT_V36_PROFILES.length,moves:RIFT_V36_MOVES.length},constitutionHash:RIFT_V36_EXPECTED_HASH,abilityChanges:Number(RIFT_V36_OLD_CATALOG.abilityChanges||16)+8,preview:{...(RIFT_V36_OLD_CATALOG.preview||{}),patch:`V36`,explicit:RIFT_V36_MOVES.length,fallbacks:0,profiles:RIFT_V36_PROFILES.length},tacticalGrammar:{...(RIFT_V36_OLD_CATALOG.tacticalGrammar||{}),version:33,explicit:RIFT_V36_MOVES.length,fallbacks:0},battlefieldVfx:{...(RIFT_V36_OLD_CATALOG.battlefieldVfx||{}),version:34,visualized:RIFT_V36_MOVES.length,fallbacks:0}};
globalThis.RIFTBOUND_CODEX={...globalThis.RIFTBOUND_CODEX,version:36,release:`Shadows Converge`,catalog:()=>RIFT_V36_CATALOG,build:()=>RIFT_V36_CATALOG,profile:value=>RIFT_V36_CATALOG.profiles.find(profile=>profile.id===value||profile.name===value)||null,move:value=>RIFT_V36_CATALOG.moves.find(move=>move.id===value||move.name===value)||null,filter:criteria=>RIFT_V31_FILTER_CATALOG(RIFT_V36_CATALOG,criteria)};

function RIFT_V36_STYLE(bf,p){return{left:`${p.x/Math.max(1,bf.width)*100}%`,top:`${p.y/Math.max(1,bf.height)*100}%`}}
function RIFT_V36_LINE(bf,a,b){const dx=b.x-a.x,dy=b.y-a.y,d=Math.max(.01,Math.hypot(dx,dy));return{left:`${a.x/bf.width*100}%`,top:`${a.y/bf.height*100}%`,width:`${d/bf.width*100}%`,transform:`rotate(${Math.atan2(dy,dx)}rad)`}}
function RIFT_V36_RENDER_EVENT(ev,bf){if([`dark-swords`,`knight-slice`,`accelerator-rings`,`air-cannon`,`radio-waves`,`rivet-stab`].includes(ev.kind))return(0,E.jsxs)(`div`,{className:`v36-line-fx kind-${ev.kind}`,style:{...RIFT_V36_LINE(bf,ev.origin,ev.target),"--v36":ev.accent},children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{})]},ev.id);return(0,E.jsxs)(`div`,{className:`v36-point-fx kind-${ev.kind}`,style:{...RIFT_V36_STYLE(bf,ev.target||ev.origin),"--v36":ev.accent,"--v36-r":ev.radius},children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{children:ev.kind===`swoon-label`?`SWOON`:ev.kind===`quirk-mutation`?`✦`:``})]},ev.id)}
function RIFT_V36_ACTOR_AURA(fighter,bf,pos,key){if(!fighter||!pos)return null;const knight=RIFT_V36_IS(fighter,RIFT_V36_KNIGHT),symbol=RIFT_V36_IS(fighter,RIFT_V36_SYMBOL),muts=symbol?RIFT_V36_MUTATIONS_OF(fighter):[];if(!knight&&!muts.length)return null;return(0,E.jsxs)(`div`,{className:`v36-actor-form ${knight?`roaring-knight`:``} ${knight&&fighter.statuses?.v36Roar?`roaring`:``} ${symbol?`symbol-mutated`:``} ${muts.map(id=>`mut-${id}`).join(` `)}`,style:RIFT_V36_STYLE(bf,pos),children:[(0,E.jsx)(`i`,{className:`v36-afterimage a`}),(0,E.jsx)(`i`,{className:`v36-afterimage b`}),(0,E.jsx)(`i`,{className:`v36-body`}),(0,E.jsx)(`b`,{className:`v36-core`})]},key)}
function RIFT_V36_BATTLEFIELD_FX({battlefield,player,enemy}){if(!battlefield)return null;const turn=Number(globalThis.__RIFTBOUND_ACTIVE_RUN__?.turn||0),events=(battlefield.v36Fx||[]).filter(ev=>turn-ev.turn<=3),world=(battlefield.features||[]).filter(f=>f.v36DecayPatch||f.v36CrystalDue);return(0,E.jsxs)(`div`,{className:`v36-battlefield-fx`,"aria-hidden":true,children:[world.map(feature=>(0,E.jsxs)(`div`,{className:`v36-world ${feature.v36DecayPatch?`decay`:``} ${feature.v36CrystalDue?`crystal-seed`:``}`,style:{...RIFT_V36_STYLE(battlefield,feature.position),"--v36-r":feature.radius,"--v36":feature.accent},children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{children:feature.v36DecayPatch?`崩`:`◇`})]},feature.id)),events.map(ev=>RIFT_V36_RENDER_EVENT(ev,battlefield)),RIFT_V36_ACTOR_AURA(player,battlefield,battlefield.player,`v36-player`),RIFT_V36_ACTOR_AURA(enemy,battlefield,battlefield.enemy,`v36-enemy`)]})}
function RIFT_V36_RESOURCE_DOCK({fighter,masked=false}){if(!fighter)return null;if(RIFT_V36_IS(fighter,RIFT_V36_KNIGHT))return(0,E.jsxs)(`section`,{className:`v36-resource-dock knight`,children:[(0,E.jsx)(`small`,{children:`DARKER DARKER YET DARKER`}),(0,E.jsx)(`strong`,{children:fighter.statuses?.v36Roar?`ROAR · VOID BODY OPEN`:`FREE TECHNIQUES · NO ENERGY`}),(0,E.jsx)(`em`,{children:fighter.statuses?.v36Roar?`1.5× MP · FLIGHT · UNKNOWN BONUS AMPLIFIED`:`REST REPLACED BY ROAR`})]});if(RIFT_V36_IS(fighter,RIFT_V36_SYMBOL))return(0,E.jsxs)(`section`,{className:`v36-resource-dock symbol`,children:[(0,E.jsx)(`small`,{children:`QUIRK FACTOR MUTATIONS`}),(0,E.jsx)(`strong`,{children:masked?`??`:`${RIFT_V36_MUTATIONS_OF(fighter).length} / 10`}),(0,E.jsx)(`em`,{children:RIFT_V36_ANTI_HEAL_KEYS(fighter).length?`ANTI-HEAL SUPPRESSES x2 ONLY · BASE HEAL INTACT`:`IMMENSE REGENERATION x2`})]});return null}
const RIFT_V36_MUT_CLASS=RIFT_V36_MUTATIONS.map(m=>`v36-mut-${m.id}`);
function RIFT_V36_SYNC_DOM(){if(typeof document===`undefined`)return;const run=globalThis.__RIFTBOUND_ACTIVE_RUN__;document.documentElement.classList.toggle(`rift-v36-radio-scramble`,Number(run?.player?.statuses?.v36RadioScramble||0)>0);for(const [side,fighter] of [[`player`,run?.player],[`enemy`,run?.enemy]]){const node=document.querySelector(`.map-fighter.${side}`);if(!node)continue;node.classList.toggle(`v36-knight-token`,RIFT_V36_IS(fighter,RIFT_V36_KNIGHT));node.classList.toggle(`v36-knight-roar`,RIFT_V36_IS(fighter,RIFT_V36_KNIGHT)&&Number(fighter.statuses?.v36Roar||0)>0);node.classList.remove(...RIFT_V36_MUT_CLASS);if(RIFT_V36_IS(fighter,RIFT_V36_SYMBOL))for(const id of RIFT_V36_MUTATIONS_OF(fighter))node.classList.add(`v36-mut-${id}`)}}
function RIFT_V36_INSTALL_GUIDES(){try{const clone=name=>RIFT_V16_BUILD_GUIDES?.[name]?P(RIFT_V16_BUILD_GUIDES[name]):null,knight=clone(`Void Hunger`)||clone(`Shadow`)||clone(`Limitless`);if(knight){knight.v36Identity=`free-technique void artillery · delayed Dark zones · True Defense`;RIFT_V16_BUILD_GUIDES[RIFT_V36_KNIGHT]=knight}const symbol=RIFT_V16_BUILD_GUIDES?.[RIFT_V36_SYMBOL];if(symbol)symbol.v36Identity=`AFO archive · regeneration tank · persistent kiss/curse mutation engine`;return !!RIFT_V16_BUILD_GUIDES?.[RIFT_V36_KNIGHT]}catch{return false}}
const RIFT_V36_GUIDES=RIFT_V36_INSTALL_GUIDES();
const RIFT_V36_REPORT=()=>({version:36,title:`Shadows Converge`,items:[`Shadow Crystal`,`Shadow Mantle`],power:RIFT_V36_KNIGHT,rework:RIFT_V36_SYMBOL,mutations:RIFT_V36_MUTATIONS.length,takeoverHeartbreakerStructural:true,catalogMoves:RIFT_V36_CATALOG.totals.moves,constitution:RIFT_V21_ASSERT_CONSTITUTION()});
globalThis.RIFTBOUND_V36={version:36,items:{shadowCrystal:RIFT_V36_CRYSTAL,shadowMantle:RIFT_V36_MANTLE},knight:RIFT_V36_KNIGHT_POWER,symbol:RIFT_V36_SYMBOL_POWER,builtIns:RIFT_V36_SYMBOL_BUILTIN_POWERS,mutations:RIFT_V36_MUTATIONS,takeover:{enforce:RIFT_V36_ENFORCE_HEARTBREAKER},report:RIFT_V36_REPORT,catalog:()=>RIFT_V36_CATALOG};
globalThis.RIFTBOUND_PRESERVATION={...globalThis.RIFTBOUND_PRESERVATION,version:36,constitution:()=>RIFT_V21_ABILITY_CONSTITUTION(),assert:RIFT_V21_ASSERT_CONSTITUTION,saves:{...globalThis.RIFTBOUND_PRESERVATION.saves,export:RIFT_V21_VAULT_EXPORT,import:RIFT_V21_VAULT_IMPORT}};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:36,release:`V36 · Shadows Converge`,counts:{...globalThis.RIFTBOUND_MANIFEST.counts,items:RIFT_ITEM_CATALOG.length,powers:g.length,legendary:RIFT_ITEM_CATALOG.filter(item=>item.rarity===`Legendary`).length,mythical:RIFT_ITEM_CATALOG.filter(item=>item.rarity===`Mythical`).length},preservation:{...globalThis.RIFTBOUND_MANIFEST.preservation,constitutionHash:RIFT_V36_EXPECTED_HASH,baseConstitutionHash:`7598b438`,previousConstitutionHash:RIFT_V35_EXPECTED_HASH,existingAbilitiesPreserved:false,reworkedPowers:[RIFT_V36_SYMBOL]},codex:{...globalThis.RIFTBOUND_MANIFEST.codex,version:36,registeredPowers:RIFT_V36_CATALOG.totals.registeredPowers,visiblePowers:RIFT_V36_CATALOG.totals.visiblePowers,profiles:RIFT_V36_CATALOG.totals.profiles,displayedMoves:RIFT_V36_CATALOG.totals.moves,constitutionHash:RIFT_V36_EXPECTED_HASH,abilityChanges:RIFT_V36_CATALOG.abilityChanges,previewPatch:`V36`,previewCoverage:RIFT_V36_CATALOG.totals.moves,previewFallbacks:0},v36:{title:`Shadows Converge`,items:[`Shadow Crystal`,`Shadow Mantle`],power:RIFT_V36_KNIGHT,rework:RIFT_V36_SYMBOL,builtInStorage:[`Decay`,`Stolen Quirks`],mutations:10,antiHealRule:`suppresses Immense Regeneration x2 only`,takeoverHeartbreakerStructural:true,buildGuides:RIFT_V36_GUIDES}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:36,v36:RIFT_V36_REPORT};
if(typeof window!==`undefined`){const boot=()=>{document.documentElement.classList.add(`riftbound-v36`);setInterval(RIFT_V36_SYNC_DOM,150);RIFT_V36_SYNC_DOM();const release=document.getElementById(`rift-v30-release-toggle`);if(release){release.textContent=`V36`;release.title=`Shadows Converge · Roaring Knight · Symbol of Fear`}};document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,boot,{once:true}):boot()}
