/* ---------- RESOLUTION ---------- */
function RIFT_V36_COMMIT(base,run,side,action,ctx){const move={...RIFT_V36_COPY(action.move||{}),power:0,hits:1,tags:[...(action.move?.tags||[]).filter(tag=>!/(trueDamage|area|projectile|line|wave|slash|decay|corrosive|knockback|bleed)/i.test(String(tag))),`selfCast`,`v36CommitOnly`]};return base(run,side,{...action,type:`special`,move},ctx)}
function RIFT_V36_ATTACK_DAMAGE(attacker,action){const stat=(action?.move?.tags||[]).includes(`magic`)||action?.sourcePower===`Decay`?Y(attacker,`ap`):Y(attacker,`as`);return Math.max(1,Math.round((22+Math.max(0,stat)*4.4)*Math.max(.35,Number(action?.move?.power||.8))))}
function RIFT_V36_DASH(run,fighter,target,maxDistance){const id=RIFT_V36_ACTOR(run,fighter);if(!id||!run?.battlefield)return null;const from=RIFT_V36_POINT(run,fighter),to=RIFT_V36_POINT(run,target),dx=to.x-from.x,dy=to.y-from.y,d=Math.max(.001,Math.hypot(dx,dy)),scale=Math.min(1,maxDistance/d),wanted={x:from.x+dx*scale,y:from.y+dy*scale},occupied=Ft(run,id).map(entry=>entry.position),dest=Wi(run.battlefield,wanted,occupied);ki(run,id,dest);return{from,dest,id}}
function RIFT_V36_DECAY_PATCH(run,fighter){const pos=RIFT_V36_POINT(run,fighter),patch=RIFT_V36_ADD_FEATURE(run,{v36DecayPatch:true,owner:fighter,position:pos,radius:7,damage:Math.max(12,12+Y(fighter,`ap`)*1.8),expiresTurn:Number(run.turn||0)+4,accent:`#54152f`});RIFT_V36_FX(run,`decay-ground`,fighter,pos,{radius:7,accent:`#6a1939`});return patch}
function RIFT_V36_CRYSTAL_SEED(run,fighter,position,radius=8,damage=null){return RIFT_V36_ADD_FEATURE(run,{v36CrystalDue:true,owner:fighter,position:{...position},radius,damage:damage||Math.max(18,16+Y(fighter,`ap`)*2.2),corrosionTurns:RIFT_V36_IS(fighter,RIFT_V36_SYMBOL)&&RIFT_V36_HAS_MUT(fighter,`ooze`)?3:2,dueTurn:Number(run.turn||0)+1,accent:`#7738e5`})}
function RIFT_V36_DESTROY_ROUTE(run,from,to){if(!run?.battlefield)return 0;let removed=0;run.battlefield.features=(run.battlefield.features||[]).filter(feature=>{if(feature.v35Harrow||feature.v35Wraith||feature.v36DecayPatch||feature.v36CrystalDue)return true;const pos=feature.position||feature.pos;if(!pos)return true;const hit=RIFT_V36_SEGMENT_DISTANCE(pos,from,to)<=Math.max(3,Number(feature.radius||2));if(hit&&feature.destructible!==false){removed+=1;return false}return true});return removed}
function RIFT_V36_STORED_REPEAT(fighter,action){if(!RIFT_V36_IS(fighter,RIFT_V36_SYMBOL))return action;const stored=action?.v36Builtin||action?.sourcePower&&action.sourcePower!==RIFT_V36_SYMBOL;if(!stored)return action;const key=`${action.sourcePower||`archive`}|${action.name}`,prev=fighter.statuses?.v36LastStoredMove,chain=prev===key?Math.min(3,Number(fighter.statuses.v36StoredRepeat||0)+1):0;fighter.statuses.v36LastStoredMove=key;fighter.statuses.v36StoredRepeat=chain;if(!chain)return action;const factor=[1,.76,.58,.46][chain]||.46;return{...action,description:`DIMINISHING FACTOR · ${Math.round(factor*100)}% output · ${action.description||``}`,move:{...RIFT_V36_COPY(action.move),power:Number(action.move?.power||0)*factor,destruction:Number(action.move?.destruction||0)*factor,tags:[...(action.move?.tags||[]),`v36Diminished`]}}}
function RIFT_V36_SWOON(run,fighter){fighter.ultimate=0;const hostiles=RIFT_V36_HOSTILES(run,fighter);RIFT_V36_FX(run,`swoon-cutscene`,fighter,fighter,{radius:9999,accent:`#ffffff`});if(typeof document!==`undefined`)RIFT_V36_SW0ON_CUTSCENE();for(const entry of hostiles){const damage=Math.max(24,Math.round(46+Y(fighter,`ap`)*3.1+Y(fighter,`as`)*1.4));go(run,fighter,entry.fighter,damage,true,[`trueDamage`,`global`,`slash`,`ultimate`,`v36Swoon`,`noItemProc`]);const bonus=RIFT_V36_UNKNOWN_BONUS(run,fighter,entry.fighter,`SWOON`);if(bonus)go(run,fighter,entry.fighter,bonus,true,[`magic`,`v36UnknownBonus`,`noItemProc`]);RIFT_V36_FX(run,`swoon-label`,fighter,entry.fighter,{radius:7,accent:`#ffffff`,text:`SWOON`})}RIFT_V36_LOG(run,`SWOON // one white slash crosses every hostile on the map.`,fighter,`mythic`)}
const RIFT_V36_BASE_RS=rs;
rs=function RIFT_V36_RESOLVE(run,side,action,ctx={}){RIFT_V36_PROCESS_WORLD(run);const fighter=ctx.attacker||(side===`player`?run.player:run.enemy),target=ctx.target||(side===`player`?run.enemy:run.player),rawTags=action?.move?.tags||[];let tags=[...rawTags],sure=!!fighter?.statuses?.v36HoldBreathSureHit,logIds=new Set((run?.logs||[]).map(row=>row.id));if(sure&&action?.type!==`guard`&&action?.type!==`rest`){action={...action,move:{...RIFT_V36_COPY(action.move),tags:[...new Set(tags.concat([`guaranteedHit`,`sureHit`,`cannotMiss`]))]}};tags=action.move.tags}action=RIFT_V36_STORED_REPEAT(fighter,action);tags=action?.move?.tags||[];const beforeTarget=target?.hp;
 if(tags.includes(`v36Roar`)){const out=RIFT_V36_COMMIT(RIFT_V36_BASE_RS,run,side,action,ctx);fighter.statuses.v36Roar=2;fighter.statuses.v36RoarBaseFlight=!!fighter.flight;fighter.flight=true;RIFT_V36_FX(run,`knight-roar`,fighter,fighter,{radius:10,accent:`#9a54ff`});RIFT_V36_LOG(run,`ROAR // the Knight's body opens into a darker shape. Movement, flight, and unseen-technique pressure surge for the next turn.`,fighter);return out}
 if(tags.includes(`v36CrystalBarrage`)){const out=RIFT_V36_COMMIT(RIFT_V36_BASE_RS,run,side,action,ctx),point=action?.aim?.target||RIFT_V36_POINT(run,target);RIFT_V36_CRYSTAL_SEED(run,fighter,point,10,Math.max(22,18+Y(fighter,`ap`)*2.45));RIFT_V36_FX(run,`crystal-telegraph`,fighter,point,{radius:10,accent:`#6f30d9`});return out}
 if(tags.includes(`v36Swoon`)){const out=RIFT_V36_COMMIT(RIFT_V36_BASE_RS,run,side,action,ctx);RIFT_V36_SWOON(run,fighter);return out}
 if(tags.includes(`v36DecayGround`)){const out=RIFT_V36_COMMIT(RIFT_V36_BASE_RS,run,side,action,ctx);RIFT_V36_DECAY_PATCH(run,fighter);return out}
 if(tags.includes(`v36FocusedRegeneration`)){const out=RIFT_V36_COMMIT(RIFT_V36_BASE_RS,run,side,action,ctx);RIFT_V36_CLEAR_DEBUFFS(fighter);oo(fighter,Math.max(1,Math.round(fighter.maxHp*.36)));fighter.statuses.stun=Math.max(1,Number(fighter.statuses.stun||0));RIFT_V36_FX(run,`focused-regeneration`,fighter,fighter,{radius:9,accent:`#73ffbb`});RIFT_V36_TRY_MUTATE(run,fighter);return out}
 if(tags.includes(`v36AcceleratorRings`)){const out=RIFT_V36_COMMIT(RIFT_V36_BASE_RS,run,side,action,ctx),dash=RIFT_V36_DASH(run,fighter,action?.aim?.target||RIFT_V36_POINT(run,target),RIFT_V36_HAS_MUT(fighter,`spring`)?40:34);if(dash){for(const entry of RIFT_V36_HOSTILES(run,fighter))if(RIFT_V36_SEGMENT_DISTANCE(entry.position,dash.from,dash.dest)<=4)go(run,fighter,entry.fighter,Math.max(18,20+Y(fighter,`as`)*3.2),false,[`physical`,`dash`,`line`,`destruction`,`v36AcceleratorRings`,`noItemProc`]);const broken=RIFT_V36_DESTROY_ROUTE(run,dash.from,dash.dest);RIFT_V36_FX(run,`accelerator-rings`,dash.from,dash.dest,{radius:5,accent:`#8a204d`,broken})}return out}
 const out=RIFT_V36_BASE_RS(run,side,action,ctx);
 if(RIFT_V36_IS(fighter,RIFT_V36_KNIGHT)&&action.type===`strike`&&target&&String(target.race?.name||target.race||`Human`).toLowerCase()!==`human`&&target.hp>0)go(run,fighter,target,Math.max(4,8+Y(fighter,`as`)*1.35),false,[`physical`,`strike`,`v36NonHumanSmite`,`noItemProc`]);
 if(RIFT_V36_IS(fighter,RIFT_V36_KNIGHT)&&tags.some(tag=>[`v36DarkSword`,`v36Slice`].includes(tag))&&target){const bonus=RIFT_V36_UNKNOWN_BONUS(run,fighter,target,action.name||action.move?.name);if(bonus)go(run,fighter,target,bonus,true,[`magic`,`v36UnknownBonus`,`noItemProc`])}
 if(tags.includes(`v36DarkSword`))RIFT_V36_FX(run,`dark-swords`,fighter,target||action?.aim?.target,{radius:5,accent:`#7d47f5`});
 if(tags.includes(`v36Slice`)&&target&&target.hp<(beforeTarget??target.hp)){const p=RIFT_V36_POINT(run,target);RIFT_V36_CRYSTAL_SEED(run,fighter,p,6,Math.max(18,14+Y(fighter,`ap`)*2));RIFT_V36_FX(run,`knight-slice`,fighter,target,{radius:7,accent:`#d7c8ff`})}
 if(tags.includes(`v36RadioWaves`)&&target&&target.hp<(beforeTarget??target.hp)){target.statuses.v36RadioScramble=2;RIFT_V36_FX(run,`radio-waves`,fighter,target,{radius:10,accent:`#75264a`});RIFT_V36_LOG(run,`RADIO WAVES // ${target.name}'s HP, Energy, and cooldown telemetry dissolves into static for the next round.`,fighter)}
 if(tags.includes(`v36RivetStab`)&&target&&target.hp<(beforeTarget??target.hp)){target.statuses.bleed=Math.min(6,Number(target.statuses.bleed||0)+3);RIFT_V36_FX(run,`rivet-stab`,fighter,target,{radius:6,accent:`#1b0810`})}
 if(tags.includes(`v36AirCannon`))RIFT_V36_FX(run,`air-cannon`,fighter,target||action?.aim?.target,{radius:8,accent:`#d6c7d8`});
 if(tags.includes(`v36ForcefulDecay`)||tags.includes(`v36Hatred`)){if(target&&target.hp<(beforeTarget??target.hp))target.statuses.decayWound=Math.max(Number(target.statuses.decayWound||0),tags.includes(`v36Hatred`)?3:2);RIFT_V36_FX(run,`decay-touch`,fighter,target,{radius:5,accent:`#671334`})}
 if(tags.includes(`v36DecayUltimate`)){const center=action?.aim?.target||RIFT_V36_POINT(run,target);RIFT_V36_ADD_FEATURE(run,{v36DecayPatch:true,owner:fighter,position:{...center},radius:15,damage:Math.max(20,16+Y(fighter,`ap`)*2),expiresTurn:Number(run.turn||0)+5,accent:`#4d0d28`});RIFT_V36_FX(run,`decay-ultimate`,fighter,center,{radius:15,accent:`#671334`})}
 if(RIFT_V36_IS(fighter,RIFT_V36_SYMBOL)&&RIFT_V36_HAS_MUT(fighter,`blacklightning`)&&action.type===`special`&&target&&target.hp>0&&!tags.includes(`v36FocusedRegeneration`))go(run,fighter,target,Math.max(5,7+Y(fighter,`ap`)*1.2),true,[`magic`,`lightning`,`v36BlackLightning`,`noItemProc`]);
 if(RIFT_V36_IS(fighter,RIFT_V36_SYMBOL)&&RIFT_V36_HAS_MUT(fighter,`fangs`)&&target&&beforeTarget!=null&&target.hp<beforeTarget&&tags.some(tag=>/melee|strike|weapon/i.test(String(tag))))oo(fighter,Math.max(1,Math.round((beforeTarget-target.hp)*.06)));
 if(sure&&fighter?.statuses?.v36HoldBreathSureHit&&action.type!==`guard`&&action.type!==`rest`){delete fighter.statuses.v36HoldBreathSureHit;const missed=(run.logs||[]).filter(row=>!logIds.has(row.id)).some(row=>/\bmiss(?:es|ed)?\b|\bdodges?\b/i.test(String(row.text||``)));if(missed&&target?.hp>0){go(run,fighter,target,RIFT_V36_ATTACK_DAMAGE(fighter,action),(tags||[]).includes(`magic`),[...(tags||[]).filter(tag=>!/^v36/i.test(String(tag))),`v36HoldBreathSureHit`,`noItemProc`]);RIFT_V36_LOG(run,`HELD BREATH // the Shadow Crystal corrects the missed line. This attack cannot miss.`,fighter,`mythic`)}}
 return out};

const RIFT_V36_BASE_UA=Ua;
Ua=function RIFT_V36_TICK(fighter){RIFT_V36_BASE_UA(fighter);if(!fighter?.statuses)return;if(Number(fighter.statuses.v36Roar||0)>0){fighter.statuses.v36Roar-=1;if(fighter.statuses.v36Roar<=0){fighter.flight=RIFT_V36_HAS_MUT(fighter,`airwalk`)?true:!!fighter.statuses.v36RoarBaseFlight;delete fighter.statuses.v36Roar;delete fighter.statuses.v36RoarBaseFlight}}if(Number(fighter.statuses.v36Corrosion||0)>0){fighter.statuses.v36Corrosion-=1;if(fighter.statuses.v36Corrosion<=0)delete fighter.statuses.v36Corrosion}if(Number(fighter.statuses.v36RadioScramble||0)>0){fighter.statuses.v36RadioScramble-=1;if(fighter.statuses.v36RadioScramble<=0)delete fighter.statuses.v36RadioScramble}};
const RIFT_V36_BASE_GI=Gi;
Gi=function RIFT_V36_ENCOUNTER(run,...args){const out=RIFT_V36_BASE_GI(run,...args);for(const entry of H(run||out||{})){const f=entry.fighter;if(!f?.statuses)continue;delete f.statuses.v36HoldBreathSpent;delete f.statuses.v36HoldBreathSureHit;delete f.statuses.v36KnightKnowledge;delete f.statuses.v36KnightKnowledgeFloor;delete f.statuses.v36RadioScramble;delete f.statuses.v36Corrosion;delete f.statuses.v36LastStoredMove;delete f.statuses.v36StoredRepeat;if(RIFT_V36_IS(f,RIFT_V36_KNIGHT)){f.energy=0;f.maxEnergy=0}}return out};
function RIFT_V36_SW0ON_CUTSCENE(){if(typeof document===`undefined`)return;let node=document.getElementById(`rift-v36-swoon`);if(node)node.remove();node=document.createElement(`div`);node.id=`rift-v36-swoon`;node.innerHTML=`<i></i>`;document.body.appendChild(node);requestAnimationFrame(()=>node.classList.add(`live`));setTimeout(()=>node.classList.add(`slash`),220);setTimeout(()=>node.remove(),1450)}
const RIFT_V36_BASE_ITEM_ICON=RIFT_ITEM_ICON;
RIFT_ITEM_ICON=function RIFT_V36_ITEM_ICON({item,size=`normal`}){if(item?.id===RIFT_V36_CRYSTAL||item?.id===RIFT_V36_MANTLE)return(0,E.jsx)(`span`,{className:`rift-item-icon art-icon ${size} rarity-${String(item.rarity||``).toLowerCase()} v36-shadow-portrait ${item.id}`,style:{"--item-a":item.accent},title:item.name,children:(0,E.jsx)(`img`,{src:`./assets/v36-${item.id}.webp`,alt:``,draggable:false,"aria-hidden":true})});return RIFT_V36_BASE_ITEM_ICON({item,size})};
