const RIFT_V36_MARKER=`Riftbound Shadows Converge V36`;
const RIFT_V36_VERSION=36;
const RIFT_V36_KNIGHT=`The Roaring Knight`,RIFT_V36_SYMBOL=`Symbol of Fear`;
const RIFT_V36_COPY=value=>value==null?value:P(value);
const RIFT_V36_MOVE=(name,description,cost,power,destruction,tags=[],hits=1,glyph=`◆`)=>({name,description,cost,power,destruction,tags:[...tags],hits,glyph});
const RIFT_V36_CRYSTAL=`shadow-crystal`,RIFT_V36_MANTLE=`shadow-mantle`;

function RIFT_V36_IS(fighter,name){return fighter?.power?.name===name}
function RIFT_V36_ACTOR(run,fighter){try{return RIFT_ACTOR_ID_FOR_FIGHTER(run,fighter)||RIFT_V22_ACTOR_ID?.(run,fighter)||null}catch{return fighter===run?.player?`player`:fighter===run?.enemy?`enemy`:null}}
function RIFT_V36_POINT(run,thing){if(!run?.battlefield)return{x:0,y:0};if(typeof thing?.x===`number`)return{x:thing.x,y:thing.y};const id=typeof thing===`string`?thing:RIFT_V36_ACTOR(run,thing);try{return id?{...W(run,id)}:{x:run.battlefield.width/2,y:run.battlefield.height/2}}catch{return{x:run.battlefield.width/2,y:run.battlefield.height/2}}}
function RIFT_V36_HOSTILES(run,fighter){const actor=U(run,RIFT_V36_ACTOR(run,fighter));return actor?H(run).filter(entry=>entry.kind===`fighter`&&entry.fighter?.hp>0&&entry.team!==actor.team):[]}
function RIFT_V36_ITEM(fighter,id){try{return RIFT_ACTIVE_ITEM(fighter,id)}catch{return (fighter?.inventory||[]).some(slot=>(slot?.id||slot)===id)}}
function RIFT_V36_LOG(run,text,fighter=null,tone=`mythic`){try{G(run,text,fighter?fighter===run?.player?`player`:`enemy`:tone)}catch{}}
function RIFT_V36_FX(run,kind,source,target,extra={}){if(!run?.battlefield)return;const event={id:`v36-${F()}`,kind,turn:Number(run.turn||0),origin:RIFT_V36_POINT(run,source),target:RIFT_V36_POINT(run,target||source),radius:Number(extra.radius||7),accent:extra.accent||`#8f56ff`,...extra};run.battlefield.v36Fx=(run.battlefield.v36Fx||[]).concat(event).slice(-28);return event}
function RIFT_V36_CAUSAL(tags=[]){return (tags||[]).some(tag=>/causal|causality|absolute|deathAuthority|conceptErasure|masterOfTime|revertToZero/i.test(String(tag)))}
function RIFT_V36_TRUE(tags=[]){return (tags||[]).some(tag=>/trueDamage|true-damage|true\b/i.test(String(tag)))}

const RIFT_V36_SHADOW_CRYSTAL={id:RIFT_V36_CRYSTAL,name:`Shadow Crystal`,rarity:`Legendary`,category:`Relic`,price:910,recipe:[`constellation-robe`,`memory-shard`],stats:{energy:5,ap:2},glyph:`◆`,accent:`#9b5cff`,passiveId:`v36HoldBreath`,passive:`HOLD BREATH — once per fight, damage that would kill you instead leaves you at exactly 1 HP. Afterward your next damaging attack cannot miss. The death save is spent for the rest of that fight.`,lore:`A Dark crystal that catches one final breath and refuses to let it become the last.`,reference:`DELTARUNE · Shadow Crystal`,tags:[`unique`,`v36`,`dark`,`deathSave`]};
const RIFT_V36_SHADOW_MANTLE={id:RIFT_V36_MANTLE,name:`Shadow Mantle`,rarity:`Mythical`,category:`Defense`,price:2140,recipe:[`voidwalker-hide`,`null-mantle`,`bastion-frame`],stats:{durability:6},glyph:`◼`,accent:`#5d34a4`,passiveId:`v36TrueDarkness`,passive:`TRUE DARKNESS — causality-level damaging attacks deal 50% less damage to you. Grants no offensive statistics: all of its budget is committed to Defense.`,lore:`A mantle made for a battle that normal armor was never supposed to survive.`,reference:`DELTARUNE · Shadow Mantle`,tags:[`unique`,`mythical`,`v36`,`dark`,`causalityDefense`]};

const RIFT_V36_KNIGHT_POWER={name:RIFT_V36_KNIGHT,rarity:`Mythic`,damageType:`Hybrid`,glyph:`◼`,accent:`#8e54ff`,reference:`DELTARUNE · The Roaring Knight`,passive:`DARKER DARKER YET DARKER — techniques gain bonus AP damage the first time a given enemy witnesses that technique each fight. True Defense forces non-causal True Damage back through normal armor; only causality bypasses it. Strikes deal bonus damage to non-Human races. The Knight uses no Energy.`,codexDescription:`A levitating void silhouette whose body and blade blur together. It never spends Energy. Roar replaces Rest, briefly heightening Movement, flight, and the unseen-technique bonus. Delayed crystal storms and wounds turn the battlefield itself into Dark geometry.`,moves:[RIFT_V36_MOVE(`Crystal Barrage`,`Choose a large region. One combatant turn later, a rain of Dark crystals impales the area and leaves Corrosion on everyone caught inside.`,0,.78,1.02,[`magic`,`area`,`delayed`,`corrosive`,`v36CrystalBarrage`],1,`◇`),RIFT_V36_MOVE(`Dark Sword`,`Manifest three sword-bullets behind the Knight and fire them down the aimed line. All three contacts can trigger ordinary on-hit passives.`,0,.34,.66,[`physical`,`projectile`,`multi`,`weapon`,`v36DarkSword`],3,`†`),RIFT_V36_MOVE(`Slice`,`Release a huge sword arc at extreme melee-line range. Hitting a fighter seeds the exact impact point; Dark crystals erupt there one turn later for Corrosive damage.`,0,1.18,1.28,[`physical`,`slash`,`line`,`v36Slice`],1,`╱`),RIFT_V36_MOVE(`SWOON`,`Black out the battlefield and draw one slow white slash through every hostile on the map. Each target takes non-causal True Damage and is branded SWOON immediately afterward.`,0,1.42,1.85,[`global`,`trueDamage`,`v36Swoon`,`ultimate`],1,`—`)]};
if(!g.some(power=>power.name===RIFT_V36_KNIGHT))g.push(RIFT_V36_KNIGHT_POWER);try{RIFT_V22_REGISTRY?.powers?.set(RIFT_V36_KNIGHT,RIFT_V36_KNIGHT_POWER)}catch{}

const RIFT_V36_SYMBOL_BASE=g.find(power=>power.name===RIFT_V36_SYMBOL);
const RIFT_V36_SYMBOL_OLD_ULT=RIFT_V36_COPY(RIFT_V36_SYMBOL_BASE?.moves?.[3]||RIFT_V36_MOVE(`Omni-Factor`,`Unleash stolen Ultimate factors together.`,100,1.6,2,[`ultimate`]));
const RIFT_V36_SYMBOL_OLD_AFO=RIFT_V36_COPY(RIFT_V36_SYMBOL_BASE?.moves?.[0]||RIFT_V36_MOVE(`All For One`,`Open the stolen-factor archive.`,0,0,0,[`symbolFactorWheel`,`selfCast`]));
const RIFT_V36_SYMBOL_POWER={...RIFT_V36_COPY(RIFT_V36_SYMBOL_BASE||{}),name:RIFT_V36_SYMBOL,rarity:RIFT_V36_SYMBOL_BASE?.rarity||`Mythic`,accent:`#7b163f`,passive:`IMMENSE REGENERATION — every heal and regeneration source is doubled. Anti-heal cannot reduce or disable the underlying heal; while anti-heal is active it suppresses only this x2 passive, so base healing remains fully effective. Quirk Factor Mutations persist through the run.`,codexDescription:`The completed Symbol of Fear carries Decay and a curated Stolen Quirks package inside All For One from the start. Repeating the same stored technique back-to-back causes diminishing output. Focused Regeneration can mutate the Quirk Factor into persistent kiss/curse body changes, while Accelerator Rings turns the body itself into a demolition projectile.`,moves:[{...RIFT_V36_SYMBOL_OLD_AFO,name:`All For One`,description:`Open the internal stolen-power archive. Decay and Stolen Quirks are built in from the start; defeated powers join the same storage. Repeating the exact same stored move back-to-back weakens it.`,tags:[...new Set([...(RIFT_V36_SYMBOL_OLD_AFO.tags||[]),`symbolFactorWheel`,`selfCast`,`v36AfoStorage`])]},RIFT_V36_MOVE(`Focused Regeneration`,`Rebuild the body with an immense heal and purge debuffs, then become Stunned for the next owner turn. Each use has a low, archive-scaled chance to cause one of ten permanent Quirk Factor Mutations.`,32,0,.2,[`magic`,`heal`,`selfCast`,`v36FocusedRegeneration`],1,`再`),RIFT_V36_MOVE(`Accelerator Rings`,`Ignite ring-shaped force around the body and dash a great distance, pulverizing destructible battlefield geometry and damaging enemies crossed by the route.`,28,1.08,1.9,[`physical`,`dash`,`line`,`destruction`,`v36AcceleratorRings`],1,`◎`),RIFT_V36_SYMBOL_OLD_ULT]};
if(RIFT_V36_SYMBOL_BASE){const index=g.indexOf(RIFT_V36_SYMBOL_BASE);if(index>=0)g[index]=RIFT_V36_SYMBOL_POWER;try{RIFT_V22_REGISTRY?.powers?.set(RIFT_V36_SYMBOL,RIFT_V36_SYMBOL_POWER)}catch{}}

const RIFT_V36_DECAY_ULT=RIFT_V36_MOVE(`Awakened Ruin`,`Flood the chosen battlefield with awakened Decay.`,0,1.62,2.25,[`magic`,`area`,`decay`,`ultimate`,`v36DecayUltimate`],1,`崩`);
const RIFT_V36_SYMBOL_BUILTIN_POWERS=Object.freeze([{name:`Decay`,rarity:`BUILT-IN`,glyph:`崩`,accent:`#7b163f`,moves:[RIFT_V36_MOVE(`Destruction`,`Decay the ground directly beneath yourself in a visible AOE. The ruined patch persists briefly and damages hostile bodies standing in it.`,18,.82,1.2,[`magic`,`selfCast`,`area`,`decay`,`v36DecayGround`],1,`崩`),RIFT_V36_MOVE(`Forceful Decay`,`Deliver Decay through a close-range touch at fixed Strike range.`,20,1.08,.95,[`magic`,`melee`,`decay`,`v36ForcefulDecay`],1,`掌`),RIFT_V36_MOVE(`Hatred`,`Drive hatred through a close-range Decay strike at fixed Strike range.`,24,1.28,1.15,[`magic`,`melee`,`decay`,`v36Hatred`],1,`憎`),RIFT_V36_DECAY_ULT]},{name:`Stolen Quirks`,rarity:`BUILT-IN`,glyph:`万`,accent:`#4a172c`,moves:[RIFT_V36_MOVE(`Radio Waves`,`Release a disruptive radio-wave burst. A hit scrambles the victim's interface for the next round: HP, Energy, and cooldown readouts become unreadable.`,16,.46,.42,[`magic`,`wave`,`debuff`,`v36RadioWaves`],1,`波`),RIFT_V36_MOVE(`Rivet Stab`,`Launch barbed black-red tendrils that stab the target and inflict heavy Bleeding.`,19,.92,.84,[`physical`,`projectile`,`tether`,`bleed`,`v36RivetStab`],1,`鋲`),RIFT_V36_MOVE(`Air Cannon`,`Compress the atmosphere into a giant forward blast with heavy knockback and structure damage.`,22,1.16,1.5,[`magic`,`wave`,`knockback`,`destruction`,`v36AirCannon`],1,`砲`),RIFT_V36_MOVE(`Stolen Quirks`,`Built-in non-Ultimate factor set.`,0,0,0,[`selfCast`])]}]);
function RIFT_V36_SYMBOL_BUILTINS(fighter){return RIFT_V36_IS(fighter,RIFT_V36_SYMBOL)?RIFT_V36_SYMBOL_BUILTIN_POWERS:[]}
function RIFT_V36_SYMBOL_BUILTIN_NAME(name){return RIFT_V36_SYMBOL_BUILTIN_POWERS.some(power=>power.name===name)}
function RIFT_V36_SYMBOL_ACTION(fighter,power,index){const move=RIFT_V36_COPY(power?.moves?.[index]);return{id:`v36-symbol-${String(power?.name||``).toLowerCase().replace(/\W+/g,`-`)}-${index}`,slot:5+index,name:move.name,description:move.description,glyph:move.glyph,type:`special`,cost:move.cost||0,move,moveIndex:index,sourcePower:power.name,v36Builtin:true}}
function RIFT_V36_SYMBOL_ULT_BUILTIN(){return RIFT_V36_SYMBOL_BUILTIN_POWERS[0]}
function RIFT_V36_SYMBOL_ULT_SOURCES(fighter){return RIFT_V36_IS(fighter,RIFT_V36_SYMBOL)?[RIFT_V36_SYMBOL_BUILTIN_POWERS[0]]:[]}
function RIFT_V36_SYMBOL_ULT_ACTION(fighter,power){const move=RIFT_V36_COPY(power?.moves?.[3]||RIFT_V36_DECAY_ULT);return{id:`v36-symbol-decay-omni`,slot:8,name:move.name,description:`OMNI-FACTOR · BUILT-IN DECAY ULTIMATE — ${move.description}`,glyph:move.glyph,type:`ultimate`,cost:0,move:{...move,tags:[...(move.tags||[]),`v36OmniBuiltIn`]},moveIndex:3,sourcePower:`Decay`,v36Builtin:true}}

const RIFT_V36_MUTATIONS=Object.freeze([{id:`spring`,name:`Springlike Limbs`,buff:`+2 Speed and +2 AS; Accelerator Rings gains 6m reach.`,curse:`-2 Durability from unstable recoil.`,stats:{speed:2,as:2,durability:-2},glyph:`⌁`},{id:`hypertrophy`,name:`Hypertrophy`,buff:`+3 AS and +3 Durability.`,curse:`-3 Speed and reduced Movement efficiency.`,stats:{as:3,durability:3,speed:-3},glyph:`巨`},{id:`bones`,name:`Spearlike Bones`,buff:`Strikes gain Bleed and +2 AS.`,curse:`-2 Regeneration and -8% structural max HP.`,stats:{as:2,regeneration:-2},hp:.92,glyph:`骨`},{id:`airwalk`,name:`Air Walk`,buff:`Permanent flight and +2 Speed.`,curse:`-2 Durability while airborne.`,stats:{speed:2,durability:-2},flight:true,glyph:`空`},{id:`forcefield`,name:`Force Field Organ`,buff:`+4 Durability and stronger Guard.`,curse:`-2 AP and -2 AS.`,stats:{durability:4,ap:-2,as:-2},glyph:`盾`},{id:`blacklightning`,name:`Black Lightning`,buff:`+3 AP; damaging techniques arc bonus AP damage.`,curse:`Every Special costs 4 additional Energy.`,stats:{ap:3},energyTax:4,glyph:`ϟ`},{id:`fangs`,name:`Fanged Jaw`,buff:`Close-range hits heal 6% of post-mitigation damage.`,curse:`-3 Range and -1 Battle IQ.`,stats:{range:-3,battleIq:-1},glyph:`牙`},{id:`spikes`,name:`Spiked Growth`,buff:`Attackers taking direct melee contact receive retaliation damage.`,curse:`-2 Speed and -25% Movement efficiency.`,stats:{speed:-2},mp:.75,glyph:`棘`},{id:`ooze`,name:`Ooze Glands`,buff:`Decay/Corrosive effects last +1 turn and +2 AP.`,curse:`All non-Immense external healing is 20% less effective.`,stats:{ap:2},heal:.8,glyph:`液`},{id:`hardening`,name:`Hardening`,buff:`+5 Durability and 12% ordinary damage resistance.`,curse:`-3 Speed and -2 Regeneration.`,stats:{durability:5,speed:-3,regeneration:-2},glyph:`硬`}]);
function RIFT_V36_MUTATIONS_OF(fighter){fighter.v36QuirkMutations=Array.isArray(fighter.v36QuirkMutations)?fighter.v36QuirkMutations:[];return fighter.v36QuirkMutations}
function RIFT_V36_MUTATION(id){return RIFT_V36_MUTATIONS.find(m=>m.id===id)}
function RIFT_V36_HAS_MUT(fighter,id){return RIFT_V36_MUTATIONS_OF(fighter).includes(id)}
