/* ---------- VIEGO: STRUCTURAL HEARTBREAKER FIX ---------- */
function RIFT_V36_ENFORCE_HEARTBREAKER(fighter){if(!fighter?.statuses?.v35Takeover)return fighter;const heart=RIFT_V36_COPY(RIFT_V35_RUINED_POWER.moves[3]),borrowed=RIFT_V36_COPY(fighter.power||{});borrowed.moves=[...(borrowed.moves||[]).slice(0,3),{...heart,cost:0,tags:[...(heart.tags||[]).filter(tag=>tag!==`allEnergy`),`ultimate`,`v35TakeoverExit`,`v351FreeHeartbreaker`,`v36TakeoverHeartbreaker`]}];fighter.power=borrowed;fighter.statuses.v35OriginalPower=RIFT_V35_RUINED;return fighter}
const RIFT_V36_BASE_BEGIN_TAKEOVER=RIFT_V35_BEGIN_TAKEOVER;
RIFT_V35_BEGIN_TAKEOVER=function RIFT_V36_BEGIN_TAKEOVER(run,fighter,snapshot,position,source=`wraith`){const ok=RIFT_V36_BASE_BEGIN_TAKEOVER(run,fighter,snapshot,position,source);if(ok)RIFT_V36_ENFORCE_HEARTBREAKER(fighter);return ok};
const RIFT_V36_BASE_NORMALIZE_FIGHTER=RIFT_NORMALIZE_FIGHTER_BUILD;
RIFT_NORMALIZE_FIGHTER_BUILD=function RIFT_V36_NORMALIZE_FIGHTER(fighter,...args){const out=RIFT_V36_BASE_NORMALIZE_FIGHTER(fighter,...args);RIFT_V36_ENFORCE_HEARTBREAKER(out||fighter);if(RIFT_V36_IS(out||fighter,RIFT_V36_SYMBOL)&&RIFT_V36_HAS_MUT(out||fighter,`airwalk`))(out||fighter).flight=true;return out};
const RIFT_V36_BASE_NORMALIZE_RUN=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V36_NORMALIZE_RUN(run,...args){run=RIFT_V36_BASE_NORMALIZE_RUN(run,...args);for(const fighter of [run?.player,run?.enemy,...(run?.auxiliaryCombatants||[]).map(x=>x.fighter)].filter(Boolean))RIFT_V36_ENFORCE_HEARTBREAKER(fighter);if(run)run.riftboundSchemaVersion=Math.max(36,Number(run.riftboundSchemaVersion||0));return run};

const RIFT_V36_BASE_GO=go;
go=function RIFT_V36_GO(run,attacker,target,amount,magic,tags=[]){tags=Array.isArray(tags)?[...tags]:[];if(target&&RIFT_V36_ITEM(target,RIFT_V36_MANTLE)&&RIFT_V36_CAUSAL(tags)){amount*=.5;RIFT_V36_FX(run,`true-darkness`,target,target,{radius:8,accent:`#321a58`})}if(target&&RIFT_V36_IS(target,RIFT_V36_KNIGHT)&&RIFT_V36_TRUE(tags)&&!RIFT_V36_CAUSAL(tags))tags=tags.filter(tag=>!/trueDamage|true-damage|true\b/i.test(String(tag))).concat([`v36TrueDefenseMitigated`]);if(target&&RIFT_V36_IS(target,RIFT_V36_SYMBOL)&&RIFT_V36_HAS_MUT(target,`hardening`)&&!RIFT_V36_CAUSAL(tags))amount*=.88;const directMelee=tags.some(tag=>/melee|strike|weapon/i.test(String(tag)))&&!tags.some(tag=>/area|wave|projectile|environment/i.test(String(tag)));const out=RIFT_V36_BASE_GO(run,attacker,target,amount,magic,tags);if(target&&RIFT_V36_IS(target,RIFT_V36_SYMBOL)&&RIFT_V36_HAS_MUT(target,`spikes`)&&directMelee&&attacker&&attacker!==target&&Number(out)>0)RIFT_V36_BASE_GO(run,target,attacker,Math.max(1,8+Y(target,`durability`)*1.4),false,[`physical`,`retaliation`,`v36Spikes`,`noItemProc`]);return out};
function RIFT_V36_AFTER_RAW_DAMAGE(run,attacker,target,damage,tags=[]){if(!target||target.hp>0||!RIFT_V36_ITEM(target,RIFT_V36_CRYSTAL)||target.statuses?.v36HoldBreathSpent)return;target.statuses=target.statuses||{};target.hp=1;target.statuses.v36HoldBreathSpent=1;target.statuses.v36HoldBreathSureHit=1;RIFT_V36_FX(run,`hold-breath`,target,target,{radius:10,accent:`#a968ff`});RIFT_V36_LOG(run,`HOLD BREATH // ${target.name} catches the lethal instant inside the Shadow Crystal and remains at 1 HP. Their next attack cannot miss.`,target,`mythic`)}

function RIFT_V36_ANTI_HEAL_KEYS(fighter){return Object.keys(fighter?.statuses||{}).filter(key=>/(anti.?heal|v14Spores|bloodspore|healing.?block|heal.?reduction)/i.test(key)&&fighter.statuses[key])}
const RIFT_V36_BASE_HEAL=oo;
oo=function RIFT_V36_HEAL(fighter,amount,...args){if(!RIFT_V36_IS(fighter,RIFT_V36_SYMBOL))return RIFT_V36_BASE_HEAL(fighter,amount,...args);const keys=RIFT_V36_ANTI_HEAL_KEYS(fighter),saved={};for(const key of keys){saved[key]=fighter.statuses[key];delete fighter.statuses[key]}let mult=keys.length?1:2;if(RIFT_V36_HAS_MUT(fighter,`ooze`))mult*=.8;let out;try{out=RIFT_V36_BASE_HEAL(fighter,Math.max(0,amount)*mult,...args)}finally{for(const [key,value] of Object.entries(saved))fighter.statuses[key]=value}return out};

const RIFT_V36_BASE_Y=Y;
Y=function RIFT_V36_STAT(fighter,stat){let value=RIFT_V36_BASE_Y(fighter,stat);if(RIFT_V36_IS(fighter,RIFT_V36_SYMBOL))for(const id of RIFT_V36_MUTATIONS_OF(fighter)){const mut=RIFT_V36_MUTATION(id);value+=Number(mut?.stats?.[stat]||0)}return value};
const RIFT_V36_BASE_MT=mt;
mt=function RIFT_V36_MOVEMENT(fighter){let value=RIFT_V36_BASE_MT(fighter);if(RIFT_V36_IS(fighter,RIFT_V36_SYMBOL)){if(RIFT_V36_HAS_MUT(fighter,`hypertrophy`))value*=.86;if(RIFT_V36_HAS_MUT(fighter,`spikes`))value*=.75}if(RIFT_V36_IS(fighter,RIFT_V36_KNIGHT)&&Number(fighter.statuses?.v36Roar||0)>0)value*=1.5;return value};

function RIFT_V36_KNOWN_MAP(target,run){target.statuses=target.statuses||{};if(target.statuses.v36KnightKnowledgeFloor!==run.floor){target.statuses.v36KnightKnowledgeFloor=run.floor;target.statuses.v36KnightKnowledge={}}return target.statuses.v36KnightKnowledge||(target.statuses.v36KnightKnowledge={})}
function RIFT_V36_UNKNOWN_BONUS(run,knight,target,moveName){if(!target)return 0;const map=RIFT_V36_KNOWN_MAP(target,run),key=String(moveName||`unknown`);if(map[key])return 0;map[key]=1;const roar=Number(knight.statuses?.v36Roar||0)>0?1.65:1;return Math.max(1,Math.round((10+Y(knight,`ap`)*3.2)*roar))}
function RIFT_V36_ADD_FEATURE(run,feature){if(!run?.battlefield)return null;run.battlefield.features=run.battlefield.features||[];const row={id:`v36-world-${F()}`,createdTurn:Number(run.turn||0),...feature};run.battlefield.features.push(row);return row}
function RIFT_V36_SEGMENT_DISTANCE(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(!l2)return I(p,a);const t=M(((p.x-a.x)*dx+(p.y-a.y)*dy)/l2,0,1),q={x:a.x+t*dx,y:a.y+t*dy};return I(p,q)}
function RIFT_V36_PROCESS_WORLD(run){if(!run?.battlefield||run.battlefield.v36ProcessedTurn===run.turn)return;run.battlefield.v36ProcessedTurn=run.turn;const features=run.battlefield.features||[],keep=[];for(const feature of features){if(feature.v36CrystalDue&&Number(run.turn||0)>=feature.dueTurn){for(const entry of H(run).filter(x=>x.kind===`fighter`&&x.fighter?.hp>0)){if(I(entry.position,feature.position)<=feature.radius){go(run,feature.owner||run.player,entry.fighter,feature.damage||28,true,[`magic`,`area`,`corrosive`,`v36CrystalRain`,`noItemProc`]);entry.fighter.statuses.v36Corrosion=Math.max(Number(entry.fighter.statuses.v36Corrosion||0),feature.corrosionTurns||2)}}RIFT_V36_FX(run,`crystal-rain`,feature.owner||run.player,feature.position,{radius:feature.radius,accent:`#7b39e8`});continue}if(feature.v36DecayPatch){if(feature.expiresTurn<=Number(run.turn||0))continue;if(feature.lastTick!==run.turn){feature.lastTick=run.turn;for(const entry of H(run).filter(x=>x.kind===`fighter`&&x.fighter?.hp>0)){if(entry.fighter!==feature.owner&&I(entry.position,feature.position)<=feature.radius)go(run,feature.owner,entry.fighter,feature.damage||18,true,[`magic`,`area`,`decay`,`environment`,`v36DecayGroundTick`,`noItemProc`])}}}keep.push(feature)}run.battlefield.features=keep}
const RIFT_V36_STAT_BEFORE_CORROSION=Y;
Y=function RIFT_V36_CORROSION_STAT(fighter,stat){let value=RIFT_V36_STAT_BEFORE_CORROSION(fighter,stat);if(stat===`durability`&&Number(fighter?.statuses?.v36Corrosion||0)>0)value-=2;return value};

function RIFT_V36_STOLEN_COUNT(fighter){const pools=[fighter?.stolenFactors,fighter?.factorArchive,fighter?.allForOneArchive,fighter?.powerArchive,fighter?.statuses?.stolenFactors,fighter?.statuses?.factorArchive,fighter?.statuses?.allForOneArchive];let names=new Set();for(const pool of pools)if(Array.isArray(pool))for(const row of pool)names.add(String(row?.name||row?.sourcePower||row||``));return [...names].filter(Boolean).length}
function RIFT_V36_CLEAR_DEBUFFS(fighter){for(const key of Object.keys(fighter?.statuses||{}))if(/burn|bleed|chill|freeze|stun|stagger|blind|poison|spore|anti.?heal|decayWound|restrain|crippl|jam|shock|static|slow|silence|debuff/i.test(key))delete fighter.statuses[key]}
function RIFT_V36_TRY_MUTATE(run,fighter){const owned=RIFT_V36_MUTATIONS_OF(fighter),available=RIFT_V36_MUTATIONS.filter(m=>!owned.includes(m.id));if(!available.length)return null;const stolen=RIFT_V36_STOLEN_COUNT(fighter),chance=M(.08+stolen*.035,.08,.38),rng=RIFT_V22_SEEDED(`${run?.v26Seed||run?.floor||0}|${run?.turn||0}|${fighter.name}|quirk-mutation`);if(rng()>chance)return null;const mut=available[Math.floor(rng()*available.length)%available.length];owned.push(mut.id);fighter.v36QuirkMutations=owned;if(mut.flight)fighter.flight=true;RIFT_V36_FX(run,`quirk-mutation`,fighter,fighter,{radius:11,accent:`#8d1746`,mutation:mut.id,name:mut.name});RIFT_V36_LOG(run,`QUIRK FACTOR MUTATION // ${mut.name}. KISS: ${mut.buff} CURSE: ${mut.curse}`,fighter,`mythic`);return mut}

const RIFT_V36_BASE_TT=Tt;
Tt=function RIFT_V36_TARGETING(action,fighter){const tags=action?.move?.tags||[];if(tags.includes(`v36Roar`))return{requiresAim:false,shape:`self`,range:0,radius:5,ignoresCover:true,label:`ROAR · SELF`,naturalRange:true};if(tags.includes(`v36CrystalBarrage`))return{requiresAim:true,shape:`area`,range:34,radius:10,ignoresCover:false,label:`DARK CRYSTAL STORM · 34m`,naturalRange:true};if(tags.includes(`v36DarkSword`))return{requiresAim:true,shape:`projectile`,range:36,radius:2.6,ignoresCover:false,label:`3 SWORD-BULLETS · 36m`,naturalRange:true};if(tags.includes(`v36Slice`))return{requiresAim:true,shape:`line`,range:24,radius:3.4,ignoresCover:false,label:`VOID SWORD ARC · 24m`,naturalRange:true};if(tags.includes(`v36Swoon`))return{requiresAim:false,shape:`global`,range:9999,radius:9999,ignoresCover:true,label:`GLOBAL · ALL HOSTILES`,naturalRange:true};if(tags.includes(`v36DecayGround`))return{requiresAim:false,shape:`self`,range:0,radius:7,ignoresCover:true,label:`DECAY GROUND · SELF AOE`,naturalRange:true};if(tags.includes(`v36ForcefulDecay`)||tags.includes(`v36Hatred`))return{requiresAim:true,shape:`target`,range:5.2,radius:2.4,ignoresCover:false,label:`STRIKE RANGE · 5.2m`,naturalRange:true};if(tags.includes(`v36RadioWaves`))return{requiresAim:true,shape:`wave`,range:28,radius:5,ignoresCover:false,label:`RADIO WAVE · 28m`,naturalRange:true};if(tags.includes(`v36RivetStab`))return{requiresAim:true,shape:`projectile`,range:24,radius:2.5,ignoresCover:false,label:`RIVET TENDRILS · 24m`,naturalRange:true};if(tags.includes(`v36AirCannon`))return{requiresAim:true,shape:`wave`,range:32,radius:7,ignoresCover:false,label:`AIR CANNON · 32m`,naturalRange:true};if(tags.includes(`v36AcceleratorRings`))return{requiresAim:true,shape:`dash`,range:RIFT_V36_HAS_MUT(fighter,`spring`)?40:34,radius:4,ignoresCover:false,label:`ACCELERATOR RINGS · ${RIFT_V36_HAS_MUT(fighter,`spring`)?40:34}m`,naturalRange:true};return RIFT_V36_BASE_TT(action,fighter)};

const RIFT_V36_BASE_LA=La;
La=function RIFT_V36_ACTIONS(fighter){RIFT_V36_ENFORCE_HEARTBREAKER(fighter);let actions=RIFT_V36_BASE_LA(fighter);if(RIFT_V36_IS(fighter,RIFT_V36_KNIGHT)){actions=actions.map(action=>action.type===`rest`?{...action,id:`v36-roar`,name:`Roar`,description:`Replace Rest with a void roar. For the next owner turn: 1.5× Movement efficiency, stronger unknown-technique AP bonus, and flight.`,glyph:`◉`,type:`special`,cost:0,move:RIFT_V36_MOVE(`Roar`,`Increase Movement efficiency and Darker Darker Yet Darker's unseen-technique bonus for the next turn while gaining flight.`,0,0,.1,[`selfCast`,`v36Roar`],1,`◉`)}:({...action,cost:action.type===`special`?0:action.cost,move:action.type===`special`?{...RIFT_V36_COPY(action.move),cost:0}:action.move}))}if(RIFT_V36_IS(fighter,RIFT_V36_SYMBOL)&&RIFT_V36_HAS_MUT(fighter,`blacklightning`))actions=actions.map(action=>action.type===`special`&&!((action.move?.tags||[]).includes(`symbolFactorWheel`))?{...action,cost:Number(action.cost||0)+4,move:{...RIFT_V36_COPY(action.move),cost:Number(action.move?.cost||0)+4}}:action);if(fighter?.statuses?.v35Takeover){RIFT_V36_ENFORCE_HEARTBREAKER(fighter);actions=actions.filter(action=>Number(action.slot)!==8&&Number(action.moveIndex)!==3&&action.type!==`ultimate`&&!(action.move?.tags||[]).some(tag=>tag===`ultimate`||tag===`allEnergy`));const heart=fighter.power.moves[3];actions.push({id:`v36-heartbreaker-takeover`,slot:8,name:`Heartbreaker`,description:`TAKEOVER · FREE · Viego's own Heartbreaker. Cast to teleport, execute, and immediately eject from the stolen body.`,glyph:`心`,type:`ultimate`,cost:0,move:RIFT_V36_COPY(heart),moveIndex:3,sourcePower:RIFT_V35_RUINED})}return actions};
