const RIFT_V26_MARKER=`Riftbound Ascension Reframed V26`;
const RIFT_V26_VERSION=26,RIFT_V26_SEED_KEY=`riftbound:v26:pending-seed`,RIFT_V26_TUTORIAL_KEY=`riftbound:v26:tutorials`;
const RIFT_V26_MILESTONES=Object.freeze([{floor:1,label:`FIRST DESCENT`},{floor:5,label:`FIRST SOVEREIGN`},{floor:10,label:`BUILD PRESSURE`},{floor:20,label:`RIFT ASCENDANT`},{floor:35,label:`REQUIEM CROSSROADS`},{floor:50,label:`CALAMITY THRESHOLD`}]);
const RIFT_V26_TUTORIALS=Object.freeze({movement:{title:`MOVEMENT & RANGE`,body:`Movement does not spend the fighter action. Open the tactical map to read routes, cover, height, hazards, and the real footprint of an armed move.`},items:{title:`BUILD WORKBENCH`,body:`Components contribute stats while owned. The Armory shows exact remaining recipe cost and every item that a craft consumes.`},stand:{title:`INDEPENDENT STAND TURN`,body:`Summoned Stands occupy the battlefield and receive their own command. Their range and position can differ from the user's body.`},domain:{title:`DOMAIN SPACE`,body:`Domains are physical battlefield fields with integrity, radius, duration, and a separate burnout phase.`},rika:{title:`RIKA AUTHORITY`,body:`Rika has her own position, movement reserve, command mode, and inventory ownership. Hunt, Protect, and Hold are distinct orders.`},resource:{title:`POWER RESOURCE`,body:`This power adds a resource or transformation track. Its combat HUD shows setup, spend conditions, and the resulting action state.`},coop:{title:`HOST AUTHORITY`,body:`Player 2 owns the Rift Echo. The host validates movement and one ally action per turn before committing reality.`}});
function RIFT_V26_PENDING_SEED(){try{return String(RIFT_V21_STORAGE().getItem(RIFT_V26_SEED_KEY)||``).slice(0,64)}catch{return``}}
function RIFT_V26_SET_SEED(seed){seed=String(seed||``).trim().slice(0,64);if(seed)RIFT_V21_STORAGE().setItem(RIFT_V26_SEED_KEY,seed);else RIFT_V21_STORAGE().removeItem(RIFT_V26_SEED_KEY);return seed}
function RIFT_V26_RUN_SEED(run){return String(run?.v26Seed||run?.seed||run?.battlefield?.seed||`RIFT-${run?.floor||1}-${RIFT_V21_HASH(run?.player?.name||`Hunter`)}`)}
function RIFT_V26_ROUTE_ROW(route){if(!route)return null;return{id:route.id||qt(route.name||`route`),name:route.name||`Unknown Route`,archetype:route.archetype||`UNKNOWN`,risk:route.risk||route.description||`Unknown pressure`,reward:route.reward||`Unknown reward`,minFloor:Number(route.minFloor||1),accent:route.accent||`#a77dff`}}
function RIFT_V26_ASCENSION_MODEL(run){
 if(!run)return{active:false,seed:RIFT_V26_PENDING_SEED()||null,milestones:RIFT_V26_MILESTONES};const history=Array.isArray(run.v26RouteChronicle)?run.v26RouteChronicle:[],choices=(run.routeChoices||[]).map(choice=>typeof choice===`string`?(typeof He!==`undefined`?He.find(route=>route.id===choice):null):choice).filter(Boolean).map(RIFT_V26_ROUTE_ROW),next=RIFT_V26_MILESTONES.find(row=>row.floor>=Number(run.floor||1))||RIFT_V26_MILESTONES.at(-1);
 return{active:true,seed:RIFT_V26_RUN_SEED(run),floor:Number(run.floor||1),phase:run.phase,objective:run.phase===`combat`?`Defeat ${run.enemy?.name||`the current hostile`}`:run.phase===`intermission`?`Rebuild, recover, and choose the next descent`:`Continue the Ascension`,history:P(history),choices,milestones:RIFT_V26_MILESTONES.map(row=>({...row,state:row.floor<run.floor?`complete`:row.floor===run.floor?`current`:`future`})),nextMilestone:next,build:RIFT_ITEM_INSTANCES(run.player).map(instance=>RIFT_ITEM(instance.itemId)?.name).filter(Boolean),discoveries:(run.chronicle||[]).slice(-6)};
}
const RIFT_V26_EMPTY_METRICS=()=>({actions:0,damage:0,healing:0,movement:0,resources:0,byAction:{}}),RIFT_V26_ORPHAN_METRICS=RIFT_V26_EMPTY_METRICS();
function RIFT_V26_METRICS(run=globalThis.__RIFTBOUND_ACTIVE_RUN__){if(!run)return RIFT_V26_ORPHAN_METRICS;run.v26Metrics=run.v26Metrics&&typeof run.v26Metrics===`object`?run.v26Metrics:RIFT_V26_EMPTY_METRICS();run.v26Metrics.byAction=run.v26Metrics.byAction&&typeof run.v26Metrics.byAction===`object`?run.v26Metrics.byAction:{};return run.v26Metrics}
RIFT_V22_EVENT_BUS.on(`ACTION_FINISHED`,event=>{const metrics=RIFT_V26_METRICS();metrics.actions+=1;const name=event.payload.name||`Action`;metrics.byAction[name]=(metrics.byAction[name]||0)+1});
RIFT_V22_EVENT_BUS.on(`DAMAGE_APPLIED`,event=>{RIFT_V26_METRICS().damage+=Number(event.payload.amount||0)});RIFT_V22_EVENT_BUS.on(`HEALING_APPLIED`,event=>{RIFT_V26_METRICS().healing+=Number(event.payload.amount||0)});RIFT_V22_EVENT_BUS.on(`ACTOR_MOVED`,event=>{RIFT_V26_METRICS().movement+=Number(event.payload.distance||0)});RIFT_V22_EVENT_BUS.on(`RESOURCE_CHANGED`,()=>{RIFT_V26_METRICS().resources+=1});
function RIFT_V26_RUN_SUMMARY(run){const metrics=RIFT_V26_METRICS(run),actions=Object.entries(metrics.byAction).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([name,count])=>({name,count})),atlas=RIFT_V26_ASCENSION_MODEL(run),replay=RIFT_V21_REPLAY_EXPORT();return{version:26,result:run?.player?.hp>0?`surviving`:`defeated`,floor:run?.floor||0,seed:atlas.seed,actions:metrics.actions,damage:Math.round(metrics.damage),healing:Math.round(metrics.healing),movement:Math.round(metrics.movement*10)/10,resourceChanges:metrics.resources,mostUsed:actions,build:atlas.build,route:atlas.history,replayHash:replay.hash,stateHash:RIFT_V22_STATE_HASH(run)}}
function RIFT_V26_TUTORIAL_STATE(){const stored=RIFT_V21_READ_JSON(RIFT_V26_TUTORIAL_KEY,{disabled:false,seen:[]});stored.seen=Array.isArray(stored.seen)?stored.seen:[];return stored}
function RIFT_V26_TUTORIAL(run){if(!run)return null;const state=RIFT_V26_TUTORIAL_STATE();if(state.disabled)return null;const candidates=[];if(run.phase===`combat`&&run.floor<=2)candidates.push(`movement`);if(run.phase===`intermission`)candidates.push(`items`);if(run.player?.stand)candidates.push(`stand`);if((run.battlefield?.domains||[]).length||run.player?.power?.moves?.some(move=>(move.tags||[]).includes(`domain`)))candidates.push(`domain`);if(RIFT_CURSED_CHILD(run.player))candidates.push(`rika`);if(Object.keys(run.player?.statuses||{}).some(key=>/charge|gear|spiral|flair|combo|inertia/i.test(key)))candidates.push(`resource`);if(run.v20Coop?.active)candidates.push(`coop`);const id=candidates.find(candidate=>!state.seen.includes(candidate));return id?{id,...RIFT_V26_TUTORIALS[id]}:null}
function RIFT_V26_TUTORIAL_SEEN(id){const state=RIFT_V26_TUTORIAL_STATE();if(!state.seen.includes(id))state.seen.push(id);RIFT_V21_WRITE_JSON(RIFT_V26_TUTORIAL_KEY,state);return state}
const RIFT_V26_BASE_APPLY_ROUTE=RIFT_V16_APPLY_ROUTE;
RIFT_V16_APPLY_ROUTE=function RIFT_V26_APPLY_ROUTE(run,...args){const selected=RIFT_V26_ROUTE_ROW((run.routeChoices||[]).find(choice=>(choice.id||choice)===run.selectedRoute)||(args[0]&&typeof args[0]===`object`?args[0]:null)),before={floor:run.floor,hp:run.player?.hp,shards:run.shards};const output=RIFT_V26_BASE_APPLY_ROUTE(run,...args);run.v26RouteChronicle=Array.isArray(run.v26RouteChronicle)?run.v26RouteChronicle:[];run.v26RouteChronicle.push({floor:before.floor,route:selected?.id||run.v16RouteState?.active||run.selectedRoute||`unknown`,name:selected?.name||run.v16RouteState?.name||`Unknown Route`,risk:selected?.risk||null,reward:selected?.reward||null,hpBefore:before.hp,shardsBefore:before.shards,at:Date.now()});run.v26RouteChronicle=run.v26RouteChronicle.slice(-80);return output};
const RIFT_V26_BASE_NEW_RUN=Da;
Da=function RIFT_V26_NEW_RUN(...args){const run=RIFT_V26_BASE_NEW_RUN(...args),pending=RIFT_V26_PENDING_SEED();run.v26Seed=pending||`RIFT-${Date.now().toString(36).toUpperCase()}-${RIFT_V21_HASH(run.player?.power?.name||`POWER`).slice(0,5).toUpperCase()}`;run.v26RouteChronicle=[];run.v26Metrics=RIFT_V26_EMPTY_METRICS();globalThis.__RIFTBOUND_ACTIVE_RUN__=run;RIFT_V21_REPLAY_BEGIN(run.v26Seed);return run};
function RIFT_V26_ESCAPE(text){return String(text??``).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}
function RIFT_V26_ASCENSION_PANEL(){
 if(typeof document===`undefined`||document.getElementById(`rift-v26-atlas-root`))return;const root=document.createElement(`div`);root.id=`rift-v26-atlas-root`;root.innerHTML=`<button type="button" id="rift-v26-atlas-toggle">ASCENSION</button><section hidden><header><span><small>V26 ASCENSION REFRAMED</small><strong>RUN ATLAS</strong></span><button type="button" data-close>×</button></header><main data-content></main></section>`;document.body.appendChild(root);const panel=root.querySelector(`section`),content=root.querySelector(`[data-content]`);let lastHash=``;const render=()=>{const run=globalThis.__RIFTBOUND_ACTIVE_RUN__,model=RIFT_V26_ASCENSION_MODEL(run),hash=RIFT_V21_HASH(model);if(hash===lastHash)return;lastHash=hash;if(!model.active){content.innerHTML=`<div class="v26-seed-setup"><small>NEXT RUN SEED</small><strong>${RIFT_V26_ESCAPE(model.seed||`RANDOM`)}</strong><input maxlength="64" placeholder="Optional custom seed"><button type="button" data-seed>SET SEED</button></div>`;return}const tutorial=RIFT_V26_TUTORIAL(run),summary=RIFT_V26_RUN_SUMMARY(run);content.innerHTML=`<div class="v26-atlas-head"><span><small>FLOOR ${model.floor} · ${RIFT_V26_ESCAPE(model.phase).toUpperCase()}</small><strong>${RIFT_V26_ESCAPE(model.objective)}</strong><em>SEED ${RIFT_V26_ESCAPE(model.seed)}</em></span><b>${model.build.length}/6 ITEMS</b></div><div class="v26-milestones">${model.milestones.map(row=>`<i class="${row.state}"><b>${row.floor}</b><small>${row.label}</small></i>`).join(``)}</div><section class="v26-route-choices"><small>NEXT ROUTES</small>${model.choices.length?model.choices.map(route=>`<article><b>${RIFT_V26_ESCAPE(route.name)}</b><span>${RIFT_V26_ESCAPE(route.risk)}</span><em>${RIFT_V26_ESCAPE(route.reward)}</em></article>`).join(``):`<p>Route choices appear at the next intermission.</p>`}</section><section class="v26-run-metrics"><span><small>DAMAGE</small><b>${summary.damage}</b></span><span><small>ACTIONS</small><b>${summary.actions}</b></span><span><small>MOVED</small><b>${summary.movement}m</b></span><span><small>ROUTES</small><b>${model.history.length}</b></span></section>${tutorial?`<aside class="v26-tutorial" data-tutorial="${tutorial.id}"><small>CONTEXTUAL GUIDE</small><strong>${tutorial.title}</strong><p>${tutorial.body}</p><button type="button" data-dismiss>UNDERSTOOD</button></aside>`:``}`};root.querySelector(`#rift-v26-atlas-toggle`).onclick=()=>{panel.hidden=!panel.hidden;lastHash=``;render()};root.querySelector(`[data-close]`).onclick=()=>panel.hidden=true;root.addEventListener(`click`,event=>{if(event.target.closest(`[data-seed]`)){const input=root.querySelector(`input`);RIFT_V26_SET_SEED(input?.value||``);lastHash=``;render()}if(event.target.closest(`[data-dismiss]`)){const tutorial=event.target.closest(`[data-tutorial]`);if(tutorial)RIFT_V26_TUTORIAL_SEEN(tutorial.dataset.tutorial);lastHash=``;render()}});setInterval(()=>{if(!panel.hidden)render()},750);render();
}
const RIFT_V26_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V26_NORMALIZE_RUN_BUILD(run){run=RIFT_V26_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(26,Number(run.riftboundSchemaVersion||0));run.v26Seed=run.v26Seed||RIFT_V26_RUN_SEED(run);run.v26RouteChronicle=Array.isArray(run.v26RouteChronicle)?run.v26RouteChronicle:[];RIFT_V26_METRICS(run);globalThis.__RIFTBOUND_ACTIVE_RUN__=run;return run};
globalThis.RIFTBOUND_ASCENSION={version:26,model:RIFT_V26_ASCENSION_MODEL,summary:RIFT_V26_RUN_SUMMARY,seed:{get:RIFT_V26_PENDING_SEED,set:RIFT_V26_SET_SEED},tutorial:{current:RIFT_V26_TUTORIAL,dismiss:RIFT_V26_TUTORIAL_SEEN,definitions:RIFT_V26_TUTORIALS},milestones:RIFT_V26_MILESTONES};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:26,release:`V26 · Ascension Reframed`,ascension:{customSeed:true,routeAtlas:true,floorHistory:true,milestones:RIFT_V26_MILESTONES,contextualTutorials:Object.keys(RIFT_V26_TUTORIALS),runSummary:[`damage`,`healing`,`movement`,`actions`,`build`,`route`,`replay`]}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:26,ascension:()=>RIFT_V26_ASCENSION_MODEL(globalThis.__RIFTBOUND_ACTIVE_RUN__)};
if(typeof window!==`undefined`){const boot=()=>RIFT_V26_ASCENSION_PANEL();document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,boot,{once:true}):boot()}
