 if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)){if(tags.includes(`v35ChainLash`)){RIFT_V35_CHAIN_MARK(run,fighter,action?.aim?.target||RIFT_V35_POINT(run,target));RIFT_V35_EFFECT(run,`chain-lash`,fighter,action?.aim?.target||target,{radius:5.5})}if(tags.includes(`v35Kingslayer`)){RIFT_V35_DASH_TO(run,fighter,RIFT_V35_POINT(run,target),5.2);const dealt=Math.max(0,(targetHp||0)-(target?.hp||0));if(dealt>0)oo(fighter,Math.max(1,Math.round(dealt*.2)));RIFT_V35_EFFECT(run,`kingslayer`,fighter,target,{radius:5})}if(tags.includes(`v35Abscond`)){const cd=Ba(fighter,action);if(cd)delete fighter.statuses[cd];RIFT_V35_DASH_TO(run,fighter,action?.aim?.target,11);fighter.statuses.v35AbductWindow=2;RIFT_V35_EFFECT(run,`abscond`,fighter,action?.aim?.target,{radius:4})}if(action.type===`strike`&&(fighter.statuses.v35Petricite||0)>0){fighter.statuses.v35Petricite-=1;const hit=target&&target.hp<(targetHp??target.hp);if(hit){const center=RIFT_V35_POINT(run,fighter);for(const entry of RIFT_V35_HOSTILES(run,fighter))if(I(W(run,entry.id),center)<=6)go(run,fighter,entry.fighter,12+Y(fighter,`ap`)*2.7,true,[`magic`,`area`,`v35PetriciteBurst`,`noItemProc`]);RIFT_V35_EFFECT(run,`petricite`,fighter,center,{radius:6})}}if(action.type===`special`||action.type===`ultimate`)RIFT_V35_PETRICITE(fighter,1)}
 return result};

/* ---------- DIRECT TARGETING INVISIBILITY + KILL / RAGE HOOK ---------- */
const RIFT_V35_BASE_GO=go;
go=function RIFT_V35_GO(run,attacker,target,amount,flag,tags=[]){tags=Array.isArray(tags)?tags:[];if(target&&RIFT_V35_IS(target,RIFT_V35_RUINED)&&target.statuses?.v35HarrowInvisible&&RIFT_V35_IN_HARROW(run,target)&&!tags.some(tag=>[`area`,`environment`,`domain`,`shockwave`,`explosion`,`radiation`,`wave`,`cone`,`sweep`].includes(tag))){RIFT_V35_LOG(run,`HARROWED PATH // ${target.name} is only a wraith-shape in the Black Mist. Direct targeting loses the body.`,target,`mythic`);return 0}const before=target?.hp,result=RIFT_V35_BASE_GO(run,attacker,target,amount,flag,tags);if(target&&before>0&&target.hp<=0)RIFT_V35_ON_KILL(run,attacker,target);return result};

/* ---------- TURN TICKS ---------- */
const RIFT_V35_BASE_UA=Ua;
Ua=function RIFT_V35_TICK(fighter){RIFT_V35_BASE_UA(fighter);if(!fighter?.statuses)return;if(fighter.statuses.v35BorkClawCooldown>0){fighter.statuses.v35BorkClawCooldown-=1;if(fighter.statuses.v35BorkClawCooldown<=0)delete fighter.statuses.v35BorkClawCooldown}if(fighter.statuses.v35BorkSlow>0){fighter.statuses.v35BorkSlow-=1;if(fighter.statuses.v35BorkSlow<=0)delete fighter.statuses.v35BorkSlow}if(fighter.statuses.v35AbscondCooldown>0){fighter.statuses.v35AbscondCooldown-=1;if(fighter.statuses.v35AbscondCooldown<=0)delete fighter.statuses.v35AbscondCooldown}else if(fighter.statuses.v35AbductWindow>0){fighter.statuses.v35AbductWindow-=1;if(fighter.statuses.v35AbductWindow<=0){delete fighter.statuses.v35AbductWindow;fighter.statuses.v35AbscondCooldown=3}}if(RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)&&fighter.statuses.v35Berserk){fighter.statuses.v35Rage=Math.max(0,RIFT_V35_RAGE(fighter)-14);if(fighter.statuses.v35Rage<=0)delete fighter.statuses.v35Berserk}if(fighter.statuses.v35HijackedDevilTrigger?.turns>0){fighter.statuses.v35HijackedDevilTrigger.turns-=1;if(fighter.statuses.v35HijackedDevilTrigger.turns<=0){fighter.flight=!!fighter.statuses.v35HijackedDevilTrigger.baseFlight;delete fighter.statuses.v35HijackedDevilTrigger}}if(fighter.statuses.v35Wrath>0){fighter.statuses.v35Wrath-=1;if(fighter.statuses.v35Wrath<=0)delete fighter.statuses.v35Wrath}if(fighter.statuses.v35Takeover?.remaining>0){fighter.statuses.v35Takeover.remaining-=1;if(fighter.statuses.v35Takeover.remaining<=0){const run=globalThis.__RIFTBOUND_ACTIVE_RUN__;if(run)RIFT_V35_RESTORE_TAKEOVER(run,fighter,`Five stolen turns expire`)}}};

/* ---------- READ-ONLY BORROWED INVENTORY ---------- */
const RIFT_V35_BASE_BUY=RIFT_BUY_ITEM,RIFT_V35_BASE_SELL=RIFT_SELL_ITEM,RIFT_V35_BASE_MOVE_ITEM=RIFT_MOVE_ITEM;
RIFT_BUY_ITEM=function RIFT_V35_BUY(run,itemId){if(run?.player?.statuses?.v35Takeover)return{ok:false,reason:`TAKEOVER INVENTORY IS BORROWED · exit the body before changing equipment.`};return RIFT_V35_BASE_BUY(run,itemId)};
RIFT_SELL_ITEM=function RIFT_V35_SELL(run,slot){if(run?.player?.statuses?.v35Takeover)return{ok:false,reason:`TAKEOVER INVENTORY IS BORROWED · stolen-body items cannot be sold.`};return RIFT_V35_BASE_SELL(run,slot)};
RIFT_MOVE_ITEM=function RIFT_V35_MOVE_ITEM(fighter,from,to){if(fighter?.statuses?.v35Takeover)return{ok:false,reason:`TAKEOVER INVENTORY IS BORROWED · item layout is read-only.`};return RIFT_V35_BASE_MOVE_ITEM(fighter,from,to)};
const RIFT_V35_BASE_SPARTAN_REFORGE=RIFT_SPARTAN_REFORGE;
RIFT_SPARTAN_REFORGE=function RIFT_V35_REFORGE(run,uid){if(run?.player?.statuses?.v35Takeover)return{ok:false,reason:`TAKEOVER INVENTORY IS BORROWED · borrowed gear cannot be reforged.`};return RIFT_V35_BASE_SPARTAN_REFORGE(run,uid)};

/* ---------- NORMALIZATION ---------- */
const RIFT_V35_BASE_NORMALIZE=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V35_NORMALIZE(run){run=RIFT_V35_BASE_NORMALIZE(run);if(!run)return run;const meta=RIFT_V35_SYNC_META(run);run.riftboundSchemaVersion=Math.max(35,Number(run.riftboundSchemaVersion||0));run.metaProgression={...(run.metaProgression||{}),ragegodUnlocked:meta.ragegodUnlocked};for(const fighter of [run.player,run.enemy,...(run.auxiliaryCombatants||[]).map(entry=>entry.fighter)].filter(Boolean)){if(RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)){fighter.statuses.v35Rage=M(Number(fighter.statuses.v35Rage||0),0,100);fighter.maxEnergy=0;fighter.energy=0}RIFT_REFRESH_ITEM_POOLS(fighter)}globalThis.__RIFTBOUND_ACTIVE_RUN__=run;return run};

/* ---------- CODEX + TACTICAL CONTRACTS ---------- */
const RIFT_V35_PREVIEW={
 [`Ruined King|Blade of the Ruined King`]:{pattern:`melee-line-pierce`,geometry:{shape:`line`,range:7.5,radius:1.9},acquisition:`Aim a short direction.`,resolution:`Viego's body commits behind a spectral zweihander thrust.`,aftermath:`Successful contact refreshes the technique.`},
 [`Ruined King|Spectral Maw`]:{pattern:`dash-projectile`,geometry:{shape:`projectile`,range:20,radius:2.8},acquisition:`Aim a line.`,resolution:`Body dashes briefly while the Black Mist projectile keeps travelling.`,aftermath:`Projectile contact stuns.`},
 [`Ruined King|Harrowed Path`]:{pattern:`point-persistent-field-stealth`,geometry:{shape:`area`,range:18,radius:14},acquisition:`Choose a nearby region.`,resolution:`Black Mist spreads into persistent world geometry.`,aftermath:`3-turn camouflage and movement-efficiency field.`},
 [`Ruined King|Heartbreaker`]:{pattern:`teleport-area`,geometry:{shape:`area`,range:24,radius:7.5},acquisition:`Choose the execution center.`,resolution:`Viego appears at the center and cleaves outward.`,aftermath:`Missing-HP scaling; exits Takeover.`},
