Y=function RIFT_V35_Y(fighter,stat){let value=RIFT_V35_BASE_Y(fighter,stat);if(RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)&&fighter.statuses?.v35Berserk&&[`as`,`durability`,`speed`,`regeneration`].includes(stat)){const bonus=RIFT_V35_BERSERK_BONUS(fighter);value+=stat===`speed`?Math.max(2,Math.ceil(bonus*.85)):bonus}if(fighter?.statuses?.v35HijackedDevilTrigger&&[`as`,`ap`,`durability`,`speed`,`regeneration`].includes(stat))value+=stat===`regeneration`?2:3;return value};

/* Movement debuffs/efficiency. Harrowed Path refunds one third of spent MP while the body remains in its mist. */
const RIFT_V35_BASE_MT=mt;
mt=function RIFT_V35_MT(fighter){let value=RIFT_V35_BASE_MT(fighter);if(fighter?.statuses?.v35BorkSlow>0)value*=.7;return value};
const RIFT_V35_BASE_AI=Ai;
Ai=function RIFT_V35_AI(run,actorId,next){let current=Oi(run,actorId),fighter=U(run,actorId)?.fighter;if(fighter&&next<current&&RIFT_V35_IS(fighter,RIFT_V35_RUINED)&&RIFT_V35_IN_HARROW(run,fighter)){const spent=current-next;next=current-spent/1.5}return RIFT_V35_BASE_AI(run,actorId,next)};

/* ---------- TARGETING GRAMMAR ---------- */
const RIFT_V35_BASE_TT=Tt;
Tt=function RIFT_V35_TARGETING(action,fighter){const tags=action?.move?.tags||[],has=tag=>tags.includes(tag);if(has(`v35ViegoQ`))return{requiresAim:true,shape:`line`,range:7.5,radius:1.9,ignoresCover:false,label:`SPECTRAL ZWEIHANDER · 7.5m`,naturalRange:true};if(has(`v35ViegoW`))return{requiresAim:true,shape:`projectile`,range:20,radius:2.8,ignoresCover:false,label:`BLACK MIST MAW · DASH + 20m SHOT`,naturalRange:true};if(has(`v35ViegoE`))return{requiresAim:true,shape:`area`,range:18,radius:14,ignoresCover:true,label:`HARROWED PATH · 14m FIELD`,naturalRange:true};if(has(`v35Heartbreaker`))return{requiresAim:true,shape:`area`,range:24,radius:7.5,ignoresCover:true,label:`HEARTBREAKER · TELEPORT AOE`,naturalRange:true};if(has(`v35ChainLash`))return{requiresAim:true,shape:`line`,range:18,radius:3.6,ignoresCover:false,label:`CROSSING CHAINS · DELAYED RUPTURE`,naturalRange:true};if(has(`v35Kingslayer`))return{requiresAim:true,shape:`melee`,range:5.2,radius:2.3,ignoresCover:false,label:`FIXED STRIKE RANGE · 5.2m`,naturalRange:true};if(has(`v35Abscond`))return{requiresAim:true,shape:`dash`,range:11,radius:2.5,ignoresCover:true,label:`ABSCOND · 11m`,naturalRange:true};if(has(`v35Abduct`))return{requiresAim:true,shape:`projectile`,range:22,radius:2.4,ignoresCover:false,label:`ABDUCT · ENEMY ONLY · 22m`,naturalRange:true};return RIFT_V35_BASE_TT(action,fighter)};

/* ---------- ACTION SURFACE ---------- */
const RIFT_V35_BASE_LA=La;
La=function RIFT_V35_ACTIONS(fighter){let actions=RIFT_V35_BASE_LA(fighter);if(!fighter)return actions;
 if(RIFT_V35_IS(fighter,RIFT_V35_RUINED)&&fighter.statuses.v35Takeover){const state=fighter.statuses.v35Takeover,heart=RIFT_V35_RUINED_POWER.moves[3];actions=actions.filter(action=>action.type!==`ultimate`);actions.push({id:`v35-heartbreaker-takeover`,slot:8,name:`Heartbreaker · EXIT BODY`,description:`FREE DURING TAKEOVER · ${state.remaining} turn${state.remaining===1?``:`s`} remain. Teleport into the AOE, execute on missing HP, and immediately restore Viego's original body and build.`,glyph:`心`,type:`special`,cost:0,move:{...RIFT_V35_COPY(heart),cost:0,tags:[...heart.tags.filter(tag=>tag!==`allEnergy`),`ultimate`,`v35TakeoverExit`]},moveIndex:3,sourcePower:RIFT_V35_RUINED})}
 if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)){const pet=Math.round(fighter.statuses.v35Petricite||0);actions=actions.map(action=>action.id===`strike`?{...action,description:`${action.description} PETRICITE ${pet}/3 · ${pet?`next Strike detonates an AP chain-burst around Sylas`:`cast a technique to arm it`}.`}:action);if(fighter.statuses.v35AbductWindow>0)actions.push({id:`v35-abduct`,slot:7.5,name:`Abduct`,description:`RECAST WINDOW ${fighter.statuses.v35AbductWindow}T · Grapple yourself to an enemy and stun them. Using it starts Abscond's 3-turn recovery.`,glyph:`鏈`,type:`special`,cost:0,move:RIFT_V35_ABDUCT_MOVE,moveIndex:2,sourcePower:RIFT_V35_UNSHACKLED});if(fighter.statuses.v35Hijacked){const stored=fighter.statuses.v35Hijacked;actions=actions.filter(action=>action.type!==`ultimate`);actions.push({id:`v35-hijacked-cast`,slot:8,name:`HIJACKED · ${stored.name}`,description:`STOLEN FROM ${stored.sourceName.toUpperCase()} · FREE ONE-TIME CAST · uses Sylas's stats · original passive prerequisites waived.`,glyph:`奪`,type:`special`,cost:0,move:{...RIFT_V35_COPY(stored.action.move),cost:0,tags:[...(stored.action.move?.tags||[]).filter(tag=>tag!==`allEnergy`),`ultimate`,`v35HijackedTechnique`]},moveIndex:3,sourcePower:stored.sourcePower,selectedFactors:stored.action.selectedFactors})}else actions=actions.map(action=>action.move?.tags?.includes(`v35Hijack`)?{...action,cost:0,description:`${action.description} CURRENT THRESHOLD: ${RIFT_V35_HIJACK_COST(fighter,globalThis.__RIFTBOUND_ACTIVE_RUN__?.enemy||{})}% against the selected target.`}:action)}
 if(RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)){fighter.maxEnergy=0;fighter.energy=0;actions=actions.map(action=>{const cost=RIFT_V35_RAGE_COST(action);if(action.type===`rest`)return{...action,name:`Steady Breath`,description:`Hold position. Rage is not Energy and cannot be restored by resting.`,cost:0};if(action.move?.tags?.includes(`v35RageMove`))return{...action,cost:0,description:`${action.description} · ${cost} RAGE`,rageCost:cost};if(action.move?.tags?.includes(`v35Wrath`))return{...action,cost:0,description:`${action.description} · 100% ULTIMATE · NO RAGE COST`};return action})}
 return actions};

const RIFT_V35_BASE_KR=kr;
kr=function RIFT_V35_ULT_READY(fighter,target){if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)&&!fighter.statuses.v35Hijacked)return fighter.ultimate>=RIFT_V35_HIJACK_COST(fighter,target);return RIFT_V35_BASE_KR(fighter,target)};
const RIFT_V35_BASE_QA=qa;
qa=function RIFT_V35_BLOCK_REASON(run,action,resolving,locked,target){const fighter=run?.player,tags=action?.move?.tags||[];if(RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)&&tags.includes(`v35RageMove`)){const cost=RIFT_V35_RAGE_COST(action);if(RIFT_V35_RAGE(fighter)<cost)return`${Math.ceil(cost-RIFT_V35_RAGE(fighter))} more Rage required`}if(tags.includes(`v35Abscond`)&&fighter?.statuses?.v35AbscondCooldown>0)return`Abscond recovers in ${fighter.statuses.v35AbscondCooldown} turn${fighter.statuses.v35AbscondCooldown===1?``:`s`}`;return RIFT_V35_BASE_QA(run,action,resolving,locked,target)};

/* ---------- CORE RESOLUTION ---------- */
function RIFT_V35_DASH_TO(run,fighter,point,maxDistance){const id=RIFT_V35_ACTOR(run,fighter);if(!id||!point)return null;const from={...W(run,id)},dist=Math.max(.01,I(from,point)),scale=Math.min(1,maxDistance/dist),dest={x:from.x+(point.x-from.x)*scale,y:from.y+(point.y-from.y)*scale},land=Wi(run.battlefield,dest,Ft(run,id).map(entry=>entry.position));ki(run,id,land);return{origin:from,end:{...land}}}
