function RIFT_V35_SYNC_META(run){const meta=RIFT_V35_META();if(run?.player?.power?.name===`Super Strength`&&Number(run.floor||1)>=11)meta.ragegodUnlocked=true;return RIFT_V35_SAVE_META(meta)}
Object.defineProperty(RIFT_V35_RAGEGOD_POWER,`rollable`,{configurable:true,get(){return !!RIFT_V35_META().ragegodUnlocked}});

/* ---------- BORK ITEM MECHANICS ---------- */
function RIFT_V35_BORK(fighter){try{return RIFT_ACTIVE_ITEM(fighter)?.id===`blade-ruined-king`?RIFT_ACTIVE_ITEM(fighter):null}catch{return null}}
const RIFT_V35_BASE_ITEM_OUT=RIFT_ITEM_OUTGOING;
RIFT_ITEM_OUTGOING=function RIFT_V35_ITEM_OUT(run,attacker,target,amount,tags=[]){let value=RIFT_V35_BASE_ITEM_OUT(run,attacker,target,amount,tags);const item=RIFT_V35_BORK(attacker),type=attacker?.statuses?.riftItemActionType;if(item&&!tags.includes(`itemProc`)&&[`strike`,`weapon`].includes(type)&&target?.hp>0)value+=Math.max(1,target.hp*.09);return value};
const RIFT_V35_BASE_ITEM_AFTER=RIFT_ITEM_AFTER_DAMAGE;
RIFT_ITEM_AFTER_DAMAGE=function RIFT_V35_ITEM_AFTER(run,attacker,target,damage,tags=[]){RIFT_V35_BASE_ITEM_AFTER(run,attacker,target,damage,tags);const item=RIFT_V35_BORK(attacker),type=attacker?.statuses?.riftItemActionType;if(!item||!target||damage<=0||tags.includes(`itemProc`)||![`strike`,`weapon`].includes(type))return;oo(attacker,Math.max(1,Math.round(damage*.1)));const key=`${target.name}|${target.power?.name||``}`;if(attacker.statuses.v35BorkTarget!==key){attacker.statuses.v35BorkTarget=key;attacker.statuses.v35BorkHits=0}if(!(attacker.statuses.v35BorkClawCooldown>0))attacker.statuses.v35BorkHits=(attacker.statuses.v35BorkHits||0)+1;if(attacker.statuses.v35BorkHits>=3&&!(attacker.statuses.v35BorkClawCooldown>0)){attacker.statuses.v35BorkHits=0;attacker.statuses.v35BorkClawCooldown=3;target.statuses.v35BorkSlow=2;try{G(run,`CLAWING SHADOWS // Blade of the Ruined King bites a third time. ${target.name}'s Movement efficiency collapses for 2 turns.`,attacker===run.player?`player`:`enemy`)}catch{}}};

/* ---------- DURABILITY HP + DAMAGE SANITY ---------- */
const RIFT_V35_BASE_REFRESH_POOLS=RIFT_REFRESH_ITEM_POOLS;
RIFT_REFRESH_ITEM_POOLS=function RIFT_V35_REFRESH_POOLS(fighter){if(!fighter)return fighter;const previous=Math.max(0,Number(fighter.v35DurabilityHp||0));if(previous&&Number.isFinite(fighter.maxHp)){fighter.maxHp=Math.max(1,fighter.maxHp-previous);fighter.hp=Math.min(fighter.hp,fighter.maxHp)}RIFT_V35_BASE_REFRESH_POOLS(fighter);if(!Number.isFinite(fighter.maxHp))return fighter;const itemHp=Math.max(0,Number(fighter.itemDerived?.hp||0)),baseHp=Math.max(1,fighter.maxHp-itemHp),durability=Math.max(0,Number(fighter.tiers?.durability||0)+Number(RIFT_ITEM_STAT_BONUS(fighter,`durability`)||0)),targetTotal=Math.round(baseHp*Math.min(1.35,durability*.06)),extra=Math.max(0,targetTotal-itemHp);fighter.v35DurabilityHp=extra;fighter.maxHp+=extra;fighter.hp=Math.min(fighter.maxHp,fighter.hp+Math.max(0,extra-previous));return fighter};
function RIFT_V35_CAUSAL(tags=[]){return tags.some(tag=>[`causality`,`causal`,`deathPierce`,`conceptErase`,`realityErase`,`higherDimensional`,`absolute`].includes(tag))}
function RIFT_V35_BALANCE_DAMAGE(run,attacker,target,amount,tags=[]){amount=Math.max(0,Number(amount||0));if(!target?.maxHp||amount<=0||tags.includes(`environment`)||RIFT_V35_CAUSAL(tags))return amount;const type=attacker?.statuses?.riftItemActionType||`special`,ultimate=tags.includes(`ultimate`)||type===`ultimate`,basic=[`strike`,`weapon`].includes(type);const soft=target.maxHp*(ultimate?.78:basic?.38:.52),hard=target.maxHp*(ultimate?1.15:basic?.62:.8);if(amount<=soft)return amount;return Math.min(hard,soft+(amount-soft)*.16)}

/* ---------- BOSS LOADOUT CURVE ---------- */
function RIFT_V35_AI_SLOTS(fighter,floor=1,boss=false){const name=`${fighter?.name||``} ${fighter?.power?.name||``}`.toLowerCase();if(name.includes(`all for one`))return 6;if(name.includes(`wamuu`))return 3;if(boss){if(floor<10)return 1;if(floor<20)return 3;if(floor<35)return 4;if(floor<50)return 5;return 6}if(floor<5)return 0;if(floor<10)return 1;if(floor<15)return 2;if(floor<25)return 3;if(floor<40)return 4;return 5}
const RIFT_V35_BASE_AI_BUILD=RIFT_V18_ASSIGN_AI_BUILD;
RIFT_V18_ASSIGN_AI_BUILD=function RIFT_V35_ASSIGN_AI_BUILD(fighter,floor=1,boss=false){fighter=RIFT_V35_BASE_AI_BUILD(fighter,floor,boss);if(!fighter?.inventory)return fighter;const slots=RIFT_V35_AI_SLOTS(fighter,floor,boss),existing=fighter.inventory.filter(Boolean),weapon=fighter.inventory[0]||existing.find(entry=>RIFT_ITEM(entry.itemId)?.category===`Weapon`)||null,others=existing.filter(entry=>entry!==weapon).slice(0,Math.max(0,slots-(weapon?1:0)));fighter.inventory=Array(6).fill(null);if(slots>0&&weapon)fighter.inventory[0]=weapon;for(let i=0;i<others.length&&i<5;i++)fighter.inventory[i+1]=others[i];RIFT_SYNC_WEAPON(fighter);RIFT_REFRESH_ITEM_POOLS(fighter);fighter.statuses.v35AiItemBudget=slots;return fighter};

/* ---------- STATE HELPERS ---------- */
function RIFT_V35_IS(fighter,name){return fighter?.power?.name===name||fighter?.statuses?.v35OriginalPower===name}
function RIFT_V35_ACTOR(run,fighter){return RIFT_ACTOR_ID_FOR_FIGHTER(run,fighter)}
function RIFT_V35_POINT(run,fighter){const id=RIFT_V35_ACTOR(run,fighter);try{return id?{...W(run,id)}:{x:run.battlefield.width/2,y:run.battlefield.height/2}}catch{return{x:50,y:32}}}
function RIFT_V35_LOG(run,text,fighter,tone){try{G(run,text,tone||(fighter===run.player?`player`:`enemy`))}catch{}}
function RIFT_V35_HOSTILES(run,fighter){const own=Do(run,fighter)?.team||(fighter===run.player?run.playerTeam:run.enemyTeam);return H(run).filter(entry=>entry.fighter!==fighter&&entry.fighter?.hp>0&&entry.team!==own)}
function RIFT_V35_EFFECT(run,kind,actor,target,extra={}){if(!run?.battlefield)return null;const event={id:`v35-${F()}`,kind,actorId:RIFT_V35_ACTOR(run,actor),origin:RIFT_V35_POINT(run,actor),target:target?.x!=null?{...target}:target?RIFT_V35_POINT(run,target):RIFT_V35_POINT(run,actor),turn:run.turn,accent:actor?.power?.accent||`#63efad`,...extra};run.battlefield.v35Fx=Array.isArray(run.battlefield.v35Fx)?run.battlefield.v35Fx:[];run.battlefield.v35Fx.push(event);run.battlefield.v35Fx=run.battlefield.v35Fx.slice(-36);return event}
function RIFT_V35_TARGET_KEY(target){return`${target?.name||`Unknown`}|${target?.power?.name||``}`}

/* ---------- VIEGO ---------- */
function RIFT_V35_WRAITH_FEATURE(run,target,position){return{id:`v35-wraith-${F()}`,kind:`v35Wraith`,label:`Wraith · ${target.name}`,position:{...position},radius:3.6,solid:false,cover:0,destructible:false,integrity:1,maxIntegrity:1,accent:`#55f1ad`,v35Wraith:true,expiresAtTurn:Number(run.turn||0)+3,targetSnapshot:RIFT_V35_COPY(target)}}
