function RIFT_V35_COMMIT(run,side,action,ctx,name=`Command`){const fake={...action,name,type:`special`,cost:0,move:{name,description:`V35 command commit`,cost:0,power:0,destruction:0,tags:[`selfCast`,`v35Commit`]}};return RIFT_V35_BASE_RS(run,side,fake,ctx)}
const RIFT_V35_BASE_RS=rs;
rs=function RIFT_V35_RESOLVE(run,side,action,ctx={}){const fighter=ctx.attacker||(side===`player`?run.player:run.enemy),target=ctx.target||(side===`player`?run.enemy:run.player),tags=action?.move?.tags||[];RIFT_V35_PROCESS_WORLD(run);
 if(RIFT_V35_IS(fighter,RIFT_V35_RUINED)&&[`strike`,`weapon`,`special`].includes(action.type)){const wraith=RIFT_V35_WRAITH_AT(run,action);if(wraith){RIFT_V35_COMMIT(run,side,action,ctx,`Takeover Wraith`);run.battlefield.features=run.battlefield.features.filter(feature=>feature.id!==wraith.id);RIFT_V35_BEGIN_TAKEOVER(run,fighter,wraith.targetSnapshot,wraith.position,`battlefield wraith`);return}}
 if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)&&tags.includes(`v35Hijack`)){RIFT_V35_COMMIT(run,side,action,ctx,`Hijack`);RIFT_V35_HIJACK(run,fighter,target);RIFT_V35_PETRICITE(fighter,1);return}
 if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)&&tags.includes(`v35HijackedTechnique`)){const stored=fighter.statuses.v35Hijacked;if(!stored)return;const before=target?.hp;const borrowed={...action,type:`special`,cost:0,move:{...action.move,cost:0,tags:[...(action.move?.tags||[]),`v35HijackedTechnique`,`ultimate`]}};let result;if(RIFT_V35_HIJACK_ADAPTER(run,fighter,target,borrowed,ctx))result={v35HijackAdapted:true};else{result=RIFT_V35_BASE_RS(run,side,borrowed,ctx);if(target&&Number.isFinite(before)&&target.hp===before&&(borrowed.move?.power||0)>0)go(run,fighter,target,(30+Y(fighter,(borrowed.move.tags||[]).includes(`physical`)?`as`:`ap`)*5.1)*borrowed.move.power,(borrowed.move.tags||[]).includes(`magic`),[...(borrowed.move.tags||[]),`ultimate`,`v35HijackFallback`])}RIFT_V35_EFFECT(run,`hijacked-cast`,fighter,target,{radius:9,name:stored.name});delete fighter.statuses.v35Hijacked;RIFT_V35_PETRICITE(fighter,1);return result}
 if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)&&tags.includes(`v35Abduct`)){const point=target?RIFT_V35_POINT(run,target):action?.aim?.target;if(!target){RIFT_V35_LOG(run,`ABDUCT DENIED // Petricite chains require a living enemy, not terrain.`,fighter);return}const result=RIFT_V35_BASE_RS(run,side,{...action,move:{...action.move,power:0}},ctx);const damage=go(run,fighter,target,18+Y(fighter,`ap`)*2.9,true,[`magic`,`tether`,`v35AbductHit`]);if(damage>0){target.statuses.stun=Math.max(1,target.statuses.stun||0);RIFT_V35_DASH_TO(run,fighter,point,22)}fighter.statuses.v35AbductWindow=0;fighter.statuses.v35AbscondCooldown=3;RIFT_V35_EFFECT(run,`abduct`,fighter,point,{radius:4});RIFT_V35_PETRICITE(fighter,1);return result}
 if(RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)&&tags.includes(`v35RageMove`)){const cost=RIFT_V35_RAGE_COST(action);if(!RIFT_V35_SPEND_RAGE(run,fighter,cost)){RIFT_V35_LOG(run,`RAGE DENIED // ${action.name} needs ${cost} Rage.`,fighter);return}const result=RIFT_V35_BASE_RS(run,side,{...action,cost:0,move:{...action.move,cost:0}},ctx);return result}
 if(RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)&&tags.includes(`v35Wrath`)){const result=RIFT_V35_BASE_RS(run,side,{...action,move:{...action.move,cost:0}},ctx);fighter.ultimate=0;fighter.statuses.v35Wrath=RIFT_V35_WRATH_TURNS;RIFT_V35_EFFECT(run,`wrath`,fighter,RIFT_V35_POINT(run,fighter),{radius:12});RIFT_V35_LOG(run,`WRATH OF THE UNDYING // Death is refused for 5 turns. Causality remains a kill route unless Berserker Mode is burning.`,fighter,`mythic`);return result}
 const targetHp=target?.hp,fighterHp=fighter?.hp,skill=fighter?.statuses?.skillBuff||0;if(RIFT_V35_IS(fighter,RIFT_V35_RUINED)&&RIFT_V35_IN_HARROW(run,fighter)&&[`strike`,`weapon`].includes(action.type))fighter.statuses.skillBuff=skill+3;if(RIFT_V35_IS(fighter,RIFT_V35_RUINED)&&!tags.includes(`v35ViegoE`)&&action.type!==`guard`&&action.type!==`rest`)fighter.statuses.v35HarrowInvisible=0;
 const result=RIFT_V35_BASE_RS(run,side,action,ctx);fighter.statuses.skillBuff=skill;
 if(RIFT_V35_IS(fighter,RIFT_V35_RUINED)){if(tags.includes(`v35ViegoQ`)){const dealt=Math.max(0,(targetHp||0)-(target?.hp||0));if(dealt>0&&target?.hp>0){const bonus=go(run,fighter,target,Math.max(1,target.hp*.1),false,[`physical`,`v35ViegoCurrentHp`,`noItemProc`]);const cd=Ba(fighter,action);if(cd)delete fighter.statuses[cd];RIFT_V35_LOG(run,`BLADE OF THE RUINED KING // The zweihander impales for ${bonus} bonus current-HP damage. The hit refreshes the thrust.`,fighter)}RIFT_V35_EFFECT(run,`viego-q`,fighter,action?.aim?.target||target,{radius:4})}
  if(tags.includes(`v35ViegoW`)){const route=RIFT_V35_DASH_TO(run,fighter,action?.aim?.target||RIFT_V35_POINT(run,target),6);if(route)RIFT_V35_EFFECT(run,`spectral-dash`,fighter,route.end,{origin:route.origin,radius:3});RIFT_V35_EFFECT(run,`spectral-maw`,fighter,action?.aim?.target||target,{radius:4})}
  if(tags.includes(`v35ViegoE`)){const point=action?.aim?.target||RIFT_V35_POINT(run,fighter);run.battlefield.features.push(RIFT_V35_HARROW_FEATURE(run,fighter,point));fighter.statuses.v35HarrowInvisible=1;const cd=Ba(fighter,action);if(cd)fighter.statuses[cd]=Math.max(fighter.statuses[cd]||0,5);RIFT_V35_EFFECT(run,`harrow`,fighter,point,{radius:14})}
  if(tags.includes(`v35Heartbreaker`)){const center=action?.aim?.target||RIFT_V35_POINT(run,target);RIFT_V35_DASH_TO(run,fighter,center,999);for(const entry of RIFT_V35_HOSTILES(run,fighter))if(I(W(run,entry.id),center)<=7.5){const missing=1-entry.fighter.hp/Math.max(1,entry.fighter.maxHp);go(run,fighter,entry.fighter,(20+Y(fighter,`as`)*3.8)*(1+missing*1.35),false,[`physical`,`area`,`ultimate`,`v35HeartbreakerExecute`])}RIFT_V35_EFFECT(run,`heartbreaker`,fighter,center,{radius:7.5});if(tags.includes(`v35TakeoverExit`))RIFT_V35_RESTORE_TAKEOVER(run,fighter,`Heartbreaker detonates the stolen body`)}}
