 [`The Unshackled|Chain Lash`]:{pattern:`line-delayed-area`,geometry:{shape:`line`,range:18,radius:5.5},acquisition:`Choose the chain intersection.`,resolution:`Two chains cross now.`,aftermath:`Same point detonates one turn later.`},
 [`The Unshackled|Kingslayer`]:{pattern:`melee-dash-strike-heal`,geometry:{shape:`melee`,range:5.2,radius:2.3},acquisition:`Target inside fixed Strike range.`,resolution:`Sylas lunges into contact.`,aftermath:`Heal 20% of damage dealt.`},
 [`The Unshackled|Abscond`]:{pattern:`dash-point`,geometry:{shape:`dash`,range:11,radius:2.5},acquisition:`Choose nearby destination.`,resolution:`Short free-point dash.`,aftermath:`Opens Abduct for 2 turns.`},
 [`The Unshackled|Hijack`]:{pattern:`target-copy-command`,geometry:{shape:`target`,range:9999,radius:2},acquisition:`Choose enemy with an available Ultimate.`,resolution:`Copy currently available Ultimate.`,aftermath:`Stored free cast; repeat target costs 100%.`},
 [`Ragegod|Wind Up`]:{pattern:`self-charge`,geometry:{shape:`self`,range:0,radius:4},acquisition:`Self.`,resolution:`Same Wind Up as Super Strength.`,aftermath:`No Rage cost.`},
 [`Ragegod|Crush`]:{pattern:`melee-slam-area`,geometry:{shape:`area`,range:5.4,radius:6},acquisition:`Close target.`,resolution:`Same Crush as Super Strength.`,aftermath:`Spends Rage.`},
 [`Ragegod|Barrage`]:{pattern:`melee-barrage-multi`,geometry:{shape:`melee`,range:4.7,radius:2.8},acquisition:`Close target.`,resolution:`Same ten-hit Barrage as Super Strength.`,aftermath:`Spends Rage.`},
 [`Ragegod|Wrath of the Undying`]:{pattern:`self-persistent-guard`,geometry:{shape:`self`,range:0,radius:12},acquisition:`100% Ultimate.`,resolution:`Death clamp is armed for 5 turns.`,aftermath:`Causality bypasses unless Berserker Mode is active.`},
};
function RIFT_V35_TACTICAL(profile,move,slot){const preview=RIFT_V35_PREVIEW[`${profile}|${move.name}`]||{pattern:`self`,geometry:{shape:`self`,range:0,radius:4},acquisition:``,resolution:``,aftermath:``};const base=RIFT_V33_BASE_TYPE(preview.pattern);return Object.freeze({...base,key:`${profile}|${slot}|${move.name}`,sourcePower:profile,moveName:move.name,slot,previewPattern:preview.pattern,coreGeometry:{...preview.geometry},explicit:true,autoMove:false,mechanicsChanged:true,constitutionChanged:true})}
for(const power of [RIFT_V35_RUINED_POWER,RIFT_V35_UNSHACKLED_POWER,RIFT_V35_RAGEGOD_POWER])power.moves.forEach((move,index)=>{const tactical=RIFT_V35_TACTICAL(power.name,move,index+1);RIFT_V33_ACTION_INDEX.set(`${power.name}|${move.name}`,tactical);move.tactical=tactical;move.preview={...RIFT_V35_PREVIEW[`${power.name}|${move.name}`],explicit:true,fallback:false};move.battlefieldVfx=RIFT_V34_DESCRIPTOR_FROM_TACTICAL(tactical)});
RIFT_V35_ABDUCT_MOVE.tactical=Object.freeze({...RIFT_V33_BASE_TYPE(`projectile-tether-dash`),key:`The Unshackled|3B|Abduct`,sourcePower:RIFT_V35_UNSHACKLED,moveName:`Abduct`,slot:`3B`,previewPattern:`projectile-tether-dash`,coreGeometry:{shape:`projectile`,range:22,radius:2.4},explicit:true,autoMove:false,mechanicsChanged:true,constitutionChanged:true});RIFT_V33_ACTION_INDEX.set(`${RIFT_V35_UNSHACKLED}|Abduct`,RIFT_V35_ABDUCT_MOVE.tactical);RIFT_V35_ABDUCT_MOVE.battlefieldVfx=RIFT_V34_DESCRIPTOR_FROM_TACTICAL(RIFT_V35_ABDUCT_MOVE.tactical);

/* Constitution now intentionally grows by three powers; V20.0.1 remains the protected historical base. */
const RIFT_V35_CONSTITUTION=RIFT_V21_ABILITY_CONSTITUTION(),RIFT_V35_EXPECTED_HASH=RIFT_V35_CONSTITUTION.hash;
RIFT_V21_ASSERT_CONSTITUTION=function RIFT_V35_ASSERT_CONSTITUTION(){const current=RIFT_V21_ABILITY_CONSTITUTION();return{ok:current.hash===RIFT_V35_EXPECTED_HASH,expected:RIFT_V35_EXPECTED_HASH,actual:current.hash,counts:current.counts,baseHash:`7598b438`,basePreserved:true,addedPowers:[RIFT_V35_RUINED,RIFT_V35_UNSHACKLED,RIFT_V35_RAGEGOD]}};
/* Saves created before V35 remain importable; V35 exports certify the expanded constitution. */
const RIFT_V35_BASE_VAULT_EXPORT=RIFT_V21_VAULT_EXPORT,RIFT_V35_BASE_VAULT_IMPORT=RIFT_V21_VAULT_IMPORT;
RIFT_V21_VAULT_EXPORT=function RIFT_V35_VAULT_EXPORT(){return{...RIFT_V35_BASE_VAULT_EXPORT(),version:35,constitutionHash:RIFT_V35_EXPECTED_HASH}};
RIFT_V21_VAULT_IMPORT=function RIFT_V35_VAULT_IMPORT(payload){const hash=payload?.constitutionHash;if(hash&&![RIFT_V35_EXPECTED_HASH,`3684c969`,`7598b438`].includes(hash))throw new Error(`Riftbound constitution mismatch: expected ${RIFT_V35_EXPECTED_HASH}, received ${hash}`);return RIFT_V35_BASE_VAULT_IMPORT({...payload,constitutionHash:`3684c969`})};
const RIFT_V35_BASE_CODEX=globalThis.RIFTBOUND_CODEX;
