function RIFT_V35_HIJACK(run,fighter,target){if(!target)return false;const cost=RIFT_V35_HIJACK_COST(fighter,target);if(fighter.ultimate<cost){RIFT_V35_LOG(run,`HIJACK DENIED // ${cost}% Ultimate is required to steal from ${target.name}.`,fighter);return false}const borrowed=RIFT_V35_AVAILABLE_ULT(run,target,fighter);if(!borrowed){RIFT_V35_LOG(run,`HIJACK DENIED // ${target.name} has no currently available Ultimate to steal.`,fighter);return false}fighter.ultimate=Math.max(0,fighter.ultimate-cost);fighter.statuses.v35HijackedTargets={...(fighter.statuses.v35HijackedTargets||{}),[RIFT_V35_TARGET_KEY(target)]:1};fighter.statuses.v35Hijacked={name:borrowed.name,sourcePower:borrowed.sourcePower||target.power?.name||target.stand?.name||`Unknown`,sourceName:target.name,action:RIFT_V35_COPY(borrowed)};RIFT_V35_EFFECT(run,`hijack`,fighter,RIFT_V35_POINT(run,target),{radius:9,name:borrowed.name});RIFT_V35_LOG(run,`HIJACK // ${fighter.name} rips ${borrowed.name} from ${target.name}. The copied Ultimate is stored for one free cast and will resolve from Sylas's own stats.`,fighter,`mythic`);return true}
function RIFT_V35_CHAIN_MARK(run,fighter,point){run.battlefield.features.push({id:`v35-chain-lash-${F()}`,kind:`v35ChainLash`,label:`Chain Lash · Petricite rupture`,position:{...point},radius:5.5,solid:false,cover:0,destructible:false,integrity:1,maxIntegrity:1,accent:`#8fe7dd`,ownerId:RIFT_V35_ACTOR(run,fighter),detonatesAtTurn:Number(run.turn||0)+1,v35ChainLash:true,ap:Y(fighter,`ap`)})}
function RIFT_V35_HIJACK_ADAPTER(run,fighter,target,action,ctx={}){const tags=action?.move?.tags||[],actorId=RIFT_V35_ACTOR(run,fighter),center=action?.aim?.target||(target?RIFT_V35_POINT(run,target):RIFT_V35_POINT(run,fighter));
 if(tags.includes(`spardaJudgementCut`)){const radius=13;for(let index=0;index<18;index+=1){const angle=Math.PI*2*index/18,r=2+(index%6)*1.7;RIFT_V35_EFFECT(run,`hijacked-cut`,fighter,{x:M(center.x+Math.cos(angle)*r,1,run.battlefield.width-1),y:M(center.y+Math.sin(angle)*r,1,run.battlefield.height-1)},{radius:2.2,accent:index%3===0?`#ff3154`:`#e9d7ff`})}for(const entry of H(run).filter(entry=>entry.id!==actorId&&entry.fighter.hp>0&&I(W(run,entry.id),center)<=radius+O))for(let cut=0;cut<9&&entry.fighter.hp>0&&!run.timelineRestoredByKcr;cut+=1)go(run,fighter,entry.fighter,18+Y(fighter,`as`)*1.45+Y(fighter,`ap`)*1.35,true,[`physical`,`magic`,`hybrid`,`area`,`ultimate`,`spardaJudgementCut`,`noCounter`,`v35HijackedAdapted`]);run.battlefield.features.filter(feature=>feature.integrity>0&&I(feature.position,center)<=radius+feature.radius).forEach(feature=>Io(run,feature,fighter,Math.max(45,Math.round(Y(fighter,`as`)*7+Y(fighter,`ap`)*6)),`Hijacked Judgement Cut`));RIFT_V35_EFFECT(run,`hijacked-judgement`,fighter,center,{radius});RIFT_V35_LOG(run,`HIJACK ADAPTATION // Judgement Cut resolves without Combo or Yamato prerequisites. Sylas supplies the stats; the stolen technique supplies the law.`,fighter,`mythic`);return true}
 if(tags.includes(`spardaDevilTrigger`)){fighter.statuses.v35HijackedDevilTrigger={turns:6,baseFlight:!!fighter.flight};fighter.flight=true;RIFT_V35_EFFECT(run,`hijacked-trigger`,fighter,RIFT_V35_POINT(run,fighter),{radius:11,accent:`#9f63ff`});RIFT_V35_LOG(run,`HIJACK ADAPTATION // Devil Trigger becomes a six-turn stolen transformation. It uses Sylas's body and stats instead of requiring Vergil's Combo engine.`,fighter,`mythic`);return true}
 return false}
function RIFT_V35_PROCESS_WORLD(run){if(!run?.battlefield)return;for(const feature of [...run.battlefield.features]){if(feature.v35ChainLash&&feature.detonatesAtTurn<=run.turn){const owner=U(run,feature.ownerId)?.fighter;if(owner){for(const entry of RIFT_V35_HOSTILES(run,owner))if(I(W(run,entry.id),feature.position)<=feature.radius)go(run,owner,entry.fighter,28+Number(feature.ap||0)*4.8,true,[`magic`,`area`,`v35ChainExplosion`]);RIFT_V35_EFFECT(run,`chain-explosion`,owner,feature.position,{radius:feature.radius})}run.battlefield.features=run.battlefield.features.filter(row=>row.id!==feature.id)}}run.battlefield.features=run.battlefield.features.filter(feature=>!feature.v35Wraith||feature.expiresAtTurn>=run.turn).filter(feature=>!feature.v35Harrow||feature.expiresAtTurn>=run.turn)}

/* ---------- RAGEGOD ---------- */
function RIFT_V35_RAGE(fighter){return Math.max(0,Number(fighter?.statuses?.v35Rage||0))}
function RIFT_V35_RAGE_COST(action){const tag=(action?.move?.tags||[]).find(entry=>entry.startsWith(`v35RageCost:`));return tag?Math.max(0,Number(tag.split(`:`)[1])||0):Math.max(0,Number(action?.move?.rageCost||0))}
function RIFT_V35_ENTER_BERSERK(run,fighter){if(!fighter?.statuses?.v35Berserk&&RIFT_V35_RAGE(fighter)>=100){fighter.statuses.v35Rage=100;fighter.statuses.v35Berserk=1;fighter.statuses.v35BerserkFlash=2;RIFT_V35_EFFECT(run,`berserker-awaken`,fighter,RIFT_V35_POINT(run,fighter),{radius:12});RIFT_V35_LOG(run,`BERSERKER MODE // Rage reaches 100%. Physical stats erupt; the amplification scales from ${Math.round(Y(fighter,`ap`))} AP.`,fighter,`mythic`)}}
function RIFT_V35_GAIN_RAGE(run,fighter,damage){if(!RIFT_V35_IS(fighter,RIFT_V35_RAGEGOD)||damage<=0)return;const gain=M(damage/Math.max(1,fighter.maxHp)*55,2,22);fighter.statuses.v35Rage=M(RIFT_V35_RAGE(fighter)+gain,0,100);RIFT_V35_ENTER_BERSERK(run,fighter)}
function RIFT_V35_BERSERK_BONUS(fighter){const ap=Math.max(0,Number(RIFT_V35_BASE_Y(fighter,`ap`)||0));return M(2+Math.floor(ap/2.75),2,9)}
function RIFT_V35_SPEND_RAGE(run,fighter,amount){if(amount<=0)return true;if(RIFT_V35_RAGE(fighter)<amount)return false;fighter.statuses.v35Rage=Math.max(0,RIFT_V35_RAGE(fighter)-amount);if(fighter.statuses.v35Berserk&&fighter.statuses.v35Rage<=0){delete fighter.statuses.v35Berserk;RIFT_V35_LOG(run,`BERSERKER MODE ENDS // The Rage bar hits zero.`,fighter)}return true}
function RIFT_V35_WRATH_ACTIVE(fighter){return Number(fighter?.statuses?.v35Wrath||0)>0}
function RIFT_V35_AFTER_RAW_DAMAGE(run,attacker,target,damage,tags=[]){if(!target||damage<=0)return;RIFT_V35_GAIN_RAGE(run,target,damage);if(!RIFT_V35_IS(target,RIFT_V35_RAGEGOD)||!RIFT_V35_WRATH_ACTIVE(target)||target.hp>0)return;const causal=RIFT_V35_CAUSAL(tags),protectedFromCausal=!!target.statuses.v35Berserk;if(!causal||protectedFromCausal){target.hp=Math.max(1,Math.ceil(target.maxHp*.01));target.statuses.v35WrathClamped=1;RIFT_V35_LOG(run,causal?`WRATH OF THE UNDYING // Berserker Mode denies even Causality. ${target.name} remains at 1% HP.`:`WRATH OF THE UNDYING // Lethal force lands, but ${target.name} cannot fall below 1% HP.`,target,`mythic`)}}

/* Y has to be wrapped after the helper above so Berserker AP can cash into physical tiers. */
const RIFT_V35_BASE_Y=Y;
