const RIFT_V22_MARKER=`Riftbound Open Core V22`;
const RIFT_V22_VERSION=22;
const RIFT_V22_EVENT_TYPES=Object.freeze([`ACTION_STARTED`,`ACTOR_MOVED`,`ATTACK_CONTACTED`,`GUARD_BROKEN`,`DAMAGE_APPLIED`,`HEALING_APPLIED`,`RESOURCE_CHANGED`,`STATUS_APPLIED`,`STATUS_REMOVED`,`ENVIRONMENT_DESTROYED`,`ACTION_FINISHED`,`STATE_COMMITTED`]);
function RIFT_V22_RING(limit=320){const rows=[];return{push:value=>{rows.push(value);if(rows.length>limit)rows.splice(0,rows.length-limit);return value},read:()=>P(rows),clear:()=>{rows.length=0},get size(){return rows.length}}}
const RIFT_V22_EVENT_LOG=RIFT_V22_RING(480),RIFT_V22_LISTENERS=new Map();
const RIFT_V22_EVENT_BUS=Object.freeze({
 emit(type,payload={}){if(!RIFT_V22_EVENT_TYPES.includes(type))throw Error(`Unknown Open Core event ${type}`);const event=Object.freeze({id:`v22-${Date.now()}-${RIFT_V22_EVENT_LOG.size}`,type,at:Date.now(),payload:P(payload)});RIFT_V22_EVENT_LOG.push(event);for(const listener of RIFT_V22_LISTENERS.get(type)||[])try{listener(event)}catch(error){RIFT_V17_DIAGNOSTIC(`v22-event-listener`,error,{type})}for(const listener of RIFT_V22_LISTENERS.get(`*`)||[])try{listener(event)}catch{}return event},
 on(type,listener){if(!RIFT_V22_LISTENERS.has(type))RIFT_V22_LISTENERS.set(type,new Set());RIFT_V22_LISTENERS.get(type).add(listener);return()=>RIFT_V22_LISTENERS.get(type)?.delete(listener)},
 history:()=>RIFT_V22_EVENT_LOG.read(),clear:()=>RIFT_V22_EVENT_LOG.clear(),types:RIFT_V22_EVENT_TYPES
});
function RIFT_V22_FIGHTER_VIEW(fighter){if(!fighter)return null;return{name:fighter.name,hp:Number(fighter.hp||0),maxHp:Number(fighter.maxHp||0),energy:Number(fighter.energy||0),maxEnergy:Number(fighter.maxEnergy||0),ultimate:Number(fighter.ultimate||0),posture:Number(fighter.posture||0),guard:!!fighter.guard,shield:Number(fighter.shield||0),power:fighter.power?.name||null,statuses:P(fighter.statuses||{}),cooldowns:P(fighter.cooldowns||fighter.itemCooldowns||{}),inventory:P(fighter.inventory||[])}}
function RIFT_V22_STATE_VIEW(run){if(!run)return null;return{schemaVersion:Number(run.riftboundSchemaVersion||0),floor:Number(run.floor||0),turn:Number(run.turn||0),round:Number(run.round||0),phase:run.phase||null,activeTargetId:run.activeTargetId||null,shards:Number(run.shards||0),player:RIFT_V22_FIGHTER_VIEW(run.player),enemy:RIFT_V22_FIGHTER_VIEW(run.enemy),auxiliary:(run.auxiliaryCombatants||[]).map(entry=>({id:entry.id,team:entry.team,role:entry.role,fighter:RIFT_V22_FIGHTER_VIEW(entry.fighter)})),battlefield:run.battlefield?{width:run.battlefield.width,height:run.battlefield.height,units:P(run.battlefield.units||[]),features:(run.battlefield.features||[]).map(feature=>({id:feature.id,kind:feature.kind,integrity:feature.integrity,position:feature.position})),hazards:P(run.battlefield.hazards||[]),domains:P(run.battlefield.domains||[])}:null}}
function RIFT_V22_STATE_HASH(run){return RIFT_V21_HASH(RIFT_V22_STATE_VIEW(run))}
function RIFT_V22_DIFF(before,after){
 const rows=[];if(!before||!after)return rows;for(const side of [`player`,`enemy`]){const a=before[side],b=after[side];if(!a||!b)continue;if(b.hp<a.hp)rows.push({type:`DAMAGE_APPLIED`,actor:side,amount:a.hp-b.hp});if(b.hp>a.hp)rows.push({type:`HEALING_APPLIED`,actor:side,amount:b.hp-a.hp});for(const resource of [`energy`,`ultimate`,`posture`,`shield`])if(a[resource]!==b[resource])rows.push({type:`RESOURCE_CHANGED`,actor:side,resource,before:a[resource],after:b[resource]});const oldStatuses=new Set(Object.keys(a.statuses||{})),newStatuses=new Set(Object.keys(b.statuses||{}));for(const status of newStatuses)if(!oldStatuses.has(status))rows.push({type:`STATUS_APPLIED`,actor:side,status});for(const status of oldStatuses)if(!newStatuses.has(status))rows.push({type:`STATUS_REMOVED`,actor:side,status})}return rows;
}
function RIFT_V22_ACTOR_ID(run,fighter){if(!run||!fighter)return null;try{return H(run).find(entry=>entry.fighter===fighter)?.id||null}catch{return fighter===run.player?`player`:fighter===run.enemy?`enemy`:null}}
const RIFT_V22_BASE_DAMAGE=go;
let RIFT_V22_DAMAGE_SEQUENCE=0;
go=function RIFT_V22_DAMAGE(run,attacker,target,raw,magic,tags){const before=Number(target?.hp||0),result=RIFT_V22_BASE_DAMAGE(run,attacker,target,raw,magic,tags),after=Number(target?.hp||0),amount=Math.max(0,before-after);RIFT_V22_EVENT_BUS.emit(`ATTACK_CONTACTED`,{floor:run?.floor,turn:run?.turn,attackerId:RIFT_V22_ACTOR_ID(run,attacker),targetId:RIFT_V22_ACTOR_ID(run,target),raw:Number(raw||0),tags:[...(tags||[])]});if(amount>0){RIFT_V22_DAMAGE_SEQUENCE+=1;RIFT_V22_EVENT_BUS.emit(`DAMAGE_APPLIED`,{floor:run?.floor,turn:run?.turn,attackerId:RIFT_V22_ACTOR_ID(run,attacker),targetId:RIFT_V22_ACTOR_ID(run,target),amount,tags:[...(tags||[])],source:`damage-resolver`})}return result};
const RIFT_V22_BASE_RESOLVE=rs;
rs=function RIFT_V22_RESOLVE(run,side,action,context={}){const actor=context.actorId||RIFT_V22_ACTOR_ID(run,context.attacker)||(side===`player`?`player`:`enemy`),target=context.targetId||RIFT_V22_ACTOR_ID(run,context.target)||(side===`player`?run?.activeTargetId||`enemy`:`player`),before=RIFT_V22_STATE_VIEW(run),beforeHash=RIFT_V21_HASH(before),damageSequence=RIFT_V22_DAMAGE_SEQUENCE,input={floor:run?.floor,turn:run?.turn,side,actorId:actor,targetId:target,actionId:action?.id||null,name:action?.name||action?.move?.name||`Action`,aim:P(action?.aim||null)};RIFT_V22_EVENT_BUS.emit(`ACTION_STARTED`,input);RIFT_V21_REPLAY_RECORD(`action`,input,before);let output;try{output=RIFT_V22_BASE_RESOLVE(run,side,action,context)}catch(error){RIFT_V17_DIAGNOSTIC(`open-core-resolver`,error,input);throw error}const after=RIFT_V22_STATE_VIEW(run),afterHash=RIFT_V21_HASH(after);for(const row of RIFT_V22_DIFF(before,after)){if(row.type===`DAMAGE_APPLIED`&&RIFT_V22_DAMAGE_SEQUENCE>damageSequence)continue;RIFT_V22_EVENT_BUS.emit(row.type,{...row,floor:run?.floor,turn:run?.turn,sourceActionId:action?.id||null,source:`state-diff`})}RIFT_V22_EVENT_BUS.emit(`ACTION_FINISHED`,{...input,beforeHash,afterHash,changed:beforeHash!==afterHash});RIFT_V22_EVENT_BUS.emit(`STATE_COMMITTED`,{floor:run?.floor,turn:run?.turn,hash:afterHash,source:`action`});return output};
const RIFT_V22_BASE_MOVE=Gt;
Gt=function RIFT_V22_MOVE(run,actorId,destination,silent=false){let origin=null;try{origin={...W(run,actorId)}}catch{}const output=RIFT_V22_BASE_MOVE(run,actorId,destination,silent);if(output?.moved){const target=(()=>{try{return{...W(run,actorId)}}catch{return P(destination)}})();const payload={floor:run?.floor,turn:run?.turn,actorId,origin,target,distance:Number(output.traveledDistance||0),movementRemaining:Number(Oi(run,actorId)||0)};RIFT_V22_EVENT_BUS.emit(`ACTOR_MOVED`,payload);RIFT_V21_REPLAY_RECORD(`move`,payload,RIFT_V22_STATE_VIEW(run))}return output};
function RIFT_V22_SEEDED(seed=`riftbound`){let state=parseInt(RIFT_V21_HASH(String(seed)),16)>>>0;return()=>{state+=0x6D2B79F5;let t=state;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function RIFT_V22_CONTENT_REGISTRY(){const powers=new Map(),items=new Map(),races=new Map(),traits=new Map();g.forEach(entry=>powers.set(entry.name,entry));RIFT_ITEM_CATALOG.forEach(entry=>items.set(entry.id,entry));d.forEach(entry=>races.set(entry.name,entry));p.forEach(entry=>traits.set(entry.name,entry));return Object.freeze({powers,items,races,traits,validate(){const issues=[];for(const [name,power] of powers)if(!Array.isArray(power.moves)||power.moves.length<4)issues.push(`${name}: invalid move catalog`);for(const [id,item] of items)for(const component of item.recipe||[])if(!items.has(component))issues.push(`${id}: missing recipe ${component}`);return{ok:!issues.length,issues,counts:{powers:powers.size,items:items.size,races:races.size,traits:traits.size}}}})}
const RIFT_V22_REGISTRY=RIFT_V22_CONTENT_REGISTRY();
function RIFT_V22_EFFECT_QUEUE(effects=[]){return RIFT_V17_ORDER_EFFECTS(effects).map((effect,index)=>Object.freeze({...effect,sequence:index}))}
function RIFT_V22_SHADOW_COMPARE(left,right){const leftHash=typeof left===`string`?left:RIFT_V21_HASH(left),rightHash=typeof right===`string`?right:RIFT_V21_HASH(right);return{ok:leftHash===rightHash,leftHash,rightHash}}
const RIFT_V22_ENGINE=Object.freeze({version:22,mode:`open-core`,registry:RIFT_V22_REGISTRY,events:RIFT_V22_EVENT_BUS,stateView:RIFT_V22_STATE_VIEW,stateHash:RIFT_V22_STATE_HASH,legality:RIFT_V17_ACTION_LEGALITY,effectQueue:RIFT_V22_EFFECT_QUEUE,seeded:RIFT_V22_SEEDED,shadowCompare:RIFT_V22_SHADOW_COMPARE,legacyAdapter:Object.freeze({resolve:(...args)=>rs(...args),move:(...args)=>Gt(...args),damage:(...args)=>go(...args)})});
const RIFT_V22_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V22_NORMALIZE_RUN_BUILD(run){run=RIFT_V22_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(22,Number(run.riftboundSchemaVersion||0));run.v22Core=run.v22Core&&typeof run.v22Core===`object`?run.v22Core:{engine:`open-core`,lastStateHash:null};run.v22Core.engine=`open-core`;return run};
globalThis.RIFTBOUND_CORE=RIFT_V22_ENGINE;
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:22,release:`V22 · Open Core`,engine:{mode:`open-core`,eventTypes:RIFT_V22_EVENT_TYPES,deterministicStateHashes:true,shadowComparison:true,registry:RIFT_V22_REGISTRY.validate().counts,legacyAdapter:true}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:22,core:()=>({registry:RIFT_V22_REGISTRY.validate(),events:RIFT_V22_EVENT_LOG.size,constitution:RIFT_V21_ASSERT_CONSTITUTION()})};
