const RIFT_V30_MARKER=`Riftbound Remastered V30`;
const RIFT_V30_VERSION=30,RIFT_V30_RELEASE=`Riftbound Remastered`;
const RIFT_V30_COMPATIBILITY=Object.freeze({legacyRuntime:`adapter`,defaultRuntime:`open-core`,saveFloor:1,saveCeiling:30,rollbackWindow:`previous-valid-backup`,abilityChanges:0,immutableBase:`v0.3.0`});
function RIFT_V30_CAPABILITIES(){return{serviceWorker:typeof navigator!==`undefined`&&`serviceWorker`in navigator,indexedDb:typeof indexedDB!==`undefined`,webAudio:typeof window!==`undefined`&&!!(window.AudioContext||window.webkitAudioContext),gamepad:typeof navigator!==`undefined`&&typeof navigator.getGamepads===`function`,touch:typeof navigator!==`undefined`&&navigator.maxTouchPoints>0,reducedMotion:typeof matchMedia!==`undefined`&&matchMedia(`(prefers-reduced-motion: reduce)`).matches,contrast:typeof matchMedia!==`undefined`&&matchMedia(`(prefers-contrast: more)`).matches}}
function RIFT_V30_CERTIFICATION(){
 const checks=[],add=(id,ok,detail)=>checks.push({id,ok:!!ok,detail});const constitution=RIFT_V21_ASSERT_CONSTITUTION(),registry=RIFTBOUND_CORE.registry.validate(),spatial=RIFT_V24_COVERAGE();add(`ability-constitution`,constitution.ok,`${constitution.counts.moves} locked moves · ${constitution.actual}`);add(`content-registry`,registry.ok,`${registry.counts.powers} powers · ${registry.counts.items} items`);add(`event-core`,RIFTBOUND_CORE.version===22,`${RIFT_V22_EVENT_TYPES.length} event contracts`);add(`spatial-coverage`,spatial.typed===spatial.total,`${spatial.typed}/${spatial.total} moves typed`);add(`save-vault`,typeof RIFTBOUND_PRESERVATION.saves.create===`function`,`named slots + 8 recovery points`);add(`interface`,RIFTBOUND_INTERFACE.version===23,`${RIFTBOUND_INTERFACE.spaces.length} interface spaces`);add(`armory`,RIFTBOUND_ARMORY.version===25,`${RIFTBOUND_ARMORY.modes.length} workspaces`);add(`ascension`,RIFTBOUND_ASCENSION.version===26,`${RIFT_V26_MILESTONES.length} milestones`);add(`arenas`,Object.keys(RIFT_V27_ARENA_PALETTES).length===20,`${Object.keys(RIFT_V27_ARENA_PALETTES).length} themed arenas`);add(`intelligence`,RIFTBOUND_COMBAT_INTELLIGENCE.version===28,`fair tactical reasoning`);add(`coop`,RIFTBOUND_COOP_V29.protocolVersion===3,`protocol 3 host authority`);const ok=checks.every(check=>check.ok);return{version:30,release:RIFT_V30_RELEASE,ok,checks,constitutionHash:constitution.actual,spatialTypes:Object.keys(RIFT_V24_SPATIAL_TYPES).length,capabilities:RIFT_V30_CAPABILITIES(),compatibility:RIFT_V30_COMPATIBILITY}}
function RIFT_V30_BOOT_REPORT(){const certification=RIFT_V30_CERTIFICATION(),errors=globalThis.RIFTBOUND_DIAGNOSTICS?.errors?.()||[];return{...certification,bootedAt:Date.now(),errors:errors.slice(-10),stateHash:globalThis.__RIFTBOUND_ACTIVE_RUN__?RIFT_V22_STATE_HASH(globalThis.__RIFTBOUND_ACTIVE_RUN__):null,manifestHash:RIFT_V21_HASH(globalThis.RIFTBOUND_MANIFEST)}}
function RIFT_V30_RELEASE_PANEL(){
 if(typeof document===`undefined`||document.getElementById(`rift-v30-release-root`))return;const root=document.createElement(`div`);root.id=`rift-v30-release-root`;root.innerHTML=`<button type="button" id="rift-v30-release-toggle">V30</button><section hidden><header><span><small>DEFINITIVE RELEASE</small><strong>RIFTBOUND REMASTERED</strong></span><button type="button" data-close>×</button></header><main data-report></main><footer>ABILITIES PRESERVED · SYSTEMS REMASTERED</footer></section>`;document.body.appendChild(root);const panel=root.querySelector(`section`),render=()=>{const report=RIFT_V30_BOOT_REPORT();root.querySelector(`[data-report]`).innerHTML=`<div class="v30-release-state ${report.ok?`ready`:`blocked`}"><b>${report.ok?`CERTIFIED`:`ATTENTION REQUIRED`}</b><span>ABILITY LOCK ${report.constitutionHash}</span></div>${report.checks.map(check=>`<article class="${check.ok?`ok`:`bad`}"><b>${check.ok?`✓`:`!`}</b><span><strong>${check.id.replace(/-/g,` `).toUpperCase()}</strong><small>${check.detail}</small></span></article>`).join(``)}<div class="v30-capabilities">${Object.entries(report.capabilities).map(([key,value])=>`<span class="${value?`on`:`off`}">${key.replace(/([A-Z])/g,` $1`).toUpperCase()}</span>`).join(``)}</div>`};root.querySelector(`#rift-v30-release-toggle`).onclick=()=>{panel.hidden=!panel.hidden;render()};root.querySelector(`[data-close]`).onclick=()=>panel.hidden=true;render();
}
function RIFT_V30_REGISTER_OFFLINE(){if(typeof navigator===`undefined`||!navigator.serviceWorker||location.protocol===`file:`||location.hostname===`localhost`&&location.port)return;navigator.serviceWorker.register(`./riftbound-sw.js`).catch(error=>RIFT_V17_DIAGNOSTIC(`service-worker`,error))}
const RIFT_V30_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V30_NORMALIZE_RUN_BUILD(run){run=RIFT_V30_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(30,Number(run.riftboundSchemaVersion||0));run.v30=run.v30&&typeof run.v30===`object`?run.v30:{};run.v30.release=`remastered`;run.v30.compatibility=`open-core-with-legacy-adapter`;run.v30.constitutionHash=RIFT_V21_ABILITY_CONSTITUTION().hash;globalThis.__RIFTBOUND_ACTIVE_RUN__=run;return run};
const RIFT_V30_CERT=RIFT_V30_CERTIFICATION();
globalThis.RIFTBOUND_REMASTERED={version:30,release:RIFT_V30_RELEASE,certify:RIFT_V30_CERTIFICATION,report:RIFT_V30_BOOT_REPORT,compatibility:RIFT_V30_COMPATIBILITY,capabilities:RIFT_V30_CAPABILITIES};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:30,release:`V30 · Riftbound Remastered`,remastered:{certified:RIFT_V30_CERT.ok,constitutionHash:RIFT_V30_CERT.constitutionHash,abilityChanges:0,openCoreDefault:true,legacyAdapter:true,offlineInstall:true,compatibility:RIFT_V30_COMPATIBILITY,certification:RIFT_V30_CERT.checks}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:30,release:RIFT_V30_BOOT_REPORT};
if(typeof window!==`undefined`){const boot=()=>{document.documentElement.classList.add(`riftbound-remastered`);RIFT_V30_RELEASE_PANEL();RIFT_V30_REGISTER_OFFLINE()};document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,boot,{once:true}):boot()}
