const RIFT_V351_MARKER=`Riftbound Sovereigns Hotfix V35.1`;
const RIFT_V351_HIJACK_RANGE=36,RIFT_V351_ABDUCT_RANGE=30;

/* ---------- Canon/state corrections without mutating the registered constitution ---------- */
const RIFT_V351_HIJACK_MOVE=RIFT_V35_UNSHACKLED_POWER.moves[3];
const RIFT_V351_HIJACK_TAGS=[...new Set((RIFT_V351_HIJACK_MOVE.tags||[]).filter(tag=>tag!==`selfCast`).concat([`target`]))];
const RIFT_V351_HIJACK_DESCRIPTION=`Target an enemy at great range. Spend 50% Ultimate to steal the Ultimate form their current state exposes, regardless of whether their own Ultimate meter is charged. After stealing from that enemy once, every later theft from the same enemy costs 100%. The stolen cast is free and uses Sylas's stats.`;
const RIFT_V351_ABDUCT_DESCRIPTION=`RECAST OF ABSCOND — fire a long Petricite chain at an enemy up to ${RIFT_V351_ABDUCT_RANGE}m away. On hit, stun them and grapple Sylas into contact. Cannot target terrain or objects.`;
try{
 RIFT_V35_PREVIEW[`${RIFT_V35_UNSHACKLED}|Hijack`]={pattern:`target-copy-command`,geometry:{shape:`target`,range:RIFT_V351_HIJACK_RANGE,radius:2.6},acquisition:`Choose a living enemy within ${RIFT_V351_HIJACK_RANGE}m. Their Ultimate charge does not matter.`,resolution:`Petricite chains tear out the Ultimate form exposed by the target's current state.`,aftermath:`Stored free cast; repeat theft from that same enemy costs 100%.`};
 RIFT_V35_PREVIEW[`${RIFT_V35_UNSHACKLED}|Abscond`]={...RIFT_V35_PREVIEW[`${RIFT_V35_UNSHACKLED}|Abscond`],aftermath:`M3 itself becomes Abduct for 2 owner turns.`};
}catch{}

function RIFT_V351_POOL_STATE(fighter){return{itemDerived:RIFT_V35_COPY(fighter?.itemDerived||null),v35DurabilityHp:Math.max(0,Number(fighter?.v35DurabilityHp||0)),maxPosture:Number.isFinite(fighter?.maxPosture)?fighter.maxPosture:null,posture:Number.isFinite(fighter?.posture)?fighter.posture:null,flight:!!fighter?.flight}}
function RIFT_V351_APPLY_POOL_STATE(fighter,state){if(state?.itemDerived)fighter.itemDerived=RIFT_V35_COPY(state.itemDerived);else delete fighter.itemDerived;fighter.v35DurabilityHp=Math.max(0,Number(state?.v35DurabilityHp||0));if(Number.isFinite(state?.maxPosture))fighter.maxPosture=state.maxPosture;if(Number.isFinite(state?.posture))fighter.posture=state.posture;if(state&&`flight` in state)fighter.flight=!!state.flight}

/* Viego shell swaps move the HP bookkeeping with the body. Percentage is applied AFTER normalization. */
RIFT_V35_RESTORE_TAKEOVER=function RIFT_V351_RESTORE_TAKEOVER(run,fighter,reason=`Takeover ends`){const state=fighter?.statuses?.v35Takeover;if(!state)return false;const ratio=M(fighter.hp/Math.max(1,fighter.maxHp),.01,1),preservedPosition=RIFT_V35_POINT(run,fighter),original=state.original;fighter.power=RIFT_V35_COPY(original.power);fighter.race=RIFT_V35_COPY(original.race);fighter.trait=RIFT_V35_COPY(original.trait);fighter.tiers=RIFT_V35_COPY(original.tiers);fighter.inventory=RIFT_V35_COPY(original.inventory);fighter.weapon=RIFT_V35_COPY(original.weapon);fighter.boons=RIFT_V35_COPY(original.boons);fighter.stand=RIFT_V35_COPY(original.stand);fighter.maxEnergy=original.maxEnergy;fighter.energy=Math.min(original.maxEnergy,original.energy);fighter.maxHp=original.maxHp;fighter.statuses=RIFT_V35_COPY(original.statuses||{});RIFT_V351_APPLY_POOL_STATE(fighter,original.pool);RIFT_NORMALIZE_FIGHTER_BUILD(fighter);fighter.hp=Math.max(1,Math.round(fighter.maxHp*ratio));fighter.ultimate=original.ultimate;fighter.statuses.v35TakeoverFlash=2;fighter.statuses.v35OriginalPower=RIFT_V35_RUINED;const id=RIFT_V35_ACTOR(run,fighter);if(id)ki(run,id,preservedPosition);RIFT_V35_EFFECT(run,`takeover-exit`,fighter,preservedPosition,{radius:8});RIFT_V35_LOG(run,`HEART OF THE RUINED KING // ${reason}. Viego tears free and his own build returns.`,fighter,`mythic`);return true};
RIFT_V35_BEGIN_TAKEOVER=function RIFT_V351_BEGIN_TAKEOVER(run,fighter,snapshot,position,source=`wraith`){if(!fighter||!snapshot||!RIFT_V35_IS(fighter,RIFT_V35_RUINED))return false;if(fighter.statuses.v35Takeover)RIFT_V35_RESTORE_TAKEOVER(run,fighter,`The next soul overrides the previous body`);const originalStatuses=RIFT_V35_COPY(fighter.statuses||{});delete originalStatuses.v35Takeover;const original={power:RIFT_V35_COPY(fighter.power),race:RIFT_V35_COPY(fighter.race),trait:RIFT_V35_COPY(fighter.trait),tiers:RIFT_V35_COPY(fighter.tiers),inventory:RIFT_V35_COPY(fighter.inventory),weapon:RIFT_V35_COPY(fighter.weapon),boons:RIFT_V35_COPY(fighter.boons),stand:RIFT_V35_COPY(fighter.stand),maxEnergy:fighter.maxEnergy,energy:fighter.energy,maxHp:fighter.maxHp,ultimate:fighter.ultimate,statuses:originalStatuses,pool:RIFT_V351_POOL_STATE(fighter)};oo(fighter,Math.max(1,Math.round(fighter.maxHp*.2)));const ratio=M(fighter.hp/Math.max(1,fighter.maxHp),.01,1);fighter.power=RIFT_V35_COPY(snapshot.power);fighter.race=RIFT_V35_COPY(snapshot.race);fighter.trait=RIFT_V35_COPY(snapshot.trait);fighter.tiers=RIFT_V35_COPY(snapshot.tiers);fighter.inventory=RIFT_V35_COPY(snapshot.inventory||[]);fighter.weapon=RIFT_V35_COPY(snapshot.weapon);fighter.boons=RIFT_V35_COPY(snapshot.boons||[]);fighter.stand=RIFT_V35_COPY(snapshot.stand);fighter.maxEnergy=Number(snapshot.maxEnergy||fighter.maxEnergy);fighter.energy=Math.min(fighter.maxEnergy,Number(snapshot.energy||fighter.maxEnergy));fighter.maxHp=Math.max(1,Number(snapshot.maxHp||fighter.maxHp));fighter.statuses={...RIFT_V35_COPY(snapshot.statuses||{}),v35OriginalPower:RIFT_V35_RUINED,v35Takeover:{remaining:RIFT_V35_TAKEOVER_TURNS,borrowed:RIFT_V35_TARGET_KEY(snapshot),original,source}};RIFT_V351_APPLY_POOL_STATE(fighter,RIFT_V351_POOL_STATE(snapshot));RIFT_NORMALIZE_FIGHTER_BUILD(fighter);fighter.hp=Math.max(1,Math.round(fighter.maxHp*ratio));fighter.ultimate=original.ultimate;const id=RIFT_V35_ACTOR(run,fighter);if(id&&position)ki(run,id,Wi(run.battlefield,position,Ft(run,id).map(entry=>entry.position)));RIFT_V35_EFFECT(run,`takeover`,fighter,position||RIFT_V35_POINT(run,fighter),{radius:10,borrowed:snapshot.name});RIFT_V35_LOG(run,`SOVEREIGN'S DOMINATION // ${fighter.name} seizes ${snapshot.name}'s body for 5 turns at ${Math.round(ratio*100)}% HP. Borrowed stats, items, passives, and M1–M3 replace his own; Heartbreaker remains the only Ultimate.`,fighter,`mythic`);return true};

/* ---------- Hijack means current FORM, never current charge ---------- */
function RIFT_V351_ULTIMATE_LIKE(action){const tags=action?.move?.tags||[];if(tags.includes(`v35Hijack`)||tags.includes(`v35HijackedTechnique`))return false;return action?.type===`ultimate`||Number(action?.slot)===8||Number(action?.moveIndex)===3||tags.includes(`ultimate`)||tags.includes(`allEnergy`)}
function RIFT_V351_PICK_ULTIMATE(actions=[]){return actions.filter(RIFT_V351_ULTIMATE_LIKE).sort((a,b)=>(Number(a.slot===8)-Number(b.slot===8))*-1)[0]||null}
RIFT_V35_AVAILABLE_ULT=function RIFT_V351_AVAILABLE_ULT(run,target,thief){if(!target)return null;let actions=[];try{actions=La(target)||[]}catch{}let picked=RIFT_V351_PICK_ULTIMATE(actions);if(picked)return picked;const fallback=target?.power?.moves?.[3];if(fallback&&!((fallback.tags||[]).includes(`v35Hijack`)))picked={id:`v351-fallback-ultimate`,slot:8,name:fallback.name,type:`ultimate`,cost:fallback.cost||0,move:RIFT_V35_COPY(fallback),moveIndex:3,sourcePower:target.power?.name};return picked||null};
RIFT_V35_HIJACK=function RIFT_V351_HIJACK(run,fighter,target){if(!target)return false;const cost=RIFT_V35_HIJACK_COST(fighter,target);if(fighter.ultimate<cost){RIFT_V35_LOG(run,`HIJACK DENIED // ${cost}% Ultimate is required to steal from ${target.name}.`,fighter);return false}const borrowed=RIFT_V35_AVAILABLE_ULT(run,target,fighter);if(!borrowed){RIFT_V35_LOG(run,`HIJACK DENIED // ${target.name} has no stealable Ultimate form in their current state.`,fighter);return false}fighter.ultimate=Math.max(0,fighter.ultimate-cost);fighter.statuses.v35HijackedTargets={...(fighter.statuses.v35HijackedTargets||{}),[RIFT_V35_TARGET_KEY(target)]:1};fighter.statuses.v35Hijacked={name:borrowed.name,sourcePower:borrowed.sourcePower||target.power?.name||target.stand?.name||`Unknown`,sourceName:target.name,action:RIFT_V35_COPY(borrowed)};RIFT_V35_EFFECT(run,`v351-hijack-cinematic`,fighter,RIFT_V35_POINT(run,target),{radius:12,name:borrowed.name,sourceName:target.name,accent:`#c47aff`});RIFT_V35_EFFECT(run,`hijack`,fighter,RIFT_V35_POINT(run,target),{radius:9,name:borrowed.name});RIFT_V35_LOG(run,`HIJACK // ${fighter.name} tears ${borrowed.name} from ${target.name}'s current form. Their Ultimate meter was irrelevant; the stolen cast is free and resolves from Sylas's stats.`,fighter,`mythic`);return true};

/* ---------- Targeting corrections ---------- */
const RIFT_V351_BASE_TT=Tt;
Tt=function RIFT_V351_TARGETING(action,fighter){const tags=action?.move?.tags||[];if(tags.includes(`v35Hijack`))return{requiresAim:true,shape:`target`,range:RIFT_V351_HIJACK_RANGE,radius:2.6,ignoresCover:false,label:`HIJACK · SELECT ENEMY · ${RIFT_V351_HIJACK_RANGE}m`,naturalRange:true};if(tags.includes(`v35Abduct`))return{requiresAim:true,shape:`projectile`,range:RIFT_V351_ABDUCT_RANGE,radius:2.4,ignoresCover:false,label:`ABDUCT · ENEMY ONLY · ${RIFT_V351_ABDUCT_RANGE}m`,naturalRange:true};return RIFT_V351_BASE_TT(action,fighter)};
const RIFT_V351_BASE_DASH=RIFT_V35_DASH_TO;
RIFT_V35_DASH_TO=function RIFT_V351_DASH_TO(run,fighter,point,maxDistance){if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)&&fighter?.statuses?.v35AbductWindow>0&&Number(maxDistance)===22)maxDistance=RIFT_V351_ABDUCT_RANGE;return RIFT_V351_BASE_DASH(run,fighter,point,maxDistance)};

/* ---------- Action surface: Heartbreaker owns slot 8; Abscond literally transforms into Abduct ---------- */
function RIFT_V351_REWRITE_ACTIONS(fighter,actions=[]){let out=[...actions];
 if(RIFT_V35_IS(fighter,RIFT_V35_UNSHACKLED)){out=out.map(action=>{const tags=action?.move?.tags||[];if(!tags.includes(`v35Hijack`))return action;return{...action,description:RIFT_V351_HIJACK_DESCRIPTION,move:{...RIFT_V35_COPY(action.move),description:RIFT_V351_HIJACK_DESCRIPTION,tags:[...RIFT_V351_HIJACK_TAGS]}}});out=out.filter(action=>action.id!==`v35-abduct`);if(fighter.statuses?.v35AbductWindow>0){let replaced=false;const abductMove={...RIFT_V35_COPY(RIFT_V35_ABDUCT_MOVE),description:RIFT_V351_ABDUCT_DESCRIPTION,tags:[...(RIFT_V35_ABDUCT_MOVE.tags||[])]};out=out.map(action=>{if(!(action?.move?.tags||[]).includes(`v35Abscond`))return action;replaced=true;return{...action,id:`v351-abduct-recast`,name:`Abduct`,description:`ABSCOND RECAST · ${fighter.statuses.v35AbductWindow}T · ${RIFT_V351_ABDUCT_RANGE}m enemy-only chain. On hit: Stun + grapple Sylas into contact.`,glyph:`鏈`,type:`special`,cost:0,move:abductMove,moveIndex:2,sourcePower:RIFT_V35_UNSHACKLED}});if(!replaced)out.push({id:`v351-abduct-recast`,slot:7,name:`Abduct`,description:`ABSCOND RECAST · ${fighter.statuses.v35AbductWindow}T · ${RIFT_V351_ABDUCT_RANGE}m enemy-only chain.`,glyph:`鏈`,type:`special`,cost:0,move:abductMove,moveIndex:2,sourcePower:RIFT_V35_UNSHACKLED})}}
 if(fighter?.statuses?.v35Takeover){const heart=RIFT_V35_RUINED_POWER.moves[3],state=fighter.statuses.v35Takeover;out=out.filter(action=>{const tags=action?.move?.tags||[];return action.id!==`v35-heartbreaker-takeover`&&action.id!==`v351-heartbreaker-takeover`&&action.type!==`ultimate`&&Number(action.slot)!==8&&Number(action.moveIndex)!==3&&!tags.includes(`ultimate`)&&!tags.includes(`allEnergy`)});out.push({id:`v351-heartbreaker-takeover`,slot:8,name:`Heartbreaker`,description:`TAKEOVER ${state.remaining}T · FREE ULTIMATE · teleport into the execution AOE, scale from missing HP, then immediately leave the stolen body.`,glyph:`心`,type:`ultimate`,cost:0,move:{...RIFT_V35_COPY(heart),cost:0,tags:[...heart.tags.filter(tag=>tag!==`allEnergy`),`ultimate`,`v35TakeoverExit`,`v351FreeHeartbreaker`]},moveIndex:3,sourcePower:RIFT_V35_RUINED})}
 return out}
const RIFT_V351_BASE_LA=La;
La=function RIFT_V351_ACTIONS(fighter){return RIFT_V351_REWRITE_ACTIONS(fighter,RIFT_V351_BASE_LA(fighter))};
const RIFT_V351_BASE_KR=kr;
kr=function RIFT_V351_ULT_READY(fighter,target){if(fighter?.statuses?.v35Takeover)return true;return RIFT_V351_BASE_KR(fighter,target)};
const RIFT_V351_BASE_QA=qa;
qa=function RIFT_V351_BLOCK_REASON(run,action,resolving,locked,target){if((action?.move?.tags||[]).includes(`v351FreeHeartbreaker`))return null;return RIFT_V351_BASE_QA(run,action,resolving,locked,target)};
const RIFT_V351_BASE_RS=rs;
rs=function RIFT_V351_RESOLVE(run,side,action,ctx={}){const tags=action?.move?.tags||[];if(tags.includes(`v351FreeHeartbreaker`)){const fighter=ctx.attacker||(side===`player`?run.player:run.enemy),savedUlt=fighter?.ultimate||0;fighter.ultimate=Math.max(100,savedUlt);const result=RIFT_V351_BASE_RS(run,side,action,ctx);if(fighter?.statuses?.v35Takeover)fighter.ultimate=savedUlt;return result}return RIFT_V351_BASE_RS(run,side,action,ctx)};

/* ---------- Hijack cinematic ---------- */
const RIFT_V351_BASE_RENDER_FX=RIFT_V35_RENDER_FX;
RIFT_V35_RENDER_FX=function RIFT_V351_RENDER_FX(event,bf){if(event?.kind===`v351-hijack-cinematic`){const origin=event.origin||event.target,target=event.target||origin;return(0,E.jsxs)(`div`,{className:`v351-hijack-cinematic`,style:{"--v351":event.accent||`#c47aff`},children:[(0,E.jsx)(`i`,{className:`v351-hijack-veil`}),(0,E.jsxs)(`div`,{className:`v351-hijack-chain`,style:RIFT_V35_LINE(bf,origin,target),children:[(0,E.jsx)(`i`,{className:`v351-chain-a`}),(0,E.jsx)(`i`,{className:`v351-chain-b`}),(0,E.jsx)(`b`,{className:`v351-stolen-core`})]}),(0,E.jsxs)(`div`,{className:`v351-hijack-target`,style:RIFT_V35_STYLE(bf,target),children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{children:`奪`})]}),(0,E.jsxs)(`div`,{className:`v351-hijack-source`,style:RIFT_V35_STYLE(bf,origin),children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{children:`⛓`})]}),(0,E.jsxs)(`div`,{className:`v351-hijack-title`,children:[(0,E.jsx)(`small`,{children:`PETRICITE EXTRACTION`}),(0,E.jsx)(`strong`,{children:`HIJACK`}),(0,E.jsx)(`em`,{children:event.name||`ULTIMATE STOLEN`})]})]},event.id)}return RIFT_V351_BASE_RENDER_FX(event,bf)};

/* ---------- BORK portrait ---------- */
const RIFT_V351_BASE_ITEM_ICON=RIFT_ITEM_ICON;
RIFT_ITEM_ICON=function RIFT_V351_ITEM_ICON({item,size=`normal`}){if(item?.id!==`blade-ruined-king`)return RIFT_V351_BASE_ITEM_ICON({item,size});return(0,E.jsx)(`span`,{className:`rift-item-icon art-icon ${size} rarity-legendary v351-bork-portrait`,style:{"--item-a":item.accent},title:item.name,children:(0,E.jsx)(`img`,{src:`./assets/v35-bork-portrait.webp`,alt:``,draggable:false,"aria-hidden":true})})};

globalThis.RIFTBOUND_V35={...globalThis.RIFTBOUND_V35,hotfix:{version:`35.1`,takeoverPoolSafe:true,heartbreakerOwnsUltimateSlot:true,hijackIgnoresVictimCharge:true,hijackRange:RIFT_V351_HIJACK_RANGE,abductReplacesAbscond:true,abductRange:RIFT_V351_ABDUCT_RANGE,pickUltimate:RIFT_V351_PICK_ULTIMATE,rewriteActions:RIFT_V351_REWRITE_ACTIONS,portrait:`./assets/v35-bork-portrait.webp`},takeover:{begin:RIFT_V35_BEGIN_TAKEOVER,end:RIFT_V35_RESTORE_TAKEOVER},hijack:{cost:RIFT_V35_HIJACK_COST,copy:RIFT_V35_HIJACK,available:RIFT_V35_AVAILABLE_ULT},abduct:RIFT_V35_ABDUCT_MOVE};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,v35:{...globalThis.RIFTBOUND_MANIFEST.v35,hotfix:`35.1`,takeoverPoolSafe:true,heartbreakerOwnsUltimateSlot:true,hijackIgnoresVictimCharge:true,hijackRange:RIFT_V351_HIJACK_RANGE,abductReplacesAbscond:true,abductRange:RIFT_V351_ABDUCT_RANGE,borkPortrait:true}};
