const RIFT_V28_MARKER=`Riftbound Combat Intelligence II V28`;
const RIFT_V28_VERSION=28;
const RIFT_V28_OBSERVATIONS=new WeakMap();
function RIFT_V28_HAZARD_AT(run,position){return(run?.battlefield?.hazards||[]).filter(hazard=>I(hazard.position,position)<=Number(hazard.radius||0)).reduce((sum,hazard)=>sum+Number(hazard.power||1),0)}
function RIFT_V28_COVER(run,origin,target){try{return Et(run.battlefield,origin,target,false)}catch{return false}}
function RIFT_V28_ESCAPE_PATHS(run,actorId){if(!run?.battlefield)return 0;const origin=W(run,actorId),step=7;return[[step,0],[-step,0],[0,step],[0,-step]].map(([x,y])=>({x:M(origin.x+x,1,run.battlefield.width-1),y:M(origin.y+y,1,run.battlefield.height-1)})).filter(point=>!RIFT_V28_HAZARD_AT(run,point)&&!Et(run.battlefield,origin,point,false)).length}
function RIFT_V28_PLAYER_OBSERVATION(run){let state=RIFT_V28_OBSERVATIONS.get(run);if(!state){state={actions:{},types:{},positions:[],guards:0,total:0};RIFT_V28_OBSERVATIONS.set(run,state)}return state}
RIFT_V22_EVENT_BUS.on(`ACTION_FINISHED`,event=>{const run=globalThis.__RIFTBOUND_ACTIVE_RUN__;if(!run||event.payload.side!==`player`)return;const state=RIFT_V28_PLAYER_OBSERVATION(run),name=event.payload.name||`Action`;state.actions[name]=(state.actions[name]||0)+1;state.total+=1});RIFT_V22_EVENT_BUS.on(`ACTOR_MOVED`,event=>{const run=globalThis.__RIFTBOUND_ACTIVE_RUN__;if(!run||event.payload.actorId!==`player`)return;const state=RIFT_V28_PLAYER_OBSERVATION(run);state.positions.push(P(event.payload.target));state.positions=state.positions.slice(-12)});
function RIFT_V28_TACTICAL_CONTEXT(run,actorId,targetId,action){
 const actor=U(run,actorId),target=U(run,targetId),origin=W(run,actorId),destination=W(run,targetId),geometry=Tt(action,actor.fighter),distance=I(origin,destination),observation=RIFT_V28_PLAYER_OBSERVATION(run),repeat=Math.max(0,...Object.values(observation.actions||{}),0)/Math.max(1,observation.total||1),allies=H(run).filter(entry=>entry.team===actor.team&&entry.id!==actorId&&entry.fighter.hp>0),hostiles=H(run).filter(entry=>entry.team!==actor.team&&entry.fighter.hp>0),cooldowns=La(actor.fighter).filter(candidate=>Va(actor.fighter,candidate)>0).length;
 return{actorId,targetId,distance,range:geometry.range,inRange:!geometry.requiresAim||distance<=geometry.range,shape:geometry.shape,cover:RIFT_V28_COVER(run,origin,destination),actorHazard:RIFT_V28_HAZARD_AT(run,origin),targetHazard:RIFT_V28_HAZARD_AT(run,destination),escapePaths:RIFT_V28_ESCAPE_PATHS(run,actorId),energyRatio:actor.fighter.energy/Math.max(1,actor.fighter.maxEnergy),ultimateThreat:target.fighter.ultimate/100,cooldowns,allies:allies.length,hostiles:hostiles.length,outnumbered:hostiles.length>allies.length+1,playerRepeat:repeat,recentPlayerActions:Object.entries(observation.actions).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([name,count])=>({name,count})),knownInformation:[`visible positions`,`visible statuses`,`revealed equipment`,`performed actions`,`public resources`]};
}
const RIFT_V28_WEIGHTS=Object.freeze({sentinel:{cover:12,hazard:-13,escape:4,resource:5,control:10,finisher:2},architect:{cover:7,hazard:8,escape:3,resource:4,control:18,finisher:3},conserver:{cover:8,hazard:-7,escape:4,resource:15,control:7,finisher:4},duelist:{cover:3,hazard:-4,escape:2,resource:5,control:8,finisher:10},predator:{cover:1,hazard:-2,escape:1,resource:2,control:5,finisher:19},storm:{cover:-3,hazard:7,escape:-1,resource:-2,control:6,finisher:14}});
function RIFT_V28_ACTION_SCORE(run,actorId,targetId,action){const actor=U(run,actorId)?.fighter,target=U(run,targetId)?.fighter;if(!actor||!target||!action)return{score:-1e9,factors:[{label:`invalid context`,value:-1e9}]};const personality=RIFT_V19_AI_PERSONALITY(actor),weights=RIFT_V28_WEIGHTS[personality.id]||RIFT_V28_WEIGHTS.duelist,context=RIFT_V28_TACTICAL_CONTEXT(run,actorId,targetId,action),tags=action.move?.tags||[],factors=[];const add=(label,value)=>{if(Number.isFinite(value)&&Math.abs(value)>=.01)factors.push({label,value:Math.round(value*100)/100})};add(`V19 tactical base`,RIFT_V19_ACTION_SCORE(actor,target,action,personality));add(context.inRange?`inside effective range`:`outside effective range`,context.inRange?12:-42);add(context.cover?`target behind cover`:`clear line`,context.cover&&!tags.some(tag=>[`beam`,`line`,`guaranteedHit`,`spatial`].includes(tag))?-18:context.cover?3:5);add(`actor hazard`,context.actorHazard*weights.hazard);add(`target hazard synergy`,context.targetHazard*weights.control);add(`escape options`,context.escapePaths*weights.escape);if(context.energyRatio<.3)add(`low Energy`,action.cost?-(action.cost/10)*weights.resource:weights.resource);if(context.ultimateThreat>.75)add(`enemy Ultimate threat`,(tags.includes(`stun`)||action.type===`guard`?1:-.35)*weights.control*context.ultimateThreat);if(context.outnumbered)add(`outnumbered`,(action.type===`guard`||tags.includes(`area`)?12:-8));if(tags.some(tag=>[`stun`,`restrain`,`force`,`guardbreak`,`slow`].includes(tag)))add(`control profile`,weights.control);if(target.hp/target.maxHp<.3)add(`finisher window`,weights.finisher*Number(action.move?.power||0));if(context.playerRepeat>.45&&(action.type===`guard`||tags.includes(`counter`)))add(`observed repetition`,14*context.playerRepeat);if(context.cooldowns>=3&&action.cost>0)add(`cooldown congestion`,-5);const score=factors.reduce((sum,row)=>sum+row.value,0);return{score:Math.round(score*100)/100,personality:personality.name,context,factors:factors.sort((a,b)=>Math.abs(b.value)-Math.abs(a.value))}}
function RIFT_V28_EXPLAIN(run,actorId,targetId,action){const result=RIFT_V28_ACTION_SCORE(run,actorId,targetId,action);return{actionId:action?.id||null,action:action?.name||null,score:result.score,personality:result.personality,reasons:result.factors.slice(0,5).map(row=>`${row.value>=0?`+`:``}${row.value} ${row.label}`),information:result.context?.knownInformation||[]}}
const RIFT_V28_BASE_CHOOSE=is;
is=function RIFT_V28_CHOOSE(fighter,target){const base=RIFT_V28_BASE_CHOOSE(fighter,target),run=globalThis.__RIFTBOUND_ACTIVE_RUN__;if(!run||!fighter||!target||fighter.statuses?.calamityBoss||fighter.statuses?.rikaCompanion)return base;const actorId=RIFT_V22_ACTOR_ID(run,fighter),targetId=RIFT_V22_ACTOR_ID(run,target);if(!actorId||!targetId)return base;const actions=RIFT_V19_SAFE_AI_ACTIONS(fighter,target);if(!actions.length)return base;const ranked=actions.map(action=>({action,result:RIFT_V28_ACTION_SCORE(run,actorId,targetId,action)})).sort((a,b)=>b.result.score-a.result.score||String(a.action.id).localeCompare(String(b.action.id))),best=ranked[0];const choice=best?.result.score>(ranked.find(row=>row.action.id===base?.id)?.result.score??-1e9)+4||Math.random()<.74?best?.action:base;fighter.v28LastDecision={turn:run.turn,...RIFT_V28_EXPLAIN(run,actorId,targetId,choice),alternatives:ranked.slice(0,3).map(row=>({id:row.action.id,name:row.action.name,score:row.result.score}))};return choice||base};
function RIFT_V28_ENCOUNTER_DIRECTOR(run){const budget=RIFT_V18_ENCOUNTER_BUDGET(run),buildWarnings=RIFT_V18_BUILD_WARNINGS(run.player),summary=RIFT_V26_RUN_SUMMARY(run),danger=Math.round((1-M(run.player.hp/Math.max(1,run.player.maxHp),0,1))*35+Math.min(30,buildWarnings.length*7)+Math.min(20,summary.damage/Math.max(1,run.floor*70))*5),recommendation=budget.band===`over`||danger>58?`relief`:budget.band===`under`&&danger<25?`pressure`:`hold`;return{version:28,floor:run.floor,budget,danger,recommendation,nextEncounter:recommendation===`relief`?{roles:[`Sentinel`],rewardMultiplier:1.18,reason:`Current route pressure exceeds the build's recovery.`}:recommendation===`pressure`?{roles:[`Architect`,`Predator`],rewardMultiplier:1.1,reason:`The party is materially ahead of the route budget.`}:{roles:[`Duelist`],rewardMultiplier:1,reason:`Encounter pressure is inside target band.`},abilityModifiers:false,betweenBattlesOnly:true}}
const RIFT_V28_BASE_APPLY_ROUTE=RIFT_V16_APPLY_ROUTE;
RIFT_V16_APPLY_ROUTE=function RIFT_V28_APPLY_ROUTE(run,...args){const prior=RIFT_V28_ENCOUNTER_DIRECTOR(run),out=RIFT_V28_BASE_APPLY_ROUTE(run,...args);run.v28Director=prior;if(run.v16RouteState)run.v16RouteState.shardMult=Math.max(1,Number(run.v16RouteState.shardMult||1)*Number(prior.nextEncounter.rewardMultiplier||1));return out};
const RIFT_V28_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V28_NORMALIZE_RUN_BUILD(run){run=RIFT_V28_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(28,Number(run.riftboundSchemaVersion||0));run.v28Director=run.v28Director&&typeof run.v28Director===`object`?run.v28Director:null;globalThis.__RIFTBOUND_ACTIVE_RUN__=run;return run};
globalThis.RIFTBOUND_COMBAT_INTELLIGENCE={...globalThis.RIFTBOUND_COMBAT_INTELLIGENCE,version:28,context:RIFT_V28_TACTICAL_CONTEXT,tacticalScore:RIFT_V28_ACTION_SCORE,explain:RIFT_V28_EXPLAIN,director:RIFT_V28_ENCOUNTER_DIRECTOR,fairInformation:[`visible positions`,`visible statuses`,`revealed equipment`,`performed actions`,`public resources`]};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:28,release:`V28 · Combat Intelligence II`,combatIntelligence:{version:28,personalities:[`Sentinel`,`Architect`,`Conserver`,`Duelist`,`Predator`,`Storm`],reasons:[`range`,`cover`,`hazards`,`cooldowns`,`resources`,`ultimate threat`,`allies`,`escape paths`,`observed actions`],fairInformation:true,hiddenDecisionAccess:false,director:`between-battles-only`,abilityModifiers:false}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:28,intelligence:()=>globalThis.__RIFTBOUND_ACTIVE_RUN__?RIFT_V28_ENCOUNTER_DIRECTOR(globalThis.__RIFTBOUND_ACTIVE_RUN__):null};
