const RIFT_V32_MARKER=`Riftbound Restless Gambler V32`;
const RIFT_V32_VERSION=32;
const RIFT_V32_POWER_NAME=`Restless Gambler`;
const RIFT_V32_FEVER_MAX=6;
const RIFT_V32_DOMAIN_TURNS=12;
const RIFT_V32_DOMAIN_CAP=18;
const RIFT_V32_JACKPOT_TURNS=20;
const RIFT_V32_JACKPOT_REGEN=.08;

function RIFT_V32_MOVE(name,description,cost,power,destruction,tags,hits=1,glyph=`◆`){return{name,description,cost,power,destruction,tags,hits,glyph}}
const RIFT_V32_BASE_MOVES=Object.freeze([
 RIFT_V32_MOVE(`Chromatic Balls`,`Fire a rough-energy pachinko ball that ricochets through three contacts. Its damage tier is rolled from six possible values; rolling the minimum grants 1 Fever.`,13,.34,.72,[`physical`,`projectile`,`multi`,`ricochet`,`bleed`,`v32ChromaticBalls`],3,`彩`),
 RIFT_V32_MOVE(`Train Door`,`Place a solid train door within 30m. It telegraphs for one combatant turn, then slams shut; hostile fighters caught in its 3.2m threshold take damage and are Stunned. The closed door remains as destructible cover.`,18,0,.55,[`magic`,`wall`,`field`,`delayed`,`v32TrainDoor`],1,`門`),
 RIFT_V32_MOVE(`Rough Blast`,`Drive a rough-energy uppercut through a nearby target, launch them backward, and immediately set Bleed to its six-stack maximum.`,24,1.28,1.35,[`physical`,`melee`,`bleed`,`knockback`,`v32RoughBlast`],1,`昇`),
 RIFT_V32_MOVE(`Private Pure Love Train`,`Expand a twelve-turn gambling domain. Every two Special techniques roll three digits: odd extends the domain, even restores Energy, consecutive digits fully heal and refresh power cooldowns, and matching digits trigger Jackpot. Maximum Fever guarantees Jackpot immediately.`,100,0,.65,[`magic`,`domain`,`selfCast`,`allEnergy`,`v32LoveTrain`],1,`賭`),
]);
const RIFT_V32_JACKPOT_MOVES=Object.freeze([
 RIFT_V32_MOVE(`Lucky Shot`,`Unleash an eight-hit fist barrage. Every hit carries Rough Energy, rapidly driving Bleed to maximum. Free while Jackpot is active.`,0,.18,.8,[`physical`,`melee`,`barrage`,`multi`,`bleed`,`v32JackpotOnly`,`v32LuckyShot`],8,`連`),
 RIFT_V32_MOVE(`Relentless Luck`,`Blink to a target within 24m and hammer them into the ground. The impact damages other hostiles inside a 7m shockwave. Free while Jackpot is active.`,0,1.32,1.7,[`physical`,`teleport`,`dashAttack`,`area`,`knockback`,`v32JackpotOnly`,`v32RelentlessLuck`],1,`墜`),
 RIFT_V32_MOVE(`Fever Punch`,`Compress the Jackpot aura into one committed punch with massive damage, Guard Break, and extreme knockback. Free while Jackpot is active.`,0,2.08,2.35,[`physical`,`melee`,`charge`,`guardbreak`,`knockback`,`v32JackpotOnly`,`v32FeverPunch`],1,`熱`),
]);
const RIFT_V32_POWER=Object.freeze({
 name:RIFT_V32_POWER_NAME,rarity:`Legendary`,damageType:`Physical`,glyph:`賭`,accent:`#64ff8f`,
 passive:`Rough Energy makes successful physical strikes apply stacking Bleed. Failed accuracy or dodge outcomes and minimum-damage Chromatic Balls build a six-segment Fever bar. Every two Fever segments grant +1 Attack Strength, Durability, and Speed tier; maximum Fever guarantees the next Private Pure Love Train becomes Jackpot.`,
 codexDescription:`You bet your life for the sweet shock of a winning line. Private Pure Love Train starts ready every battle, rolls after every two Special techniques, and can erupt into twenty combatant turns of free Energy, relentless regeneration, triple Movement, a green aura, and an entirely different moveset. Jackpot is not invulnerability: lethal burst and anti-heal remain decisive counters.`,
 moves:RIFT_V32_BASE_MOVES,
});
if(!g.some(power=>power.name===RIFT_V32_POWER_NAME))g.push(RIFT_V32_POWER);
try{RIFT_V22_REGISTRY.powers.set(RIFT_V32_POWER_NAME,RIFT_V32_POWER)}catch{}

function RIFT_V32_IS(fighter){return fighter?.power?.name===RIFT_V32_POWER_NAME}
function RIFT_V32_ACTOR(run,fighter){return RIFT_ACTOR_ID_FOR_FIGHTER(run,fighter)||RIFT_V22_ACTOR_ID?.(run,fighter)||null}
function RIFT_V32_ENTRIES(run){try{return H(run).filter(entry=>RIFT_V32_IS(entry.fighter))}catch{return[`player`,`enemy`].map(id=>({id,fighter:run?.[id]})).filter(entry=>RIFT_V32_IS(entry.fighter))}}
function RIFT_V32_TONE(fighter,run){return fighter===run?.player?`player`:`enemy`}
function RIFT_V32_RANDOM(run,fighter,channel,index=0){const actor=RIFT_V32_ACTOR(run,fighter)||fighter?.name||`gambler`,seed=`${run?.v26Seed||run?.floor||0}|${run?.turn||0}|${actor}|${channel}|${index}`;return RIFT_V22_SEEDED(seed)()}
function RIFT_V32_LOG(run,message,fighter=null,tone=`mythic`){G(run,message,fighter?RIFT_V32_TONE(fighter,run):tone)}
function RIFT_V32_FEVER(fighter,amount,run,reason){if(!RIFT_V32_IS(fighter)||amount<=0)return Number(fighter?.statuses?.v32Fever||0);fighter.statuses=fighter.statuses||{};const before=Number(fighter.statuses.v32Fever||0),after=Math.min(RIFT_V32_FEVER_MAX,before+amount);fighter.statuses.v32Fever=after;if(after>before&&run)RIFT_V32_LOG(run,`FEVER ${after}/${RIFT_V32_FEVER_MAX} // ${reason}${after===RIFT_V32_FEVER_MAX?` Maximum Fever locks the next domain onto Jackpot.`:``}`,fighter);return after}
function RIFT_V32_EFFECT(run,fighter,className,target=null,options={}){if(!run?.battlefield||!fighter)return null;const actorId=RIFT_V32_ACTOR(run,fighter),origin=actorId?W(run,actorId):{x:run.battlefield.width/2,y:run.battlefield.height/2},at=target||origin,effect={id:`v32-${F()}`,className,shape:options.shape||`field`,motion:options.motion||`burst`,origin:{...origin},target:{...at},radius:Number(options.radius||7),accent:options.accent||`#61ff8e`,secondary:options.secondary||`#fff36b`,tertiary:options.tertiary||`#071a10`,glyph:options.glyph||`賭`,name:options.name||RIFT_V32_POWER_NAME,turns:Number(options.turns||2),force:Number(options.force||1.4)};run.battlefield.effectEchoes=run.battlefield.effectEchoes||[];run.battlefield.effectEchoes.push(effect);return effect}
function RIFT_V32_HOSTILES(run,fighter){const owner=U(run,RIFT_V32_ACTOR(run,fighter));return owner?H(run).filter(entry=>entry.kind===`fighter`&&entry.fighter.hp>0&&entry.team!==owner.team):[]}
function RIFT_V32_RAW(attacker,target,coefficient=1){const as=Math.max(0,Y(attacker,`as`)),dur=Math.max(0,Y(target,`durability`));return Math.max(1,(25+as*4.65)*coefficient*Math.pow(1.1,as-dur))}

const RIFT_V32_BASE_Y=Y;
Y=function RIFT_V32_EFFECTIVE_STAT(fighter,stat){let value=RIFT_V32_BASE_Y(fighter,stat);if(RIFT_V32_IS(fighter)&&[`as`,`durability`,`speed`].includes(stat))value+=Math.floor(Math.min(RIFT_V32_FEVER_MAX,Number(fighter.statuses?.v32Fever||0))/2);return value};
const RIFT_V32_BASE_MT=mt;
mt=function RIFT_V32_MOVEMENT(fighter){const value=RIFT_V32_BASE_MT(fighter);return RIFT_V32_IS(fighter)&&Number(fighter.statuses?.v32JackpotTurns||0)>0?value*3:value};

const RIFT_V32_BASE_TT=Tt;
Tt=function RIFT_V32_GEOMETRY(action,fighter){const tags=action?.move?.tags||[];
 if(tags.includes(`v32ChromaticBalls`))return{requiresAim:true,shape:`projectile`,range:42,radius:2.8,ignoresCover:false,label:`RICOCHET LINE · 42m`,naturalRange:true};
 if(tags.includes(`v32TrainDoor`))return{requiresAim:true,shape:`area`,range:30,radius:3.2,ignoresCover:false,label:`TRAIN DOOR · 30m`,naturalRange:true};
 if(tags.includes(`v32RoughBlast`))return{requiresAim:true,shape:`target`,range:6,radius:2.8,ignoresCover:false,label:`UPPERCUT · 6m`,naturalRange:true};
 if(tags.includes(`v32LoveTrain`))return{requiresAim:false,shape:`self`,range:0,radius:24,ignoresCover:true,label:`DOMAIN EXPANSION`,naturalRange:true};
 if(tags.includes(`v32LuckyShot`))return{requiresAim:true,shape:`target`,range:6.5,radius:3.2,ignoresCover:false,label:`BARRAGE · 6.5m`,naturalRange:true};
 if(tags.includes(`v32RelentlessLuck`))return{requiresAim:true,shape:`teleport`,range:24,radius:7,ignoresCover:false,label:`BLINK SLAM · 24m`,naturalRange:true};
 if(tags.includes(`v32FeverPunch`))return{requiresAim:true,shape:`target`,range:7,radius:4,ignoresCover:false,label:`FEVER PUNCH · 7m`,naturalRange:true};
 return RIFT_V32_BASE_TT(action,fighter)};

const RIFT_V32_BASE_LA=La;
La=function RIFT_V32_ACTIONS(fighter){let actions=RIFT_V32_BASE_LA(fighter);if(!RIFT_V32_IS(fighter)||Number(fighter.statuses?.v32JackpotTurns||0)<=0)return actions;return actions.map(action=>{const tags=action?.move?.tags||[],index=tags.includes(`v32ChromaticBalls`)?0:tags.includes(`v32TrainDoor`)?1:tags.includes(`v32RoughBlast`)?2:-1;if(index<0)return action;const move=RIFT_V32_JACKPOT_MOVES[index];return{...action,name:move.name,description:move.description,cost:0,glyph:move.glyph,move:{...move},sourcePower:RIFT_V32_POWER_NAME}})};

function RIFT_V32_RESET_COOLDOWNS(fighter){for(const key of Object.keys(fighter?.statuses||{}))if(key.startsWith(`standardCooldown_`)||/^power.*Cooldown/i.test(key))fighter.statuses[key]=0;try{for(const action of La(fighter)){const key=Ba(fighter,action);if(key&&Number.isFinite(fighter.statuses[key]))fighter.statuses[key]=0}}catch{}}
function RIFT_V32_IS_CONSECUTIVE(digits){const [a,b,c]=digits;return b-a===1&&c-b===1||a-b===1&&b-c===1}
function RIFT_V32_BASS_ALLOWED(){return typeof window!==`undefined`&&RIFT_V20_ACCESS?.jackpotMusic!==false&&Number(RIFT_V27_AUDIO_STATE?.master||0)>0&&Number(RIFT_V27_AUDIO_STATE?.music||0)>0}
const RIFT_V32_BASS_STATE={active:false,token:0,timer:null,step:0};
function RIFT_V32_ANY_JACKPOT(run=globalThis.__RIFTBOUND_ACTIVE_RUN__){return RIFT_V32_ENTRIES(run).some(entry=>Number(entry.fighter.statuses?.v32JackpotTurns||0)>0)}
function RIFT_V32_BASS_STOP(){RIFT_V32_BASS_STATE.active=false;RIFT_V32_BASS_STATE.token+=1;if(RIFT_V32_BASS_STATE.timer)clearTimeout(RIFT_V32_BASS_STATE.timer);RIFT_V32_BASS_STATE.timer=null}
function RIFT_V32_BASS_NOTE(frequency){if(!RIFT_V32_BASS_ALLOWED())return;try{const Ctx=window.AudioContext||window.webkitAudioContext,context=RIFT_V27_AUDIO_STATE.context||(RIFT_V27_AUDIO_STATE.context=new Ctx),now=context.currentTime,gain=context.createGain(),filter=context.createBiquadFilter(),bass=context.createOscillator(),bite=context.createOscillator();filter.type=`lowpass`;filter.frequency.setValueAtTime(520,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055*RIFT_V27_AUDIO_STATE.master*RIFT_V27_AUDIO_STATE.music,now+.018);gain.gain.exponentialRampToValueAtTime(.0001,now+.31);bass.type=`sawtooth`;bass.frequency.setValueAtTime(frequency,now);bite.type=`square`;bite.frequency.setValueAtTime(frequency*2,now);bass.connect(filter);bite.connect(filter);filter.connect(gain).connect(context.destination);bass.start(now);bite.start(now);bass.stop(now+.33);bite.stop(now+.12)}catch{}}
function RIFT_V32_BASS_START(){if(!RIFT_V32_BASS_ALLOWED()||RIFT_V32_BASS_STATE.active)return;RIFT_V32_BASS_STATE.active=true;RIFT_V32_BASS_STATE.token+=1;const token=RIFT_V32_BASS_STATE.token,notes=[49,55,65.41,49,73.42,65.41,55,49];const loop=()=>{if(token!==RIFT_V32_BASS_STATE.token||!RIFT_V32_BASS_ALLOWED()||!RIFT_V32_ANY_JACKPOT()){RIFT_V32_BASS_STOP();return}RIFT_V32_BASS_NOTE(notes[RIFT_V32_BASS_STATE.step++%notes.length]);RIFT_V32_BASS_STATE.timer=setTimeout(loop,360)};loop()}

function RIFT_V32_SYNC_ROOT(run=globalThis.__RIFTBOUND_ACTIVE_RUN__){if(typeof document===`undefined`)return;const entries=RIFT_V32_ENTRIES(run),domain=entries.some(entry=>Number(entry.fighter.statuses?.v32DomainTurns||0)>0),jackpot=entries.some(entry=>Number(entry.fighter.statuses?.v32JackpotTurns||0)>0);document.documentElement.classList.toggle(`rift-v32-domain`,domain);document.documentElement.classList.toggle(`rift-v32-jackpot`,jackpot);document.documentElement.style.setProperty(`--v32-domain-turns`,String(Math.max(0,...entries.map(entry=>Number(entry.fighter.statuses?.v32DomainTurns||0)))));if(jackpot)RIFT_V32_BASS_START();else RIFT_V32_BASS_STOP()}
function RIFT_V32_START_JACKPOT(run,fighter,source=`777`){fighter.statuses.v32JackpotTurns=RIFT_V32_JACKPOT_TURNS;fighter.statuses.v32JackpotStartedTurn=run.turn;fighter.statuses.v32JackpotLastTick=null;fighter.statuses.v32JackpotRegenTurn=null;delete fighter.statuses.v32DomainTurns;delete fighter.statuses.v32DomainMoves;fighter.ultimate=0;fighter.energy=fighter.maxEnergy;RIFT_V32_EFFECT(run,fighter,`v32-jackpot-awakening`,null,{shape:`field`,radius:24,force:2.6,glyph:`777`,name:`JACKPOT`});RIFT_V32_LOG(run,`JACKPOT · ${source} // Infinite Energy, 8% regeneration every combatant turn, triple Movement, and the Jackpot moveset are live for ${RIFT_V32_JACKPOT_TURNS} turns. Lethal burst and anti-heal still apply.`,fighter);RIFT_V32_SYNC_ROOT(run);RIFT_V32_BASS_START()}
function RIFT_V32_START_DOMAIN(run,fighter){const fever=Number(fighter.statuses?.v32Fever||0);fighter.ultimate=0;if(fever>=RIFT_V32_FEVER_MAX){fighter.statuses.v32Fever=0;RIFT_V32_LOG(run,`MAXIMUM FEVER // Private Pure Love Train opens on a predetermined winning line.`,fighter);RIFT_V32_START_JACKPOT(run,fighter,`FEVER GUARANTEE`);return}fighter.statuses.v32DomainTurns=RIFT_V32_DOMAIN_TURNS;fighter.statuses.v32DomainMoves=0;fighter.statuses.v32DomainRolls=0;fighter.statuses.v32DomainStartedTurn=run.turn;fighter.statuses.v32LastRoll=null;RIFT_V32_EFFECT(run,fighter,`v32-love-train-domain`,null,{shape:`field`,radius:24,force:2.2,glyph:`賭`,name:`PRIVATE PURE LOVE TRAIN`});RIFT_V32_LOG(run,`DOMAIN EXPANSION · PRIVATE PURE LOVE TRAIN // ${RIFT_V32_DOMAIN_TURNS} turns. Every two Special techniques roll a three-digit line.`,fighter);RIFT_V32_SYNC_ROOT(run)}
function RIFT_V32_ROLL(run,fighter){fighter.statuses.v32DomainRolls=Number(fighter.statuses.v32DomainRolls||0)+1;const rollIndex=fighter.statuses.v32DomainRolls,digits=[0,1,2].map(index=>1+Math.floor(RIFT_V32_RANDOM(run,fighter,`domain-${rollIndex}`,index)*9)),number=digits[0]*100+digits[1]*10+digits[2],same=digits[0]===digits[1]&&digits[1]===digits[2],consecutive=RIFT_V32_IS_CONSECUTIVE(digits);fighter.statuses.v32LastRoll=number;fighter.statuses.v32DomainMoves=0;
 if(same){RIFT_V32_LOG(run,`ROLL ${number} // THREE OF A KIND. The barriers split beneath the winning line.`,fighter);RIFT_V32_START_JACKPOT(run,fighter,String(number));return{number,digits,outcome:`jackpot`}}
 if(consecutive){fighter.hp=fighter.maxHp;RIFT_V32_RESET_COOLDOWNS(fighter);RIFT_V32_EFFECT(run,fighter,`v32-consecutive-roll`,null,{shape:`field`,radius:10,glyph:String(number),name:`CONSECUTIVE LINE`});RIFT_V32_LOG(run,`ROLL ${number} // CONSECUTIVE LINE. HP is fully restored and every power cooldown is refreshed.`,fighter);return{number,digits,outcome:`consecutive`}}
 if(number%2){fighter.statuses.v32DomainTurns=Math.min(RIFT_V32_DOMAIN_CAP,Number(fighter.statuses.v32DomainTurns||0)+1);RIFT_V32_LOG(run,`ROLL ${number} // ODD. Private Pure Love Train gains 1 turn (${fighter.statuses.v32DomainTurns}/${RIFT_V32_DOMAIN_CAP}).`,fighter);return{number,digits,outcome:`odd`}}
 const restored=Math.max(1,Math.round(fighter.maxEnergy*.24)),before=fighter.energy;Ir(fighter,restored);RIFT_V32_LOG(run,`ROLL ${number} // EVEN. ${Math.round(fighter.energy-before)} Energy floods back into the wager.`,fighter);return{number,digits,outcome:`even`}}

function RIFT_V32_PLACE_DOOR(run,fighter,action){if(!run?.battlefield)return null;const actorId=RIFT_V32_ACTOR(run,fighter),origin=actorId?W(run,actorId):{x:run.battlefield.width/2,y:run.battlefield.height/2},requested=action?.aim?.target||origin,position=Wi(run.battlefield,{x:M(requested.x,3,run.battlefield.width-3),y:M(requested.y,3,run.battlefield.height-3)},Ft(run,actorId).map(entry=>entry.position)),feature={id:`v32-train-door-${F()}`,kind:`wall`,label:`Train Door · Opening`,position:{...position},radius:3.2,solid:true,cover:.92,destructible:true,integrity:82,maxIntegrity:82,accent:`#65ff92`,mechanic:`v32TrainDoor`,ownerId:actorId,createdTurn:run.turn,closesAtTurn:run.turn+1,expiresAtTurn:run.turn+7,closed:false};run.battlefield.features=run.battlefield.features||[];run.battlefield.features.push(feature);RIFT_V32_EFFECT(run,fighter,`v32-train-door-open`,position,{shape:`wall`,radius:4,glyph:`門`,name:`TRAIN DOOR · WIND-UP`});RIFT_V32_LOG(run,`TRAIN DOOR // A solid threshold rises at (${position.x.toFixed(0)}, ${position.y.toFixed(0)}). It slams shut after one combatant turn.`,fighter);return feature}
function RIFT_V32_PROCESS_DOORS(run){if(!run?.battlefield||run.battlefield.v32DoorProcessedTurn===run.turn)return;run.battlefield.v32DoorProcessedTurn=run.turn;for(const door of [...(run.battlefield.features||[])]){if(door.mechanic!==`v32TrainDoor`||door.integrity<=0)continue;if(!door.closed&&run.turn>=door.closesAtTurn){door.closed=true;door.label=`Train Door · Closed`;const owner=U(run,door.ownerId),fighter=owner?.fighter;if(fighter){const caught=H(run).filter(entry=>entry.kind===`fighter`&&entry.fighter.hp>0&&entry.team!==owner.team&&I(W(run,entry.id),door.position)<=door.radius);for(const entry of caught){const damage=go(run,fighter,entry.fighter,RIFT_V32_RAW(fighter,entry.fighter,1.05),false,[`physical`,`stun`,`guardbreak`,`v32TrainDoorHit`]);entry.fighter.statuses.stun=Math.max(1,Number(entry.fighter.statuses.stun||0));RIFT_V32_LOG(run,`TRAIN DOOR · SLAM // ${entry.fighter.name} is caught in the threshold for ${damage} damage and Stunned.`,fighter)}RIFT_V32_EFFECT(run,fighter,`v32-train-door-slam`,door.position,{shape:`wall`,radius:5.5,glyph:`閉`,name:`TRAIN DOOR · SLAM`})}}}run.battlefield.features=run.battlefield.features.filter(feature=>feature.mechanic!==`v32TrainDoor`||feature.integrity>0&&run.turn<feature.expiresAtTurn)}
function RIFT_V32_RELENTLESS(run,fighter,target){if(!target?.hp||!run?.battlefield)return;const actorId=RIFT_V32_ACTOR(run,fighter),targetId=RIFT_V32_ACTOR(run,target);if(actorId&&targetId){const at=W(run,targetId),from=W(run,actorId),distance=Math.max(.01,I(from,at)),near=Wi(run.battlefield,{x:at.x+(from.x-at.x)/distance*2.1,y:at.y+(from.y-at.y)/distance*2.1},Ft(run,actorId).map(entry=>entry.position));ki(run,actorId,near);for(const entry of RIFT_V32_HOSTILES(run,fighter))if(entry.fighter!==target&&I(W(run,entry.id),at)<=7)go(run,fighter,entry.fighter,RIFT_V32_RAW(fighter,entry.fighter,.48),false,[`physical`,`area`,`knockback`,`v32RelentlessSplash`]);RIFT_V32_EFFECT(run,fighter,`v32-relentless-luck`,at,{shape:`area`,motion:`dash`,radius:7,glyph:`墜`,name:`RELENTLESS LUCK`})}}

const RIFT_V32_BASE_TO=To;
To=function RIFT_V32_AFTER_HIT(run,attacker,target,tags,damage,action){const out=RIFT_V32_BASE_TO(run,attacker,target,tags,damage,action);if(damage>0&&RIFT_V32_IS(attacker)&&(action?.type===`strike`||tags?.includes(`physical`)||tags?.includes(`v32LuckyShot`))){target.statuses=target.statuses||{};const before=Number(target.statuses.bleed||0),gain=tags?.includes(`v32RoughBlast`)?RIFT_V32_FEVER_MAX:tags?.includes(`v32LuckyShot`)?Number(action?.move?.hits||8):1;target.statuses.bleed=Math.min(6,before+gain);target.statuses.bleedPower=Math.max(Number(target.statuses.bleedPower||0),1+Y(attacker,`as`)*.13);if(target.statuses.bleed>before)RIFT_V32_LOG(run,`ROUGH ENERGY // ${target.name} carries Bleed ${target.statuses.bleed}/6.`,attacker)}return out};

const RIFT_V32_BASE_RS=rs;
rs=function RIFT_V32_RESOLVE(run,side,action,ctx={}){const attacker=ctx.attacker||(side===`player`?run.player:run.enemy),target=ctx.target||(side===`player`?run.enemy:run.player);if(!RIFT_V32_IS(attacker))return RIFT_V32_BASE_RS(run,side,action,ctx);let tags=action?.move?.tags||[],resolved=action;if(tags.includes(`v32ChromaticBalls`)){attacker.statuses.v32ChromaticUses=Number(attacker.statuses.v32ChromaticUses||0)+1;const tiers=[.55,.78,1,1.25,1.55,1.9],index=Math.min(tiers.length-1,Math.floor(RIFT_V32_RANDOM(run,attacker,`chromatic`,attacker.statuses.v32ChromaticUses)*tiers.length));resolved={...action,move:{...action.move,power:Number(action.move.power||.34)*tiers[index]}};if(index===0)RIFT_V32_FEVER(attacker,1,run,`Chromatic Balls rolled minimum damage`);RIFT_V32_LOG(run,`CHROMATIC BALLS // Damage tier ${index+1}/6 · ${tiers[index].toFixed(2)}×. Three ricochet contacts enter the line.`,attacker)}const previousLogs=new Set((run.logs||[]).map(row=>row.id)),result=RIFT_V32_BASE_RS(run,side,resolved,ctx);tags=resolved?.move?.tags||tags;
 if(tags.includes(`v32LoveTrain`))RIFT_V32_START_DOMAIN(run,attacker);
 if(tags.includes(`v32TrainDoor`))RIFT_V32_PLACE_DOOR(run,attacker,resolved);
 if(tags.includes(`v32RelentlessLuck`))RIFT_V32_RELENTLESS(run,attacker,target);
 if(tags.includes(`v32ChromaticBalls`))RIFT_V32_EFFECT(run,attacker,`v32-chromatic-balls`,target?Oo(run,target):resolved?.aim?.target,{shape:`projectile`,motion:`burst`,radius:4,glyph:`彩`,name:`CHROMATIC BALLS`});
 if(tags.includes(`v32RoughBlast`))RIFT_V32_EFFECT(run,attacker,`v32-rough-blast`,target?Oo(run,target):null,{shape:`line`,radius:5,glyph:`昇`,name:`ROUGH BLAST`});
 if(tags.includes(`v32LuckyShot`))RIFT_V32_EFFECT(run,attacker,`v32-lucky-shot`,target?Oo(run,target):null,{shape:`line`,radius:6,glyph:`連`,name:`LUCKY SHOT`});
 if(tags.includes(`v32FeverPunch`))RIFT_V32_EFFECT(run,attacker,`v32-fever-punch`,target?Oo(run,target):null,{shape:`line`,radius:9,force:2.4,glyph:`熱`,name:`FEVER PUNCH`});
 if(Number(attacker.statuses.v32DomainTurns||0)>0&&action?.type===`special`&&!tags.includes(`v32LoveTrain`)&&!tags.includes(`bonusAction`)&&!tags.includes(`freeAction`)){attacker.statuses.v32DomainMoves=Number(attacker.statuses.v32DomainMoves||0)+1;RIFT_V32_LOG(run,`DOMAIN WAGER // Special ${attacker.statuses.v32DomainMoves}/2 committed toward the next roll.`,attacker);if(attacker.statuses.v32DomainMoves>=2)RIFT_V32_ROLL(run,attacker)}
 const failed=(run.logs||[]).filter(row=>!previousLogs.has(row.id)).some(row=>/\b(dodges|misses|missed|fails the roll|failed roll)\b/i.test(String(row.text||``)));if(failed&&!tags.includes(`v32TrainDoor`)&&!tags.includes(`v32LoveTrain`))RIFT_V32_FEVER(attacker,1,run,`${resolved.name||resolved.move?.name||`The wager`} lost an accuracy or dodge outcome`);
 if(Number(attacker.statuses.v32JackpotTurns||0)>0)attacker.energy=attacker.maxEnergy;RIFT_V32_SYNC_ROOT(run);return result};

const RIFT_V32_BASE_GI=Gi;
Gi=function RIFT_V32_ENCOUNTER(run,...args){const out=RIFT_V32_BASE_GI(run,...args);for(const entry of RIFT_V32_ENTRIES(run)){const fighter=entry.fighter;for(const key of Object.keys(fighter.statuses||{}))if(key.startsWith(`v32`))delete fighter.statuses[key];fighter.statuses.v32Fever=0;fighter.statuses.v32BattleFloor=run.floor;fighter.ultimate=100}RIFT_V32_BASS_STOP();RIFT_V32_SYNC_ROOT(run);return out};
const RIFT_V32_BASE_PT=Pt;
Pt=function RIFT_V32_TURN_START(run,actorId){const out=RIFT_V32_BASE_PT(run,actorId);RIFT_V32_PROCESS_DOORS(run);for(const entry of RIFT_V32_ENTRIES(run)){const fighter=entry.fighter;if(Number(fighter.statuses?.v32JackpotTurns||0)>0&&fighter.hp>0){fighter.energy=fighter.maxEnergy;if(fighter.statuses.v32JackpotRegenTurn!==run.turn){fighter.statuses.v32JackpotRegenTurn=run.turn;const before=fighter.hp;oo(fighter,Math.max(1,Math.round(fighter.maxHp*RIFT_V32_JACKPOT_REGEN)));if(fighter.hp>before)RIFT_V32_LOG(run,`JACKPOT REGENERATION // ${fighter.name} restores ${Math.round(fighter.hp-before)} HP. Anti-heal modifies this recovery normally.`,fighter)}}}RIFT_V32_SYNC_ROOT(run);return out};
const RIFT_V32_BASE_QO=Qo;
Qo=function RIFT_V32_TURN_END(run,fighter){const out=RIFT_V32_BASE_QO(run,fighter);for(const entry of RIFT_V32_ENTRIES(run)){const gambler=entry.fighter;if(Number(gambler.statuses?.v32DomainTurns||0)>0&&gambler.statuses.v32DomainStartedTurn!==run.turn&&gambler.statuses.v32DomainLastTick!==run.turn){gambler.statuses.v32DomainLastTick=run.turn;gambler.statuses.v32DomainTurns-=1;if(gambler.statuses.v32DomainTurns<=0){delete gambler.statuses.v32DomainTurns;delete gambler.statuses.v32DomainMoves;RIFT_V32_LOG(run,`PRIVATE PURE LOVE TRAIN ENDS // The final reel goes dark without Jackpot.`,gambler)}}if(Number(gambler.statuses?.v32JackpotTurns||0)>0&&gambler.statuses.v32JackpotStartedTurn!==run.turn&&gambler.statuses.v32JackpotLastTick!==run.turn){gambler.statuses.v32JackpotLastTick=run.turn;gambler.statuses.v32JackpotTurns-=1;if(gambler.statuses.v32JackpotTurns<=0){delete gambler.statuses.v32JackpotTurns;delete gambler.statuses.v32JackpotStartedTurn;gambler.ultimate=100;RIFT_V32_LOG(run,`JACKPOT ENDS // The green aura collapses. Private Pure Love Train returns to 100% Ultimate.`,gambler)}}}RIFT_V32_SYNC_ROOT(run);return out};

const RIFT_V32_BASE_IS=is;
is=function RIFT_V32_AI(fighter,target){if(RIFT_V32_IS(fighter)&&Number(fighter.ultimate||0)>=100&&!fighter.statuses?.v32DomainTurns&&!fighter.statuses?.v32JackpotTurns){const ultimate=La(fighter).find(action=>action.type===`ultimate`&&action.move?.tags?.includes(`v32LoveTrain`));if(ultimate)return ultimate}return RIFT_V32_BASE_IS(fighter,target)};
const RIFT_V32_BASE_JA=Ja;
Ja=function RIFT_V32_STATUS_LABELS(fighter){const base=RIFT_V32_BASE_JA(fighter);if(!RIFT_V32_IS(fighter))return base;const extra=[`FEVER ${Number(fighter.statuses?.v32Fever||0)}/${RIFT_V32_FEVER_MAX}`];if(fighter.statuses?.v32DomainTurns)extra.push(`LOVE TRAIN · ${fighter.statuses.v32DomainTurns}T · ${Number(fighter.statuses.v32DomainMoves||0)}/2`);if(fighter.statuses?.v32JackpotTurns)extra.push(`JACKPOT · ${fighter.statuses.v32JackpotTurns}T`);return[...extra,...base].slice(0,8)};
const RIFT_V32_BASE_STATUS_CLASSES=RIFT_V15_STATUS_CLASSES;
RIFT_V15_STATUS_CLASSES=function RIFT_V32_STATUS_CLASSES(fighter){const classes=RIFT_V32_BASE_STATUS_CLASSES(fighter);if(RIFT_V32_IS(fighter)){if(Number(fighter.statuses?.v32Fever||0)>0)classes.push(`v32-fever-live`);if(Number(fighter.statuses?.v32JackpotTurns||0)>0)classes.push(`v32-jackpot-live`)}return classes};
const RIFT_V32_BASE_CANVAS_CLASS=RIFT_V15_CANVAS_CLASS;
RIFT_V15_CANVAS_CLASS=function RIFT_V32_CANVAS_CLASS(battlefield){const base=RIFT_V32_BASE_CANVAS_CLASS(battlefield),run=globalThis.__RIFTBOUND_ACTIVE_RUN__,entries=RIFT_V32_ENTRIES(run);return`${base} ${entries.some(entry=>entry.fighter.statuses?.v32DomainTurns)?`v32-domain-map`:``} ${entries.some(entry=>entry.fighter.statuses?.v32JackpotTurns)?`v32-jackpot-map`:``}`.trim()};

function RIFT_V32_GAMBLER_HUD({fighter}){if(!RIFT_V32_IS(fighter))return null;const fever=Math.min(RIFT_V32_FEVER_MAX,Number(fighter.statuses?.v32Fever||0)),domain=Number(fighter.statuses?.v32DomainTurns||0),jackpot=Number(fighter.statuses?.v32JackpotTurns||0),last=fighter.statuses?.v32LastRoll==null?`---`:String(fighter.statuses.v32LastRoll).padStart(3,`0`);return(0,E.jsxs)(`section`,{className:`v32-gambler-hud ${jackpot?`jackpot`:domain?`domain`:``}`,style:{"--v32-fever":fever,"--v32-fever-ratio":fever/RIFT_V32_FEVER_MAX},"aria-live":`polite`,children:[(0,E.jsxs)(`header`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:jackpot?`RESTLESS GAMBLER · WINNING LINE`:domain?`PRIVATE PURE LOVE TRAIN · DOMAIN LIVE`:`RESTLESS GAMBLER · FEVER ENGINE`}),(0,E.jsx)(`strong`,{children:jackpot?`JACKPOT`:domain?`KEEP GAMBLING`:`BET YOUR LIFE`})]}),(0,E.jsx)(`b`,{children:jackpot?`${jackpot}T`:domain?`${domain}T`:`ULT ${Math.round(fighter.ultimate||0)}%`})]}),(0,E.jsxs)(`div`,{className:`v32-fever-track`,children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`FEVER`}),(0,E.jsxs)(`strong`,{children:[fever,` / `,RIFT_V32_FEVER_MAX]})]}),(0,E.jsx)(`i`,{children:Array.from({length:RIFT_V32_FEVER_MAX},(_,index)=>(0,E.jsx)(`b`,{className:index<fever?`filled`:``},index))}),(0,E.jsx)(`em`,{children:fever===RIFT_V32_FEVER_MAX?`NEXT DOMAIN GUARANTEED`:`+${Math.floor(fever/2)} PHYSICAL TIERS`})]}),(0,E.jsxs)(`div`,{className:`v32-roll-readout`,children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`LAST ROLL`}),(0,E.jsx)(`strong`,{children:last})]}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`NEXT ROLL`}),(0,E.jsxs)(`strong`,{children:[Number(fighter.statuses?.v32DomainMoves||0),` / 2 SPECIALS`]})]}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`JACKPOT LAW`}),(0,E.jsx)(`strong`,{children:jackpot?`FREE ENERGY · 3× MP · REGEN`:`XXX MATCHES`})]})]})]})}

const RIFT_V32_BASE_REQUIREMENTS=RIFT_V31_REQUIREMENTS;
RIFT_V31_REQUIREMENTS=function RIFT_V32_REQUIREMENTS(move,slot){const requirements=RIFT_V32_BASE_REQUIREMENTS(move,slot);if(move?.tags?.includes(`v32JackpotOnly`))requirements.splice(0,requirements.length,`Jackpot active`,`0 Energy`);return requirements};
const RIFT_V32_BASE_POWER_PROFILE=RIFT_V31_POWER_PROFILE;
RIFT_V31_POWER_PROFILE=function RIFT_V32_POWER_PROFILE(power,index){if(power?.name!==RIFT_V32_POWER_NAME)return RIFT_V32_BASE_POWER_PROFILE(power,index);const base={id:`power-${RIFT_V31_SLUG(power.name)}`,index,kind:`power`,kindLabel:`Special Power`,name:power.name,rarity:power.rarityLabel||power.rarity,glyph:power.glyph,accent:power.accent,rawDamageType:power.damageType,passive:power.passive,lore:power.codexDescription,personality:``,range:null,rollable:true,enemyRollable:true,source:power};return RIFT_V31_FINALIZE_PROFILE(base,[{id:`techniques`,label:`Technique Array`,detail:`Three Special techniques and the gambling Domain`,slots:[`M1`,`M2`,`M3`,`ULT`],moves:power.moves},{id:`jackpot`,label:`Jackpot Override`,detail:`Replaces the three Special techniques for twenty combatant turns`,slots:[`J1`,`J2`,`J3`],moves:RIFT_V32_JACKPOT_MOVES}])};
const RIFT_V32_PREVIEW_SPECS=Object.freeze([
 [`Chromatic Balls`,`projectile-multi`,`Aim line up to 42m`,`Three ricochet contacts roll one of six damage tiers`,`Minimum damage grants Fever`],
 [`Train Door`,`wall-point-delayed`,`Ground point within 30m`,`Raise a solid door with a one-turn warning`,`Door slams, Stuns caught enemies, then remains as cover`],
 [`Rough Blast`,`melee-rising-wave`,`Target within 6m`,`Rough-energy uppercut launches the target`,`Bleed becomes 6/6`],
 [`Private Pure Love Train`,`self-domain`,`Self`,`Expand a twelve-turn gambling domain`,`Every two Specials roll XXX; Maximum Fever guarantees Jackpot`,{rangeText:`SELF`,radiusText:`DOMAIN`}],
 [`Lucky Shot`,`melee-barrage-multi`,`Target within 6.5m`,`Eight rough-energy punches resolve in sequence`,`Each hit stacks Bleed`],
 [`Relentless Luck`,`teleport-strike-area`,`Target within 24m`,`Blink to the target and slam them down`,`A 7m shockwave damages nearby hostiles`],
 [`Fever Punch`,`melee-charge-strike-wave`,`Target within 7m`,`Compress the green aura into one punch`,`Massive damage, Guard Break, and knockback`],
]);
function RIFT_V32_INSTALL_PREVIEWS(catalog){const seenProfiles=new Set(),seenMoves=new Set();let installed=0;for(const profile of catalog.profiles){const specs=profile.name===RIFT_V32_POWER_NAME?RIFT_V32_PREVIEW_SPECS:RIFT_V311_PROFILE_SPECS[profile.name];if(!specs)throw new Error(`V32 missing profile preview contract: ${profile.name}`);if(specs.length!==profile.moves.length)throw new Error(`V32 preview count mismatch for ${profile.name}: ${specs.length}/${profile.moves.length}`);seenProfiles.add(profile.name);for(let index=0;index<profile.moves.length;index+=1){const move=profile.moves[index],preview=RIFT_V311_BUILD_PREVIEW(move,specs[index],profile);if(seenMoves.has(preview.key))throw new Error(`V32 duplicate preview contract: ${preview.key}`);seenMoves.add(preview.key);move.preview=preview;const definition=RIFT_V24_SPATIAL_TYPES[preview.primaryType]||RIFT_V24_SPATIAL_TYPES.target;move.spatial={...move.spatial,type:preview.primaryType,label:preview.label,glyph:definition.glyph,family:definition.family,coreShape:move.geometry.shape,presentationOnly:true,mechanicsChanged:false,previewVersion:RIFT_V311_PREVIEW_VERSION,previewRenderer:`v31-cinematic`};installed+=1}profile.spatialTypes=RIFT_V31_UNIQUE(profile.moves.map(move=>move.spatial.type));profile.searchText=[profile.searchText,...profile.moves.flatMap(move=>[move.preview.label,move.preview.acquisition,move.preview.resolution,move.preview.aftermath])].join(` `).toLowerCase()}const orphanProfiles=Object.keys(RIFT_V311_PROFILE_SPECS).filter(name=>!seenProfiles.has(name));if(orphanProfiles.length)throw new Error(`V32 orphan preview profiles: ${orphanProfiles.join(`, `)}`);if(installed!==catalog.totals.moves)throw new Error(`V32 preview coverage mismatch: ${installed}/${catalog.totals.moves}`);catalog.spatialTypes=RIFT_V31_UNIQUE(catalog.moves.map(move=>move.spatial.type)).sort();catalog.preview={version:RIFT_V311_PREVIEW_VERSION,patch:`V32`,explicit:installed,fallbacks:0,profiles:seenProfiles.size,patterns:RIFT_V31_UNIQUE(catalog.moves.map(move=>move.preview.pattern)).sort(),renderer:`v31-cinematic`,layout:`stable-dom`,mechanicsChanged:false};catalog.abilityChanges=4;return catalog.preview}
RIFT_V31_BUILD_CATALOG=function RIFT_V32_BUILD_CATALOG(...sources){const catalog=RIFT_V311_BASE_BUILD_CATALOG(...sources);RIFT_V32_INSTALL_PREVIEWS(catalog);return catalog};

const RIFT_V32_BASE_ROWS=RIFT_V21_ABILITY_ROWS().filter(row=>!(row.kind===`power`&&row.name===RIFT_V32_POWER_NAME));
const RIFT_V32_BASE_CONSTITUTION_HASH=RIFT_V21_HASH({contractVersion:1,capturedFrom:`V20.0.1`,abilities:RIFT_V32_BASE_ROWS});
const RIFT_V32_CONSTITUTION=RIFT_V21_ABILITY_CONSTITUTION();
const RIFT_V32_EXPECTED_HASH=RIFT_V32_CONSTITUTION.hash;
RIFT_V21_ASSERT_CONSTITUTION=function RIFT_V32_ASSERT_CONSTITUTION(){const current=RIFT_V21_ABILITY_CONSTITUTION();return{ok:current.hash===RIFT_V32_EXPECTED_HASH&&RIFT_V32_BASE_CONSTITUTION_HASH===`7598b438`,expected:RIFT_V32_EXPECTED_HASH,actual:current.hash,counts:current.counts,baseHash:RIFT_V32_BASE_CONSTITUTION_HASH,basePreserved:RIFT_V32_BASE_CONSTITUTION_HASH===`7598b438`}};
const RIFT_V32_BASE_VAULT_EXPORT=RIFT_V21_VAULT_EXPORT,RIFT_V32_BASE_VAULT_IMPORT=RIFT_V21_VAULT_IMPORT;
RIFT_V21_VAULT_EXPORT=function RIFT_V32_VAULT_EXPORT(){return{...RIFT_V32_BASE_VAULT_EXPORT(),version:32,constitutionHash:RIFT_V32_EXPECTED_HASH}};
RIFT_V21_VAULT_IMPORT=function RIFT_V32_VAULT_IMPORT(payload){if(payload?.constitutionHash&&!['7598b438',RIFT_V32_EXPECTED_HASH].includes(payload.constitutionHash))throw Error(`Save Vault ability constitution mismatch`);return RIFT_V32_BASE_VAULT_IMPORT({...payload,constitutionHash:`7598b438`})};
globalThis.RIFTBOUND_PRESERVATION={...globalThis.RIFTBOUND_PRESERVATION,version:32,constitution:()=>RIFT_V21_ABILITY_CONSTITUTION(),assert:RIFT_V21_ASSERT_CONSTITUTION,saves:{...globalThis.RIFTBOUND_PRESERVATION.saves,export:RIFT_V21_VAULT_EXPORT,import:RIFT_V21_VAULT_IMPORT}};
const RIFT_V32_CATALOG=RIFT_V31_BUILD_CATALOG();
globalThis.RIFTBOUND_CODEX={...globalThis.RIFTBOUND_CODEX,version:32,release:`Restless Gambler`,build:RIFT_V31_BUILD_CATALOG,catalog:()=>RIFT_V32_CATALOG,filter:criteria=>RIFT_V31_FILTER_CATALOG(RIFT_V32_CATALOG,criteria),profile:value=>RIFT_V32_CATALOG.profiles.find(profile=>profile.id===value||profile.name===value)||null,move:value=>RIFT_V32_CATALOG.moves.find(move=>move.id===value||move.name===value)||null,previewReport:()=>RIFT_V32_CATALOG.preview};

const RIFT_V32_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V32_NORMALIZE_RUN_BUILD(run){run=RIFT_V32_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(32,Number(run.riftboundSchemaVersion||0));run.v32RestlessGambler=run.v32RestlessGambler&&typeof run.v32RestlessGambler===`object`?run.v32RestlessGambler:{version:1};globalThis.__RIFTBOUND_ACTIVE_RUN__=run;return run};

function RIFT_V32_INSTALL_MUSIC_SETTING(){if(typeof document===`undefined`)return;if(RIFT_V20_ACCESS.jackpotMusic===undefined)RIFT_V20_SET_ACCESS(`jackpotMusic`,true);const panel=document.getElementById(`rift-v20-access-panel`);if(panel&&!panel.querySelector(`[data-setting="jackpotMusic"]`)){const label=document.createElement(`label`);label.innerHTML=`<span>JACKPOT BASS<small>Plays the synthesized winning-line bass during Restless Gambler's Jackpot.</small></span><input type="checkbox" data-setting="jackpotMusic">`;panel.insertBefore(label,panel.querySelector(`footer`));label.querySelector(`input`).checked=RIFT_V20_ACCESS.jackpotMusic!==false}document.addEventListener(`change`,event=>{if(event.target?.dataset?.setting!==`jackpotMusic`)return;event.target.checked?RIFT_V32_BASS_START():RIFT_V32_BASS_STOP()})}
globalThis.RIFTBOUND_RESTLESS_GAMBLER={version:32,power:RIFT_V32_POWER,jackpotMoves:RIFT_V32_JACKPOT_MOVES,constants:{feverMax:RIFT_V32_FEVER_MAX,domainTurns:RIFT_V32_DOMAIN_TURNS,domainCap:RIFT_V32_DOMAIN_CAP,jackpotTurns:RIFT_V32_JACKPOT_TURNS,jackpotRegen:RIFT_V32_JACKPOT_REGEN},fever:RIFT_V32_FEVER,startDomain:RIFT_V32_START_DOMAIN,startJackpot:RIFT_V32_START_JACKPOT,roll:RIFT_V32_ROLL,processDoors:RIFT_V32_PROCESS_DOORS,catalog:()=>RIFT_V32_CATALOG,constitution:()=>RIFT_V21_ASSERT_CONSTITUTION(),audio:{start:RIFT_V32_BASS_START,stop:RIFT_V32_BASS_STOP,state:RIFT_V32_BASS_STATE}};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:32,release:`V32 · Restless Gambler`,counts:{...globalThis.RIFTBOUND_MANIFEST.counts,powers:g.length},accessibility:[...new Set([...(globalThis.RIFTBOUND_MANIFEST.accessibility||[]),`jackpotMusic`])],preservation:{...globalThis.RIFTBOUND_MANIFEST.preservation,constitutionHash:RIFT_V32_EXPECTED_HASH,abilities:RIFT_V32_CONSTITUTION.counts.abilities,moves:RIFT_V32_CONSTITUTION.counts.moves,baseConstitutionHash:RIFT_V32_BASE_CONSTITUTION_HASH,existingAbilitiesPreserved:true},spatialGrammar:{...globalThis.RIFTBOUND_MANIFEST.spatialGrammar,moves:RIFT_V32_CONSTITUTION.counts.moves,typed:RIFT_V32_CONSTITUTION.counts.moves},codex:{...globalThis.RIFTBOUND_MANIFEST.codex,version:32,registeredPowers:RIFT_V32_CATALOG.totals.registeredPowers,visiblePowers:RIFT_V32_CATALOG.totals.visiblePowers,profiles:RIFT_V32_CATALOG.totals.profiles,displayedMoves:RIFT_V32_CATALOG.totals.moves,constitutionHash:RIFT_V32_EXPECTED_HASH,abilityChanges:4,previewPatch:`V32`,previewCoverage:RIFT_V32_CATALOG.preview.explicit,previewFallbacks:0},restlessGambler:{rarity:`Legendary`,feverMax:RIFT_V32_FEVER_MAX,domainTurns:RIFT_V32_DOMAIN_TURNS,domainCap:RIFT_V32_DOMAIN_CAP,jackpotTurns:RIFT_V32_JACKPOT_TURNS,jackpotRegen:RIFT_V32_JACKPOT_REGEN,tripleMovement:true,infiniteEnergy:true,antiHealCounterplay:true,oneShotCounterplay:true,jackpotMusicSetting:true,baseMoves:RIFT_V32_BASE_MOVES.map(move=>move.name),jackpotMoves:RIFT_V32_JACKPOT_MOVES.map(move=>move.name)}};
if(globalThis.RIFTBOUND_MANIFEST.remastered)globalThis.RIFTBOUND_MANIFEST.remastered={...globalThis.RIFTBOUND_MANIFEST.remastered,constitutionHash:RIFT_V32_EXPECTED_HASH,certified:RIFT_V21_ASSERT_CONSTITUTION().ok};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:32,restlessGambler:()=>({constitution:RIFT_V21_ASSERT_CONSTITUTION(),catalog:RIFT_V32_CATALOG.totals,preview:RIFT_V32_CATALOG.preview,audio:{active:RIFT_V32_BASS_STATE.active}})};
if(typeof window!==`undefined`){const boot=()=>{document.documentElement.classList.add(`riftbound-restless-gambler`);RIFT_V32_INSTALL_MUSIC_SETTING();RIFT_V32_SYNC_ROOT();const release=document.getElementById(`rift-v30-release-toggle`);if(release){release.textContent=`V32`;release.title=`Restless Gambler · Codex Ascendant foundation`}};document.readyState===`loading`?document.addEventListener(`DOMContentLoaded`,boot,{once:true}):boot()}
