const RIFT_V29_MARKER=`Riftbound Bound Together V29`;
const RIFT_V29_VERSION=29;
function RIFT_V29_BUILD_VIEW(fighter){return{items:(fighter?.inventory||[]).map((instance,slot)=>{const item=instance?RIFT_ITEM(instance.itemId):null;return{slot,itemId:item?.id||null,name:item?.name||null,rarity:item?.rarity||null,cooldown:item?.passiveId?Number(fighter.itemCooldowns?.[RIFT_ITEM_COOLDOWN_KEY(item)]||0):0}}),stats:RIFT_ITEM_STAT_TOTALS(fighter),warnings:RIFT_V18_BUILD_WARNINGS(fighter)}}
function RIFT_V29_TARGETS(run,actorId){return zi(run,actorId).filter(entry=>entry.fighter.hp>0).map(entry=>({id:entry.id,name:entry.fighter.name,hp:entry.fighter.hp,maxHp:entry.fighter.maxHp,position:P(W(run,entry.id)),distance:Math.round(I(W(run,actorId),W(run,entry.id))*10)/10}))}
function RIFT_V29_ACTION_VIEW(run,entry,action,busy=false){const base=RIFT_V20_ALLY_ACTIONS(run,busy).find(row=>row.id===action.id)||{},target=RIFT_V29_TARGETS(run,entry.id)[0]||null,geometry=Tt(action,entry.fighter),spatial=RIFT_V24_CLASSIFY(action,entry.fighter,geometry);return{...base,geometry:{core:geometry.shape,spatial:spatial.type,label:spatial.label,range:geometry.range,radius:geometry.radius,requiresAim:geometry.requiresAim},targetId:target?.id||base.targetId||null,target:target?.name||null}}
function RIFT_V29_SNAPSHOT_EXTRAS(run,context={}){const base=RIFT_V20_SNAPSHOT_EXTRAS(run,context),entry=U(run,RIFT_V20_ALLY_ID);if(!entry)return{...base,protocolVersion:3,sessionState:`waiting`,stateHash:RIFT_V22_STATE_HASH(run),targets:[],build:null};return{...base,protocolVersion:3,sessionState:base.canAct?`ready`:context.busy?`host-resolving`:`waiting`,stateHash:RIFT_V22_STATE_HASH(run),targets:RIFT_V29_TARGETS(run,entry.id),build:RIFT_V29_BUILD_VIEW(entry.fighter),actions:La(entry.fighter).slice(0,12).map(action=>RIFT_V29_ACTION_VIEW(run,entry,action,!!context.busy)),authority:{owner:`player-2`,resolver:`host`,actorId:RIFT_V20_ALLY_ID,oneActionPerTurn:true}}}
function RIFT_V29_DESYNC_REPORT(remoteHash,run){const localHash=RIFT_V22_STATE_HASH(run);return{ok:!remoteHash||remoteHash===localHash,remoteHash:remoteHash||null,localHash,turn:run?.turn||null,floor:run?.floor||null,recoverable:true}}
function RIFT_V29_SESSION_RECOVERY(run){return{version:29,at:Date.now(),stateHash:RIFT_V22_STATE_HASH(run),floor:run?.floor,turn:run?.turn,phase:run?.phase,ally:RIFT_V29_SNAPSHOT_EXTRAS(run),state:RIFT_V22_STATE_VIEW(run)}}
const RIFT_V29_BASE_APPLY_INTENT=RIFT_V20_APPLY_COOP_INTENT;
function RIFT_V29_APPLY_INTENT(intent,run,context={}){if(intent?.expectedStateHash&&intent.expectedStateHash!==RIFT_V22_STATE_HASH(run))return{ok:false,message:`STATE RESYNC REQUIRED`,desync:RIFT_V29_DESYNC_REPORT(intent.expectedStateHash,run)};const result=RIFT_V29_BASE_APPLY_INTENT(intent,run,context);if(result?.ok)RIFT_V22_EVENT_BUS.emit(`STATE_COMMITTED`,{source:`coop-intent`,intentId:intent.id,stateHash:RIFT_V22_STATE_HASH(run)});return result}
const RIFT_V29_COOP_BRIDGE=Object.freeze({version:29,protocolVersion:3,snapshotExtras:RIFT_V29_SNAPSHOT_EXTRAS,applyIntent:RIFT_V29_APPLY_INTENT,recovery:RIFT_V29_SESSION_RECOVERY,desync:RIFT_V29_DESYNC_REPORT});
const RIFT_V29_BASE_COOP_EXPOSE=RIFT_V20_COOP_EXPOSE;
RIFT_V20_COOP_EXPOSE=function RIFT_V29_COOP_EXPOSE(run,onAction,selectedActionId,busy,commit){const coop=globalThis.RIFT_COOP;coop?.registerGameBridge?.(RIFT_V29_COOP_BRIDGE);RIFT_V20_SCHEDULE_ALLY_SYNC(run,commit);return null};
const RIFT_V29_BASE_NORMALIZE_RUN_BUILD=RIFT_NORMALIZE_RUN_BUILD;
RIFT_NORMALIZE_RUN_BUILD=function RIFT_V29_NORMALIZE_RUN_BUILD(run){run=RIFT_V29_BASE_NORMALIZE_RUN_BUILD(run);if(!run||typeof run!==`object`)return run;run.riftboundSchemaVersion=Math.max(29,Number(run.riftboundSchemaVersion||0));run.v29Coop=run.v29Coop&&typeof run.v29Coop===`object`?run.v29Coop:{protocolVersion:3,lastRecovery:null,lastDesync:null};run.v29Coop.protocolVersion=3;return run};
globalThis.RIFTBOUND_COOP_V29={version:29,protocolVersion:3,bridge:RIFT_V29_COOP_BRIDGE,recovery:RIFT_V29_SESSION_RECOVERY,desync:RIFT_V29_DESYNC_REPORT};
globalThis.RIFTBOUND_MANIFEST={...globalThis.RIFTBOUND_MANIFEST,schemaVersion:29,release:`V29 · Bound Together`,coop:{protocolVersion:3,authority:`host`,partnerActor:RIFT_V20_ALLY_ID,reconnect:true,recovery:true,resync:true,desyncDetection:true,ackHistory:true,networkHealth:true,hostMigration:`research`,transport:[`LAN`,`loopback`]}};
if(globalThis.RIFTBOUND_DIAGNOSTICS)globalThis.RIFTBOUND_DIAGNOSTICS={...globalThis.RIFTBOUND_DIAGNOSTICS,version:29,coop:()=>({active:RIFT_V20_COOP_ACTIVE(),protocolVersion:3,run:globalThis.__RIFTBOUND_ACTIVE_RUN__?RIFT_V29_SESSION_RECOVERY(globalThis.__RIFTBOUND_ACTIVE_RUN__):null})};
