const RIFT_V29_MARKER=`Riftbound Bound Together V29`;
const RIFT_V29_NETWORK={protocolVersion:3,connectedAt:0,lastEventAt:0,lastSnapshotAt:0,lastHeartbeatAt:0,latency:null,reconnects:0,resyncs:0,ackHistory:[],lastStateHash:null,remoteStateHash:null};
function v29Age(at){if(!at)return`—`;const seconds=Math.max(0,Math.round((Date.now()-at)/1000));return seconds<2?`NOW`:`${seconds}s`}
function renderNetworkHealth(){const online=$('rift-coop-online');if(!online)return;let root=$('rift-v29-network');if(!root){root=document.createElement('section');root.id='rift-v29-network';root.className='rift-v29-network';online.appendChild(root)}const health=state.connected?state.eventSource?.readyState===1?`ONLINE`:`RECONNECTING`:`OFFLINE`,remote=state.remoteSnapshot?.state?.coop?.stateHash||state.remoteSnapshot?.stateHash||null;RIFT_V29_NETWORK.remoteStateHash=remote;root.innerHTML=`<span><small>NETWORK</small><b>${health}</b></span><span><small>LATENCY</small><b>${RIFT_V29_NETWORK.latency==null?'WAITING':`${RIFT_V29_NETWORK.latency}ms`}</b></span><span><small>SNAPSHOT</small><b>${v29Age(RIFT_V29_NETWORK.lastSnapshotAt)}</b></span><span><small>STATE</small><b>${remote?String(remote).slice(0,8):'WAITING'}</b></span><button type="button" data-v29-resync>REQUEST FULL RESYNC</button><div class="rift-v29-ack-history">${RIFT_V29_NETWORK.ackHistory.slice(-6).reverse().map(row=>`<article class="${row.ok?'ok':'bad'}"><b>${escapeHtml(row.message)}</b><span>${v29Age(row.at)}</span></article>`).join('')}</div>`}
function v29AbsorbResults(rows=[]){for(const result of rows)if(result&&!RIFT_V29_NETWORK.ackHistory.some(row=>row.intentId===result.intentId))RIFT_V29_NETWORK.ackHistory.push({intentId:result.intentId,ok:result.ok,message:result.message,at:result.at||Date.now()});if(RIFT_V29_NETWORK.ackHistory.length>30)RIFT_V29_NETWORK.ackHistory.splice(0,RIFT_V29_NETWORK.ackHistory.length-30)}
async function resyncNow(){if(!state.room)return;try{const data=await request(`/rooms/${state.room.id}/resync`,{method:'POST',headers:authHeaders(),body:'{}'});state.room=data.room;state.remoteSnapshot=data.snapshot;state.lastSnapshotRevision=data.snapshotRevision||0;v29AbsorbResults(data.intentResults);RIFT_V29_NETWORK.resyncs+=1;RIFT_V29_NETWORK.lastSnapshotAt=Date.now();render();renderNetworkHealth();setStatus(`Full authoritative state received.`)}catch(error){setStatus(`Resync failed: ${error.message}`,true)}}
document.addEventListener('click',event=>{if(event.target.closest('[data-v29-resync]'))resyncNow()});
const RIFT_V29_BASE_RENDER=render;render=function RIFT_V29_RENDER(){const out=RIFT_V29_BASE_RENDER();renderNetworkHealth();return out};
const RIFT_V29_BASE_CONNECT=connectSession;connectSession=function RIFT_V29_CONNECT(data){RIFT_V29_NETWORK.connectedAt=Date.now();return RIFT_V29_BASE_CONNECT(data)};
const RIFT_V29_BASE_HEARTBEAT=startHeartbeat;startHeartbeat=function RIFT_V29_HEARTBEAT(){clearInterval(state.heartbeatTimer);state.heartbeatTimer=setInterval(async()=>{if(!state.room)return;const started=performance.now();try{const data=await request(`/rooms/${state.room.id}/heartbeat`,{method:'POST',headers:authHeaders(),body:'{}'});RIFT_V29_NETWORK.latency=Math.max(0,Math.round(performance.now()-started));RIFT_V29_NETWORK.lastHeartbeatAt=Date.now();state.room=data.room;render()}catch(error){setStatus(`Connection: ${error.message}`,true)}},5000)};
const RIFT_V29_BASE_REFRESH=refreshState;refreshState=async function RIFT_V29_REFRESH(){const out=await RIFT_V29_BASE_REFRESH();RIFT_V29_NETWORK.lastSnapshotAt=Date.now();renderNetworkHealth();return out};
const RIFT_V29_BASE_HANDLE_INTENT=handleIntent;handleIntent=async function RIFT_V29_HANDLE_INTENT(intent){RIFT_V29_NETWORK.lastEventAt=Date.now();return RIFT_V29_BASE_HANDLE_INTENT(intent)};
const RIFT_V29_BASE_SEND_INTENT=sendIntent;sendIntent=async function RIFT_V29_SEND_INTENT(type,payload={}){const remoteHash=state.remoteSnapshot?.state?.coop?.stateHash||state.remoteSnapshot?.stateHash||null;return RIFT_V29_BASE_SEND_INTENT(type,{...payload,expectedStateHash:remoteHash})};
const RIFT_V29_BASE_SET_STATUS=setStatus;setStatus=function RIFT_V29_STATUS(message,danger=false){if(/reconnect/i.test(message))RIFT_V29_NETWORK.reconnects+=1;if(/sync online/i.test(message))RIFT_V29_NETWORK.lastEventAt=Date.now();RIFT_V29_BASE_SET_STATUS(message,danger);renderNetworkHealth()};
const RIFT_V29_BASE_RESUME=resumeSession;resumeSession=async function RIFT_V29_RESUME(){await RIFT_V29_BASE_RESUME();if(!state.connected||!state.room)return;try{const data=await request(`/rooms/${state.room.id}/recovery`,{headers:authHeaders()});state.room=data.room;state.remoteSnapshot=data.snapshot;state.lastSnapshotRevision=data.snapshotRevision||0;v29AbsorbResults(data.intentResults);RIFT_V29_NETWORK.lastSnapshotAt=Date.now();render()}catch(error){setStatus(`Recovery failed: ${error.message}`,true)}};
const RIFT_V29_BASE_ALLY=renderAllyController;renderAllyController=function RIFT_V29_ALLY(snapshot){RIFT_V29_BASE_ALLY(snapshot);const root=$('rift-coop-ally'),coop=snapshot?.coop;if(!root||!coop?.ally)return;const build=(coop.build?.items||[]).filter(item=>item?.itemId).map(item=>`<span><small>${item.slot===0?'W':item.slot}</small><b>${escapeHtml(item.name)}</b></span>`).join(''),targets=(coop.targets||[]).map(target=>`<span><b>${escapeHtml(target.name)}</b><small>${Math.round(target.hp)}/${Math.round(target.maxHp)} HP · ${target.distance}m</small></span>`).join(''),actions=(coop.actions||[]).map(action=>`<span><b>${escapeHtml(action.name)}</b><small>${escapeHtml(action.geometry?.label||action.geometry?.core||'TARGET')} · ${Number(action.geometry?.range||0).toFixed(1)}m${action.reason?` · ${escapeHtml(action.reason)}`:''}</small></span>`).join('');root.insertAdjacentHTML('beforeend',`<section class="rift-v29-partner-detail"><header><small>AUTHORITY</small><b>${escapeHtml(coop.sessionState||'waiting').toUpperCase()}</b><span>${escapeHtml(coop.authority?.resolver||'host').toUpperCase()} RESOLVES</span></header><div class="rift-v29-loadout">${build||'<em>NO LOADOUT DATA</em>'}</div><div class="rift-v29-targets">${targets||'<em>NO VISIBLE TARGETS</em>'}</div><div class="rift-v29-geometry">${actions}</div></section>`)};
setInterval(()=>{const result=state.lastIntentResult;if(result)v29AbsorbResults([result]);renderNetworkHealth()},1000);
Object.assign(coopApi,{network:RIFT_V29_NETWORK,resync:resyncNow,ackHistory:()=>[...RIFT_V29_NETWORK.ackHistory]});
