const RIFT_V17_ARMORY_MARKER=`Riftbound Armory Reforged V17`;
const RIFT_V17_ARMORY_MODES=[[`build`,`BUILD`],[`browse`,`BROWSE`],[`craft`,`CRAFT`],[`inventory`,`INVENTORY`],[`favorites`,`FAVORITES`]];
function RIFT_V17_DEFAULT_ARMORY(catalog=[]){return{mode:`build`,query:``,category:`All`,rarity:`All`,stat:`All`,sort:`Recommended`,selectedId:catalog[0]?.id||null,archetypeId:`signature`,catalogScroll:0}}
function RIFT_V17_ARMORY_MEMORY(run,owner,catalog=[]){RIFT_NORMALIZE_RUN_BUILD(run);let current=run.v17Armory[owner];if(!current||typeof current!==`object`)current=RIFT_V17_DEFAULT_ARMORY(catalog);else current={...RIFT_V17_DEFAULT_ARMORY(catalog),...current};run.v17Armory[owner]=current;return current}
function RIFT_V17_STAT_MATCH(item,stat){return stat===`All`||(stat===`AS`&&(item.stats?.as||0)>0)||(stat===`AP`&&(item.stats?.ap||0)>0)||(stat===`Defense`&&((item.stats?.durability||0)>0||(item.stats?.regeneration||0)>0))||(stat===`Utility`&&[`speed`,`energy`,`range`,`battleIq`,`iq`,`combatSkill`].some(key=>(item.stats?.[key]||0)>0))}
function RIFT_V17_SORT_ITEMS(items,sort,fighter,shards){return[...items].sort((a,b)=>{
 const pa=RIFT_RECIPE_PLAN(fighter,a.id),pb=RIFT_RECIPE_PLAN(fighter,b.id),ca=pa.ok?pa.cost:a.price,cb=pb.ok?pb.cost:b.price;
 if(sort===`Affordable`)return +(cb<=shards)-+(ca<=shards)||ca-cb||a.name.localeCompare(b.name);
 if(sort===`Components`)return (pb.consumeUids?.length||0)-(pa.consumeUids?.length||0)||ca-cb;
 if(sort===`Price Low`)return ca-cb||a.name.localeCompare(b.name);
 if(sort===`Price High`)return cb-ca||a.name.localeCompare(b.name);
 if(sort===`Name`)return a.name.localeCompare(b.name);
 const sa=typeof RIFT_V18_ITEM_SCORE===`function`?RIFT_V18_ITEM_SCORE(fighter,a,{plan:pa,shards}):0,sb=typeof RIFT_V18_ITEM_SCORE===`function`?RIFT_V18_ITEM_SCORE(fighter,b,{plan:pb,shards}):0;
 return sb-sa||ca-cb||a.name.localeCompare(b.name)
})}
function RIFT_V17_BUILD_DOCK({fighter}){let inventory=Array.isArray(fighter?.inventory)?fighter.inventory:Array(6).fill(null);return (0,E.jsx)(`div`,{className:`v17-build-dock`,children:Array.from({length:6},(_,slot)=>{let instance=inventory[slot],item=instance?RIFT_ITEM(instance.itemId):null;return(0,E.jsxs)(`div`,{className:`v17-dock-slot ${item?`filled`:`empty`} ${slot===0?`weapon`:``}`,title:item?.name||`Empty slot ${slot+1}`,children:[(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`tiny`}),(0,E.jsx)(`b`,{children:slot===0?`W`:slot+1}),(0,E.jsx)(`span`,{children:item?.name||`EMPTY`})]},slot)})})}
function RIFT_V17_ITEM_CARD({item,fighter,selected,favorite,onInspect,onBuy,onFavorite}){
 const plan=RIFT_RECIPE_PLAN(fighter,item.id),owned=RIFT_OWNS_ITEM(fighter,item.id),score=typeof RIFT_V18_ITEM_SCORE===`function`?RIFT_V18_ITEM_SCORE(fighter,item,{plan}):0;
 return (0,E.jsxs)(`article`,{className:`v17-item-card rarity-${item.rarity.toLowerCase()} ${selected?`selected`:``} ${owned?`owned`:``}`,style:{"--v17-item":item.accent},children:[
  (0,E.jsx)(`button`,{type:`button`,className:`v17-card-main`,onClick:()=>onInspect(item.id),children:[(0,E.jsx)(RIFT_V166_CATALOG_ICON,{item}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`${item.rarity} · ${item.category}`}),(0,E.jsx)(`strong`,{children:item.name}),(0,E.jsx)(`em`,{children:RIFT_ITEM_STAT_TEXT(item)})]})]}),
  (0,E.jsx)(`button`,{type:`button`,className:`v17-card-favorite`,title:favorite?`Remove favorite`:`Add favorite`,onClick:()=>onFavorite(item.id),children:favorite?`★`:`☆`}),
  (0,E.jsxs)(`footer`,{children:[(0,E.jsxs)(`span`,{children:[owned?`OWNED`:plan.consumeUids?.length?`${plan.consumeUids.length} COMPONENT${plan.consumeUids.length===1?``:`S`}`:score>=20?`STRONG FIT`:`AVAILABLE`,(0,E.jsxs)(`b`,{children:[plan.ok?plan.cost:item.price,` ◆`]})]}),(0,E.jsx)(`button`,{type:`button`,disabled:!plan.ok,onClick:()=>onBuy(item.id),children:plan.ok?(item.recipe?.length?`BUILD`:`BUY`):`LOCKED`})]})
 ]})
}
const RIFT_V17_ITEM_CARD_MEMO=(0,r.memo)(RIFT_V17_ITEM_CARD);
function RIFT_V17_VIRTUAL_CATALOG({items,fighter,selectedId,favorites,onInspect,onBuy,onFavorite,memory}){
 const ref=(0,r.useRef)(null),raf=(0,r.useRef)(0),[box,setBox]=(0,r.useState)(()=>({top:Number(memory?.catalogScroll||0),height:640,width:760}));
 const read=()=>{let el=ref.current;if(!el)return;setBox(prev=>{let next={top:el.scrollTop,height:el.clientHeight||640,width:el.clientWidth||760};return Math.abs(prev.top-next.top)<1&&prev.height===next.height&&prev.width===next.width?prev:next})};
 (0,r.useEffect)(()=>{let el=ref.current;if(!el)return;el.scrollTop=Number(memory?.catalogScroll||0);read();let ro=typeof ResizeObserver!==`undefined`?new ResizeObserver(read):null;ro?.observe(el);return()=>{ro?.disconnect();if(raf.current)(globalThis.cancelAnimationFrame||clearTimeout)(raf.current)}},[memory]);
 const onScroll=event=>{if(memory)memory.catalogScroll=event.currentTarget.scrollTop;if(raf.current)return;let schedule=globalThis.requestAnimationFrame||(fn=>setTimeout(fn,16));raf.current=schedule(()=>{raf.current=0;read()})};
 const cols=Math.max(2,Math.min(5,Math.floor(Math.max(300,box.width-12)/154))),rowH=154,rows=Math.ceil(items.length/cols),from=Math.max(0,Math.floor((box.top-180)/rowH)),to=Math.min(rows,Math.ceil((box.top+box.height+180)/rowH));
 let mounted=[];for(let row=from;row<to;row+=1)mounted.push({row,items:items.slice(row*cols,row*cols+cols)});
 return (0,E.jsx)(`div`,{ref,className:`v17-virtual-catalog`,onScroll,children:(0,E.jsx)(`div`,{className:`v17-virtual-space`,style:{height:Math.max(1,rows*rowH)},children:mounted.map(entry=>(0,E.jsx)(`div`,{className:`v17-virtual-row`,style:{top:entry.row*rowH,gridTemplateColumns:`repeat(${cols},minmax(0,1fr))`},children:entry.items.map(item=>(0,E.jsx)(RIFT_V17_ITEM_CARD_MEMO,{item,fighter,selected:selectedId===item.id,favorite:favorites.has(item.id),onInspect,onBuy,onFavorite},item.id))},entry.row))})})
}
function RIFT_V17_INSPECTOR({item,fighter,plan,onBuy,onInspect,onRecipeBuy,favorite,onFavorite}){
 const [tab,setTab]=(0,r.useState)(`overview`);(0,r.useEffect)(()=>setTab(`overview`),[item?.id]);if(!item)return (0,E.jsx)(`aside`,{className:`v17-inspector empty`,children:`Choose an item.`});
 const upgrades=RIFT_SHOP_PERF_BUILDS_INTO(item.id),owned=RIFT_OWNS_ITEM(fighter,item.id);
 return (0,E.jsxs)(`aside`,{className:`v17-inspector rarity-${item.rarity.toLowerCase()}`,style:{"--v17-detail":item.accent},children:[
  (0,E.jsxs)(`header`,{children:[(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`hero`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`${item.rarity} · ${item.category}`}),(0,E.jsx)(`h3`,{children:item.name}),(0,E.jsx)(`em`,{children:item.reference||`Riftbound Original`})]}),(0,E.jsx)(`button`,{type:`button`,onClick:onFavorite,children:favorite?`★`:`☆`})]}),
  (0,E.jsx)(`nav`,{children:[[`overview`,`OVERVIEW`],[`recipe`,`RECIPE`],[`upgrades`,`UPGRADES`],[`lore`,`LORE`]].map(([id,label])=>(0,E.jsx)(`button`,{type:`button`,className:tab===id?`active`:``,onClick:()=>setTab(id),children:label},id))}),
  (0,E.jsxs)(`div`,{className:`v17-inspector-scroll`,children:[tab===`overview`&&(0,E.jsxs)(E.Fragment,{children:[(0,E.jsx)(RIFT_ITEM_STATS,{item}),(0,E.jsx)(RIFT_ITEM_STAT_PREVIEW,{item,fighter,plan}),(0,E.jsxs)(`section`,{className:`v17-passive`,children:[(0,E.jsx)(`small`,{children:item.passiveId?`UNIQUE PASSIVE`:`ITEM PROPERTY`}),(0,E.jsx)(`strong`,{children:item.passiveId?item.passiveId.replace(/([A-Z])/g,` $1`).toUpperCase():`SPECIALIZED COMPONENT`}),(0,E.jsx)(`p`,{children:item.passive}),(0,E.jsxs)(`footer`,{children:[(0,E.jsxs)(`span`,{children:[`TRIGGER · `,RIFT_ITEM_TRIGGER_LABEL(item)]}),item.cooldown>0&&(0,E.jsxs)(`span`,{children:[`COOLDOWN · `,item.cooldown,`T`]})]})]})]}),tab===`recipe`&&(0,E.jsx)(RIFT_V16_RECIPE_VIEW,{item,fighter,onSelect:onInspect,onBuy:onRecipeBuy,onHover:()=>{}}),tab===`upgrades`&&(0,E.jsx)(`section`,{className:`v17-upgrades`,children:upgrades.length?upgrades.map(next=>(0,E.jsxs)(`button`,{type:`button`,onClick:()=>onInspect(next.id),children:[(0,E.jsx)(RIFT_ITEM_ICON,{item:next,size:`tiny`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`strong`,{children:next.name}),(0,E.jsxs)(`small`,{children:[next.rarity,` · `,next.price,` ◆`]})]})]},next.id)):(0,E.jsx)(`p`,{children:`No direct upgrade. This is a finished branch.`})}),tab===`lore`&&(0,E.jsxs)(`blockquote`,{children:[`“`,item.lore,`”`]})]}),
  (0,E.jsxs)(`footer`,{className:`v17-buy-bar`,children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:owned?`OWNED`:plan.consumeUids?.length?`${plan.consumeUids.length} OWNED COMPONENTS APPLIED`:`TOTAL COST`}),(0,E.jsxs)(`strong`,{children:[plan.ok?plan.cost:item.price,` ◆`]})]}),(0,E.jsx)(`button`,{type:`button`,disabled:!plan.ok,onClick:onBuy,children:plan.ok?(item.recipe?.length?`BUILD ITEM`:`BUY ITEM`):plan.reason||`UNAVAILABLE`})]})
 ]})
}
function RIFT_V17_BUILD_HOME({fighter,run,archetypeId,onArchetype,onInspect,onBuy}){
 let archetypes=typeof RIFT_V18_ARCHETYPES===`function`?RIFT_V18_ARCHETYPES(fighter,RIFT_ITEM_CATALOG,run.shards||0):[{id:`signature`,name:`Signature`,description:`The authored six-item identity for this power.`,items:(RIFT_V16_GUIDE(fighter)?.core||[]).map(RIFT_ITEM).filter(Boolean)}],active=archetypes.find(path=>path.id===archetypeId)||archetypes[0],owned=new Set(RIFT_ITEM_INSTANCES(fighter).map(x=>x.itemId)),next=active.items.find(item=>!owned.has(item.id)),warnings=typeof RIFT_V18_BUILD_WARNINGS===`function`?RIFT_V18_BUILD_WARNINGS(fighter):[];
 return (0,E.jsxs)(`section`,{className:`v17-build-home`,children:[(0,E.jsxs)(`header`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`BUILD COMMAND`}),(0,E.jsx)(`h2`,{children:RIFT_V16_IDENTITY(fighter)}),(0,E.jsx)(`p`,{children:`Choose a direction. The Armory adapts targets to your current six slots and Shards.`})]}),(0,E.jsxs)(`strong`,{children:[owned.size,` / 6 SLOTS · ◆ `,run.shards||0]})]}),(0,E.jsx)(`div`,{className:`v17-archetypes`,children:archetypes.map(path=>(0,E.jsxs)(`button`,{type:`button`,className:path.id===active.id?`active`:``,onClick:()=>onArchetype(path.id),children:[(0,E.jsx)(`small`,{children:path.label||`BUILD PATH`}),(0,E.jsx)(`strong`,{children:path.name}),(0,E.jsx)(`span`,{children:path.description})]},path.id))}),(0,E.jsxs)(`div`,{className:`v17-next-target`,children:[(0,E.jsx)(`small`,{children:`NEXT TARGET`}),(0,E.jsx)(`strong`,{children:next?.name||`BUILD COMPLETE`}),(0,E.jsx)(`span`,{children:next?`${RIFT_RECIPE_PLAN(fighter,next.id).cost} ◆ · ${RIFT_ITEM_STAT_TEXT(next)}`:`All six targets are owned. Refine alternatives or begin another path.`}),next&&(0,E.jsxs)(`div`,{children:[(0,E.jsx)(`button`,{type:`button`,onClick:()=>onInspect(next.id),children:`INSPECT`}),(0,E.jsx)(`button`,{type:`button`,disabled:RIFT_RECIPE_PLAN(fighter,next.id).cost>(run.shards||0),onClick:()=>onBuy(next.id),children:`BUILD NOW`})]})]}),(0,E.jsx)(`div`,{className:`v17-path-items`,children:active.items.map((item,index)=>{let plan=RIFT_RECIPE_PLAN(fighter,item.id),isOwned=owned.has(item.id);return(0,E.jsxs)(`article`,{className:`${isOwned?`owned`:``} ${item.id===next?.id?`next`:``}`,children:[(0,E.jsx)(`b`,{children:String(index+1).padStart(2,`0`)}),(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`small`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`strong`,{children:item.name}),(0,E.jsx)(`small`,{children:isOwned?`OWNED`:plan.ok?`${plan.cost} ◆`:`UNAVAILABLE`})]}),(0,E.jsx)(`button`,{type:`button`,onClick:()=>onInspect(item.id),children:`VIEW`})]},item.id)})}),warnings.length>0&&(0,E.jsx)(`div`,{className:`v17-build-warnings`,children:warnings.map((warning,index)=>(0,E.jsxs)(`p`,{children:[(0,E.jsx)(`b`,{children:`!`}),(0,E.jsx)(`span`,{children:warning})]},index))})]})
}
function RIFT_V17_CRAFT_HOME({item,fighter,plan,onInspect,onBuy}){if(!item)return null;let missing=[...new Set(plan?.missing||[])].map(RIFT_ITEM).filter(Boolean);return (0,E.jsxs)(`section`,{className:`v17-craft-home`,children:[(0,E.jsxs)(`header`,{children:[(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`hero`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`PINNED CRAFT`}),(0,E.jsx)(`h2`,{children:item.name}),(0,E.jsxs)(`p`,{children:[plan?.consumeUids?.length||0,` owned components · `,missing.length,` missing component types`]})]}),(0,E.jsxs)(`strong`,{children:[plan?.cost??item.price,` ◆`]})]}),(0,E.jsxs)(`div`,{className:`v17-craft-summary`,children:[(0,E.jsx)(`span`,{children:`The smart plan consumes exact owned instances and purchases only what remains.`}),(0,E.jsx)(`button`,{type:`button`,disabled:!plan?.ok,onClick:()=>onBuy(item.id),children:plan?.ok?`COMPLETE ITEM`:(plan?.reason||`UNAVAILABLE`)})]}),(0,E.jsx)(RIFT_V16_RECIPE_VIEW,{item,fighter,onSelect:onInspect,onBuy:id=>onBuy(id),onHover:()=>{}}),missing.length>0&&(0,E.jsxs)(`section`,{className:`v17-missing`,children:[(0,E.jsx)(`h3`,{children:`MISSING COMPONENTS`}),(0,E.jsx)(`div`,{children:missing.map(component=>(0,E.jsxs)(`button`,{type:`button`,onClick:()=>onInspect(component.id),children:[(0,E.jsx)(RIFT_ITEM_ICON,{item:component,size:`tiny`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`strong`,{children:component.name}),(0,E.jsxs)(`small`,{children:[component.price,` ◆ · `,component.rarity]})]})]},component.id))})]})]})}
function RIFT_V17_INVENTORY_HOME({run,fighter,rikaShop,onCommit}){let warnings=typeof RIFT_V18_BUILD_WARNINGS===`function`?RIFT_V18_BUILD_WARNINGS(fighter):[];return(0,E.jsxs)(`section`,{className:`v17-inventory-home`,children:[(0,E.jsxs)(`header`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`SIX-SLOT WORKBENCH`}),(0,E.jsx)(`h2`,{children:`Inventory & Loadout`}),(0,E.jsx)(`p`,{children:`Equip, reorder, replace, or sell without leaving the Armory.`})]}),(0,E.jsx)(`strong`,{children:RIFT_ITEM_STAT_TEXT({stats:RIFT_ITEM_STAT_TOTALS(fighter)})})]}),rikaShop?(0,E.jsx)(RIFT_V13_RIKA_INVENTORY_MANAGER,{run,onCommit}):(0,E.jsx)(RIFT_INVENTORY_MANAGER_MEMO,{run,onCommit}),warnings.length>0&&(0,E.jsx)(`div`,{className:`v17-build-warnings`,children:warnings.map((warning,index)=>(0,E.jsxs)(`p`,{children:[(0,E.jsx)(`b`,{children:`!`}),(0,E.jsx)(`span`,{children:warning})]},index))})]})}
RIFT_ITEM_SHOP=function RIFT_V17_ITEM_SHOP({run,onCommit}){
 RIFT_NORMALIZE_RUN_BUILD(run);const initialOwner=RIFT_CURSED_CHILD(run.player)?run.v16ArmoryOwner||`yuta`:`yuta`,[owner,setOwner]=(0,r.useState)(initialOwner),rikaShop=RIFT_CURSED_CHILD(run.player)&&owner===`rika`,fighter=rikaShop?RIFT_V13_RIKA_SHOP_FIGHTER(run):run.player,catalog=(0,r.useMemo)(()=>RIFT_SHOP_OFFERS(run.floor,fighter),[run.floor,fighter]),initial=RIFT_V17_ARMORY_MEMORY(run,owner,catalog),launchRef=(0,r.useRef)(null),searchRef=(0,r.useRef)(null);
 const [open,setOpen]=(0,r.useState)(false),[mode,setMode]=(0,r.useState)(initial.mode),[query,setQuery]=(0,r.useState)(initial.query),[category,setCategory]=(0,r.useState)(initial.category),[rarity,setRarity]=(0,r.useState)(initial.rarity),[stat,setStat]=(0,r.useState)(initial.stat),[sort,setSort]=(0,r.useState)(initial.sort),[selectedId,setSelectedId]=(0,r.useState)(initial.selectedId||catalog[0]?.id),[archetypeId,setArchetypeId]=(0,r.useState)(initial.archetypeId||`signature`),[feedback,setFeedback]=(0,r.useState)(null),[favoriteVersion,setFavoriteVersion]=(0,r.useState)(0);
 const memory=RIFT_V17_ARMORY_MEMORY(run,owner,catalog),favorites=(0,r.useMemo)(()=>RIFT_V16_FAVORITE_IDS(fighter),[fighter,favoriteVersion]),selected=RIFT_ITEM(selectedId)||catalog[0]||null,plan=(0,r.useMemo)(()=>selected?RIFT_RECIPE_PLAN(fighter,selected.id):null,[fighter,selected?.id]),needle=query.trim().toLowerCase(),filtered=(0,r.useMemo)(()=>RIFT_V17_SORT_ITEMS(catalog.filter(item=>(mode!==`favorites`||favorites.has(item.id))&&(category===`All`||item.category===category)&&(rarity===`All`||item.rarity===rarity)&&RIFT_V17_STAT_MATCH(item,stat)&&(!needle||RIFT_SHOP_PERF_SEARCH_TEXT(item).includes(needle))),sort,fighter,run.shards||0),[catalog,mode,favorites,category,rarity,stat,needle,sort,fighter,run.shards]);
 const persist=()=>Object.assign(memory,{mode,query,category,rarity,stat,sort,selectedId,archetypeId});(0,r.useEffect)(()=>{persist()},[mode,query,category,rarity,stat,sort,selectedId,archetypeId,owner]);
 const close=()=>{persist();RIFT_V16_SAFE_SAVE(run);setOpen(false);setFeedback(null);try{setTimeout(()=>launchRef.current?.focus(),0)}catch{}};
 const flash=result=>{setFeedback(result);if(result?.ok)try{setTimeout(()=>setFeedback(null),2400)}catch{}};
 const buy=id=>{let item=RIFT_ITEM(id);if(!item)return;let next=P(run),result=rikaShop?RIFT_V13_RIKA_ITEM(next,id):RIFT_BUY_ITEM(next,id);flash(result);if(result.ok)onCommit(next)};
 const inspect=id=>{setSelectedId(id);if(mode===`build`)setMode(`browse`)};
 const toggleFavorite=id=>{RIFT_V16_TOGGLE_FAVORITE(fighter,id);setFavoriteVersion(v=>v+1)};
 const reset=()=>{setQuery(``);setCategory(`All`);setRarity(`All`);setStat(`All`);setSort(`Recommended`)};
 const switchOwner=()=>{persist();let nextOwner=owner===`rika`?`yuta`:`rika`,next=RIFT_V17_ARMORY_MEMORY(run,nextOwner,catalog);setOwner(nextOwner);setMode(next.mode);setQuery(next.query);setCategory(next.category);setRarity(next.rarity);setStat(next.stat);setSort(next.sort);setSelectedId(next.selectedId||catalog[0]?.id);setArchetypeId(next.archetypeId||`signature`)};
 (0,r.useEffect)(()=>{if(!open||typeof window===`undefined`)return;let handler=event=>{let editing=[`INPUT`,`TEXTAREA`,`SELECT`].includes(event.target?.tagName);if(event.key===`Escape`){event.preventDefault();close();return}if(event.key===`/`&&!editing){event.preventDefault();setMode(`browse`);setTimeout(()=>searchRef.current?.focus(),0);return}if(editing)return;if(event.key.toLowerCase()===`b`&&selected){event.preventDefault();buy(selected.id)}if(event.key.toLowerCase()===`f`&&selected){event.preventDefault();toggleFavorite(selected.id)}if([`ArrowRight`,`ArrowLeft`].includes(event.key)&&filtered.length){event.preventDefault();let index=Math.max(0,filtered.findIndex(item=>item.id===selectedId)),delta=event.key===`ArrowRight`?1:-1;setSelectedId(filtered[(index+delta+filtered.length)%filtered.length].id)}};window.addEventListener(`keydown`,handler,true);document.documentElement.classList.add(`rift-v17-armory-open`);return()=>{window.removeEventListener(`keydown`,handler,true);document.documentElement.classList.remove(`rift-v17-armory-open`)}},[open,selectedId,selected?.id,filtered,mode,owner]);
 if(!open)return (0,E.jsxs)(`section`,{className:`v17-armory-launcher`,children:[(0,E.jsxs)(`div`,{children:[(0,E.jsx)(`small`,{children:`V17 · ARMORY REFORGED`}),(0,E.jsx)(`h2`,{children:`BUILD COMMAND`}),(0,E.jsx)(`p`,{children:`Plan, browse, craft, and manage your six-slot build in one deliberate workflow.`})]}),(0,E.jsx)(RIFT_V17_BUILD_DOCK,{fighter}),(0,E.jsxs)(`aside`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`SHARDS`}),(0,E.jsxs)(`strong`,{children:[`◆ `,run.shards||0]})]}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`CATALOG`}),(0,E.jsxs)(`strong`,{children:[catalog.length,` ITEMS`]})]}),(0,E.jsx)(`button`,{ref:launchRef,type:`button`,onClick:()=>setOpen(true),children:`OPEN ARMORY`})]})]});
 return (0,E.jsx)(`div`,{className:`v17-armory-viewport`,role:`dialog`,"aria-modal":true,onPointerDown:event=>{if(event.target===event.currentTarget)close()},children:(0,E.jsxs)(`div`,{className:`v17-armory-shell mode-${mode}`,children:[
  (0,E.jsxs)(`header`,{className:`v17-command-bar`,children:[(0,E.jsxs)(`div`,{className:`v17-command-brand`,children:[(0,E.jsx)(`small`,{children:`V17 · ARMORY REFORGED`}),(0,E.jsx)(`h1`,{children:`RIFTBOUND ARMORY`}),(0,E.jsxs)(`span`,{children:[RIFT_V16_IDENTITY(fighter),` · FLOOR `,run.floor]})]}),(0,E.jsx)(RIFT_V17_BUILD_DOCK,{fighter}),(0,E.jsxs)(`div`,{className:`v17-command-actions`,children:[(0,E.jsxs)(`strong`,{children:[`◆ `,run.shards||0]}),RIFT_CURSED_CHILD(run.player)&&(0,E.jsx)(`button`,{type:`button`,onClick:switchOwner,children:rikaShop?`RIKA → YUTA`:`YUTA → RIKA`}),(0,E.jsx)(`button`,{type:`button`,onClick:close,children:`RETURN TO FLOOR`})]})]}),
  (0,E.jsx)(`nav`,{className:`v17-primary-nav`,children:RIFT_V17_ARMORY_MODES.map(([id,label])=>(0,E.jsx)(`button`,{type:`button`,className:mode===id?`active`:``,onClick:()=>setMode(id),children:label},id))}),
  feedback&&(0,E.jsxs)(`div`,{className:`v17-feedback ${feedback.ok?`success`:`failure`}`,children:[(0,E.jsx)(`b`,{children:feedback.ok?`✓`:`!`}),(0,E.jsx)(`span`,{children:feedback.message||feedback.reason})]}),
  mode===`build`&&(0,E.jsx)(RIFT_V17_BUILD_HOME,{fighter,run,archetypeId,onArchetype:setArchetypeId,onInspect:inspect,onBuy:buy}),
  [`browse`,`favorites`].includes(mode)&&(0,E.jsxs)(`div`,{className:`v17-shop-workspace`,children:[(0,E.jsxs)(`main`,{className:`v17-catalog-pane`,children:[(0,E.jsxs)(`header`,{className:`v17-catalog-tools`,children:[(0,E.jsxs)(`label`,{children:[(0,E.jsx)(`b`,{children:`⌕`}),(0,E.jsx)(`input`,{ref:searchRef,value:query,onChange:event=>setQuery(event.target.value),placeholder:`Search name, passive, reference, or stat…`})]}),(0,E.jsx)(`select`,{value:sort,onChange:event=>setSort(event.target.value),children:[`Recommended`,`Affordable`,`Components`,`Price Low`,`Price High`,`Name`].map(value=>(0,E.jsx)(`option`,{value,children:value.toUpperCase()},value))}),(0,E.jsx)(`button`,{type:`button`,onClick:reset,children:`RESET`}),(0,E.jsxs)(`em`,{children:[filtered.length,` SHOWN`]})]}),(0,E.jsxs)(`div`,{className:`v17-filter-row`,children:[(0,E.jsx)(`div`,{children:[`All`,...RIFT_ITEM_CATEGORIES].map(value=>(0,E.jsx)(`button`,{type:`button`,className:category===value?`active`:``,onClick:()=>setCategory(value),children:value},value))}),(0,E.jsx)(`select`,{value:rarity,onChange:event=>setRarity(event.target.value),children:[`All`,...RIFT_ITEM_RARITIES].map(value=>(0,E.jsx)(`option`,{value,children:value===`All`?`ALL RARITIES`:value.toUpperCase()},value))}),(0,E.jsx)(`select`,{value:stat,onChange:event=>setStat(event.target.value),children:[`All`,`AS`,`AP`,`Defense`,`Utility`].map(value=>(0,E.jsx)(`option`,{value,children:value===`All`?`ANY STAT`:value.toUpperCase()},value))})]}),filtered.length?(0,E.jsx)(RIFT_V17_VIRTUAL_CATALOG,{items:filtered,fighter,selectedId,favorites,onInspect:inspect,onBuy:buy,onFavorite:toggleFavorite,memory}):(0,E.jsxs)(`div`,{className:`v17-empty`,children:[(0,E.jsx)(`b`,{children:mode===`favorites`?`NO FAVORITES YET`:`NO ITEMS MATCH`}),(0,E.jsx)(`span`,{children:`Clear filters or choose another build direction.`})]})]}),(0,E.jsx)(RIFT_V17_INSPECTOR,{item:selected,fighter,plan,onBuy:()=>buy(selected.id),onInspect:inspect,onRecipeBuy:buy,favorite:favorites.has(selected?.id),onFavorite:()=>selected&&toggleFavorite(selected.id)})]}),
  mode===`craft`&&(0,E.jsx)(RIFT_V17_CRAFT_HOME,{item:selected,fighter,plan,onInspect:inspect,onBuy:buy}),
  mode===`inventory`&&(0,E.jsx)(RIFT_V17_INVENTORY_HOME,{run,fighter,rikaShop,onCommit})
 ]})})
};
