function RIFT_ITEM_HASH(id) {
  let hash=2166136261;for(const char of String(id)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return hash>>>0;
}
function RIFT_ITEM_ICON({item,size=`normal`}) {
  if(!item)return (0,E.jsx)(`span`,{className:`rift-item-icon empty ${size}`,children:`∅`});
  const hash=RIFT_ITEM_HASH(item.id),hue=hash%360,hue2=(hue+42+(hash%91))%360,pattern=hash%6;
  return (0,E.jsxs)(`span`,{className:`rift-item-icon ${size} rarity-${item.rarity.toLowerCase()} pattern-${pattern}`,style:{"--item-a":item.accent,"--item-b":`hsl(${hue2} 78% 58%)`,"--item-h":`${hue}deg`},title:item.name,children:[(0,E.jsx)(`i`,{}),(0,E.jsx)(`b`,{children:item.glyph}),(0,E.jsx)(`em`,{children:(hash%97).toString(16).toUpperCase().padStart(2,`0`)})]});
}
function RIFT_ITEM_STATS({item,compact=false}) {
  if(!item)return null;const labels={as:`AS`,ap:`AP`,durability:`DUR`,speed:`SPD`,range:`RNG`,iq:`IQ`,battleIq:`BIQ`,combatSkill:`CS`,energy:`ENG`,regeneration:`REG`};
  const entries=RIFT_ITEM_STAT_KEYS.filter(stat=>Number(item.stats?.[stat]));
  return (0,E.jsx)(`div`,{className:`rift-item-stats ${compact?`compact`:``}`,children:entries.length?entries.map(stat=>(0,E.jsxs)(`span`,{className:item.stats[stat]<0?`negative`:stat===`as`?`physical`:stat===`ap`?`arcane`:`` ,children:[(0,E.jsx)(`b`,{children:item.stats[stat]>0?`+`:``}),item.stats[stat],` `,labels[stat]]},stat)):(0,E.jsx)(`span`,{children:`PASSIVE-ONLY`})});
}
function RIFT_ITEM_STAT_PREVIEW({item,fighter,plan}) {
  if(!item||!fighter)return null;const consumed=new Set(plan?.consumeUids||[]),labels={as:`ATTACK STRENGTH`,ap:`ATTACK POWER`,durability:`DURABILITY`};
  return (0,E.jsx)(`div`,{className:`item-stat-preview`,children:[`as`,`ap`,`durability`].map(stat=>{const current=Y(fighter,stat),removed=RIFT_ITEM_INSTANCES(fighter).filter(instance=>consumed.has(instance.uid)).reduce((sum,instance)=>sum+Number(RIFT_ITEM(instance.itemId)?.stats?.[stat]||0),0),next=Math.max(0,current-removed+Number(item.stats?.[stat]||0));return(0,E.jsxs)(`span`,{className:stat,children:[(0,E.jsx)(`small`,{children:labels[stat]}),(0,E.jsxs)(`strong`,{children:[current,` → `,next]}),(0,E.jsx)(`em`,{children:next===current?`NO CHANGE`:next>current?`+${next-current} TIER`:`${next-current} TIER`})]},stat)})});
}
function RIFT_RECIPE_VIEW({item,fighter}) {
  if(!item?.recipe?.length)return (0,E.jsx)(`p`,{className:`rift-recipe-base`,children:`BASE COMPONENT · Purchases directly for ${item?.price||0} ◆`});
  const rows=RIFT_RECIPE_FLAT(item.id);
  return (0,E.jsxs)(`div`,{className:`rift-recipe-tree`,children:[(0,E.jsx)(`small`,{children:`SMART RECIPE · OWNED COMPONENTS ARE CONSUMED ONCE`}),rows.map((row,index)=>{const node=RIFT_ITEM(row.id),owned=RIFT_OWNS_ITEM(fighter,row.id);return(0,E.jsxs)(`div`,{className:`recipe-node ${owned?`owned`:``} rarity-${node.rarity.toLowerCase()}`,style:{"--depth":row.depth},children:[(0,E.jsx)(RIFT_ITEM_ICON,{item:node,size:`tiny`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`b`,{children:node.name}),(0,E.jsx)(`small`,{children:row.depth===0?`${node.combineCost} ◆ COMBINE`:owned?`OWNED · WILL CONSUME`:node.recipe.length?`${node.combineCost} ◆ COMBINE`:`${node.price} ◆`})]}),(0,E.jsx)(`em`,{children:row.depth===0?`FINAL`:owned?`✓`:`+`})]},`${row.id}-${index}`)} )]});
}
function RIFT_ITEM_DETAIL({item,fighter,plan,onBuy,recommended=false}) {
  if(!item)return (0,E.jsx)(`aside`,{className:`rift-item-detail empty`,children:`Select an item to inspect its build path, scaling, and exact stat delta.`});
  const active=item.category===`Weapon`?RIFT_ACTIVE_ITEM(fighter):null,buildsInto=RIFT_ITEM_CATALOG.filter(entry=>entry.recipe.includes(item.id)).slice(0,8);
  return (0,E.jsxs)(`aside`,{className:`rift-item-detail rarity-${item.rarity.toLowerCase()}`,style:{"--detail":item.accent},children:[
    (0,E.jsxs)(`header`,{children:[(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`hero`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`${item.rarity} · ${item.category}${recommended?` · RECOMMENDED`:``}`}),(0,E.jsx)(`h3`,{children:item.name}),(0,E.jsx)(`em`,{children:item.reference})]})]}),
    (0,E.jsx)(RIFT_ITEM_STATS,{item}),(0,E.jsx)(RIFT_ITEM_STAT_PREVIEW,{item,fighter,plan}),
    (0,E.jsxs)(`section`,{className:`item-passive-copy`,children:[(0,E.jsx)(`small`,{children:item.passiveId?`UNIQUE PASSIVE`:`ITEM PROPERTY`}),(0,E.jsx)(`strong`,{children:item.passiveId?item.passiveId.replace(/([A-Z])/g,` $1`).toUpperCase():`RELIABLE COMPONENT`}),(0,E.jsx)(`p`,{children:item.passive}),item.cooldown>0&&(0,E.jsxs)(`em`,{children:[`INTERNAL COOLDOWN · `,item.cooldown,` OWNER TURNS`]})]}),
    item.weapon&&(0,E.jsxs)(`div`,{className:`weapon-scaling-line`,children:[(0,E.jsx)(`b`,{children:item.weapon.damageType===`Hybrid`?`AS/AP`:item.weapon.damageType===`Magic`?`AP`:`AS`}),(0,E.jsxs)(`span`,{children:[item.weapon.damageType.toUpperCase(),` WEAPON ATTACK · `,item.weapon.range.toFixed(1),`m · `,item.weapon.cost,` ENERGY`]})]}),
    active&&active.id!==item.id&&(0,E.jsxs)(`div`,{className:`item-compare`,children:[(0,E.jsx)(`small`,{children:`COMPARE TO ACTIVE WEAPON`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(RIFT_ITEM_ICON,{item:active,size:`tiny`}),(0,E.jsx)(`b`,{children:active.name}),(0,E.jsx)(`em`,{children:RIFT_ITEM_STAT_TEXT(active)})]})]}),
    (0,E.jsx)(RIFT_RECIPE_VIEW,{item,fighter}),
    (0,E.jsxs)(`div`,{className:`item-builds-into`,children:[(0,E.jsx)(`small`,{children:`BUILDS INTO`}),(0,E.jsx)(`div`,{children:buildsInto.length?buildsInto.map(next=>(0,E.jsxs)(`span`,{children:[(0,E.jsx)(RIFT_ITEM_ICON,{item:next,size:`tiny`}),(0,E.jsx)(`b`,{children:next.name})]},next.id)):(0,E.jsx)(`em`,{children:item.rarity===`Legendary`?`FINAL LEGENDARY CAPSTONE`:`NO DISCOVERED UPGRADE`})})]}),
    item.rarity===`Legendary`&&(0,E.jsxs)(`div`,{className:`legendary-ownership-law`,children:[(0,E.jsx)(`b`,{children:`UNIQUE OWNERSHIP`}),(0,E.jsx)(`span`,{children:`Only one copy of this specific Legendary can exist in your six-slot build. Selling it permits a later rebuild.`})]}),
    (0,E.jsxs)(`blockquote`,{children:[`“`,item.lore,`”`]}),
    (0,E.jsxs)(`footer`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:plan?.consumeUids?.length?`${plan.consumeUids.length} OWNED COMPONENT${plan.consumeUids.length===1?``:`S`} APPLIED`:`FULL COST`}),(0,E.jsxs)(`strong`,{children:[plan?.cost??item.price,` ◆`]})]}),(0,E.jsx)(`button`,{type:`button`,onClick:onBuy,disabled:!plan?.ok,className:`item-buy-button`,children:plan?.ok?(item.recipe.length?`SMART BUILD`:`BUY ITEM`):plan?.reason||`UNAVAILABLE`})]})
  ]});
}
function RIFT_INVENTORY_MANAGER({run,onCommit}) {
  const [selected,setSelected]=(0,r.useState)(0),fighter=run.player;
  RIFT_NORMALIZE_FIGHTER_BUILD(fighter);
  const act=(kind,slot,target)=>{const next=P(run);let result;if(kind===`sell`)result=RIFT_SELL_ITEM(next,slot);else result=RIFT_MOVE_ITEM(next.player,slot,target);if(result.ok)onCommit(next);return result;};
  return (0,E.jsxs)(`section`,{className:`rift-inventory-manager`,children:[
    (0,E.jsxs)(`header`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`SIX-SLOT LOADOUT`}),(0,E.jsx)(`strong`,{children:`ACTIVE BUILD`})]}),(0,E.jsx)(`em`,{children:`SLOT 0 · WEAPON ONLY`})]}),
    (0,E.jsx)(`div`,{className:`rift-inventory-grid`,children:fighter.inventory.map((instance,slot)=>{const item=instance?RIFT_ITEM(instance.itemId):null,cd=item?.passiveId?fighter.itemCooldowns?.[RIFT_ITEM_COOLDOWN_KEY(item)]||0:0;return(0,E.jsxs)(`button`,{type:`button`,className:`inventory-slot ${slot===0?`weapon-slot`:``} ${selected===slot?`selected`:``} ${item?`rarity-${item.rarity.toLowerCase()}`:`empty`}`,onClick:()=>setSelected(slot),children:[(0,E.jsx)(`small`,{children:slot===0?`0 · ACTIVE WEAPON`:`SLOT ${slot}`}),(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`small`}),(0,E.jsx)(`strong`,{children:item?.name||`EMPTY`}),(0,E.jsx)(`em`,{children:cd?`${cd}T CD`:item?.rarity||`OPEN`})]},slot)} )}),
    (()=>{const instance=fighter.inventory[selected],item=instance?RIFT_ITEM(instance.itemId):null;if(!item)return(0,E.jsx)(`p`,{className:`inventory-hint`,children:selected===0?`Equip a weapon here to unlock the weapon action.`:`An open slot can hold any item. Components grant stats while waiting for a recipe.`});return(0,E.jsxs)(`div`,{className:`inventory-controls`,children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`b`,{children:item.name}),(0,E.jsx)(`small`,{children:RIFT_ITEM_STAT_TEXT(item)})]}),selected>0&&item.category===`Weapon`&&(0,E.jsx)(`button`,{type:`button`,onClick:()=>act(`move`,selected,0),children:`EQUIP · SLOT 0`}),selected===0&&(0,E.jsx)(`button`,{type:`button`,disabled:!fighter.inventory.slice(1).some(slot=>!slot),onClick:()=>{const free=fighter.inventory.findIndex((slot,index)=>index>0&&!slot);free>0&&act(`move`,0,free)},children:`UNEQUIP`}),selected>1&&(0,E.jsx)(`button`,{type:`button`,onClick:()=>act(`move`,selected,selected-1),children:`← MOVE`}),selected>0&&selected<5&&(0,E.jsx)(`button`,{type:`button`,onClick:()=>act(`move`,selected,selected+1),children:`MOVE →`}),(0,E.jsx)(`button`,{type:`button`,className:`sell`,onClick:()=>act(`sell`,selected),children:`SELL · ${Math.max(1,Math.floor((instance.invested||item.price)*.6))} ◆`})]});})()
  ]});
}
function RIFT_ITEM_SHOP({run,onCommit}) {
  RIFT_NORMALIZE_RUN_BUILD(run);
  const offers=(run.shopOffers?.length?run.shopOffers:RIFT_SHOP_OFFERS(run.floor,run.player)).map(offer=>typeof offer===`string`?RIFT_ITEM(offer):RIFT_ITEM(offer.id)).filter(Boolean);
  const [category,setCategory]=(0,r.useState)(`All`),[rarity,setRarity]=(0,r.useState)(`All`),[query,setQuery]=(0,r.useState)(``),[selectedId,setSelectedId]=(0,r.useState)(offers[0]?.id||null),[feedback,setFeedback]=(0,r.useState)(null);
  const recommended=new Set(RIFT_RECOMMENDED_ITEMS(run.player,offers,4));
  const filtered=offers.filter(item=>(category===`All`||item.category===category)&&(rarity===`All`||item.rarity===rarity)&&(!query||`${item.name} ${item.passive} ${item.lore}`.toLowerCase().includes(query.toLowerCase())));
  const selected=RIFT_ITEM(selectedId)||filtered[0]||offers[0]||null,plan=selected?RIFT_RECIPE_PLAN(run.player,selected.id):null;
  const buy=()=>{if(!selected)return;const next=P(run),result=RIFT_BUY_ITEM(next,selected.id);setFeedback(result);if(result.ok){onCommit(next);try{window.setTimeout(()=>setFeedback(null),2400)}catch{}}};
  return (0,E.jsxs)(`div`,{className:`build-expansion-shop`,children:[
    (0,E.jsxs)(`header`,{className:`armory-header`,children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`EVERY FLOOR · SHARD ECONOMY · SMART RECIPES`}),(0,E.jsx)(`h2`,{children:`RIFTBOUND ARMORY`})]}),(0,E.jsxs)(`strong`,{children:[`◆ `,run.shards||0]}),(0,E.jsx)(`em`,{children:`${offers.length} OFFERS · FLOOR ${run.floor}`})]}),
    feedback&&(0,E.jsxs)(`div`,{className:`purchase-feedback ${feedback.ok?`success`:`failure`}`,children:[(0,E.jsx)(`b`,{children:feedback.ok?`✓`:`!`}),(0,E.jsx)(`span`,{children:feedback.message||feedback.reason})]}),
    (0,E.jsxs)(`div`,{className:`shop-filters`,children:[(0,E.jsx)(`input`,{value:query,onChange:event=>setQuery(event.target.value),placeholder:`Search name, passive, or lore…`,"aria-label":`Search item shop`}),(0,E.jsx)(`select`,{value:category,onChange:event=>setCategory(event.target.value),children:[`All`,...RIFT_ITEM_CATEGORIES].map(value=>(0,E.jsx)(`option`,{value,children:value===`All`?`ALL CATEGORIES`:value.toUpperCase()},value))}),(0,E.jsx)(`select`,{value:rarity,onChange:event=>setRarity(event.target.value),children:[`All`,...RIFT_ITEM_RARITIES].map(value=>(0,E.jsx)(`option`,{value,children:value===`All`?`ALL RARITIES`:value.toUpperCase()},value))})]}),
    (0,E.jsxs)(`div`,{className:`shop-workbench`,children:[(0,E.jsxs)(`div`,{className:`item-offer-column`,children:[(0,E.jsxs)(`div`,{className:`recommendation-band`,children:[(0,E.jsx)(`b`,{children:`◎ BUILD READ`}),(0,E.jsxs)(`span`,{children:[RIFT_BUILD_PROFILE(run.player).name.toUpperCase(),` PROFILE · RECOMMENDATIONS USE POWER SOURCE, CURRENT STATS, AND OPEN SLOTS`]})]}),(0,E.jsx)(`div`,{className:`item-offer-grid`,children:filtered.map(item=>{const itemPlan=RIFT_RECIPE_PLAN(run.player,item.id),owned=RIFT_OWNS_ITEM(run.player,item.id);return(0,E.jsxs)(`button`,{type:`button`,onClick:()=>setSelectedId(item.id),className:`item-offer rarity-${item.rarity.toLowerCase()} ${selected?.id===item.id?`selected`:``} ${recommended.has(item.id)?`recommended`:``}`,style:{"--offer":item.accent},children:[recommended.has(item.id)&&(0,E.jsx)(`i`,{children:`RECOMMENDED`}),(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`small`}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`${item.rarity} · ${item.category}`}),(0,E.jsx)(`strong`,{children:item.name}),(0,E.jsx)(RIFT_ITEM_STATS,{item,compact:true})]}),(0,E.jsxs)(`em`,{children:[itemPlan.ok?itemPlan.cost:item.price,` ◆`,owned&&item.rarity===`Legendary`?` · OWNED`:``]})]},item.id)} )})]}),(0,E.jsx)(RIFT_ITEM_DETAIL,{item:selected,fighter:run.player,plan,onBuy:buy,recommended:recommended.has(selected?.id)})]}),
    (0,E.jsx)(RIFT_INVENTORY_MANAGER,{run,onCommit})
  ]});
}
function RIFT_BUILD_SUMMARY({fighter}) {
  if(!fighter)return null;RIFT_NORMALIZE_FIGHTER_BUILD(fighter);const profile=RIFT_BUILD_PROFILE(fighter),items=fighter.inventory.map(instance=>instance?RIFT_ITEM(instance.itemId):null);
  return (0,E.jsxs)(`section`,{className:`rift-build-summary`,children:[(0,E.jsxs)(`header`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`BUILD EXPANSION · READ ONLY IN COMBAT`}),(0,E.jsxs)(`strong`,{children:[profile.name.toUpperCase(),` BUILD`]})]}),(0,E.jsxs)(`em`,{children:[items.filter(Boolean).length,` / 6 SLOTS`]})]}),(0,E.jsx)(`div`,{className:`build-summary-slots`,children:items.map((item,index)=>(0,E.jsxs)(`div`,{className:`${index===0?`active-weapon`:``} ${item?`rarity-${item.rarity.toLowerCase()}`:`empty`}`,children:[(0,E.jsx)(`small`,{children:index===0?`0 · WEAPON`:`${index}`}),(0,E.jsx)(RIFT_ITEM_ICON,{item,size:`tiny`}),(0,E.jsx)(`b`,{children:item?.name||`OPEN`}),(0,E.jsx)(`em`,{children:item?RIFT_ITEM_STAT_TEXT(item):`NO ITEM`})]},index))}),(0,E.jsx)(`div`,{className:`build-summary-totals`,children:RIFT_ITEM_STAT_KEYS.filter(stat=>profile.totals[stat]).map(stat=>(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`b`,{children:stat===`combatSkill`?`CS`:stat===`battleIq`?`BIQ`:stat.toUpperCase()}),(0,E.jsxs)(`em`,{children:[profile.totals[stat]>0?`+`:``,profile.totals[stat]]})]},stat))})]});
}
function RIFT_SCALING_BADGE({action,fighter}) {const scaling=RIFT_ACTION_SCALING(action,fighter),label=RIFT_SCALING_LABEL(action,fighter);return(0,E.jsx)(`span`,{className:`scaling-badge scaling-${scaling.mode.toLowerCase()}`,title:`Damage source classification: ${label}`,children:label});}
function RIFT_ITEM_INTEL({fighter,hidden=false}) {if(!fighter)return null;const items=RIFT_ITEM_INSTANCES(fighter).map(instance=>RIFT_ITEM(instance.itemId)).filter(Boolean),weapon=RIFT_ACTIVE_ITEM(fighter);return(0,E.jsxs)(`div`,{className:`rift-item-intel ${hidden?`hidden`:``}`,children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`ARMAMENT`}),(0,E.jsx)(`strong`,{children:hidden?`???`:weapon?.name||`WEAPONLESS`})]}),(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`ITEM BUILD`}),(0,E.jsx)(`strong`,{children:hidden?`???`:`${items.length}/6 · ${items.filter(item=>item.rarity===`Legendary`).map(item=>item.name).join(` · `)||`NO LEGENDARY`}`})]})]});}
function RIFT_DEBUG_ITEM_PANEL({run,onCommit}) {
  const [itemId,setItemId]=(0,r.useState)(RIFT_ITEM_CATALOG.find(item=>item.rarity===`Legendary`)?.id||RIFT_ITEM_CATALOG[0].id),[openShop,setOpenShop]=(0,r.useState)(false),[message,setMessage]=(0,r.useState)(``);
  if(!run)return (0,E.jsx)(`div`,{className:`debug-tab-page`,children:(0,E.jsx)(`p`,{children:`Start or forge a run before using Build Expansion debug controls.`})});
  const commit=(next,text)=>{onCommit(next);setMessage(text)};
  const grant=(legendary=false)=>{const next=P(run);RIFT_NORMALIZE_RUN_BUILD(next);const item=legendary?RIFT_ITEM_CATALOG.find(entry=>entry.rarity===`Legendary`&&!RIFT_OWNS_ITEM(next.player,entry.id)):RIFT_ITEM(itemId);if(!item)return setMessage(`No eligible item.`);const slot=RIFT_FREE_SLOT_FOR(next.player.inventory,item);if(slot<0)return setMessage(`Inventory full.`);next.player.inventory[slot]=RIFT_ITEM_INSTANCE(item.id,item.price);RIFT_SYNC_WEAPON(next.player);RIFT_REFRESH_ITEM_POOLS(next.player);commit(next,`Granted ${item.name} to slot ${slot}.`)};
  const remove=()=>{const next=P(run);RIFT_NORMALIZE_RUN_BUILD(next);const slot=next.player.inventory.findIndex(instance=>instance?.itemId===itemId);if(slot<0)return setMessage(`Selected item is not owned.`);next.player.inventory[slot]=null;RIFT_SYNC_WEAPON(next.player);RIFT_REFRESH_ITEM_POOLS(next.player);commit(next,`Removed selected item.`)};
  const shards=()=>{const next=P(run);next.shards=(next.shards||0)+1000;commit(next,`Granted 1,000 Shards.`)};
  const stat=(key,value)=>{const next=P(run);RIFT_NORMALIZE_RUN_BUILD(next);next.player.tiers[key]=Math.max(0,Math.min(19,Math.round(value)));commit(next,`${key.toUpperCase()} set to ${next.player.tiers[key]}.`)};
  const testRecipe=()=>{const plan=RIFT_RECIPE_PLAN(run.player,itemId);setMessage(plan.ok?`Recipe valid · ${plan.cost} Shards · consumes ${plan.consumeUids.length} owned component(s) · output slot ${plan.slot}.`:plan.reason)};
  return (0,E.jsxs)(`div`,{className:`debug-tab-page build-debug-page`,children:[(0,E.jsxs)(`section`,{className:`debug-section`,children:[(0,E.jsxs)(`header`,{children:[(0,E.jsxs)(`span`,{children:[(0,E.jsx)(`small`,{children:`PRODUCTION ITEM APIs`}),(0,E.jsx)(`h3`,{children:`BUILD EXPANSION LAB`})]}),(0,E.jsx)(`em`,{children:`Catalog, recipe, inventory, and shop share one implementation`})]}),(0,E.jsxs)(`label`,{className:`debug-item-select`,children:[(0,E.jsx)(`span`,{children:`Catalog Item`}),(0,E.jsx)(`select`,{value:itemId,onChange:event=>setItemId(event.target.value),children:RIFT_ITEM_CATALOG.map(item=>(0,E.jsxs)(`option`,{value:item.id,children:[item.rarity,` · `,item.category,` · `,item.name]},item.id))})]}),(0,E.jsxs)(`div`,{className:`debug-command-row`,children:[(0,E.jsx)(`button`,{type:`button`,onClick:()=>grant(false),children:`GRANT ITEM`}),(0,E.jsx)(`button`,{type:`button`,onClick:()=>grant(true),children:`GRANT LEGENDARY`}),(0,E.jsx)(`button`,{type:`button`,onClick:remove,children:`REMOVE ITEM`}),(0,E.jsx)(`button`,{type:`button`,onClick:shards,children:`+1,000 SHARDS`}),(0,E.jsx)(`button`,{type:`button`,onClick:testRecipe,children:`TEST RECIPE`}),(0,E.jsx)(`button`,{type:`button`,onClick:()=>setOpenShop(value=>!value),children:openShop?`CLOSE SHOP`:`OPEN PRODUCTION SHOP`})]}),(0,E.jsxs)(`div`,{className:`debug-stat-setters`,children:[(0,E.jsxs)(`label`,{children:[(0,E.jsx)(`span`,{children:`Attack Strength`}),(0,E.jsx)(`input`,{type:`number`,min:0,max:19,value:run.player.tiers.as,onChange:event=>stat(`as`,event.target.value)})]}),(0,E.jsxs)(`label`,{children:[(0,E.jsx)(`span`,{children:`Attack Power`}),(0,E.jsx)(`input`,{type:`number`,min:0,max:19,value:run.player.tiers.ap,onChange:event=>stat(`ap`,event.target.value)})]})]}),message&&(0,E.jsx)(`p`,{className:`debug-item-message`,children:message})]}),openShop&&(0,E.jsx)(RIFT_ITEM_SHOP,{run,onCommit})]});
}
